### ISSUE TITLE
Uncythonized functions/Numba

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1001]
During some recent profiling runs I noticed a number of uncythonized functions that had significant contributions to runtime in some cases.  

The functions of interest are:  addSpeciesToCore, isMoleculeForbidden, markDuplicateReaction and toAdjacencyList.  

I made an attempt to cythonize most of these and ran into the issue that cythonizing a function bound to an object requires that object to be cythonized.  Attempting to cythonize these objects (for addSpeciesToCore and isMoleculeForbidden) turned into a mess.  

There are ways around this, there are a number of ways the structure could be rewritten to allow for this, however, the package Numba appears to provide a much simpler and easy solution to this.  

Numba is a Just in time (jit) compiler for python that uses type inference to compile argument specific python functions as they are called.  Tests I've done and what I've been able to find online imply that Numba is now either equally as fast as Cython or very slightly faster.  

Numba differences from Cython:
-Easy to implement, largely just put the @jit decorator at the top of function
-Unlike cython it can infer the involved types in your function, you don't have to tell it what they are
-Doesn't support comprehensions
-Limited support for class compiling
-Supports compiling bound functions within a non-compiled object
-No need for make/make clean

**Comment by mliu49** [comment]
I think that for most of the methods you listed, the limiting step should be graph isomorphism, which is cythonized and has previously been identified as a time consuming step.

It would be best if you could quantify the speedup that Numba provides, which would help determine if the speedup gain is worth the added complexity of another compiler.

**Comment by mjohnson541** [comment]
The timing I'm discussing is the "tottime" or as the python profiling documentation puts it "the total time spent in the given function (and excluding time made in calls to sub-functions)".  So internal graph isomorphism calls would be ignored.  

The gain is about the same as Cython, I'm absolutely not suggesting we replace Cython with Numba. However, in most cases Numba can be much more easily deployed and maintained than Cython can since in many cases it requires minimal changes to the code and doesn't need to be manually compiled.  

Numba doesn't really add much complexity since it's a jit compiler and it doesn't need any of the extra infrastructure Cython does.  I.e. I can numba-ize a function in my RMG-Py by simply importing numba in that file and adding the @jit decorator to the function.  

I think it's better than cython in the cases when it is applicable (equal in terms of speed, better in terms of deployment).  It may be a hammer with very few nails right now, but I think that it's a better option than Cythonization for future development.

**Comment by mliu49** [comment]
That seems somewhat odd to me. For example, `addSpeciesToCore` really only appends things to lists, which should take negligible time. The time consuming part should be checking `spec in self.edge.species`, `reactant not in self.core.species`, and `product not in self.core.species`. Graph isomorphism is used for the equivalence comparison in these cases. Perhaps it's not counted as a separate function call since it's not explicitly called?

I understand that the gain is about the same as Cython, but I'm curious about the specific gain for cythonizing/numba-ing the particular methods you mentioned.

By complexity, I mainly meant for new developers. If someone wants to add a new class or method, should they use pure cython, cythonize pure python, numba pure python, or just use pure python? If it's as fast as cython, should we switch completely to numba? Should everything that's not cythonized be numba-ed?

I'm not opposed to adding Numba, I just want to understand how it should be used and how much benefit it offers.

**Comment by rwest** [comment]
I think it's worth considering. Cython is not easy, and if Numba is as fast, switching would simplify things for developers. However we may still need Cython for the interfaces to other code eg Fortran, but I suppose all of that is (or could be) moved to other projects like PyDAS and PyDQED.

I'd entertain discussion, but would like to see example code and benchmarking of a global switchover.

**Comment by mjohnson541** [comment]
I bet you're right, that would certainly make a lot more sense.  

I'll try to run some more formal comparison tests.  

The one big catch with Numba right now is that they're only just beginning to support the jit compiling of classes.  I'll try experimenting with what they have available right now, but I don't think their "jitclasses" are optimized well enough to compete with cython's cdef classes at the moment.

**Comment by mjohnson541** [comment]
I was actually using the jitclasses improperly during my earlier tests, in fact they appear to be equally as fast as cython for my small test cases.  However, so far I've noticed that numba error messages aren't very informative.  For example:

When an incorrect parameter is fed to a cdef class:  
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-86b8b2290f3f> in <module>()
----> 1 b('a')

_cython_magic_dc829331af639e85f5da0be12f438816.pyx in _cython_magic_dc829331af639e85f5da0be12f438816.b.__init__ (/Users/mattjohnson/.ipython/cython/_cython_magic_dc829331af639e85f5da0be12f438816.c:1485)()

TypeError: a float is required

When an incorrect parameter is fed to a jitclass: 
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-6-627e05fc7049> in <module>()
----> 1 a('a')

/Users/mattjohnson/anaconda/envs/rmg_env/lib/python2.7/site-packages/numba/jitclass/base.pyc in __call__(cls, *args, **kwargs)
    112 
    113     def __call__(cls, *args, **kwargs):
--> 114         return cls._ctor(*args, **kwargs)
    115 
    116 

/Users/mattjohnson/anaconda/envs/rmg_env/lib/python2.7/site-packages/numba/dispatcher.pyc in _compile_for_args(self, *args, **kws)
    328                                 for i, err in failed_args))
    329                 e.patch_message(msg)
--> 330             raise e
    331 
    332     def inspect_llvm(self, signature=None):

TypingError: Caused By:
Traceback (most recent call last):
...a page or two of callbacks...
    "Cannot cast %s to %s: %s" % (fromty, toty, val))
LoweringError: Cannot cast str to float64: %".17" = load i8*, i8** %"x"
File "<ipython-input-3-dc27ea8a93ca>", line 4
[1] During: lowering "(self).x = x" at <ipython-input-3-dc27ea8a93ca> (4)

Failed at nopython (nopython mode backend)
Cannot cast str to float64: %".17" = load i8*, i8** %"x"
File "<ipython-input-3-dc27ea8a93ca>", line 4
[1] During: lowering "(self).x = x" at <ipython-input-3-dc27ea8a93ca> (4)
[2] During: resolving callee type: jitclass.a#7faeef841440<x:float64>
[3] During: typing of call at <string> (3)
--%<-----------------------------------------------------------------

File "<string>", line 3

While the issue can be worked out from the error message it is much less clear and so far this seems to hold for most numba related error messages I've seen.  Compiling on the fly would be very convenient, but the loss of error specificity could be quite a sacrifice.

**Comment by goldmanm** [comment]
@mjohnson541, What are your current thoughts about what should be done regarding this?

Also, when profiling returns methods like `addSpeciesToCore` as being intensive, is that due there being a lot of underlying code being run, like isomorphism, which is already cythonized or does it just count the execution of code lines in that method that do not call other RMG modules?

**Comment by mjohnson541** [comment]
I'm still entertaining the idea, compiling on the fly is very tempting, it might be interesting to test in any new systems.  However, I don't think as of now it would be a good idea to switch any cython code over to numba, because of the readability issue discussed above.  

I'm pretty sure Max is right on that issue, it's just underlying code being called in a way that the profiling interprets as being part of the call to the function since the subcalls are through special functions.

**Comment by mjohnson541** [comment]
Apparently numba has restriction I didn't realize until I tried to use it on an ordinary RMG function, it can't deal with strings normally right now.  While there are ways to work around that, they tend to ruin readability, or at least be very inconvenient.
