### ISSUE TITLE
Create "chem_annotated_thermo_only.inp" as part of RMG output

### ISSUE THREAD

**Issue by zjburas** [ReactionMechanismGenerator/RMG-Py#1003]
Not an issue, but an idea:

As part of the RMG output in the "chemkin" folder, could there be one additional file that is an annotated version of the mechanism with only the ELEMENTS, SPECIES and THERMO blocks? In other words, the same as "chem_annotated.inp", but without the often enormous REACTIONS block. Sometimes, the user may just want to know qualitatively what species are in their mechanism, in which case this smaller file would be sufficient. It would also be a lot faster to run through subsequent scripts, such as the mechanism visualizer on the website, or the mechanism merge tool.

**Comment by zjburas** [comment]
Of  course, the users could just delete the REACTION block themselves, but there might be situations where it would be convenient to already have such a file available (if you have many .inp files that you want to merge, for example, but you only care about what species are there).

**Comment by rwest** [comment]
You could try something like 
`sed /REACTIONS/q chem_annotated.inp  > chem_trimmed.inp`

**Comment by zjburas** [comment]
Sure. I just thought more generally having a file with only species as part of the standard output might be useful for some users. Seeing as RMG already generates a complete mechanism file for each iteration of the mechanism generation, adding 1 additional .inp file without all of the reactions would make a negligible contribution to the overall size of the output. 

Also, it may not be obvious to some users (it wasn't to me, initially) that you don't need to input the entire mechanism into the visualization tool on the website, if you just want to see qualitatively what you made. This could potentially save a lot of time, and burden on the website.
