### ISSUE TITLE
rmgpy.thermo.NASAPolynomial.getFreeEnergy() Returns G in J/molK

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/RMG-Py#1005]
The API on the RMG website claims that rmgpy.thermo.NASAPolynomial.getFreeEnergy() returns G(T)/RT, however after crunching some numbers it appears that it actually returns G(T) in J/mol-K. I am assuming that there are no errors in RMG because of this, but should we update the API just in case someone accidentally trusts the API?

**Comment by rwest** [comment]
Absolutely the API docs should be accurate!

Where is the error?

My quick search for docstrings shows everything saying "in J/mol"

eg.
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/e42c48ae639da7f5596265b4f9ee152e05f85ab5/rmgpy/thermo/nasa.pyx#L125

**Comment by mliu49** [comment]
Interestingly, the methods in the `NASAPolynomial` class all have the appropriate units, but the methods in the `NASA` class claim to return dimensionless values, although they directly call the methods in the `NASAPolynomial` class.

**Comment by rwest** [comment]
Ah, yes.
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/e42c48ae639da7f5596265b4f9ee152e05f85ab5/rmgpy/thermo/nasa.pyx#L287

That should definitely be fixed. Thanks @amarkpayne

**Comment by amarkpayne** [comment]
This was the webpage I was looking at http://reactionmechanismgenerator.github.io/RMG-Py/reference/thermo/nasa.html#rmgpy.thermo.NASA

**Comment by amarkpayne** [comment]
Is the fix as simple as updating the docstring? If so I can go ahead and do that real quick

**Comment by rwest** [comment]
That is first step, so please go ahead. Then the instructions for rebuilding and publishing the site are on the wiki I believe, but you may need to ask someone with the correct permissions to push it

**Comment by amarkpayne** [comment]
The docstrings have been changed and the pull request is ready to merge. I am looking into the wiki for how to update the documentation, and should hopefully have that done shortly.
