### ISSUE TITLE
Disscusion: How to Calculate Thermo for Cis/Trans Isomerism 

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/RMG-Py#1011]
I am currently working on a project where a key/sensitive species in my mechanism is 2-butene. Although RMG does not take this into account, there are two isomers for 2-butene (Cis and Trans), each with different values for thermo. Looking at data available on the NIST chembook, it appears that these isomers have a difference of ~0.75 kcal/mol in their enthalpies of formation.

In my case (and probably for anyone else using RMG) I would expect both isomers to be formed in the real life system I am trying to model. I looked up the value that RMG uses for 2-butene, and I believe that the value from the DFT_QCI_thermo library is for trans 2-butene. Once again, I know RMG does not do anything to take isomers into account, but is this really the best value to be using? When we report thermo values for a library, should we try to do some sort of weighted average based on the relative abundance of each isomer at every temperature? Furthermore, do the group additivity corrections for species like 2-butene do anything to take this effect into account?

I realize that trying to get RMG to handle isomers would be an enormous challenge, but should we try to do something like what I described above to fix thermo for species like this as we come across them? Is there a more rigorous way to try and tackle this problem? My plan for now was to deal with this issue only when it arises for sensitive species in my model (perhaps it doesn't matter most of the time anyways), but I was curious what everyone's thoughts on this matter were.

**Comment by goldmanm** [comment]
I think the reason for using trans-butene is that it is more thermodynamically stable, and likely to form in higher concentrations. Do you know if the major reactions forming butene would form it in a cis or trans fashion?

**Comment by alongd** [comment]
I agree with @goldmanm .
When I added the NitrogenCurran thermo library I needed to decide on a similar issue: in instances where two isomers are reported (e.g., C2H5ONOcis and C2H5ONOtrans) what do we feed RMG with?
I took the most stable form only and added a comment in the library file to document my choice.

This question is similar in nature to one we asked ourselves some time ago regarding the reactivity of different resonance structures. Currently, similarly to the isomers case, RMG does not take into account the relative contribution of each resonance form when applying rate rules.

I think we should be consistent. When we come across a thermo value in RMG for a specific isomer, let's make sure it is the more stable one and document it in the comments, until we decide to allow RMG to treat isomers. I don't think we should average.

**Comment by amarkpayne** [comment]
What if the two isomers are somewhat close in energy? If I did my math correctly and assuming a Boltzmann distribution at 400 C (the temp in my model) trans 2-butene is only 1.75 times as abundant as cis 2-butene. Taking trans 2-butene as the only species present since it is more stable is convenient, but this result tells me that the concentrations of both species are at least on the same order. 

I'll check my model to see what reactions are forming 2-butene, but as a first guess I would assume most of them are not stereo-specific, and thus I would expect a distribution of products.

**Comment by amarkpayne** [comment]
I guess I see why this is very much case specific though and would be hard to do anything about it in RMG. I'll stick with only dealing with this as needed based on sensitivity analysis. Let me know if you guys have any other thoughts.
