### ISSUE TITLE
Species in the library would be pruned

### ISSUE THREAD

**Issue by jimchu10** [ReactionMechanismGenerator/RMG-Py#1015]
I created the library "Ketene_related" in the SABIC_aromatic branch of RMG_database and ran the RMG job with that library in the input file.
One of the reaction which has low rate can be put into the mechanism in the first iteration, but its product was pruned in the 51st iteration, which **means now RMG would prune the species even though they are involved with the reactions in the libraries of input file**.
It might be better to keep all the rates and species from the libraries whether the pruning in on or off.

**Comment by KEHANG** [comment]
I agree, I'll look into that.
