### ISSUE TITLE
Model reduction in parallel with scoop and slurm

### ISSUE THREAD

**Issue by chiyw13** [ReactionMechanismGenerator/RMG-Py#1018]
Has anyone got a working example of using the reduction tool in parallel with a script for slurm?

We have tried things like this:
```
#!/bin/bash
#SBATCH --job-name=RMG-minimal
#SBATCH --output=slurm.out
#SBATCH --error=slurm.err
## number of tasks
#SBATCH -n 39
## don't share the node with anyone
#SBATCH --exclusive
## number of nodes
#SBATCH -N 1

HOSTS=$(srun bash -c hostname)
WORKERS=39
export RMGpy=$HOME/Code/RMG-Py

python -m scoop -n $WORKERS --host $HOSTS -vv $RMGpy/rmgpy/reduction/main.py input.py reduction_input.py chem_annotated.inp species_dictionary.txt
```

but we get a lot of jumbled up ` name 'database' is not defined` errors. It looks like 39 workers are all trying to do the same thing, without context.

If we try the simpler script in the examples folder 
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/examples/reduction/example_parallel.sh
that does not specify the hosts then we get this error instead:
```
........./site-packages/scoop/utils.py", line 95, in externalHostname
    hostname = hosts[0][0]
IndexError: list index out of range
```

**Comment by goldmanm** [comment]
I don't think anyone I know has tried using reduction in parallel, which is an issue since the post-production reduction can be quite slow.
