### ISSUE TITLE
Saving an RMG-Java style database no longer works

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1021]
The website has a function to export the entire database in RMG-Java format which is not working properly at the moment. I'm planning to change it to save a RMG-Py style database instead, but that's not the main issue.

The website uses the `exportOldDatabase.py` script in RMG-database, which does not work properly. The script calls `RMGDatabase.saveOld()`, which I assume nobody has paid any attention to for a long time.

The thing it gets stuck on currently is writing groups to an old-style adjlist. First, it tries to call `Group.toAdjacencyList(oldStyle=True)`, but that argument is not defined in that method. The main `adjlist.toAdjacencyList()` method does support it, so this might be due to reorganization that occurred at some point. However, adding the argument to the method in the Group class does not fully solve the issue, because it end up at `adjlist.toOldAdjacencyList()`, which does not support writing adjlists for Groups. Therefore, it seems like we can't save an old-style database at all.

The question I have is whether or not it's worth it to try and fix this and maintain our ability to export an RMG-Java style database? Also, if we do not want to maintain it, should we deprecate all of the related methods?

**Comment by rwest** [comment]
I personally think:
1) we invented the new style adjacency list to allow us to do things that were impossible in the old style
2) we have started to do some of those things
3) the database cannot be exported to the old style, by definition
4) none of the developers who would have to spend time maintaining the export-to-old-style are actually using RMG-java so it would not benefit them (this is speculation - let me know if I'm wrong)
4) we should deprecate the methods that tried to export to the old style

**Comment by goldmanm** [comment]
If we deprecate the methods that tried to export to the old style, might we also consider officially deprecating RMG-Java. The last people working on it at least at MIT will be gone very soon. Also, we have noticed many more user issues posted to RMG-Py than Java, which likely indicates Py is much more popular (or just more buggy, jk). 

If we want to deprecate the methods, how should we do it? We can just remove them in the next release, especially if they are currently defunct now. Or we can implement a warning in the next release that will kick in in the following release. Thoughts?

**Comment by alongd** [comment]
I think that the next release can be without RMG-Java (non-functioning) capabilities.
Along with the error we'll through, we could direct the (hypothetical) user to the version that still has them.
