### ISSUE TITLE
database loading fails in generateReaction script

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1022]
The generateReaction script is unable to load the database due to a non-ascii character `ö`. It seems these were added in commit b7cd1c19 to RMG-database. I am not sure why it is failing on generateReactions.ipynb but working perfectly on RMG-tests. 

Note: removing all the offending characters fixes the error.

Should we move to a more extensible string reading/writing or bar non-ascii characters from pull requests?

Can anyone verify this issue? I was using the master of RMG and database updated this afternoon.

**Comment by rwest** [comment]
IMO we should make reading and writing the database robust to unicode character sets.  Unicode in Python2 is a bit of a head-ache, but I think in most methods we managed to get it right eventually. Probably some lesser-used and lesser-tested parts of the code, not so much (see the comments in https://github.com/ReactionMechanismGenerator/RMG-database/pull/186 )

(Another reason to accelerate the switch to Python 3...)
