### ISSUE TITLE
TypeError: a float is required

### ISSUE THREAD

**Issue by mkovalski** [ReactionMechanismGenerator/RMG-Py#1023]
Having some issues building RMG-Py 2.1.0 from source, where I did not encounter these issues in the previous version (1.0.3)

Building this with Python 2.7.7, and when trying to run the examples, I get the following error:

  File "/path/to/RMG-Py/lib/python2.7/site-packages/rmgpy/data/kinetics/family.py", line 240, in __apply
    atom1.applyAction(['FORM_BOND', label1, info, label2])
  File "rmgpy/molecule/group.py", line 310, in rmgpy.molecule.group.GroupAtom.applyAction (rmgpy/molecule/group.c:8231)
  File "rmgpy/molecule/group.py", line 321, in rmgpy.molecule.group.GroupAtom.applyAction (rmgpy/molecule/group.c:7837)
TypeError: a float is required

The program builds to completion, but I have issues running the examples. As I said above, I had no issues building 1.0.3 with python 2.7.7 with my current setup. For reference, I'm using gcc 4.8.3. Let me know of any additional information you would need from me.

**Comment by mliu49** [comment]
Hi! We recently switched from using strings to represent bond orders to using floats, and a few changes had to be made in RMG-database to support this change. As a result, versions for RMG-Py and database from before and after this change are not cross-compatible.

The first thing I would check is whether your RMG-database is up to date. If not, you should pull the most recent version and see if that fixes your problem.

**Comment by mkovalski** [comment]
Fixed the problem, thanks!
