### ISSUE TITLE
output weight fraction instead of mol fraction

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#1026]
Is there a way to output weight fraction?
Or is there a script to convert the solver file from mol fraction to weight fraction?

**Comment by amarkpayne** [comment]
Briefly glancing at the RMG solver and the Cantera solver, I don't think there is a simple option or argument that will change the output to weight fractions (perhaps I am missing something though). However, the Molecule class has a function getMolecularWeight() that should help you do the necessary conversions using a python script. I can elaborate more if you are still working on this.

**Comment by goldmanm** [comment]
If you run your simulation in Cantera, you will utilize a `Solution` object. The mass fractions can be found by calling the attribute `solution.Y` using Cantera's python interface at any iteration during the simulation.

Which type of output are you trying to find mass fractions for?

source: http://cantera.org/docs/sphinx/html/cython/thermo.html
