### ISSUE TITLE
ThermoTests fail without internet or authentication code

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1035]
Recently updated RMG, #1030, will fail if you don't have internet connection or don't have special authentication codes. @kehang is working on disseminating the information to allow them to pass.

**Comment by KEHANG** [comment]
RMG developers should have received the auth info by now. If not or have any questions, please let me know by emailing hkh12@mit.edu

**Comment by KEHANG** [comment]
one thing I can add is to attach some decorator to those internet-required tests, developers with limited internet access can run unittests (managed by `nosetests`) with a flag turning off those tests temporarily. By the way, travis should always be able to run all the tests.

**Comment by KEHANG** [comment]
fixed by #1056. Now general users and developers without internet can run `make test` to pass the tests with no auth requirement. To pass all tests, run `make test-all`.
