### ISSUE TITLE
Error shown whenever N2 is included as an inert species

### ISSUE THREAD

**Issue by stormblessed** [ReactionMechanismGenerator/RMG-Py#1051]
Whenever I include N2 as an inert species, an error is produced. While if I remove N2 there is no error.
Since I need to use N2 as inert, please suggest me how to remove this error.
![error4](https://user-images.githubusercontent.com/29142726/27123454-3609aa20-50ee-11e7-8985-fb4a05741f9f.PNG)

**Comment by rwest** [comment]
Hi.
Please compare the species definition for your N2 to the example in 
http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/examples.html#hexadiene-pyrolysis
It should look something like this:
```python
species(
    label='N2',
    reactive=False,
    structure=InChI("InChI=1/N2/c1-2"),
)
```
If you still have errors, please share your input file (or a similar one that causes the same error).

**Comment by stormblessed** [comment]
I still have the same error.
[Main.docx](https://github.com/ReactionMechanismGenerator/RMG-Py/files/1075237/Main.docx)

**Comment by alongd** [comment]
I could run your input file fine.
The error you posted relates to forbidden structures in RMG. Did you add anything to [this file](https://github.com/ReactionMechanismGenerator/RMG-database/blob/master/input/forbiddenStructures.py) on your repository?

**Comment by stormblessed** [comment]
No I didn't.

**Comment by alongd** [comment]
Then I'm not sure what's causing this.
Please attach your RMG.log file for this run, perhaps we could find a lead there.
