### ISSUE TITLE
Sulfur Molecule Resonance

### ISSUE THREAD

**Issue by rgillis8** [ReactionMechanismGenerator/RMG-Py#1053]
I want to propose adding a new type of resonance concerning heteroatoms with lone pairs. My system cares about it's effect on sulfur chemistry but I am happy to open it to nitrogen and oxygen/keep it limited as the group thinks it is appropriate. 

Essentially it would allow radicals adjacent to lone pairs to pair with one the electrons in a lone pair to form a double bond as one representation of the molecule. Consider the following radical...

![cs o](https://user-images.githubusercontent.com/17207564/27141304-ce6d4a18-50f5-11e7-872c-2278378f03fd.JPG)

Currently the only resonance species for this species is charged...

![chargedcso](https://user-images.githubusercontent.com/17207564/27141409-11446006-50f6-11e7-9c99-af41b4191613.JPG)

I would propose the following double bonded form could also be a representation of the molecule.

![c s o](https://user-images.githubusercontent.com/17207564/27141441-2c6bd59e-50f6-11e7-9edf-cc596a0b9cd7.JPG)

The S-O bond length is calculated to be 1.499 Ang which is longer than the typical S=O bond length of 1.43 Ang which I would suggest is because both the single bond and double bond forms have some influence on the geometry.

As a second example (one that I care much more about) is this radical that appears during dimethyl sulfide oxidation and typically written/formed as...

![cs o ooc](https://user-images.githubusercontent.com/17207564/27141743-02e57aa8-50f7-11e7-98f1-afa3521efec1.JPG)

I would suggest that it has some character as...

![c s o ooc](https://user-images.githubusercontent.com/17207564/27141768-165e4704-50f7-11e7-92df-c4ce869fa20e.JPG)

... which is important as it opens a channel to the major product of DMSO2 through a disprop reaction.

Thoughts?

**Comment by nyee** [comment]
It looks reasonable. Have you considered if we need to add new atomtypes for this?

**Comment by alongd** [comment]
We have the atomTypes for it on the sulfur branch (S4s, S6d)

**Comment by mliu49** [comment]
This has been implemented :tada:
