### ISSUE TITLE
Error: Too many values to unpack

### ISSUE THREAD

**Issue by stormblessed** [ReactionMechanismGenerator/RMG-Py#1057]
Whenever I introduce a reaction library, it shows the error "Too many value to unpack"
![error](https://user-images.githubusercontent.com/29142726/27327070-a2290908-55ad-11e7-8691-e22f0c10a3d6.PNG)

**Comment by rwest** [comment]
Please try the first syntax described at https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/input.html with the False. 
The alternative syntax was only added recently 
(#943) and may not be in the version of RMG you are using (what version is reported at the top of your RMG.log?)

**Comment by stormblessed** [comment]
Version 2.1.0

**Comment by alongd** [comment]
Could you upload your input file?
