### ISSUE TITLE
Very negative Ea and fast rate from Evans-Polanyi estimate

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#1086]
@chiyw13 was investigating some very very fast reactions in her model (~10^43 at 300K) and found they had large negative activation energies. They were mostly H abstraction by the diradical `[C]#[C]`.

An example reaction is [here](http://rmg.mit.edu/database/kinetics/reaction/reactant1=1%20C%20u0%20p0%20c0%20%7B2,D%7D%20%7B3,S%7D%20%7B5,S%7D%0A2%20C%20u0%20p0%20c0%20%7B1,D%7D%20%7B6,S%7D%20%7B7,S%7D%0A3%20O%20u0%20p2%20c0%20%7B1,S%7D%20%7B4,S%7D%0A4%20O%20u0%20p2%20c0%20%7B3,S%7D%20%7B8,S%7D%0A5%20H%20u0%20p0%20c0%20%7B1,S%7D%0A6%20H%20u0%20p0%20c0%20%7B2,S%7D%0A7%20H%20u0%20p0%20c0%20%7B2,S%7D%0A8%20H%20u0%20p0%20c0%20%7B4,S%7D%0A__reactant2=multiplicity%203%0A1%20C%20u1%20p0%20c0%20%7B2,T%7D%0A2%20C%20u1%20p0%20c0%20%7B1,T%7D%0A__product1=multiplicity%202%0A1%20C%20u0%20p0%20c0%20%7B2,T%7D%20%7B3,S%7D%0A2%20C%20u1%20p0%20c0%20%7B1,T%7D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0A__product2=multiplicity%202%0A1%20C%20u0%20p0%20c0%20%7B2,D%7D%20%7B3,S%7D%20%7B4,S%7D%0A2%20C%20u0%20p0%20c0%20%7B1,D%7D%20%7B5,S%7D%20%7B6,S%7D%0A3%20O%20u0%20p2%20c0%20%7B1,S%7D%20%7B7,S%7D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0A5%20H%20u0%20p0%20c0%20%7B2,S%7D%0A6%20H%20u0%20p0%20c0%20%7B2,S%7D%0A7%20O%20u1%20p2%20c0%20%7B3,S%7D%0A), although this webpage uses slightly different groups, I think because the website does not yet use the Euclidian norm when choosing groups in the tree. But it's similar.

I think what's happening is that it wants to use the biradical C2 node `C2b` but that has no data so it falls up to generic 2-center adjacent biradical `Y_2centeradjbirad` but the value there came from averaging the only thing below it which is `O2b`, i.e. molecular oxygen. 

So it is using [O/H/NonDeC;O2b](http://rmg.mit.edu/database/kinetics/families/H_Abstraction/rules/8/) which was A=5e4 with an Evans-Polanyi α=1 estimate from @whgreen. (Side-note: the `longDesc` attribute claims it's a CBS-Q calculation by Sumathy, which is clearly incorrect. Presumably some/all of our `longDesc`s got messed up on some import/export?)

OK, so it is using an estimate that may or may not be appropriate.

But what alarms me most is that it ends up using the α=1  to predict a hugely negative activation energy.
The method [rmgpy.reaction.Reaction.fixBarrierHeight](http://reactionmechanismgenerator.github.io/RMG-Py/reference/reaction/reaction.html?highlight=fixbarrierheight#rmgpy.reaction.Reaction.fixBarrierHeight) was [intended](https://github.com/reactionmechanismgenerator/rmg-py/commit/d35614d99b853572255e103aec9b0effbbf3e016) to prevent this:
```
def fixBarrierHeight(self, forcePositive=False):
    """
    Turns the kinetics into Arrhenius (if they were ArrheniusEP)
    and ensures the activation energy is at least the endothermicity
    for endothermic reactions, and is not negative only as a result 
    of using Evans Polanyi with an exothermic reaction.
    If `forcePositive` is True, then all reactions
    are forced to have a non-negative barrier.
    """
```
(see [rmgpy/reaction.py#L569](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/efe5544b3d8c9198a29b15a4a77d5213ca209776/rmgpy/reaction.py#L569))

Did we stop calling that method at some point?
Was this accidental? 
Is it unit tested?

So there are a few thoughts:
- [x] 1. update website to use same estimation algorithm as now used in RMG?
- [x] 2. add data (or estimates) for abstraction by C2b so we don't use O2b to estimate it, if they're different?
- [x] 3. check/fix/restore/delete the `longDesc` attributes and figure out when they went wrong.
- [x] 4. fix the negative barrier heights coming from Evans Polanyi (#1089)
- [x] 5. unit tests for negative barrier heights fixes?

**Comment by whgreen** [comment]
We have run into some similar but less dramatic cases. I think we need to have a short meeting to discuss how to avoid getting really crazy rate coefficients possibly by restoring the piece of code discussed below. Could we talk on Monday?

-Bill

**Comment by rwest** [comment]
It was the paragraph your 2011 Butanol paper describing the checks ([added to RMG-Java](https://github.com/ReactionMechanismGenerator/RMG-Java/blob/3bd92bcce7d48202c935a10de5e42bc931a7782b/source/RMG/CheckForwardAndReverseRateCoefficients.java)) that nothing exceeds 10^15 which inspired @chiyw13 to start looking into this and detect the fast reactions.

**Comment by mjohnson541** [comment]
In fixBarrierHeight for ArrheniusEP negative Ea's are raised to 0 only if E0 > 0 and E0 = 0 for that rule, so at minimum the code is doing what it was originally intended to do.  It's a very easy fix if we want to have it do so for all E0.

**Comment by rwest** [comment]
Good spot, Matt!
It's doing what it was originally programmed to do - not necessarily what it was intended to do  ;-) (I can tease the original developer because it was me).
I think the aim there was to allow slightly negative Ea when they are actually intended, eg. Some rules have  E0<0 and alpha=0.  
But we could at least change it to E0>=0 instead of E0.

Or raise the barriers to min(E0,0) instead of 0, or something.

**Comment by rwest** [comment]
Point 4 from above should be addressed in https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1089 (if I did it right this time)

**Comment by rwest** [comment]
Although the immediate bug has been fixed, I'm reopening the issue for now so we don't forget points 1,2,3,5, although perhaps they should be migrated to issues on the RMG-website and RMG-database repositories (then this can be closed again)

**Comment by mjohnson541** [comment]
I can write the unittest, however another thought I had is related to point 2 and the tree structure:  

We have a rule for "C_methane;C2b" and as far as I can tell this appears to currently be our only rule associated with the C2b node.  While I'm no expert on these kinds of issues my chemical intuition tells me that [O][O] will have very different kinetics than [C][C] to the point that it would be undesirable to use any reactions/rules for [O][O] to estimate the kinetics of [C][C] reactions.  If this is the case I can set the nodalDistance for O2b very high and ensure that we don't use O2b rules for C2b reactions (this will affect both the initial averaging and how the closest node is determined).

**Comment by mjohnson541** [comment]
5 should be solved with #1090

**Comment by mjohnson541** [comment]
See new pull request in database:  [prevent the use of O2b rules in H_abstraction for abstractions not done by O2b](https://github.com/ReactionMechanismGenerator/RMG-database/pull/200)

**Comment by mjohnson541** [comment]
I've tracked 3 to the commit Manual merge of RMG-Java 8ce558. H_Abstraction family updated commit 44ea3622523811437d38a9d92267a8b57bd2d3bb of RMG-database.  But it's such a huge commit I had difficulty visualizing it locally.  As far as I can tell it appears to just be an imported mistake from RMG-Java so I think just fixing these cases in the database should be enough.

**Comment by mjohnson541** [comment]
See new pull request in database: [Fixes the longDesc attribute of two nodes that were improperly changed](https://github.com/ReactionMechanismGenerator/RMG-database/pull/201)

**Comment by mjohnson541** [comment]
I've adjusted the C2b nodalDistance to force it to use estimates from C2b for C2b rates, the longDesc attributes are fixed and I believe Max has updated the website so I'm closing this issue.
