### ISSUE TITLE
Mechanism of nitrogen compound

### ISSUE THREAD

**Issue by duychem** [ReactionMechanismGenerator/RMG-Py#1108]
Hi,
Actually i'm running RMG (version 1.0.4) to generate a mechanism of the oxidation in liquide phase of amyl nitrate (SMILE structure: CCCCCO[N+](=O)[O-]) in toluene. However, it didn't work and i got this message: 
"Error: Couldn't find in main abraham database:
Error: <Molecule "C(CCO[N+](=O)[OH2+])CC">"
Someone can help me to solve this problem, please?
Thank you in advance

**Comment by alongd** [comment]
Hi @duychem,
before dealing with the error message you got, I would first recommend you to use the latest version of RMG-Py and RMG-database (2.1.0), as major nitrogen improvements were implemented recently.
Any reason you're using v 1.0.4?

After re-running in v 2.1.0, please let us know if you get the same error message, and we'll take a look. Liquid phase in RMG is still under development, but we'll be happy to try and help you get your system to work, if possible.

**Comment by bslakman** [comment]
@duychem if it still does not work please also paste the whole error message, we will then know which specific molecular group it's not finding in the solvation database. thanks!

**Comment by duychem** [comment]
Thank you, 
I'll try the version 2.1.0
