### ISSUE TITLE
New Travis Issue

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1114]
As of about 3.5 hours ago all travis unittests builds started ending the following way:  

fetching package metadata ..........

WARNING: The remote server could not find the noarch directory for the

requested channel with url: https://conda.anaconda.org/rmg

It is possible you have given conda an invalid channel. Please double-check

your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the

channel administrator create `noarch/repodata.json` and associated

`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.

$ mkdir noarch

$ echo '{}' > noarch/repodata.json

$ bzip2 -k noarch/repodata.json

.

ResolvePackageNotFound: 

  - cantera >=2.2

The command "conda env create -f environment_linux.yml" failed and exited with 1 during .

Your build has been stopped.

**Comment by mliu49** [comment]
I haven't had any luck with figuring this out. The noarch folder does exist for the rmg channel (see https://conda.anaconda.org/rmg/noarch), and there were no apparent changes to miniconda or travis before the error began appearing.

Searching for the error did not give any particularly relevant results. There seems to have been an issue a few months ago related to the noarch folder, but it was supposedly fixed.

**Comment by mliu49** [comment]
It seems to be working again...
