### ISSUE TITLE
Improvements to Object Oriented nature of RMG

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1136]
There are some cases where RMG does not intuitively implement object oriented design. This issue is meant to be a place where multiple people can list attributes or methods that should be added, moved or deleted to make RMG more intuitive.

Possibly we could have a hackathon on a topic like this. Post some improvements below. We can also discuss why things are how they are in this issue too.

**Comment by goldmanm** [comment]
- create a multiply attribute to KineticsData (and possibly add, divide, subtract, etc) and replace instances where multiplication occurs with the simple `x * y` syntax.
- create attributes to add, subtract, multiply and divide ScalarQuantity objects.
- merge the two Species classes into one class
- move `convertToSpeciesObjects` method from rmgpy.rmg.react to rmgpy.reaction (this is my fault)
- breakup untestable methods (like `enlarge` in rmgpy.rmg.model)
- remove degeneracy attribute from Reaction and place in TemplateReaction (as long as degeneracy for Libraries is not used)

**Comment by mjohnson541** [comment]
I think execute in main and simulate in base need to be simplified using subfunctions, but I'd prefer to build these off the AcceleratorTools branches, since I've changed them so much.

**Comment by goldmanm** [comment]
I also think we might want to better modularize some parts of RMG. For example, if we want to have multiple ways to calculate which species should be added to the core, we might want to have separate classes that implement the different methods, and have an instance of one of the classes as an attribute in CoreEdgeReactionModule. If we have more than just core and edge, maybe a different class than core edge reaction module to represent the differnt methods of storing reactions. If some of this requires different information returned by solvers (or other classes), we might want to have separate inherited classes for those.

Another integration that is pretty finicky might be separating the pdep specifics from core edge reaction module, though I am less sure how this would be done. Also, the structure of estimation from families using rate rules, training reations and group additivity is not structured ideally since there is no inheritance of various estimation methods and rate rule specifics are hardcoded into family.py, database building etc. 

Ideally, I think RMG should be designed to not require changes to the core functionality, but have various inherited classes that allow for flexibility and robustness. We do this already really well with KineticsData, ThermoData, but other specific options are not implemented with independent and separate modules.

**Comment by goldmanm** [comment]
The Database objects could have structural improvements: 

* KineticsDatabase does not inherit from Database but has many similar methods
* There is not clear inheritence between different types of Entries (for example, many entry types night need to be able to add or average (though some slightly different), but the methods are not implemented with the typical operators of `+` or `*`.

**Comment by mjohnson541** [comment]
I think getting rid of the kinetics comment format in favor of real attributes should be a priority with this.

**Comment by alongd** [comment]
Then we'll need an alternative to the comment we're [adding to pdep network files](https://github.com/ReactionMechanismGenerator/RMG-Py/commit/8cae0ad20247acc56ace88b68e8f1b0c777006fe).

**Comment by goldmanm** [comment]
Thanks for the heads up @alond!
