### ISSUE TITLE
Unexpected multiple TS/degeneracy results

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1143]
So in a recent model I ran on master I got the following results:  
The reaction is:  
<img width="386" alt="screen shot 2017-08-11 at 2 41 23 pm" src="https://user-images.githubusercontent.com/7773228/29228535-194c8c6c-7ea8-11e7-82dd-cc53aa89eb4e.png"> 

! Reaction index: Chemkin #348; RMG #441
! Template reaction: intra_H_migration
! Flux pairs: S(134), S(122); 
! Estimated using template [R5H_SSSS;C_rad_out_1H;XH_out] for rate rule [R5H_SSSS;C_rad_out_H/OneDe;O_H_out]
! Euclidian distance = 1.41421356237
S(134)=S(122)                                       2.962e-02 3.277     5.996    
DUPLICATE

! Reaction index: Chemkin #349; RMG #442
! Template reaction: intra_H_migration
! Flux pairs: S(134), S(122); 
! Estimated using template [R5H_SSSS;C_rad_out_1H;XH_out] for rate rule [R5H_SSSS;C_rad_out_H/OneDe;O_H_out]
! Euclidian distance = 1.41421356237
S(134)=S(122)                                       2.962e-02 3.277     5.996    
DUPLICATE

! Reaction index: Chemkin #353; RMG #3250
! Template reaction: intra_H_migration
! Flux pairs: S(134), S(122); 
! Estimated using template [R6H_SSSSS;C_rad_out_H/NonDeC;XH_out] for rate rule [R6H_SSSSS;C_rad_out_H/NonDeC;O_H_out]
! Euclidian distance = 1.0
S(134)=S(122)                                       6.957e+02 2.675     15.250   
DUPLICATE

Things I don't understand:  
1) The first two hit the exact same node and have the exact same kinetics so why aren't they combined through degeneracy?
2) What is the transition state for the different third intra_H_migration?  I can't seem to find it.

**Comment by mliu49** [comment]
Your first point seems like a serious issue that we need to look into. For your second point, the template RMG matches can go either way around the ring, which leads to a "6-membered ring TS" vs a 7-membered ring TS" even though there should only be one actual TS.

**Comment by mjohnson541** [comment]
In that case I have a third question:  why does the other one only occur once?

**Comment by goldmanm** [comment]
Great catch! The first two reactions should have a degeneracy of 2, so their degeneracy is likely not being combined properly. Are you using the only_core_degeneracy pull request? Is this issue replicable on the master branch?

**Comment by mjohnson541** [comment]
This was on master

**Comment by goldmanm** [comment]
Trying to test using the generate reactions script but ran into #1144. I will troubleshoot this when I can figure out why the script is not working.

**Comment by goldmanm** [comment]
When using the generate reactions script, I only got the first two reactions not the third one. Can you reproduce this error with the generate reactions script?

Also, note that your model should have the overall correct reaction rates for the first two, since they should be degenerate (and multiplied by 2). Looking into debugging and fixing this.

**Comment by goldmanm** [comment]
I am a little perplexed by the origin of this. I just tested the react module with this reaction, and it found the degeneracy fine and reduced the reaction. Like the generateReactions script, it also didn't find your third reaction, which makes me think you might be using a  different version of forbidden groups in the database. The notebook reproducing this explination is [here](https://github.com/goldmanm/rmg_walkthroughs/blob/master/react%20module%20degeneracy%20check.ipynb)

I am still not sure exactly what is causing the difference in behavior from using the react.findDegeneracies method and running an entire RMG job. Possibly in model.processNewReactions, though why is degeneracy not giving the same output as it does when the react module is called directly? 

It seems like multiple things are going improperly to get both the wrong degeneracy and get added into core as separate reactions.

**Comment by mjohnson541** [comment]
Another current case:  

! Reaction index: Chemkin #469; RMG #317
! Template reaction: Diels_alder_addition
! Flux pairs: C2H4(26), C7H12(1); C5H8(72), C7H12(1); 
! Exact match found for rate rule [diene_unsub_unsub_out;diene_in_HNd;ene_unsub_unsub]
! Euclidian distance = 0
! Multiplied by reaction path degeneracy 2.0
! family: Diels_alder_addition
C5H8(72)+C2H4(26)=C7H12(1)                          2.640e+11 0.000     29.610   
DUPLICATE

! Reaction index: Chemkin #470; RMG #318
! Template reaction: Diels_alder_addition
! Flux pairs: C2H4(26), C7H12(1); C5H8(72), C7H12(1); 
! Exact match found for rate rule [diene_unsub_unsub_out;diene_in_NdH;ene_unsub_unsub]
! Euclidian distance = 0
! Multiplied by reaction path degeneracy 2.0
! family: Diels_alder_addition
C5H8(72)+C2H4(26)=C7H12(1)                          2.640e+11 0.000     29.610   
DUPLICATE

**Comment by goldmanm** [comment]
@mjohnson541, were you able to look at my previous post and do you have any conclusions from it. The notebook linked shows the results I received, which were different than what you obtained in your run. Let me know if you have any thoughts from that.

**Comment by mjohnson541** [comment]
As soon as we have quantum calculations I'm going to run the model over again.  I'll update this and see if the issue is fixed.
