### ISSUE TITLE
generateReactions.ipynb raises `UnicodeEncodeError` with current Master DB and RMG

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1144]
I tried to run `generateReactions.ipynb` but obtained a `UnicodeEncodeError` when loading the database. This was on the current Master for RMG-Py and RMG-database (with `make clean` and `make` run, and all unittests passing). I am wondering if anyone can replicate this error. For some reason, my computers (running Ubuntu 12.04, 16.04 and 16.10) are sometimes generating wrong results that other people on the same branch of database and rmgpy are not getting. Anyways, the traceback for this issue is:

```
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-5-d39a13bbdfc8> in <module>()
      8     }
      9 rmg = RMG(inputFile='temp/input.py', outputDirectory='temp')
---> 10 rmg = execute(rmg, **kwargs)

/home/mark/workspace/RMG-Py/rmgpy/tools/generate_reactions.pyc in execute(rmg, **kwargs)
    143     """   
    144     import numpy
--> 145     rmg.initialize(**kwargs)
    146 
    147     rmg.reactionModel.enlarge(reactEdge=True,

/home/mark/workspace/RMG-Py/rmgpy/rmg/main.pyc in initialize(self, **kwargs)
    393 
    394         # Load databases
--> 395         self.loadDatabase()
    396 
    397         # Do all liquid-phase startup things:

/home/mark/workspace/RMG-Py/rmgpy/rmg/main.pyc in loadDatabase(self)
    332                                 f.write("Template [{0}] uses the {1} following source(s):\n".format(template_label,str(len(entries))))
    333                                 for entry_index, entry in enumerate(entries):
--> 334                                     f.write(str(entry_index+1) + ". " + entry.shortDesc + "\n" + entry.longDesc + "\n")
    335                                 f.write('\n')
    336                             f.write('\n')

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 228: ordinal not in range(128)
```

Let me know if you can replicate this on your system.

**Comment by mliu49** [comment]
I was able to replicate this error. It's due to some newly added entries in the database that have unicode characters in the reference. Those unicode characters were also what kept the database rewrite PR from getting merged...

This particular issue is due to Python not being able to encode those unicode characters using ascii. It can be solved by opening the file using the UTF-8 encoding: replace the open command on [this line](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/rmg/main.py#L330) with `codecs.open(path, 'w', 'UTF-8')` and import codecs.

I think we might need to review all of our file IO methods, and have them read/write using UTF-8 encoding. The alternative is enforcing acsii only in RMG-database. Also, Python 3 makes unicode support the default, so it might be good to get our file IO straightened out before then.

**Comment by goldmanm** [comment]
This unicode issue has come up a lot before. I have spent hours trying to find the source of the encoding errors and not come up with any fruit for that labor. Also, this issue has held up many other advances (like machine writing database, etc). 

I am in favor of requiring ASCII in documentation until we upgrade to python 3, where the whole encoding is hopefully clearer.

**Comment by goldmanm** [comment]
See also [database issue](https://github.com/ReactionMechanismGenerator/RMG-database/pull/186) and #1022 .

**Comment by alongd** [comment]
We have plenty of non-ASCII characters in our database, such as in:
`Aäron`
`Güthe`
`–` (not `-`)
`NH(X3Σ−)`
`Röhrig`
... and so on.

Shall we convert all `ä` into `a`, `ö` into `o`, and so on?
Or shall we simply shift to Py3 already...?

**Comment by goldmanm** [comment]
I like your joke on the challenge of switching :)

We could just remove the dots. Alternatively we could 'code' them so it is clear if someone un-does them after converting. Many code options can work, though I am most familiar with latex which was built originally on ascii and wrote nice codes for representing non-ascii. 

for the double dots `\ddot{a}` or \ddot{u}`
Any greek letter is just the letters name `\Sigma` for capital and `\sigma` for lower case
The longer dash is just two short dashes `--`

**Comment by alongd** [comment]
Let's do it (easier than switching...).

-  `–`
Long dashes can be replaced by regular dashes, they don't stand for anything different in our context.

- `ä`, `ü`, `ö`
I also think we could just remove the dots (and I hope no one gets angry here...)
It will be harder to read `G\ddot{u}the` in the database, and anyway the database is not encoding for any other format.

- 'Σ'
OK, lets replace with `\Sigma`

@goldmanm, will you be able to test it after these conversions?

**Comment by goldmanm** [comment]
yeah. Just wrote a test script to test it out.
