### ISSUE TITLE
Forbidden Species Generated in Minimal Example

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/RMG-Py#1147]
I was reviewing #1141 and I stumbled upon the following error. In order to test this pull request I ran the minimal example for a wall-time of 3 minutes to generate a intermediate seed mechanism, with the idea being to use this as a restart mechanism. I followed @mjohnson541's instructions and added the seed mechanism files to the appropriate place in my RMG-database folder (see #1141 for more details). In a new directory, I modified the minimal input.py file to add the core seed mechanism to `seedMechanisms` and the edge seed mechanism to `reactionLibraries` and re-ran the RMG job.

The job crashed due to a forbidden structure that it was trying to load from the reaction library for my edge mechanism.

[species_edge_dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/1223490/species_edge_dictionary.txt)

[bad_molecule.ipynb.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/1223493/bad_molecule.ipynb.zip)

Looking at the error log (below), it appears that species `[CH]C=C` is a forbidden species. You can confirm this if you want using the ipython script `bad_molecule.ipynb` (attached). This script (if I did everything right) loads the exact same database as the minimal example. NOTE: You will need to change the location of the RMG folder in this script.

Looking in the `species_edge_dictionary.txt` file (attached), it appears that this specie was in fact generated and placed in the minimal edge (I believe it is specie `C3H4(41)`).

With this, I believe that `[CH]C=C` is in fact a globally forbidden species, but was generated in the minimal example, which if true should not happen. Perhaps it is a bug with how we check species before adding them to the edge?

```
After model enlargement:
    The model core has 19 species and 103 reactions
    The model edge has 1 species and 0 reactions

Adding reaction library edgeTest_edge to model edge...
Traceback (most recent call last):
  File "/home/mark/RMG/RMG-Py/rmg.py", line 162, in <module>
    rmg.execute(**kwargs)
  File "/home/mark/RMG/RMG-Py/rmgpy/rmg/main.py", line 534, in execute
    self.initialize(**kwargs)
  File "/home/mark/RMG/RMG-Py/rmgpy/rmg/main.py", line 428, in initialize
    self.reactionModel.addReactionLibraryToEdge(library)
  File "/home/mark/RMG/RMG-Py/rmgpy/rmg/model.py", line 1344, in addReactionLibraryToEdge
    raise ForbiddenStructureException("Species {0} from reaction library {1} is globally forbidden. You may explicitly allow it, but it will remain inert unless found in a seed mechanism or reaction library.".format(spec.label, reactionLibrary.label))
rmgpy.exceptions.ForbiddenStructureException: Species [CH]C=C from reaction library edgeTest_edge is globally forbidden. You may explicitly allow it, but it will remain inert unless found in a seed mechanism or reaction library.
```

**Comment by amarkpayne** [comment]
I found the following code in the `makeNewSpecies` method of `CoreEdgeReactionModel` in `rmgpy/rmg/model.py`. Particularly line 308 is interesting, as it has a comment for `# Check that the structure is not forbidden`, but there is no code for this here. @mjohnson541 suggested that this code should be done at the family.py level, so that each family also checks for globally forbidden structures.

So the question is do we need code here to check for globally forbidden structures, or do we need to delete this comment? 

```
        # If desired, check to ensure that the species is new; return the
        # existing species if not new
        if checkForExisting:
            found, spec = self.checkForExistingSpecies(molecule)
            if found: return spec, False

        # Check that the structure is not forbidden

        # If we're here then we're ready to make the new species
        if reactive:
            self.speciesCounter += 1   # count only reactive species
            speciesIndex = self.speciesCounter
        else:
            speciesIndex = -1
        try:
            spec = Species(index=speciesIndex, label=label, molecule=[molecule], reactive=reactive,
                 thermo=object.thermo, transportData=object.transportData)
        except AttributeError, e:
            spec = Species(index=speciesIndex, label=label, molecule=[molecule], reactive=reactive)
```

**Comment by mliu49** [comment]
It seems that Josh added that comment as a placeholder when he first created the module. We do currently check forbidden structures at the family.py level, upon generating product structures.

**Comment by mjohnson541** [comment]
I'm pretty sure we only check the structures forbidden by a given family at the family level, not the globally forbidden structures.

**Comment by mliu49** [comment]
In [`KineticsFamily().isMoleculeForbidden`](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/data/kinetics/family.py#L1325), both the family forbidden structures (`self.forbidden`) and the global forbidden structures (`getDB('forbidden')`) are checked.

**Comment by mjohnson541** [comment]
Oh, sorry, I guess I was just looking a where they loaded the forbidden attribute.

**Comment by mliu49** [comment]
We came up with a new theory which makes sense, but has not been explicitly verified. The species `:C-C=C` is forbidden as a carbene, but it has a resonance structure which is `.C=C-C.` which is not forbidden. Therefore, if the product that was generated is `.C=C-C.`, it would not be caught by the forbidden structures check. Then, when it's made into a new species, its resonance structures would be generated and the carbene form would be created, despite being forbidden.

This raises the question of what we want to do if only one resonance form of a species is on the forbidden species list.

**Comment by mjohnson541** [comment]
It appears that for now declaring allowed = ['seed mechanism', 'reaction libraries'] in the generatedSpeciesConstraints block should be sufficient to avoid the error when loading the output libraries.
