### ISSUE TITLE
Documentation problems: symmetry

### ISSUE THREAD

**Issue by nateharms** [ReactionMechanismGenerator/RMG-Py#1150]
https://reactionmechanismgenerator.github.io/RMG-Py/reference/molecule/symmetry.html

The documents for the molecule/symmetry method on RMG website fail to load. 

Below is the error listed:

`System Message: WARNING/2 (/home/mark/workspace/RMG-Py/documentation/source/reference/molecule/symmetry.rst, line 5)

autodoc: failed to import function ‘calculateAtomSymmetryNumber’ from module ‘rmgpy.molecule.symmetry’; the following exception was raised: Traceback (most recent call last): File “/home/mark/anaconda3/lib/python3.6/site-packages/Sphinx-1.5.1-py3.6.egg/sphinx/ext/autodoc.py”, line 547, in import_object __import__(self.modname) File “/home/mark/workspace/RMG-Py/rmgpy/molecule/__init__.py”, line 31, in <module> from .atomtype import * ImportError: dynamic module does not define module export function (PyInit_atomtype)`

**Comment by amarkpayne** [comment]
This appears to be my fault, as it is trying to reference a file using the path on my computer (unless the mark here is @goldmanm). I updated the documentation a while ago on #1005, and I guess something didn't go right when I did this. Let me see what I can figure out.

**Comment by amarkpayne** [comment]
I first thought that this might be something I did because it was referencing a local file for 'mark' but I realized that my RMG directory is not under workspace. @goldmanm could this be trying to reference a file on your local machine?

**Comment by zjburas** [comment]
I think this issue is the same as RMG-website Issue [#160](https://github.com/ReactionMechanismGenerator/RMG-website/issues/160)

**Comment by mliu49** [comment]
It seems that the most recent documentation update had import issues. None of the module specific pages are available. The documentation will need to be rebuilt and pushed.

I can do it. I should probably learn how anyway.

**Comment by goldmanm** [comment]
#1154
