### ISSUE TITLE
API not updated or accurate

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1153]
Our API is only somewhat automatic. It is automatic below the class level, but requires manual addition for new classes and modules.

The API seems to be years behind in adding new methods.

Also note that the Wiki doesn't describe the API updating.

It seems like we could do 3+ things:

1. move to an entirely automated api (we will lose the pretty formatting but everything will be accurate and docstrings will be utilized more effectively)
1. manually update the api pages that require manual updating (anything not stored in a Class structure)
1. deprecate the api (source code for the win!)
1. keep as status quo (confusion is a source of strength!)

**Comment by amarkpayne** [comment]
I think that having an accurate and up to date API is more important than having an out of date API that looks pretty. What would we use to do this? Can we try this out just to see what it would look like?

**Comment by mliu49** [comment]
#1273 updates some portions of the API. I mainly fixed updated things that I noticed while doing other things, so it isn't a thorough update.

We can definitely consider a fully automated API, although we would need to look into how to do that and exactly what that would look like.
