### ISSUE TITLE
Travis Build Hung-up on 'Test that Mocpac getThermoData() works correctly'

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/RMG-Py#1163]
This error is present in #1155, #1161, and #1162, so I think it is safe to say that this is an issue with Travis and not with these pull requests.

I think others in the group have seen this happen locally when running unit tests on Windows, such as @mliu49.

**Comment by amarkpayne** [comment]
For what it's worth, some of our dependencies were updated right when this issue occurred. Below is the difference between the latest conda environment and one I had made a couple days before this issue.

```
1c1
< # packages in environment at /home/mark/anaconda2/envs/newest:
---
> # packages in environment at /home/mark/anaconda2/envs/rmg_env:
50a51,52
< markupsafe                1.0                      py27_0  
---
> markupsafe                0.23                     py27_2  
89c91
< prompt_toolkit            1.0.15                   py27_0  
---
> prompt_toolkit            1.0.14                   py27_0  
119c121
< ssl_match_hostname        3.5.0.1                  py27_0  
---
> ssl_match_hostname        3.4.0.2                  py27_1  
133c135
< xz                        5.2.3                         0  
---
> xz                        5.2.2                         1  
135c137
< zlib                      1.2.11                        0  
---
> zlib                      1.2.8                         3  
```

**Comment by mliu49** [comment]
Seems like the MOPAC executable has expired. The Anaconda package was prepared exactly a year ago. The message can be ignored by pressing enter, but the subprocess call does not do that, so it hangs indefinitely. Potential solutions: 1) make new Anaconda packages, 2) press enter to continue. It seems that sending enter to the subprocess allows it to continue running without any problems. Idk why MOPAC makes their executables expire...

```
Your MOPAC executable, Version: 16.175M, has expired.
Please go to web-site: http://openmopac.net/Download_MOPAC_Executable_Step2.html to get a new version of MOPAC.
Do NOT request a new license key.  Academic license keys do not include time limits - the limit is in the program.

Press (enter) to continue.
```

**Comment by amarkpayne** [comment]
It just passed. Thanks @mliu49 for the fix! I'll close out this issue then.

**Comment by mliu49** [comment]
Personally, I think it's better to leave issues open until the fix has been merged into master. I'd also like to test this on Windows to see if that issue is also fixed before merging.

**Comment by rwest** [comment]
Although I kind of like the "automatically hit return" trick I think we should not hide an expired mopac silently (i.e. we should print a warning that we're hitting return because mopac has expired).

Although I find it annoying having to keep updating our binaries, he does this for a reason: to ensure people install bugfix updates.http://openmopac.net/maintenance.html 

We should update our conda package somewhat frequently.
