### ISSUE TITLE
MakeProfileGraph does not work on remote servers (profiling issue)

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/RMG-Py#1173]
I saw that others were doing profiling runs on remote servers, and I realized that I forgot to post an issue about this. When you run profiling on a remote server with the `-p` flag, the job gets hung up after model generation completion. I believe this is due to MakeProfileGraph needing to access the display in order to generate the profiling pdf. You can see this is the case by doing a profile run on the head node while forward your Xserver by `ssh -Y`.

To avoid this issue, you can cherry-pick two commits from my branch `profile_tools`. The first commit comments out the call to MakeProfileGraph (the profile stats will still be saved to the `RMG.profile` file). The second commit also prints the local time for each function in seconds in the profile graph pdf.

To make this work, you will need to copy the RMG.profile file to your local PC, and then run `python $RMG input.py -P`. A capital `-P` flag does not run the RMG job again but rather just generates the pdf.

**Comment by rwest** [comment]
Could some of these from https://github.com/amarkpayne/RMG-Py/commits/Profiler_Tools be worth making a pull request out of?  (Or some other way to close this issue?).
