### ISSUE TITLE
Negative Ea being raised to 0 automatically when running Pdep RMG job

### ISSUE THREAD

**Issue by jimchu10** [ReactionMechanismGenerator/RMG-Py#1175]
After importing the vTST rates for the propargyl recombination as the training reactions, which have negative barrier Ea, I ran the RMG Pdep job. When the RMG job is done, I looked into the Pdep network generated from RMG itself. In the reaction section:

reaction(
    label = 'reaction1',
    reactants = ['C#C[CH2](133)', 'C#C[CH2](133)'],
    products = ['C#CCC=C=C(333)'],
    transitionState = 'TS1',
    kinetics = Arrhenius(A=(1.307e+12,'cm^3/(mol*s)'), n=0.192, **Ea=(0,'kJ/mol')**, T0=(1,'K'), comment="""Matched reaction 29 C3H3 + C3H3-2 <=> CH2CCHCH2CCH in R_Recombination/training
**Ea raised from -2.8 to 0 kJ/mol**."""),
)

The Ea was automatically adjusted to 0. If the rates are estimated by RMG, I believe correcting the negative barrier would be reasonable. However, if the rates come from training reactions or rate rules, the negative barrier should be kept; otherwise, the kinetics will be inaccuratre.

**Comment by rwest** [comment]
IIRC there may be an additional complication for pdep networks in that they can't be solved with a negative barrier. Worth looking in to but may be more complicated than just letting the negative activation energies through...
