### ISSUE TITLE
dependance

### ISSUE THREAD

**Issue by chemk** [ReactionMechanismGenerator/RMG-Py#1176]
'cairo not found-molecule will not be drawn' is an error message i get as i run rmg in anacoda, i have tried to install cairo but its not detected.

**Comment by mliu49** [comment]
Hello, thanks for posting your issue! Could you let us know what system you're running on and what installation method (anaconda binary or anaconda from source) you used?

**Comment by chemk** [comment]
Am running on win10 64bit, anacinda binary


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Max Liu <notifications@github.com> Date: 25/08/2017  12:35 am  (GMT+05:30) To: ReactionMechanismGenerator/RMG-Py <RMG-Py@noreply.github.com> Cc: chemk <ronaldkimekye@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [ReactionMechanismGenerator/RMG-Py] dependance (#1176) 
Hello, thanks for posting your issue! Could you let us know what system you're running on and what installation method (anaconda binary or anaconda from source) you used?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ReactionMechanismGenerator/RMG-Py","title":"ReactionMechanismGenerator/RMG-Py","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ReactionMechanismGenerator/RMG-Py"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mliu49 in #1176: Hello, thanks for posting your issue! Could you let us know what system you're running on and what installation method (anaconda binary or anaconda from source) you used?"}],"action":{"name":"View Issue","url":"https://github.com/ReactionMechanismGenerator/RMG-Py/issues/1176#issuecomment-324727961"}}}

**Comment by chemk** [comment]
I installed the binary version via anaconda on a win10  64bit computer.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Max Liu <notifications@github.com> Date: 25/08/2017  12:35 am  (GMT+05:30) To: ReactionMechanismGenerator/RMG-Py <RMG-Py@noreply.github.com> Cc: chemk <ronaldkimekye@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [ReactionMechanismGenerator/RMG-Py] dependance (#1176) 
Hello, thanks for posting your issue! Could you let us know what system you're running on and what installation method (anaconda binary or anaconda from source) you used?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ReactionMechanismGenerator/RMG-Py","title":"ReactionMechanismGenerator/RMG-Py","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ReactionMechanismGenerator/RMG-Py"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mliu49 in #1176: Hello, thanks for posting your issue! Could you let us know what system you're running on and what installation method (anaconda binary or anaconda from source) you used?"}],"action":{"name":"View Issue","url":"https://github.com/ReactionMechanismGenerator/RMG-Py/issues/1176#issuecomment-324727961"}}}

**Comment by mliu49** [comment]
When you tried to install cairo manually, what method did you use? If you did not do it via anaconda, then it might be a good idea to try and uninstall it.

I think there is an issue with the win64 cairo package currently in the RMG-Py conda channel. This is something that we will need to resolve on our end, but you can install cairo from a different channel to immediately fix your issue.

Make sure you have the rmg conda environment activated:
```
activate rmg_env
```
Then you should uninstall the default cairo which was installed:
```
conda remove cairo
```
Finally, install a working cairo package from a different channel:
```
conda install cairo -c conda_forge
```
Please let us know if this fixes the issue.

**Comment by chemk** [comment]
PackageNotFoundError: Packages missing in current channels:

  - cairo

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/conda_forge/win-64
  - https://conda.anaconda.org/conda_forge/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch
That is the feed back i get

**Comment by mliu49** [comment]
Sorry, there was a typo in the command I gave. It should be `conda-forge` with a hyphen instead of an underscore.

**Comment by chemk** [comment]
am trying again after appending cairo at the end and it seems its installing i will update you. thanks a lot

**Comment by chemk** [comment]
the problem still persists, any further help is highly appreciated

**Comment by mliu49** [comment]
Ahh, I might know what's wrong. The dependency list for creating the windows binary has not been updated, so `cairo` and `cairocffi` are not automatically installed. I had assumed that they were. You will need to also install `cairocffi`:
```
conda install -c rmg cairocffi
```
I expect that this will fix the error.

**Comment by chemk** [comment]
Thank you very much the issue has been resolved


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Max Liu <notifications@github.com> Date: 25/08/2017  3:09 am  (GMT+05:30) To: ReactionMechanismGenerator/RMG-Py <RMG-Py@noreply.github.com> Cc: chemk <ronaldkimekye@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [ReactionMechanismGenerator/RMG-Py] dependance (#1176) 
Ahh, I might know what's wrong. The dependency list for creating the windows binary has not been updated, so cairo and cairocffi are not automatically installed. I had assumed that they were. You will need to also install cairocffi:
conda install -c rmg cairocffi

I expect that this will fix the error.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ReactionMechanismGenerator/RMG-Py","title":"ReactionMechanismGenerator/RMG-Py","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ReactionMechanismGenerator/RMG-Py"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mliu49 in #1176: Ahh, I might know what's wrong. The dependency list for creating the windows binary has not been updated, so `cairo` and `cairocffi` are not automatically installed. I had assumed that they were. You will need to also install `cairocffi`:\r\n```\r\nconda install -c rmg cairocffi\r\n```\r\nI expect that this will fix the error."}],"action":{"name":"View Issue","url":"https://github.com/ReactionMechanismGenerator/RMG-Py/issues/1176#issuecomment-324764948"}}}

**Comment by chemk** [comment]
I have issues with finding kinetics library, how do I add missing kinetic libraries.

**Comment by chemk** [comment]
Am getting an error message "couldn't find kinetic library"

**Comment by alongd** [comment]
I'm not entirely sure what you mean by "missing" reaction libraries.
See [4.2.2. Reaction Libraries](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/input.html#datasources) in RMG's documentation for general directions, or look at the example input files under the `examples/rmg` folder of your RMG-Py installation.
If this still isn't clear, please feel free to open a new issue to discuss it. Also, if you still experience problems it would be helpful to attach the Error Traceback that RMG outputs. Good luck!
