### ISSUE TITLE
Resonance isomers of oxygenated species

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#118]
Shouldn't these two things be resonance isomers?
![o c c c ch2 19455](https://f.cloud.github.com/assets/93807/589132/8e089d6e-c9aa-11e2-8810-194460572c09.png)
![cc c c o 496](https://f.cloud.github.com/assets/93807/589133/91dd5060-c9aa-11e2-9330-186c93f426be.png)

I may be mistaken, but they seem to be showing up as different species (whose Enthalpies at 800K differ by 224.2 kJ/mol).

**Comment by alongd** [comment]
We currently don't allow resonance transformations to change the multiplicity (we had a recent version of the code that does that for this exact case, but abandoned it in favour of the irreversible `1,2-Birad_to_alkene` family, recently elaborated for heteroatoms)

@rwest , should we close this old issue, or is this something you think requires more discussion?

**Comment by rwest** [comment]
I think it can be closed. 
(4.5 years!)
