### ISSUE TITLE
symmetry number of phenoxy radical is 1 (should be 2)

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#119]
phenoxy:

InChI=1S/C6H5O/c7-6-4-2-1-3-5-6/h1-5H

I found 1 through rmg.mit.edu.

RMG-Java still finds 2. so this means that the algorithm for calculating symmetry numbers is changed.

**Comment by goldmanm** [comment]
I can still reproduce this error on unittests.

**Comment by goldmanm** [comment]
fixed with #1014
