### ISSUE TITLE
Website kinetics search broken

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1192]
Recent changes to how reaction are generated in RMG-Py has broken the kinetics search functionality of the website. The live website is still using an old version of RMG-Py, so it doesn't interfere with website usage at the moment. However, the website cannot be updated until these issues are addressed.

For the kinetics search function, the website uses `KineticsDatabase.generateReactionsFromFamilies()` which calls `KineticsFamily.generateReactions()`. Previously, that was sufficient to get properly processed reactions. However, the post-processing has now been moved to the `rmgpy.rmg.react` module.

Additionally, group additivity for kinetics estimation now works again (#1061), so the website will actually give group additivity estimates. However, I have no idea whether or not those estimates are good or not.

Finally, the website doesn't handle multiple transition states at all, so changes will need to be made there as well.

**Comment by goldmanm** [comment]
I can refactor `KineticsDatabase.generateReactionsFromFamilies()` to use `react.reactSpecies()` instead of `KineticsFamily.generateReactions()`, so that no extra work is needed on the website for that issue....if that would be helpful. 

Maybe I'll manage to write a unittest for `generateReactionsFromFamilies` while I am at it :)

**Comment by mliu49** [comment]
Thanks, I don't think you need to work on it right away though. There are some broader organizational issues that I'm not quite sure about and would like to discuss with you at some point after I sort out my thoughts.

**Comment by mliu49** [comment]
The website has been updated following #1231, so this issue is now fixed.
