### ISSUE TITLE
bond symmetry number unreliable

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#12]
Commit 0d837833f816e44e06ab77c680215b44b8d0f94b hid a bug which should be looked at further.
This is the commit message:

> The function Structure.split() returns a list of structures that result from
> the splitting. In calculateBondSymmetryNumber(), this function was assumed to
> return exactly two structures, which it should if things are going normally.
> However, this behavior is not guaranteed, so a check was added to ensure that
> exactly two structures are returned from split(). If not, the function returns
> 1, which is as if it was not called for that bond.

**Comment by goldmanm** [comment]
bond symmetry unit tests are functioning properly.
