### ISSUE TITLE
test_collisionMatrixMemoryHandling can fail when memory is low

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1215]
I don't think this is a major issue, although it is somewhat annoying. This unit test fails for me more than half the time on my virtual machine with 4GB memory. I think what happens is that it actually runs out of memory at [this line](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/pdep/network.py#L710) before the try/except statement that is meant to handle memory errors.

**Comment by mjohnson541** [comment]
Well we could just move that line into the try/except, I don't think that would really hurt anything.

**Comment by alongd** [comment]
Should be solved via #1274
@mliu49 , would you like to check this works?

**Comment by mliu49** [comment]
I increased my vm's memory allocation, so I can't test this easily right now. I'm open to suggestions for memory intensive tasks that I can run at the same time, but otherwise, I'm ok with closing this issue.
