### ISSUE TITLE
Does molecule.parser.check(mol, aug_inchi) work as intended?

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#1218]
The [check(mol, aug_inchi)](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/parser.py#L224) function in molecule.parser requires an `aug_inchi` parameter as input and its docstring also mentions that it compares the multiplicity in that aug_inchi to the number of rads in the molecule object.

However, it does not use the `aug_inchi` at all. It simply compares  `mol.getRadicalCount()` and `mol.multiplicity`. This is OK, but not what was originally intended.

As far as I can see, it is only called by [molecule.parser.fix(mol, aug_inchi)](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/parser.py#L687) (used in `fromAugmentedInChI`), which allegedly fixes the molecule object according to its `aug_inchi`.

**Comment by KEHANG** [comment]
I think it probably is not intended. Maybe we can fix it by calculating multiplicity from aug_inchi's `u_indices` then use it to replace `mol.multiplicity` in the method `check(mol, aug_inchi)`.

**Comment by alongd** [comment]
fixed by #1214
