### ISSUE TITLE
Arrhenius parameters

### ISSUE THREAD

**Issue by sarahkha** [ReactionMechanismGenerator/RMG-Py#1238]
As regards with the Cantherm kinetic calculations, would it be possible to have the values of fitted k shown in a Table with the values of calculated k in the output file?

**Comment by alongd** [comment]
Definitely possible, I just hope it won't confuse users (any thoughts?).
For a quick half-baked solution, try checking out [this branch](https://github.com/alongd/RMG-Py/tree/unfitted) to get the unfitted k values printed in the command line.

**Comment by alongd** [comment]
From an offline discussion with @sarahkha, we concluded the the current data in CanTherm's output (calculated k values and fitted Arrhenius with A/n/Ea deviation) is sufficient.
I'm closing this issue for now, if the need to output the fitted k values at the given `Tlist` arises again we'll reconsider it.
