### ISSUE TITLE
Sanitization error: Explicit valence for atom # 5 N, 4, is greater than permitted

### ISSUE THREAD

**Issue by redBirdTx** [ReactionMechanismGenerator/RMG-Py#1278]
Hi, 
I am using rdKit 2017.09 release. With some molecules, I am getting ValueError: Sanitization error: Explicit valence for atom # 5 N, 4, is greater than permitted. Below is the call stack.

I searched the past issues and it seemed had been fixed. Any thing that i could do to get around? Thanks!

```
  File "C:\Users\AAA\Documents\Deep learning\GAN\ChemGAN-challenge-master\model\mol_metrics.py", line 299, in logP
    logp = Crippen.MolLogP(Chem.MolFromSmiles(smile))

  File "C:\ProgramData\Anaconda3\lib\site-packages\rdkit\Chem\Crippen.py", line 170, in <lambda>
    MolLogP = lambda *x, **y: rdMolDescriptors.CalcCrippenDescriptors(*x, **y)[0]

ValueError: Sanitization error: Explicit valence for atom # 5 N, 4, is greater than permitted
```

**Comment by alongd** [comment]
(related to #590)
We can try to help.
Can you confirm that you work on the updated master branch on both RMG-Py and RMG-database repositories (or that this is a relatively new install of RMG)?
Also, please upload your RMG input file so we can reproduce this error and try debugging it.

**Comment by mliu49** [comment]
Looking at this again, it seems like the original issue was with RDKit and not related to RMG.

This is a known "issue" with RDKit (in the sense that they choose to explicitly not accept hypervalent nitrogen). RMG avoids this by using OpenBabel for nitrogen related operations.

**Comment by coltonbh** [comment]
@mliu49 Is there any parameter that can be passed to `rdkit` to force it to allow hypervalent nitrogens?

**Comment by mliu49** [comment]
@coltonbh, not that I know of. I think RDKit is fairly strict about this. The only option is to reformulate your structure using partial charges, e.g. `X=X -> [X-][X+]`. There are some cases which are handled automatically by RDKit during sanitization (see [here](http://www.rdkit.org/docs/RDKit_Book.html#molecular-sanitization)), but not all cases are. This [email thread](https://sourceforge.net/p/rdkit/mailman/rdkit-discuss/thread/CAD4fdRRU9+gnQdP7nCkshjz-9s3H1wk=Zu49F+1M_PvnjsOA9g@mail.gmail.com/) also provides some explanation for this behavior.

**Comment by coltonbh** [comment]
@mliu49 Great resources! And thanks for the quick response. Super helpful.
