### ISSUE TITLE
Discontinuity in GAV Cp

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#1280]
Cp from[ GAV for [N]=S](http://rmg.mit.edu/database/thermo/molecule/multiplicity%202%0A1%20N%20u1%20p1%20c0%20%7B2,D%7D%0A2%20S%20u0%20p2%20c0%20%7B1,D%7D%0A) (and presumably many other species) has a discontinuity at 1500 K.
The groups all have reasonable values up to 1500 K, but I'm not sure where the Cp(inf) value is derived from, which probably causes this:
![image](https://user-images.githubusercontent.com/16158262/36047596-9376ae64-0daa-11e8-8fcc-97bd28a5c818.png)

**Comment by alongd** [comment]
also true for [azide](http://rmg.mit.edu/database/thermo/molecule/1%20N%20u0%20p2%20c-1%20%7B2,S%7D%20%7B3,S%7D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D%0A3%20N%20u0%20p0%20c+1%20%7B1,S%7D%20%7B4,T%7D%0A4%20N%20u0%20p1%20c0%20%7B3,T%7D%0A)

**Comment by mliu49** [comment]
This has been brought up before (#792). I think the conclusion last time was that group additivity was giving a bad estimate for Cp.

Cpinf is calculated by counting the number vibrational and rotational modes ([here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/molecule.py#L1552)). In the two examples you give, it the Cpinf value appears to be much closer to the library values, which makes sense.

The solution would then be improving the group additivity estimates for these species.

**Comment by mliu49** [comment]
Also, note that the process of fitting a NASA polynomial removes the discontinuity, for better or for worse.

**Comment by alongd** [comment]
Thanks @mliu49
I agree that the GAV should be improved.
Shouldn't we add a fix such as limiting the cumulative Cp from groups to CPinf, or leave things as they are (and of course improve heteroatom GAV, which is a know task)?

**Comment by mliu49** [comment]
That's an interesting idea. Does Cp always monotonically increase with temperature? If so, it would definitely be possible to limit Cp to Cpinf.

**Comment by alongd** [comment]
I think Cp is a monotonic function of T: a molecule should only gain degrees of freedom as T increases.
I saw one esoteric contra-example ([Schottky anomaly](https://en.wikipedia.org/wiki/Schottky_anomaly)), but it should be safe to implement this assumption for the type of systems relevant to RMG.

**Comment by alongd** [comment]
Prof. Green corrected me in the last sub-group meeting that internal rotors have an ideal Cp = R at low T when they are hindered and behave as vibrations, while at higher T when they fully rotate they have Cp = 0.5 * R. Several of these throughout a molecule can cause Cp to decrease with increasing T.

We could define a more conservative Cp inf. estimation where all rotors are counted as having Cp = R (not 0.5 * R), which could be an upper boundary for GAV Cp at any T.

**Comment by JacksonBurns** [comment]
FWIW, this discontinuity is now gone (although the GAV plot still doesn't look _great_):

![image](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/33505528/81caa39d-499a-4ba3-8e50-421001bb0cb7)

I'm going to close this as 'resolved' since the original error seems to have been resolved since this was first opened.

**Comment by JacksonBurns** [comment]
The azide example linked above has also been resolved:

![image](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/33505528/a4f6d34b-5c15-4e4b-acfe-75a6d2411cf5)
