### ISSUE TITLE
Vanilla seed mechanisms are broken as a result of restart seed mechs

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1286]
Seed mechanisms are now assumed to be for restarting, so the comments are parsed for kinetics library/family information. However, if one intends to use a seed mechanism as is and load a different set of database settings than the ones used to generate the seed mechanism, RMG will crash because it can't properly load the seed mechanism.

It would be ideal if there could be an option to choose whether to load a seed mechanism as a library or as a restart mechanism.

**Comment by mliu49** [comment]
Here is an easily replicable example, although there are plenty of more complex situations. The motivation for doing something like this might be generation of cross reactions after merging two independently generated mechanisms. In such a case, the database being loaded would be completely different (i.e., different kinetics libraries and families), causing seed mechanism loading to fail.

1. Run the superminimal example and save the seed mechanism to RMG-database.
2. Run the superminimal example again, setting the seed mechanism to `['Seed']` and families to any single family, e.g. `['H_Abstraction']`.
3. The run crashes:

```
Traceback (most recent call last):
  File "../../../rmg.py", line 173, in <module>
    main()
  File "../../../rmg.py", line 167, in main
    rmg.execute(**kwargs)
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/main.py", line 532, in execute
    self.initialize(**kwargs)
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/main.py", line 420, in initialize
    self.reactionModel.addSeedMechanismToCore(seedMechanism, react=False)
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/model.py", line 1422, in addSeedMechanismToCore
    r, isNew = self.makeNewReaction(rxn) # updates self.newSpeciesList and self.newReactionlist
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/model.py", line 488, in makeNewReaction
    found, rxn = self.checkForExistingReaction(forward)
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/model.py", line 385, in checkForExistingReaction
    familyObj = getFamilyLibraryObject(rxn.family)
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/model.py", line 1936, in getFamilyLibraryObject
    raise Exception('Could not retrieve the family/library: {}'.format(label))
Exception: Could not retrieve the family/library: R_Recombination
```

**Comment by mjohnson541** [comment]
Does this happen for libraries as well?

**Comment by mliu49** [comment]
Yeah, I'm pretty sure the same error is raised if a library is missing.

**Comment by mjohnson541** [comment]
Are you sure about that?  The last set of fixes were designed to automatically load all the necessary libraries-A restart run shouldn't include the original libraries/seed mechanisms, because this would unnecessarily add them to the core/edge.  I don't think I tested adding libraries that weren't there before, but I definitely tested that it automatically loaded the corresponding libraries for library reactions in loaded seed mechs.

**Comment by mliu49** [comment]
Oh, you're right! I was working on a earlier version before that got merged.
