### ISSUE TITLE
Forbidden Structure Exception

### ISSUE THREAD

**Issue by shrabanti1937** [ReactionMechanismGenerator/RMG-Py#1302]
Hi,
I am using RMG 2.1.0. I am beginner with this software.
I tried to generate a mechanism where I used  'Nitrogen_Dean_and_Bozzelli' as reaction library. I also used BrukeH2O2inN2 in the reaction library.
While running it is giving me the following error message.
![capture](https://user-images.githubusercontent.com/36457961/36762511-912d38f6-1be9-11e8-9beb-aefe5b4dc758.JPG)

Can any one please suggest how to deal with this issue?

Thanks
Shrabanti

**Comment by mjohnson541** [comment]
So the source of this issue is that the library has a species in it that RMG can't react properly yet.  This means that this species will only be involved in reactions from that library, which isn't always a problem.  

Your generatedSpeciesConstraints block, which you may not even have in your input file, can look something like this:  
generatedSpeciesConstraints(
    # allows exceptions to the following restrictions
    allowed=['input species', 'seed mechanisms', 'reaction libraries'],
    # maximum number of each atom in a molecule
    maximumCarbonAtoms=4,
    maximumOxygenAtoms=7,
    maximumNitrogenAtoms=0,
    maximumSiliconAtoms=0,
    maximumSulfurAtoms=0,
    # max number of non-hydrogen atoms
    # maximumHeavyAtoms=20,
    # maximum radicals on a molecule
    maximumRadicalElectrons=1,
    # If this is false or missing, RMG will throw an error if the more less-stable form of O2 is entered
    # which doesn't react in the RMG system. normally input O2 as triplet with SMILES [O][O]
    # allowSingletO2=False,
)

Default if you don't define a constraint it isn't applied, which is why the block is optional.  Important for you is the line: 

allowed=['input species', 'seed mechanisms', 'reaction libraries'], 

this line tells RMG to not raise an error if a forbidden species shows up in a seed mechanism, reaction library or as an input species.  At minimum adding:

allowed=['reaction libraries'], 

to your generatedSpeciesConstraints block should fix your problem.

**Comment by alongd** [comment]
RMG currently does not forbid NH2O (I'm aware that previously it used to, https://github.com/ReactionMechanismGenerator/RMG-Py/issues/514)

@shrabanti1937 : Is this a recent RMG installation? could you verify that you are using the latest RMG version?

* If you installed as a developer, and you'd like to update RMG, type on both repositories (RMG-Py and RMG-database)
   ```
   git checkout master
   git fetch origin
   git rebase origin/master
   ```
   (assuming that you didn't rename the default origin remote)

* If this is a basic user installation, try typing:
   ```
   source activate rmg_env
   conda update rmg rmgdatabase -c rmg
   ```
   to update RMG.

If all is up to date and you're still experiencing this issue, please upload your input file so we could try to reproduce it.

**Comment by shrabanti1937** [comment]
Thanks mjohnson541 . 

To be more elaborate, the error starts coming fast with NH3. I added NH3 as a species with defining the SMILE structure. Then It starts showing NH2O and I saw no structure is available for NH2O. 
I feel like adding just the species name may not be the solution of my current problem.
I tried  the option 
generatedSpeciesConstraints(
# allows exceptions to the following restrictions
allowed=['reaction libraries'],
)

Still having the same error.

**Comment by shrabanti1937** [comment]
I installed RMG two weeks ago from following link
http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/index.html

I installed it as a basic user

**Comment by mjohnson541** [comment]
Hmm...can you attach your input file?

**Comment by shrabanti1937** [comment]
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/1765479/input.txt)
I tried updating it. Still has the same issue. 
I attached my input file here.

**Comment by mjohnson541** [comment]
Oh, sorry, when I said "allowed = ['reaction libraries']," that was literal.  You don't need to insert the library names you just tell it to allow all reaction libraries.  

Change
allowed=['Nitrogen_Dean_and_Bozzelli','BurkeH2O2inN2'],
to 
allowed = ['reaction libraries'],

**Comment by alongd** [comment]
RMG Version 2.1.0 (March 7, 2017) does not include the latest nitrogen enhancements.
Specifically, the change to the globally forbidden groups that solves this issue. (https://github.com/ReactionMechanismGenerator/RMG-database/pull/163) merged on April 10, 2017.

@shrabanti1937: My recommendation is to reinstall RMG as a developer to have all recent nitrogen enhancements. This is critical for simulating nitrogen chemistry, and should also solve this issue for you.

**Comment by shrabanti1937** [comment]
Thanks, it seems its working for this current case. Still in progress.
Since developer version has all recent nitrogen enrichment, I will try to install that.
Just to make sure, do I need to uninstall the present version or it will just overlap?
Can I know the command for the uninstall if required? 
Thanks again.

**Comment by shrabanti1937** [comment]
The input file finally ran completely however, it haven't generate any reaction using Nitrogen. I added Nitrogen_Dean_and_Bozzelli and BrukeH2O2inN2 hoping to get reactions reaction with Nitrogen).
So should I conclude its because of the limitation of the basic installation and may solve by developer version.

**Comment by shrabanti1937** [comment]
Thanks @alongd 
I will try it again by making reactive option as True.
I am using Anaconda2 version 5.1.0 for 64bit windows.
