### ISSUE TITLE
confusing example naming in RMG-Py and RMG-tests

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1305]
In RMG-Py people can run examples with commands like `make eg3`. This example is not related to the RMG-test named 'eg3'. It would be much more helpful if these names only overlapped when the input file run is the same, so people don't get confused by the question 'which eg3 are we talking about'.

Anyways, just my opinion.

**Comment by mliu49** [comment]
I think this was mostly addressed by ReactionMechanismGenerator/RMG-tests#68. We wrote new test cases which are not named `eg#`. However, the old tests are still there, and we still run the RMG-tests version of `eg1`, which is shorter (looser tolerance) than the RMG example.

I think that is sufficient to close this issue though.
