### ISSUE TITLE
Inadequate model chemistry designations

### ISSUE THREAD

**Issue by cgrambow** [ReactionMechanismGenerator/RMG-Py#1315]
According to the documentation, the `DFT_G03_b3lyp` model chemistry is a "B3LYP calculation with a moderately large basis set", but this designation is completely useless unless we also know what the exact basis set is (similarly, `DFT_ks_b3lyp` and `DFT_uks_b3lyp` are also inadequate designations). For example, using a 6-31G(2df,p) basis set (which I would describe as moderately large) gives an atomic energy for carbon that differs from `DFT_G03_b3lyp` by almost 7 kcal/mol, which means that heats of formation for any medium sized molecule will likely be off by 50 kcal/mol or more (rates would be less affected).

Most users are probably not aware of this issue, so I propose either finding out what the basis sets are and adding them to the designation, or to remove the atomic energies and no longer allow those model chemistries because they more likely than not will give erroneous results. Thoughts?

Going beyond this, it might also make sense to add an option to Cantherm to allow the user to supply their own atomic energies, which would greatly increase its flexibility by not being restricted to the hard-coded model chemistries.

Also see #742

**Comment by alongd** [comment]
closed via #1324
