### ISSUE TITLE
check_model taking large amounts of time

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1316]
So I was running a propane model out to 222 species and it stalled after the model really finished in the check_model function I suspect this is due to the time required to search for duplicate reactions in the edge.  I'm not exactly sure how long it stalled, but I think it was ~1 hour before I stopped it.  Given this is a pretty small model with an edge with only 16226 species and 93057 reactions I can imagine this is probably a major annoyance for large models.

**Comment by mliu49** [comment]
Is this fixed now that we removed reaction checking?
