### ISSUE TITLE
Reaction reduction script

### ISSUE THREAD

**Issue by prathameSHenai** [ReactionMechanismGenerator/RMG-Py#1340]
Hi, 

I've attempted to use the reaction reduction script available with RMG 2.0 (http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/modules/reduction.html) to reduce a model that I had previously generated with RMG1.0. The original model is relatively large (~200 species and 6000 reactions). However, I found that despite letting the script run for ~ a day, there was no progress towards the mechanism reduction. Playing around with a much lenient reduction criterion also shows the same issue. It works fine on models of smaller sizes of about 60 species and 600 reactions. I initially suspected it could be a memory requirements issue, but it didn't look like so in my analysis. Is this script/functionality inherently limited to a certain size of the original model? 

Thanks in advance!
Prathamesh

**Comment by mjohnson541** [comment]
Unfortunately, our reaction reduction algorithm isn't very fast right now and this makes it not a great tool to reduce even medium sized models.  Chemkin has a tool for doing this and I think Cantera has some functionality that at least makes it possible to do this.  I also think Tianfeng Lu's group at Uconn have some nice tools for model reduction, although I can't seem to find them online right now.
