### ISSUE TITLE
Travis fails sporatically

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1342]
It sometimes happens that travis will fail before even installing all the conda packages. 

I am not sure the cause, but [a recent run](https://travis-ci.org/ReactionMechanismGenerator/RMG-Py/builds/365239962?utm_source=github_status&utm_medium=notification) showed "The command "conda install -y -c conda-forge codecov" failed and exited with 139 during ." as the error message.

Currently, it seems like the solution is to create a blank commit (`git commit --allow-empty`) to re-spawn the run. Does anyone know of any better strategies?

**Comment by mliu49** [comment]
This has been brought up on Slack. You can restart the run from the Travis job page if you're logged in.

The reason for the non-deterministic failure is still unknown.

**Comment by mliu49** [comment]
This seems to have been resolved. I don't think Travis builds have run into this in a while.
