### ISSUE TITLE
Finding more reactions RMG could not find

### ISSUE THREAD

**Issue by xiaoruiDong** [ReactionMechanismGenerator/RMG-Py#1352]
Take the first listed family: **1+2_Cycloaddition** as an example. Apparently, [CH2] + C=C -> C1CC1, belongs to this family. To make sure, I also checked 1+2_Cycloaddition/groups which contains 4. carbene and 17. mb_db_unsub. So this should be an exact match to the template, However for both forward or reverse direction, RMG can not find this reaction. 
Besides, RMG also have problem finding C=C -> [CH2][CH2], which is a reverse reaction in family **1,2-Birad_to_alkene**; [CH2] + CC -> CCC for both direction, which is a reaction is family **1,2_Insertion_carbene**. 

For reactions with carbene, I guess there is a problem for RMG to recognize [CH2]. As I enter [CH2] as a reactant in kinetics search on RMG website, the result are all 'reaction-Library' matches without any 'reaction-family' matches.

**Comment by mliu49** [comment]
Are you sure you're using the correct state (singlet/triplet) of [CH2]? Using the SMILES defaults to the triplet state, which doesn't react in 1+2_Cycloaddition. Searching for the singlet carbene gives the expected reactions from 1+2_Cycloaddition ([link](http://rmg.mit.edu/database/kinetics/reaction/reactant1=1%20C%20u0%20p1%20c0%20%7B2,S%7D%20%7B3,S%7D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0A__reactant2=1%20C%20u0%20p0%20c0%20%7B2,D%7D%20%7B3,S%7D%20%7B4,S%7D%0A2%20C%20u0%20p0%20c0%20%7B1,D%7D%20%7B5,S%7D%20%7B6,S%7D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0A5%20H%20u0%20p0%20c0%20%7B2,S%7D%0A6%20H%20u0%20p0%20c0%20%7B2,S%7D%0A__product1=1%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D%20%7B5,S%7D%0A2%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B3,S%7D%20%7B6,S%7D%20%7B7,S%7D%0A3%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B2,S%7D%20%7B8,S%7D%20%7B9,S%7D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0A5%20H%20u0%20p0%20c0%20%7B1,S%7D%0A6%20H%20u0%20p0%20c0%20%7B2,S%7D%0A7%20H%20u0%20p0%20c0%20%7B2,S%7D%0A8%20H%20u0%20p0%20c0%20%7B3,S%7D%0A9%20H%20u0%20p0%20c0%20%7B3,S%7D%0A__res=True)).

**Comment by alongd** [comment]
Note that [the 1,2-Birad_to_alkene family is irreversible](https://github.com/ReactionMechanismGenerator/RMG-database/blob/master/input/kinetics/families/1%2C2-Birad_to_alkene/groups.py#L12) (as discussed in https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1266), so it makes sense that RMG did not find it in reverse. The other families you mentioned should be checked, though.

**Comment by mliu49** [comment]
I only meant that triplet carbene does not react in the family due to how it's currently defined. I'm not that familiar with whether or not the reaction can occur in reality.
