### ISSUE TITLE
We might want to deprecate `spinMultiplicity` in Cantherm

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#1366]
@cgrambow and I think we might want to deprecate `spinMultiplicity` in Cantherm - it's not being used for anything, but we do throw errors if it's not inputted (or after #1364, if it's not read properly from the Log file).

**Comment by mliu49** [comment]
Came across #206 while sorting through old issues. Are we sure spinMultiplicity is not used?

**Comment by alongd** [comment]
Yeah, I saw that as well and was thinking what it originally meant... Colin and I went over Cantherm's code (although briefly) and saw that it's never being actually used for anything. I'll make a final check, and I'll look through the history a bit. I'll write my findings here.
BTW, how shall we proceed with a deprecation method? Tag #1353

**Comment by cgrambow** [comment]
Now that I think about it, spin multiplicity affects the electronic partition function. Setting ground state energy to zero and assuming that excited states are inaccessible, `q_e = spin_multiplicity`, which would add a contribution of `R*ln(q_e)` to the entropy. So we should definitely be using spin multiplicity.

**Comment by cgrambow** [comment]
I looked into the code. We use it appropriately in `statmech/conformer.pyx`, so I think this issue can be closed.

**Comment by alongd** [comment]
Thanks Colin!
