### ISSUE TITLE
All possible solutions for Kekulization

### ISSUE THREAD

**Issue by kiahdd** [ReactionMechanismGenerator/RMG-Py#1379]
I noticed that the algorythm by using which kekulize form of an aromatic molecule is produced just results in one solution. what if all possible solutions are needed? for example 2,3,4,5-tetradeuterio-6-nitroaniline has an aromatic ring and the molecule smiles is "C1=CC=C(C(=C1)N)[N+](=O)[O-]". it is not a symetric molecule thus the position of double bond inside the ring is importand. the given smiles just indicate one possible solution for kekulize form of the molecule. what if I need to generate all possible solutions and kekulize forms for the molecule? 

I would appreciate your help to solve the matter.

**Comment by mliu49** [comment]
Hi @kiahdd, thanks for your interest in using RMG. Actually, RMG does generate both Kekule forms of the molecule for monocyclic aromatics, though you may not be using the necessary functions.

If you use `generate_resonance_structures` directly, it will give you both Kekule structures and the aromatic structure:
```
from rmgpy.molecule import Molecule
mol = Molecule().fromSMILES('C1=CC=C(C(=C1)N)[N+](=O)[O-]')
struct = mol.generate_resonance_structures()
```

This gives the following three structures:

![image](https://user-images.githubusercontent.com/10817103/40794612-ad2ac6f4-64cd-11e8-8696-17dfe054a06e.png)
![image](https://user-images.githubusercontent.com/10817103/40794617-afc76502-64cd-11e8-8e6b-d6c60ac5e451.png)
![image](https://user-images.githubusercontent.com/10817103/40794620-b2b608ea-64cd-11e8-96c6-a11fed983f26.png)

If you only want the two Kekule structures, then you'll need to use `rmgpy.molecule.resonance.generate_kekule_structure` and `rmgpy.molecule.resonance.generate_opposite_kekule_structure` for the other form.
