### ISSUE TITLE
Interactive website for RMG-Py

### ISSUE THREAD

**Issue by shrabanti1937** [ReactionMechanismGenerator/RMG-Py#1397]
Hi
I am trying to use the interactive website for RMG-Py of following link https://reactionmechanismgenerator.github.io/RMG-Py/index.html. 
The page is failing to load for several days. I can get access to RMG documentation part in the website but not the RMG interactive website which includes other tools option like molecular or kinetic search. Even RMG resources page. and database is not loading.
Can anyone help me, how can I get access to those option and tools?

Thanks

**Comment by alongd** [comment]
Hi @shrabanti1937, the rmg server which hosts [rmg.mit.edu](http://rmg.mit.edu/) is currently down, our admins are working on getting it up and running again.

**Comment by mliu49** [comment]
Hi @shrabanti1937, apologies for the inconvenience. The server has been brought online again, so the website should be accessible now.
