### ISSUE TITLE
Chemkin File Not Saved for Last Iteration if `maxNumSpecies` is Used

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/RMG-Py#1406]
### Bug Description
If `maxNumSpecies` is specified in the input file, the Chemkin file from the last iteration where the maximum number of species is reached is not saved.

### How To Reproduce
Run any RMG model using a small value for `maxNumSpecies`. Notice that the number of species and reactions in the final model does not match that of the Chemkin file.

### Expected Behavior
The final model should be saved as a Chemkin file.

### Installation Information
Ubuntu 16.04

**Comment by cgrambow** [comment]
Oh and also the execution time is not printed at the end of the log file if `maxNumSpecies` is used.

**Comment by amarkpayne** [comment]
Closed with #1394

**Comment by amarkpayne** [comment]
Also with #1413. Thanks to @mliu49 for fixing the mistake with my fixup!
