### ISSUE TITLE
RMG-Py cannot find multiple transition states

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#142]
This issue came up after investigations for issue https://github.com/GreenGroup/RMG-Py/issues/140 RMG-Py cannot find multiple transition states when reactants and products are identical.  For instance in the following reaction between tertiary and primary isobutyl radical we only find one reaction rate (RMG-Java will predict both transition state and generate duplicate reactions): 

http://dev.rmg.mit.edu/database/kinetics/reaction/reactant1=1%20C%200%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D;2%20C%200%20%7B1,S%7D;3%20C%200%20%7B1,S%7D;4%20C%201%20%7B1,S%7D;__reactant2=1%20C%200%20%7B4,S%7D;2%20C%200%20%7B4,S%7D;3%20C%200%20%7B4,S%7D;4%20C%201%20%7B1,S%7D%20%7B2,S%7D%20%7B3,S%7D;__product1=1%20C%200%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D;2%20C%200%20%7B1,S%7D;3%20C%200%20%7B1,S%7D;4%20C%200%20%7B1,S%7D;__product2=1%20C%200%20%7B3,S%7D;2%20C%200%20%7B3,S%7D;3%20C%200%20%7B1,S%7D%20%7B2,S%7D%20%7B4,D%7D;4%20C%200%20%7B3,D%7D;

I believe this is due to the reaction degeneracy being increased after checking that reactants and products are identical without regard to different atom labels leading to potentially different reaction templates.  (https://github.com/GreenGroup/RMG-Py/blob/master/rmgpy/data/kinetics/family.py#L1437)  After the degeneracy is counted, only the very first retained reaction's template gets used to fetch kinetics.

**Comment by goldmanm** [comment]
fixed with #1055
