### ISSUE TITLE
Group additivity yields negative entropy for urea

### ISSUE THREAD

**Issue by cgrambow** [ReactionMechanismGenerator/RMG-Py#1430]
### Bug Description
The group additivity value for the entropy of urea is negative on the RMG website.

### How To Reproduce
See [here](http://rmg.mit.edu/database/thermo/molecule/1%20N%20u0%20p1%20c0%20%7B2,S%7D%20%7B5,S%7D%20%7B6,S%7D%0A2%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B3,D%7D%20%7B4,S%7D%0A3%20O%20u0%20p2%20c0%20%7B2,D%7D%0A4%20N%20u0%20p1%20c0%20%7B2,S%7D%20%7B7,S%7D%20%7B8,S%7D%0A5%20H%20u0%20p0%20c0%20%7B1,S%7D%0A6%20H%20u0%20p0%20c0%20%7B1,S%7D%0A7%20H%20u0%20p0%20c0%20%7B4,S%7D%0A8%20H%20u0%20p0%20c0%20%7B4,S%7D%0A).

Also negative for `CNC(=O)N`. No longer negative for `CCNC(=O)N`.

### Expected Behavior
Entropy can't be negative.

**Comment by mliu49** [comment]
All three matched groups have negative entropy contributions. I guess this is just a result of how they were fitted? I'm not sure if there's much we can do besides refitting groups. Would putting a hard limit at 0 be useful at all?

**Comment by cgrambow** [comment]
Negative entropy contributions are fine, but shouldn't cause the total entropy to be negative. You're probably right, it's most likely due to fitting to an inadequate dataset. Changing the total entropy to 0 will probably give somewhat more realistic rates, but is also unphysical...
