### ISSUE TITLE
Sensitivity analysis- TypeError

### ISSUE THREAD

**Issue by sarahkha** [ReactionMechanismGenerator/RMG-Py#1431]
I am trying to run a sensitivity analysis and I am having the following error:

Any idea or comment?
Thanks
***
Traceback (most recent call last):
  File "simulate.py", line 74, in <module>
    main()
  File "simulate.py", line 69, in main
    run_simulation(inputFile, chemkinFile, dictFile, diffusionLimited=dflag, checkDuplicates=checkDuplicates)
  File "/home/sarahkha/RMG-Py/rmgpy/tools/simulate.py", line 148, in run_simulation

TypeError: loadRMGJob() got an unexpected keyword argument 'checkDuplicates'
***

[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2207290/input.txt)

[chem.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2207293/chem.txt)
[species_dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2207298/species_dictionary.txt)

**Comment by cgrambow** [comment]
I am not able to reproduce your issue with the files you provided. Can you make sure you've pulled the latest RMG version and try again?

**Comment by alongd** [comment]
Also, from looking at the code it seems to be able to function OK.
@sarahkha, do you still experience this error on the updated master branch?

**Comment by sarahkha** [comment]
Thank you @cgrambow and @alongd 
I did not experience this issue again.

**Comment by alongd** [comment]
Great!
