### ISSUE TITLE
Parsing imidogen InChI incorrectly returns ammonia

### ISSUE THREAD

**Issue by cgrambow** [ReactionMechanismGenerator/RMG-Py#1440]
### Bug Description
Letting the RMG website parse the InChI for imidogen, `InChI=1S/HN/h1H`, incorrectly results in ammonia.

### How To Reproduce
Type `InChI=1S/HN/h1H` in the search box at https://rmg.mit.edu/molecule_search.

### Expected Behavior
The correct structure should be `[NH]`. Interestingly, this is not an issue when using the RMG `molecule` API, i.e., `Molecule().fromInChI('InChI=1S/HN/h1H')`.

**Comment by mliu49** [comment]
InChI parsing was switched to use RMG/RDKit functionality instead of the NCI resolver, so this is parsed properly now.
