### ISSUE TITLE
Ring attribute/props attribute is Buggy

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1441]
First, the ring attribute doesn't copy properly:  deepcopy(grp) doesn't copy the ring attribute.  Second even grp.copy() or manually copying the ring attribute over doesn't appear to operate properly for purposes of isomorphism operations.  I've had a lot of difficulty debugging it, primarily because in the code the adjacencyLists don't appear to provide enough information to reconstruct the group objects properly anymore, which is really disturbing.

**Comment by mjohnson541** [comment]
Ok, so after I fixed a different issue:

 manually copying the props attribute:  
newgrp = deepcopy(grp)
for i in xrange(len(grp.atoms)):
    newgrp.atoms[i].props = deepcopy(grp.atoms[i].props)

appears to work properly now

However
newgrp = grp.copy(deep=True) 
eventually gives me errors related to not being able to find bonds.  Something must not be being copied properly in grp.copy(deep=True).

**Comment by mliu49** [comment]
You should be using `Group.copy(deep=True)` to make deep copies of Group objects (applies for Molecules as well). If that is what you're doing, then this is indeed concerning.

**Comment by mjohnson541** [comment]
That's seems to be the problem, I'm using the first one of the one currently, I haven't looked too deeply into the details of the second except to realize that it results in missing bonds during tree generation operations.  We can take a look at it when you get back.

**Comment by mliu49** [comment]
I think we decided that the code was working properly.
