### ISSUE TITLE
No training reaction generated when using families 'all' instead of a list

### ISSUE THREAD

**Issue by ajocher** [ReactionMechanismGenerator/RMG-Py#1448]
When using kinetics_library_to_training.ipynb to convert a kinetics library to training reactions and selecting families = ['all']
no training reactions are generated. When using a list for the same library training reactions are generated.

### Expected Behavior
I expected to see the same set of training reactions to be generated with a family list as well as with the 'all' option.

### Installation Information
 - MacOS High Sierra 10.13.6
 - Installation method: with anaconda
 - RMG version information: 
   - RMG-Py: 2.1.0-1379-g4d8ffee68
   - RMG-database: 2.1.0-642-g360807ca

**Comment by mjohnson541** [comment]
Have you tried `families = 'all'`?

**Comment by ajocher** [comment]
Yes, didn’t get the training reactions I got with for example H-Abstraction.

On Aug 10, 2018, at 2:56 PM, Matt Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you tried families = 'all'?

**Comment by ajocher** [comment]
families = 'all' works. Thanks!
