### ISSUE TITLE
filtration getting caught in an infinite loop

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1456]
During some operations loading the training depository, calculating thermo and particularly during resonance structure generation on this H_abstraction reaction:  

ERROR:root:SH + C3H6S <=> H2S_r + C3H5S
ERROR:root:SH
multiplicity 2
1 *3 S u1 p2 c0 {2,S}
2    H u0 p0 c0 {1,S}

ERROR:root:C3H6S
1     S u0 p2 c0 {4,D}
2  *1 C u0 p0 c0 {3,S} {4,S} {5,S} {6,S}
3     C u0 p0 c0 {2,S} {7,S} {8,S} {9,S}
4     C u0 p0 c0 {1,D} {2,S} {10,S}
5  *2 H u0 p0 c0 {2,S}
6     H u0 p0 c0 {2,S}
7     H u0 p0 c0 {3,S}
8     H u0 p0 c0 {3,S}
9     H u0 p0 c0 {3,S}
10    H u0 p0 c0 {4,S}

get_octet_deviation starts getting called on these structures in an infinite loop (error statements are from the beginning of get_octet_deviation):  

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u0 p2 c-1 {4,D}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u1 p0 c0 {2,S} {4,S} {8,S}
4 C u0 p0 c0 {1,D} {3,S} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

ERROR:root:multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

**Comment by mjohnson541** [comment]
I've tried to reproduce it separately from tree generation, but I haven't been successful.

**Comment by alongd** [comment]
Can you check whether it's being called from [filtration.py](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/7c820339309703b102a4d52f7c559be85b8e37e4/rmgpy/molecule/filtration.py#L87) or [resonance.py](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/a6c4e4b282f05ba05ed22cb56deb425228368347/rmgpy/molecule/resonance.py#L289)?

**Comment by mjohnson541** [comment]
Here's the traceback:  

KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-8-f51c6eb1ed07> in <module>()
      1 start = time.time()
----> 2 family.generateTree(thermoDatabase=database.thermo)
      3 end = time.time()
      4 print end-start

/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/data/kinetics/family.pyc in generateTree(self, obj, thermoDatabase, T)
   2856         (its parent becomes the parent of its only relevant child node)
   2857         """
-> 2858         templateRxnMap = self.getReactionMatches(thermoDatabase=thermoDatabase,removeDegeneracy=True,fixLabels=True,exactMatchesOnly=True)
   2859 
   2860         multCompletedNodes = [] #nodes containing multiple identical training reactions

/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/data/kinetics/family.pyc in getReactionMatches(self, rxns, thermoDatabase, removeDegeneracy, estimateThermo, fixLabels, exactMatchesOnly)
   3264         """
   3265         if rxns is None:
-> 3266             rxns = self.getTrainingSet(thermoDatabase=thermoDatabase,removeDegeneracy=removeDegeneracy,estimateThermo=estimateThermo,fixLabels=fixLabels)
   3267 
   3268         entries = self.groups.entries

/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/data/kinetics/family.pyc in getTrainingSet(self, thermoDatabase, removeDegeneracy, estimateThermo, fixLabels)
   3195                 for j,react in enumerate(r.item.products):
   3196                     if rxns[i].products[j].thermo is None:
-> 3197                         rxns[i].products[j].thermo = tdb.getThermoData(react)
   3198 
   3199             rxns[i].kinetics = r.data

/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/data/thermo.pyc in getThermoData(self, species, trainingSet)
   1229 
   1230             # update entropy by symmetry correction
-> 1231             thermo0.S298.value_si -= constants.R * math.log(species.getSymmetryNumber())
   1232 
   1233 

/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/species.so in rmgpy.species.Species.getSymmetryNumber()

/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/species.so in rmgpy.species.Species.getResonanceHybrid()

/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/species.so in rmgpy.species.Species.generate_resonance_structures()

/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/molecule/molecule.so in rmgpy.molecule.molecule.Molecule.generate_resonance_structures()

/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/molecule/molecule.so in rmgpy.molecule.molecule.Molecule.generate_resonance_structures()

/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/molecule/resonance.so in rmgpy.molecule.resonance.generate_resonance_structures()

/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/molecule/resonance.so in rmgpy.molecule.resonance.generate_resonance_structures()

/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/molecule/resonance.so in rmgpy.molecule.resonance._generate_resonance_structures()

/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/molecule/filtration.py in get_octet_deviation(mol)
     90 
     91 
---> 92 def get_octet_deviation(mol):
     93     """
     94     Returns the octet deviation for a :class:Molecule object

KeyboardInterrupt:

**Comment by mjohnson541** [comment]
len(mol_list) increases by one each iteration of the while loop.

**Comment by alongd** [comment]
I think [this](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/resonance.py#L302)might be the problematic part:
```py
        for new_mol in new_mol_list:
            # Append to structure list if unique
            for mol in mol_list:
                if not keep_isomorphic and mol.isIsomorphic(new_mol):
                    break
                elif keep_isomorphic and mol.isIdentical(new_mol):
                    break
            else:
                mol_list.append(new_mol)
```

I think that during training, `keep_isomorphic ` is set to `TRUE`, which implies that `mol.isIdentical()` does not perform as expected. The first thing that I can think of is atom IDs, but looks like they are being set in the [isIdentical](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/molecule.py#L2139) function.

**Comment by mjohnson541** [comment]
I can confirm that keep_isomorphic is True.

**Comment by mjohnson541** [comment]
None of the structures isIdentical is called on seem to have labels (in either list).

**Comment by mjohnson541** [comment]
It seems that a charge gets attached to the sulfur atom making the molecule an ion so it isn't identical, however the charge seems to go away later.

**Comment by mjohnson541** [comment]
The structure it seems to add every time:  
multiplicity 2
1 S u1 p2 c-1 {4,S}
2 C u0 p0 c0 {3,S} {5,S} {6,S} {7,S}
3 C u0 p0 c0 {2,S} {4,D} {8,S}
4 C u0 p0 c0 {1,S} {3,D} {9,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {4,S}

**Comment by mjohnson541** [comment]
Should I comment these structures out of the database until we can handle them properly?

**Comment by alongd** [comment]
Perhaps. I'll take a deeper look today.

**Comment by mjohnson541** [comment]
So the branch I'm on is atg3 and I'll email you the ipython notebook I'm using.

**Comment by mliu49** [comment]
I think we figured out why this was happening?
