### ISSUE TITLE
Reactions with 4 component in the product

### ISSUE THREAD

**Issue by shrabanti1937** [ReactionMechanismGenerator/RMG-Py#1457]
Hi 
I am using RMG version 2.2.1 through python interface.
I used Aramco 2.0 as my kinetic library in my input file. There are 2/3 reactions in this library (Aramco2.0) which has 4 component as product.  RMG does not accept 4 products while generating mechanism. Therefore I comment it out to run the input file.
I tried to add just those reactions at the end of generated mechanism but it gave me unusual result while testing for ignition delay time.
Can any one suggest me, ways to add those reactions into the mechanism while running RMG or  at the end of generated mechanism.  
How to deal with reactions which has 4 component as product?
Thank you

**Comment by alongd** [comment]
Hi,
Reactions that have 4 reactants or products aren't elementary, of course. Their rates are probably estimated/fitted.
We can think of semi-automated ways to append just these reactions to the model, but you might just as well past them manually as you did. We cannot add them during run-time without significant (and unphysical) changes to our solver.
What makes you suspect that these reactions are responsible for the "unusual" results you got? Did you get "unusual" results without these reactions as well?

**Comment by shrabanti1937** [comment]
Hi, alongd. Thanks for your reply. I am using cantera to calculate ignition delay time and to compare the result with literature.  While I tried to add the reactions at the end of the cantera file (.cti) it was giving me unusual solver problem actually. I again tried now. This time adding the equation in chemkin format. Then I converted the chemkin to cantera file and it works. I am sorry to mention about "unusaul" result. 

So, I am wondering is it a correct way to do this?

**Comment by alongd** [comment]
Looks like the only problem was incorrectly formatting these reactions in the cantera file when they were manually added. Principally, there shouldn't be a difference.
Let us know if you have any other questions, I think we can close this issue for now.
