### ISSUE TITLE
saveInputFile does not work and is not up to date with input file changes

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1460]
### Bug Description
We have an `rmgpy.rmg.input.saveInputFile` function which takes an RMG object and dumps the settings to an input file. However, it has not been maintained alongside all of the changes to both the input file and RMG object which have been made recently. As a result, it no longer works.

### How To Reproduce
The input file generator on the website uses this function, but it also has its own set of bugs, so it can be difficult to show that this is the cause. You can also directly read an input file with `rmgpy.rmg.input.readInputFile` and then save it again:
```
>>> from rmgpy.rmg.main import RMG
>>> from rmgpy.rmg.input import readInputFile, saveInputFile
>>> rmg = RMG()
>>> readInputFile('input.py', rmg)
>>> saveInputFile('new_input.py', rmg)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/input.py", line 699, in saveInputFile
    f.write('    atol = {0:g},\n'.format(rmg.absoluteTolerance))
AttributeError: 'RMG' object has no attribute 'absoluteTolerance'
```

### Expected Behavior
This should work.

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): Ubuntu 16
 - Installation method: installation from source with Anaconda
 - RMG version information: current master

**Comment by mliu49** [comment]
As a side note, this function is currently used only by the website and a work-in-progress script.

Regarding the website, I will be disabling the existing input file generator soon (already done on the dev site) due to security issues (and the fact that it doesn't work). I think it will need to be completely rewritten, though it's very likely it will still need to make use of this saveInputFile function.

The work-in-progress script is for automatically generating input files, and which I think is likely the primary use case of this function in general.

**Comment by shenghuiqin** [comment]
I was trying to use Reaction Reduction module in RMG, and get the same error message
[9.11. Reaction Reduction](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/modules/reduction.html)

```Traceback (most recent call last):
  File "//home/shenghuiqin/Code/RMG-Py/rmgpy/reduction/main.py", line 115, in <module>
    main()
  File "//home/shenghuiqin/Code/RMG-Py/rmgpy/reduction/main.py", line 83, in main
    atol, rtol = rmg.absoluteTolerance, rmg.relativeTolerance
AttributeError: 'RMG' object has no attribute 'absoluteTolerance'
```
