### ISSUE TITLE
CBS-QB3 bond corrections in Cantherm not generalizable

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1476]
The bond corrections for CBS-QB3 were updated in #1272 (copy of #1186) to use values from [Paraskevas et al. 2013](https://onlinelibrary.wiley.com/doi/full/10.1002/chem.201301381) in replacement of original values from [Petersson et al. 1998](https://aip.scitation.org/doi/10.1063/1.477794).

However, @jimchu10 and I discovered today that the training set for the Paraskevas values was composed solely of stable oxygenated hydrocarbons, whereas the Petersson training set included a few aromatics and N/O/S species, although they used different CBS methods.

This results in a significant difference in the enthalpy result for benzene, where using the Petersson values gives H298 within .05 kcal of the ATcT value, using the Paraskevas values underestimates by 2 kcal, and not using bond corrections overestimates by 2 kcal.

I'm not sure what the best route to take would be from here. I'm hoping to hear what others think.

**Comment by jimchu10** [comment]
I have done comparisons on two aromatic species: Benzene and Naphthalene
For the formation of Enthalpy at 298K:
Benzene: 19.81 (Exp.), 19.87 ([Petersson et al. 1998)](https://aip.scitation.org/doi/10.1063/1.477794), 17.44 ([Paraskevas et al. 2013](https://onlinelibrary.wiley.com/doi/full/10.1002/chem.201301381))
Naphthalene: 35.99 (Exp.), 35.33 ([Petersson et al. 1998)](https://aip.scitation.org/doi/10.1063/1.477794), 31.15 ([Paraskevas et al. 2013](https://onlinelibrary.wiley.com/doi/full/10.1002/chem.201301381))

At least for aromatic species, the bond correction values from ([Petersson et al. 1998)](https://aip.scitation.org/doi/10.1063/1.477794) should be better.

**Comment by cgrambow** [comment]
In my experience with bond corrections (which has been limited), I have observed that the exact values of bond corrections vary quite a lot depending on which molecules you fit to and that they are therefore not suitable for physical interpretation and should be used purely as empirical parameters. Because of this, I am not confident that combining different corrections from different sources is a valid approach.

One possible solution for this is to create our own dataset of experimental numbers (perhaps by combining datasets from the current sources in Cantherm) and re-doing the corresponding CBS-QB3 calculations and re-fitting.

**Comment by mliu49** [comment]
I agree that it doesn't make sense to combine the two sets of corrections. I think we could consider switching between the two depending on the species being calculated, but long-term it would probably be better to refit to a broader set of species.

**Comment by fhvermei** [comment]
I agree that two sets of BAC cannot be combined. The BACs are regressed based on experimental data and enthalpies determined by calculations. These enthalpies depend on the methodology you use in your code and hence BACs will be different for different levels of theory, but also slightly different for different codes and processing. Hence the best way to go is make your own dataset of BACs.
For now, the BACs by Paraskevas et al. are developed for oxygenates, so are not expected to work well for aromatics. They have been updated by Ince et al. (A. Ince, H.-H. Carstensen, M.-F. Reyniers, G.B. Marin, AIChE Journal, 61 (2015) 3858-3870.) for (mono)aromatics, so let's hope these do a better job for benzene, naphthalene and acenaphthylene.
