### ISSUE TITLE
mechanism failing to run laminar burning speed

### ISSUE THREAD

**Issue by shrabanti1937** [ReactionMechanismGenerator/RMG-Py#1492]
Hi, 
I am using RMG 2.2.1 version on python interface.

I generated a  mechanism of ethanol using GriMech, BurkeH2O2inN2 and Aramco2.0 as my kinetic library. 
The mechanism works very well in calculating ignition delay time by using cantera. However, it is failing to converge while I am trying to calculate laminar burning speed. Can any one please suggest, how to improve it?

**Comment by mjohnson541** [comment]
I don't have much experience estimating laminar burning speeds, but In my experience typically this happpens when the thermochemistry is incorrect or inconsistent.  Where are you getting your thermochemistry?  and how large of a model are you using?

**Comment by shrabanti1937** [comment]
I used thermo library from RMG website. primaryThermolibrary, GRIMech-3.0 and BurkeH2O2. The mechanism has 67 species and 1033 reactions.

**Comment by mjohnson541** [comment]
Hmm...now that I think about it, It's possible this is a result of mixing rates from BurkeH2O2, GriMech3.0 and Aramco2.0.  In general I wouldn't recommend mixing BurkeH2O2 thermo and rates with GriMech3.0 (a very fitted mechanism) and Aramco2.0 (also fitted) thermo and rates, but if you're giving them in order I would expect almost none of the BurkeH2O2 thermo gets used.  My personal opinion is that Klippenstein_Glarborg2016, BurkeH2O2inN2 is a better choice for C2 chemistry than what you're using above.   

However, it's also possible that running your model out a little bit farther (at a bit lower tolerance) will stabilize this issue.

**Comment by shrabanti1937** [comment]
Thanks mjohnson541 for your explanation. I compared few rates and found all from Aramco since that was 1st in the serial. I will try your suggestions  to see how it works.

**Comment by shrabanti1937** [comment]
Hi,
 I tried to run the model little more to fix the laminar burning speed issue. I also tried the library combination as you referred.  I am now able to calculate laminar burning speed by using cantera for both cases, however the mechanism is very grid sensitive for laminar burning speed at lower temperature like 300K. Do you have any idea how the temperature dependencies comes from? Or how it can be adjusted? The library files that I used are all works smooth at 300K temperature.

**Comment by mjohnson541** [comment]
Sorry, I really don't know what to tell you.  We don't do a lot of CFD calculations so I'm unsure how changing the RMG run parameters might affect even very simple CFD calculations.  If the calculation doesn't take too long you could test some of the earlier chemkin files generated in the RMG run to see if they have the same grid sensitivity or you could try tweaking the run parameters a bit to get a slightly different model and see if that model isn't grid sensitive.

**Comment by shrabanti1937** [comment]
Thanks @mjohnson541  for your reply. I will work on that.
