### ISSUE TITLE
NameError 'Log' on New Windows Install

### ISSUE THREAD

**Issue by cjmcgill** [ReactionMechanismGenerator/RMG-Py#1493]
### Bug Description
I was attempting to run CanTherm with a new install to test getting kinetics data. I set up the input file to reference back to gaussian log files for energy, geometry, and frequencies. I put the input file, species files, and gaussian log files all in the same directory `/RMG/Ethanol_test` and attempted to run cantherm with this command.
`python /Anaconda/envs/rmg_env/Scripts/cantherm.py input.py`

I got back this error and text.

`Loading statistical mechanics parameters for EtOH...
Error: The species file ./EtOH.py was invalid:
Traceback (most recent call last):
  File "/Anaconda/envs/rmg_env/Scripts/cantherm.py", line 61, in <module>
    cantherm.execute()
  File "C:\Anaconda\envs\rmg_env\lib\site-packages\rmgpy\cantherm\main.py", line 259, in execute
    job.execute(outputFile=outputFile, plot=self.plot)
  File "C:\Anaconda\envs\rmg_env\lib\site-packages\rmgpy\cantherm\statmech.py", line 186, in execute
    self.load()
  File "C:\Anaconda\envs\rmg_env\lib\site-packages\rmgpy\cantherm\statmech.py", line 225, in load
    exec f in global_context, local_context
  File "./EtOH.py", line 20, in <module>
    'B3LYP/6-31G': Log('EtOH.log'),
NameError: name 'Log' is not defined`

After getting that I tried to run from example input files and got the same error.

I guess the function for parsing log files is failing to be called? Am I calling the wrong instance of cantherm?

### Installation Information
Describe your installation method and system information.
 - OS: Windows 10
 - Installation method: installation from binary, in anaconda environment
 - RMG version information: 2.1.9

**Comment by mliu49** [comment]
The `Log` class was introduced in RMG version 2.2.0, which would explain the error if you have version 2.1.9 installed. Unfortunately, at the moment we do not have Windows binaries available for the newer releases.

An immediate solution to your problem would be to use the old syntax, where you need to explicitly indicate the type of log file (i.e. `GaussianLog`, `QchemLog`, or `MolproLog`). You can browse Cantherm example files from version 2.1.9 [here](https://github.com/ReactionMechanismGenerator/RMG-Py/tree/2.1.9/examples/cantherm).

**Comment by cjmcgill** [comment]
This error makes sense, having a mismatch between my version and the examples I was using as template.

Reverting to the old function `GaussianLog` fixed everything up for me.

**Comment by mliu49** [comment]
Good to hear! I'll go ahead and close this issue. Please let us know if you have any other questions.
