### ISSUE TITLE
`mingw32-make eg1` gives `mkdir` error on Windows with Git CMD shell

### ISSUE THREAD

**Issue by shenghuiqin** [ReactionMechanismGenerator/RMG-Py#1508]
### Bug Description
`mingw32-make eg1` gives `mkdir` error on Windows with Git CMD 

### How To Reproduce
Following the instructions to build from source using Anaconda environment on Windows:
reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloperWindows.html

Using `Git CMD` as the terminal

when running `mingw32-make eg1` it gives the error:

```
mkdir -p testing/eg1
The syntax of the command is incorrect.
makefile:116: recipe for target 'eg1' failed
mingw32-make: *** [eg1] Error 1
```

### Expected Behavior
The instructions would work

### Installation Information
Describe your installation method and system information.
 - OS (win 10)
 - Installation method:  installation from binary with anaconda
 - RMG version information:latest

**Comment by mliu49** [comment]
Sorry, this is a known issue - #574. We would need to update our make targets to be Windows cmd compatible, which unfortunately is not a high priority at the moment.

I'm also not sure if the example files are included with the binary distribution. I would need to-double check.

**Comment by JacksonBurns** [comment]
This installation method is no longer supported. Closing as stale.
