### ISSUE TITLE
The function of log files used in CanTherm / Arkane

### ISSUE THREAD

**Issue by pez16103** [ReactionMechanismGenerator/RMG-Py#1514]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [ x ] CanTherm
 - [ ] Dependencies
 - [ ] An error message 

### Context
A clear and concise description what you're trying to do.

Currently, I start to learn to use canTherm through examples in the source code. Is the log file used for energy/geometry/frequencies as input or output file? If it is input, how to generate it? 

### Question
Write your question here.

### Installation Information
Describe your installation method and system information if applicable.
 - OS (include version if known): (e.g. Windows 10, Ubuntu 18, macOS 10.13, etc.)
 - Installation method: (e.g. installation from binary or source, with or without anaconda)
 - RMG version information:
   
   - RMG-Py: 
   - RMG-database:

**Comment by alongd** [comment]
These log files are provided by the user (hence in this context, they are "input files"). They are generated by running an electronic structure software on your molecule of interest (e.g., Gaussian, QChem, or Molpro). This is referred to in our documentation as `quantum chemistry output file`.
See the relevant part of the documentation here: http://reactionmechanismgenerator.github.io/RMG-Py/users/arkane/input.html#option-1-automatically-parse-quantum-chemistry-calculation-output

(Note that starting from version 2.2.2. Cantherm will be renamed as Arkane, hence the documentation refers to it as Arkane as well)

**Comment by pez16103** [comment]
Thank you very much! Could you provide some theory tutorial for Arkane? I will very appreciate it.

**Comment by alongd** [comment]
Sure. On the RMG website (https://rmg.mit.edu/) click Documentation, then Theory Guide. Then, the `Pressure-Dependence Theory Guide` might be relevant.
Also, on the RMG website, you could click on Resources and see various presentations on CanTherm and pressure-dependent calculations, among other subjects.
