### ISSUE TITLE
Our iPython notebooks must be updated

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#1533]
The `generateReactions.ipynb` under the ipyhton folder import from cantherm, hence crashing. We should also make an overhaul of all notebooks to at make sure none crashes with the default settings.

**Comment by alongd** [comment]
My initial observations are:
- canteraSensitivityComparison crashes since it imports `from rmgpy.tools.sensitivity import runSensitivity`
- generateReactions crashes since it imports `from rmgpy.cantherm.output import prettify`
- combustion_model_and_ignition_delay_demo crashes since it imports `from rmgpy.tools.sensitivity import runSensitivity`
- findParameterSourcesAndAssignUncertainies crashes with a KeyError

**Comment by mcs16** [comment]
localUncertainty.ipynb crashes at Step 1 with the following error: "ImportError: No module named dde.predictor"

**Comment by mliu49** [comment]
@mcs16, you're probably missing the new dependency for machine learning thermo. You can install it with `conda install -c rmg dde` with your rmg_env activated.

**Comment by mliu49** [comment]
I think all of the mentioned notebooks have been updated in #1541 and #1593.
