### ISSUE TITLE
Bi-radical / resonance of C4H4 (and similar things)

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#154]
For the species C4H4, comparing to published kinetic models, we predict its reactions like the literature when we treat it as a biradical `[CH]=[C]C=C` or `[CH]=C=C[CH2]` which is to say CHj=C=CH-CH2j.

However, we get the thermochemistry closer to the literature (by 180 kJ/mol!) when we represent it as the stable molecule `C#CC=C` which is to say CH#C-CH=CH2. Same positioning of H atoms (same molecule) but increased bond orders and decreased radical counts.

Should this already be taken care of by the `1,2-Birad_to_alkene` family and resonance isomer generation, or should we be doing something else?

(NB. I have only compared which reaction pathways we predict, not what kinetics we predict for them. In terms of rate estimates, I am not sure which representation is best)

**Comment by alongd** [comment]
related to #118
