### ISSUE TITLE
Dead documentation links in README

### ISSUE THREAD

**Issue by arosen93** [ReactionMechanismGenerator/RMG-Py#1547]
Just wanted to let you folks know that the PDF links to the RMG and CanTherm documentation are broken in the README. They refer to PDFs that I imagine were deleted or moved in a prior commit. The HTML versions that I imagine most people use are perfectly fine.

**Comment by alongd** [comment]
Thanks Andrew!
#1548

**Comment by arosen93** [comment]
You bet! (And a big "hello!" to the Green group, @mliu49 @goldmanm et al.  👋 💻 😄).

**Comment by mliu49** [comment]
Hi Andrew! Thanks for catching this!
