### ISSUE TITLE
What to do when an input file crashes at the end of a job

### ISSUE THREAD

**Issue by ajuluc** [ReactionMechanismGenerator/RMG-Py#1554]
### Motivation or Problem
I have just built a dimethyl ether DME model using range reactors. The two independent parameters are temperature and pressure ranging from 625K to 2500K and 1bar to 20bar respectively. The job had run for about 3 days using the Discovery cluster for high performance computing. Upon completion of the job the final lines of the log file when checking for seed mechanisms gives an error at the end of the job run. The error message reads `'rmgpy.kinetics.arrhenius.MultiArrhenius' object has no attribute 'T0'`. 

### Desired Solution
The crash message apparently has an issue with the `rmg.py` script where it is unable to recognise T0 as a parameter. It would help if this could be rectified in the next version of `rmg.py` code as there is no reference to T0 in the actual version of rmg.py code

### Potential Alternatives
A link in the rmg reference guide for dealing with such issues such as crash after running a job and what that could mean for the chemkin file.

### Additional Context
Below is the complete error message from the log file.
`After model enlargement:
    The model core has 134 species and 4433 reactions
    The model edge has 35934 species and 74090 reactions

Saving current model core to Chemkin file...
Chemkin file contains 4460 reactions.
Saving verbose version of Chemkin file...
Chemkin file contains 4460 reactions.
Saving current model core and edge to Chemkin file...
Chemkin file contains 78573 reactions.
Saving verbose version of Chemkin file...
Chemkin file contains 78573 reactions.
Saving current model core to HTML file...
Saving current model edge to HTML file...
Updating RMG execution statistics...
    Execution time (DD:HH:MM:SS): 03:20:49:32
    Memory used: 4844.29 MB

Making seed mechanism...
Performing final model checks...
Traceback (most recent call last):
  File "/home/ajulu.c/Code/RMG-Py/rmg.py", line 173, in <module>
    main()
  File "/home/ajulu.c/Code/RMG-Py/rmg.py", line 158, in main
    cProfile.runctx(command, global_vars, local_vars, stats_file)
  File "/home/ajulu.c/anaconda2/envs/rmg_env/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/home/ajulu.c/anaconda2/envs/rmg_env/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/home/ajulu.c/Code/RMG-Py/rmgpy/rmg/main.py", line 936, in execute
    self.check_model()
  File "/home/ajulu.c/Code/RMG-Py/rmgpy/rmg/main.py", line 981, in check_model
    p_min=self.Pmin, p_max=self.Pmax)
  File "rmgpy/reaction.py", line 1154, in rmgpy.reaction.Reaction.check_collision_limit_violation
  File "rmgpy/reaction.py", line 1187, in rmgpy.reaction.Reaction.check_collision_limit_violation
  File "rmgpy/reaction.py", line 704, in rmgpy.reaction.Reaction.generateReverseRateCoefficient
  File "rmgpy/reaction.py", line 704, in rmgpy.reaction.Reaction.generateReverseRateCoefficient
  File "rmgpy/reaction.py", line 769, in rmgpy.reaction.Reaction.generateReverseRateCoefficient
AttributeError: 'rmgpy.kinetics.arrhenius.MultiArrhenius' object has no attribute 'T0' `

**Comment by mjohnson541** [comment]
First off, I've seen this before, all of your output is fine, it's only crashing during the final model checks, which while useful aren't particularly vital.  Was this on the current master?

**Comment by ajuluc** [comment]
Okay thanks for the observation. I think this was on the current master I might have to check and get back to you on that. Do you mean GitHub master?

**Comment by mjohnson541** [comment]
Yes

**Comment by ajuluc** [comment]
Yes it's on master I just committed the input file

**Comment by mjohnson541** [comment]
Seems like the arrhenius objects inside a PdepArrhenius are getting converted a MultiArrhenius object at some point.

**Comment by ajuluc** [comment]
I don't understand what the MultiArrhenius object means. The pressure dependent Arrhenius equations must have been done already.

**Comment by mjohnson541** [comment]
Sorry, I'm just noting what I found at first glance without any debugging.  I'm currently working on a more problematic bug right now, but I can take a look at this one once I've fixed that one.

**Comment by mjohnson541** [comment]
You should be fine using the output without the final model checks.

**Comment by ajuluc** [comment]
Okay sure I'll allow you do your thing and wait. In the meantime I'm trying to work to see if the DME model was correctly built with the range reactors. I'm interested in the Low Temperature chemistry though which I don't really see with the correct output file.

**Comment by mjohnson541** [comment]
I don't think that's a problem with the lack of model checks.  I can take a look at your input file, slack may be a better place than this issue though.

**Comment by ajuluc** [comment]
I'll switch over to slack then

**Comment by mliu49** [comment]
This error is fixed by #1659.
