### ISSUE TITLE
Arkane Geometry Read Failure

### ISSUE THREAD

**Issue by cjmcgill** [ReactionMechanismGenerator/RMG-Py#1555]
### Bug Description
Some geometry files fail to be imported through Arkane. They return a traceback like below. The species I have encountered this on have been tin-containing molecules, but it is successful in the vast majority of tin molecules I have tried. Going back and refining a particular molecule at a different level of theory also does not appear to change the error.

```
Loading statistical mechanics parameters for T2X23...
Traceback (most recent call last):
  File "../RMG-Py/arkane.py", line 60, in <module>
    arkane.execute()
  File "/home/cjmcgill/RMG/RMG-Py/arkane/main.py", line 267, in execute
    job.execute(outputFile=outputFile, plot=self.plot)
  File "/home/cjmcgill/RMG/RMG-Py/arkane/statmech.py", line 183, in execute
    self.load()
  File "/home/cjmcgill/RMG/RMG-Py/arkane/statmech.py", line 361, in load
    coordinates, number, mass = geomLog.loadGeometry()
  File "/home/cjmcgill/RMG/RMG-Py/arkane/gaussian.py", line 152, in loadGeometry
    raise InputError('Unable to read atoms from Gaussian geometry output file {0}'.format(self.path))
rmgpy.exceptions.InputError: Unable to read atoms from Gaussian geometry output file /home/cjmcgill/RMG/Failure_Test/T2X23.log
```

### How To Reproduce
Providing two different Gaussian log files that encounter this problem. T2X23.log is a stable species and D2to3.log is a transition state. I've also observed this on transition states proceeding from T2X23, so there might be something about that structure and not just that file.

[D2to3.log](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2895677/D2to3.log)
[T2X23.log](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2895679/T2X23.log)

### Installation Information
Describe your installation method and system information.
 - OS: Windows 10 using "Bash on Ubuntu on Windows" subenvironment
 - Installation method: anaconda
 - RMG version from Source
   - RMG-Py: 2.1.0-1519-gae79625  
   - RMG-database: 2.1.0-665-g75c71db

**Comment by mjohnson541** [comment]
So the problem seems to be that Arkane's parser looks for the "Input Orientation" line which comes before the geometries it reads, this doesn't occur in any of the above files.

**Comment by cjmcgill** [comment]
That's weird. It looks like Gaussian is still taking in my input orientation and changing it over to a standard orientation (as opposed to just accepting the input orientation). But there's some criteria that I've met where it's no long explicitly showing that reorientation and the distances matrix in the log file.

**Comment by mjohnson541** [comment]
Perhaps if you tell Gaussian to explicitly print the Input Orientation?  http://gaussian.com/overlay2/#iop_(2/44)

**Comment by cjmcgill** [comment]
I will run one of these jobs again with iop(2/9=2000) and see if that works with the parser as it exists now.

Are the only effects of this in gaussian.py? Both of those searches for 'Input orientation:' look like they could be substituted with 'Standard orientation:'. I just ran it through with that change and things appear to have worked.

**Comment by mjohnson541** [comment]
It is only in guassian.py.  That will certainly run, and I believe that should work fine for anything that doesn't have rotors (because in those cases I believe the only coordinate dependent input is the geometry).  However, when we do rotors we load in the force constant matrix, which should be in the input orientation, which we've had issues related to before, so I think it will give you silent errors for rotor calculations.

**Comment by JacksonBurns** [comment]
Installation method no longer supported closing as stale/wontfix.
