### ISSUE TITLE
Error with chemkin file conversion to .cti in Cantera for Pressure dependent reactions

### ISSUE THREAD

**Issue by ajuluc** [ReactionMechanismGenerator/RMG-Py#1557]
### Bug Description
When converting an incomplete annotated chemkin file to .cti in cantera, there's a duplicate reaction detected that prevents the chemkin mechanism file from being validated. 
Reaction 995:  2 CO2(18) <=> 2 CO2(321)
Reaction 918:      CO2(321) <=> CO2(18)

### How To Reproduce
An input file for dimethyl ether was created with 2 reaction systems. Reaction system 1 was done for a range reactor of 625 - 2500K temperature, 1-40 bar pressure and phi = 0.5 -2 concentration being the variables, while reaction system 2 was for range reactor of 600-900K temperature, 1-40 bar pressure and phi between 0.5-2 for concentrations. Sensitivity of certain known species were added in the list of species for low temperature chemistry and pressure dependence between 300-3000K and 0.01-100 bar. The resulting mechanism file from the incomplete mechanism of 107 species and 3288 reactions in the core. An attempt was made to convert this chemkin file to a .cti file in Cantera, which then invalidated the mechanism for the duplicate reactions as seen above.

### Expected Behavior
Typically the chemkin annotated mechanism file is validated for any number of species and converted to a .cti file in Cantera for further analysis such as ignition delay or NOx simulation

### Installation Information
Describe your installation method and system information.
 - MacOS 10.14
 - Installation method: installation from source with anaconda
 - RMG version information: 2.3.0
   
   - RMG-Py: 
   - RMG-database: 

### Additional Context
Here's the error code from Cantera 
CanteraError thrown by Kinetics::checkDuplicates:
Undeclared duplicate reactions detected:
Reaction 995: 2 CO2(18) <=> 2 CO2(321)
Reaction 918: CO2(321) <=> CO2(18)

**Comment by mjohnson541** [comment]
These reactions don't show up in the RMG-database or reaction generation for O=C=O.  They also aren't duplicates (the reaction order is different), do you have the kinetics comments (from the chemkin file) for these reactions?

**Comment by mjohnson541** [comment]
Also what's the structure for CO2(18) vs CO2(321)?

**Comment by ajuluc** [comment]
I'm not entirely sure what the structures are. Below is the actual chemkin file kinetics comments. 

`Reaction index: Chemkin #918; RMG #1880
! PDep reaction: PDepNetwork #277
! Flux pairs: CO2(18), CO2(321); CO2(18), CO2(321); 
CO2(18)+CO2(18)(+M)=CO2(321)+CO2(321)(+M)           1.000e+00 0.000     0.000    
    TCHEB/ 300.000   3000.000 /
    PCHEB/ 0.010     98.692   /
    CHEB/ 6 4/
    CHEB/ -6.582e+01   -1.842e-02   -1.269e-02   -6.920e-03  /
    CHEB/ 6.831e+01    1.309e-02    8.958e-03    4.836e-03   /
    CHEB/ -2.004e-02   4.074e-04    3.072e-04    1.920e-04   /
    CHEB/ 8.858e-03    1.754e-04    1.215e-04    6.701e-05   /
    CHEB/ -3.797e-03   3.275e-05    2.301e-05    1.298e-05   /
    CHEB/ -3.432e-04   -4.239e-06   -2.823e-06   -1.450e-06  /`

`! Reaction index: Chemkin #995; RMG #25421
! PDep reaction: PDepNetwork #3477
! Flux pairs: CO2(321), CO2(18); 
CO2(321)(+M)=CO2(18)(+M)                            1.000e+00 0.000     0.000    
    TCHEB/ 300.000   3000.000 /
    PCHEB/ 0.010     98.692   /
    CHEB/ 6 4/
    CHEB/ 9.211e+00    1.104e+00    -3.353e-01   -1.749e-02  /
    CHEB/ -1.851e-01   1.953e-01    1.752e-02    -3.300e-02  /
    CHEB/ -4.336e-02   3.856e-02    1.067e-02    -5.482e-03  /
    CHEB/ -1.522e-02   1.275e-02    3.942e-03    -1.453e-03  /
    CHEB/ -6.170e-03   4.974e-03    1.626e-03    -4.805e-04  /
    CHEB/ -2.679e-03   2.096e-03    7.154e-04    -1.745e-04  /`

**Comment by mjohnson541** [comment]
Look in the species_dictionary.txt file.

**Comment by ajuluc** [comment]
I searched for the file in the list of species and I can't find that specific one CO2(18) in the most updated list of species using the species number in parentheses.

**Comment by mjohnson541** [comment]
There's no line in species_dictionary.txt that is "CO2(18)"?

**Comment by ajuluc** [comment]
It just says species in the folder and lists a number of species and their respective structures.

**Comment by ajuluc** [comment]
Take that back found it

CO2(18)
1 O u0 p2 c0 {3,D}
2 O u0 p2 c0 {3,D}
3 C u0 p0 c0 {1,D} {2,D}

**Comment by mjohnson541** [comment]
And CO2(321)?

**Comment by ajuluc** [comment]
CO2(321)
multiplicity 3
1 O u1 p2 c0 {3,S}
2 O u0 p2 c0 {3,D}
3 C u1 p0 c0 {1,S} {2,D}

**Comment by ajuluc** [comment]
Structures are actually different based on the species adjacency list and using the multiplicity it shouldn't show it as being the same.

**Comment by mjohnson541** [comment]
These are perfectly fine non-duplicate reactions, if I had to guess I think Cantera must be simplifying these reactions so they show up as the same reaction (with particular orders).  Although it's unusual that it's only occurring for CO2.  We rely on Cantera's parser to convert the chemkin file to a cantera file so it actually doesn't involve any of our code currently.  It may be possible to create a temporary chemkin file just for converting to cti that obeys Cantera's parsing rules.

**Comment by ajuluc** [comment]
Not sure exactly what the problem is because it does generate the .cti file but still shows the CO2(18) and CO2(321) as duplicates in the .cti file. I'll figure it out with the cantera syntax I don't think its an RMG issue anymore. Thanks for the help all the same.

`Wrote CTI mechanism file to 'chem_annotated.cti'.
Mechanism contains 106 species and 3242 reactions.
Validating mechanism...PASSED.`
