### ISSUE TITLE
Arkane Error for inadequate information for TST

### ISSUE THREAD

**Issue by cjmcgill** [ReactionMechanismGenerator/RMG-Py#1574]
### Bug Description
I am getting the below error for one of my reactions when submitted to Arkane. The problem seems to be from either the reactant MeTPA or the transition state. When I swap out for a different transition state this runs, but I also get the failure with other reactions using MeTPA elsewhere. Thermo calculations of the MeTPA and the transition state both go as normal. These reactions are likely to have negative apparent activation energies, in case that's a contributor.

```
The species in reaction MeTPA + S22 <=> EG + S24 do not have adequate information for TST, using default kinetics values.

Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.
Traceback (most recent call last):
  File "../../RMG-Py/arkane.py", line 60, in <module>
    arkane.execute()
  File "/home/cjmcgill/RMG/RMG-Py/arkane/main.py", line 298, in execute
    job.execute(outputFile=outputFile, plot=self.plot)
  File "/home/cjmcgill/RMG/RMG-Py/arkane/kinetics.py", line 137, in execute
    self.save(outputFile)
  File "/home/cjmcgill/RMG/RMG-Py/arkane/kinetics.py", line 264, in save
    kineticsrev = Arrhenius().fitToData(Tlist, numpy.array(krevs), kunits=self.krunits)
  File "rmgpy/kinetics/arrhenius.pyx", line 134, in rmgpy.kinetics.arrhenius.Arrhenius.fitToData  File "rmgpy/kinetics/arrhenius.pyx", line 166, in rmgpy.kinetics.arrhenius.Arrhenius.fitToDataIndexError: index 0 is out of bounds for axis 0 with size 0

```

### Installation Information
Describe your installation method and system information.
 - OS: Windows 10 in Ubuntu subenvironment
 - Installation method: source install with conda
 - RMG version information:
   
   - RMG-Py: 2.1.0-1519-gae79625

**Comment by alongd** [comment]
I think Arkane can only calculate rates if the energy of the TS is higher than both the reactants and the products wells. If by negative apparent activation energy you mean that the expected Ea in the final Arhhenius fit is negative, that might be OK (I think?), as long as the physical barrier is positive (as described above). Let us know what you're wells and TS energies are. Otherwise, we'll need to play around with your inputs to see what's going on (at least I don't have a better guess from looking at the trace)

**Comment by mjohnson541** [comment]
I'm not sure about 
```
Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.
```
but I'm pretty sure the error that finishes it is due to the fitting matrix having linearly dependent columns.  This is almost definitely a bug, because I'm pretty sure "do not have adequate information for TST, using default kinetics values."  should only trigger if the reaction is being estimated from RMG-database.

**Comment by cjmcgill** [comment]
I don't have separate calculations for the prereaction complexes. But I don't know that's going to be the problem, I've run things before that had negative activation energies in the past and I think another reaction in this set that didn't result in the error had it as well. More important than the energy or enthalpy barrier, these still have higher free energy at the transition state so I think a TST calculation should still work. What kind of information can I provide to help: inputs and the gaussian files?

**Comment by alongd** [comment]
I ran your files, and did not get an error. The energetics seem faulty: 
![image](https://user-images.githubusercontent.com/16158262/55821806-4f31c200-5acc-11e9-8f83-30f982ebec2e.png)
![image](https://user-images.githubusercontent.com/16158262/55821817-5527a300-5acc-11e9-9eaa-a6cc4d68b1bc.png)
Maybe check the TS geometry/energy?

**Comment by cjmcgill** [comment]
Yep, that's going to be from that transition state basis set mismatch I found. I think that's likely the problem. I realize now that the energies that I was checking against for reasonableness were actually a different reaction in the same set and not the one that was errorring.

**Comment by alongd** [comment]
I wonder how Arkane could have given you a better error message to assist in identifying the problem quicker. For me it didn't crush, and no warning lights flashed. Perhaps we could think of a maximum barrier hight above which a helpful warning could be thrown (but still a rate will be calculated if possible).

**Comment by cjmcgill** [comment]
Yes, fixing that basis set mismatch fixed the problem. Thanks for the assistance!
