### ISSUE TITLE
Species in the input file should be checked for connectivity

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#1576]
### Bug Description
Running the model in the attached input file on the mster branches resulted in the following error and trace:
```
After model enlargement:
    The model core has 43 species and 1 reactions
    The model edge has 98 species and 263 reactions


Initialization complete. Starting model generation.

conditions choosen for reactor 0 were: T = 298.0 K, 
Generating initial reactions for reaction system 1...
Error: Problem family: R_Recombination
Error: Problem reactants: (Molecule(SMILES="NC1C2CCN(C1C(C1=CC=CC=C1)C1C=CC=CC=1)CC2"),)
Traceback (most recent call last):
  File "/home/alongd/Code/RMG-Py/rmgpy/scoop_framework/util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/react.py", line 75, in reactSpecies
    reactions = getDB('kinetics').generate_reactions_from_families(speciesTuple)
  File "/home/alongd/Code/RMG-Py/rmgpy/data/kinetics/database.py", line 518, in generate_reactions_from_families
    reaction_list.extend(self.react_molecules(combo, products=products, only_families=only_families, prod_resonance=resonance))
  File "/home/alongd/Code/RMG-Py/rmgpy/data/kinetics/database.py", line 544, in react_molecules
    reaction_list.extend(family.generateReactions(molecules, products=products, prod_resonance=prod_resonance))
  File "/home/alongd/Code/RMG-Py/rmgpy/data/kinetics/family.py", line 1607, in generateReactions
    self.__generateReactions(reactants, products=products, forward=False, prod_resonance=prod_resonance))
  File "/home/alongd/Code/RMG-Py/rmgpy/data/kinetics/family.py", line 1960, in __generateReactions
    atom.label = label
AttributeError: 'list' object has no attribute 'label'
```

### How To Reproduce
The attached input file on the master branches reproduces this. It took 6 hrs to run. If needed, I'll see if I can create a faster version of it that crashes with the same error.

[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3064272/input.txt)

**Comment by alongd** [comment]
#821 had the same error message

**Comment by alongd** [comment]
I turns out (thanks, @mjohnson541) that the problem was "just" ill-defining species in the input file. We had some species in which not all atoms were connected to one another (similar to #821).
We should check the input file for such cases and crush RMG, giving a useful error message.

**Comment by rwest** [comment]
Just a headsup: RMG-Cat (soon to be merged) represents physisorbed (van der Waals) adsorbates as being part of the same chemgraph but with no bond to the surface.

```
        1 *2 X u0 p0 c0
        2 *1 C u0 p0 c0 {3,S} {4,S} {5,S} {6,S}
        3    H u0 p0 c0 {2,S}
        4    H u0 p0 c0 {2,S}
        5    H u0 p0 c0 {2,S}
        6    H u0 p0 c0 {2,S}
```

this was chosen because there is no one atom to which you should draw the bond, and picking one arbitrarily would mess up isomorphism detection, not to mention valency checks.

It should be easy enough to special-case it, because the non-bonded atom will always be a surface site `X`.

(not sure if it's relevant, but I fixed isomorphism detection for disconnected graphs in https://github.com/ReactionMechanismGenerator/RMG-Py/commit/f3641bb115b2cf5bafa0883f2b10424387f1b321 )
