### ISSUE TITLE
Generating Mechanism For Toluene

### ISSUE THREAD

**Issue by rlawson** [ReactionMechanismGenerator/RMG-Py#1579]
Topic: Running RMG
I'm basically trying to generate a simple mechanism for stoichiometric toluene - air reaction system at low temperature conditions; initial temperature 800K and initial pressure 30 bar. After running for 4 days, only ~ 32 species  and 43 reactions have been added to the model and the simulation is still ongoing. This has been a very slow simulation and I was wondering if there is a way to speed it up?  Attached is the toluene-air log file
I run a similar case but for propane-air simulation at similar conditions and it was initially slow but later sped up. It took about a day to get 130 species and 1296 reactions.

[RMG.log](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3099451/RMG.log)

**Comment by mjohnson541** [comment]
In the model block put `filterReactions=True`, that should speed you up a lot in itself.  For oxidation of molecules as large as Toulene you may need to set pruning parameters to get a large enough model see:  http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/input.html#model-tolerances.
