### ISSUE TITLE
Ring corrections defined different java <-> python version

### ISSUE THREAD

**Issue by agvandeputte** [ReactionMechanismGenerator/RMG-Py#158]
I noticed that when calculating thermo on dev.rmg.mit.edu, gauche corrections are added to rings while in java ring corrections are omitted completely for ring containing species.

Somehow I feel that the java approach is the easiest way to go and define ring corrections relating to the "strain free open ring analogue".  Although someone will have to rewrite the code that the ring structure gets recognized and all internal gauche /cis/1,5 corrections are discarded while external effect in branches and between branches and the ring should still be accounted for.

**Comment by mliu49** [comment]
Stale. Long distance corrections have since been completely redesigned.
