### ISSUE TITLE
Import chemkin mechanism

### ISSUE THREAD

**Issue by AH9316** [ReactionMechanismGenerator/RMG-Py#1581]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

### Context
I was trying to use importChemkinLibrary.py script to import chemkin mechanism into RMG database.

### Question
RMG shows me:

Traceback (most recent call last):
  File "importChemkinLibrary.py", line 34, in <module>
	speciesList, reactionList = loadChemkinFile(chemkinPath, dictionaryPath)
  File "rmgpy/chemkin.pyx", line 862, in rmgpy.chemkin.loadChemkinFile
  File "rmgpy/chemkin.pyx", line 884, in rmgpy.chemkin.loadChemkinFile
  File "rmgpy/chemkin.pyx", line 1221, in rmgpy.chemkin.readReactionsBlock
rmgpy.exceptions.ChemkinError: Invalid reaction block.

This model works fine with PREMIXED code, I do not understand why RMG shows me there is an invalid reaction block.

### Installation Information
Describe your installation method and system information if applicable.
 - OS (include version if known): (e.g. Windows 10, Ubuntu 18, macOS 10.13, etc.)
 - Installation method: (e.g. installation from binary or source, with or without anaconda)
 - RMG version information:
   
   - RMG-Py: 
   - RMG-database:

**Comment by alongd** [comment]
Could you upload your chemkin file so we can take a look?
Also, make sure you have an [RMG species dictionary](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/modules/databaseScripts.html#importchemkinlibrary-py) for this model (necessary for running this script).

**Comment by AH9316** [comment]
Here are the chemkin file and species dictionary file. @alongd 
[chemkin.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3108574/chemkin.zip)

**Comment by mjohnson541** [comment]
RMG requires the rate and energy units to be assigned in the reaction block of the chemkin file for example:  
REACTIONS    KCAL/MOLE   MOLES

**Comment by AH9316** [comment]
I add the unit, but it still gives me the same error that shows above. Is that possible to find chemkin.pyx file? I try to find it in rmgpy directory, but as shown below, there is on this file in my rmgpy directory.
![rmg](https://user-images.githubusercontent.com/49660649/56614646-5974b580-65ce-11e9-9b41-e073d2ddf19f.png)

**Comment by mliu49** [comment]
I think the comments in the file which contain `Reactions` are messing up the RMG parser. It seems that we don't properly check for comment lines at the file level (we do check within the individual blocks).

For now, the easiest solution might be to either remove all comment lines or find and replace the word `Reactions` in comments with something else.

Thanks for bringing this bug to our attention!

**Comment by AH9316** [comment]
I delete all comments that include Reactions, however, it still shows me the same error.

**Comment by mliu49** [comment]
There are also some comments which contain the word `reactions` (all lowercase). Removing those got me past the `Invalid reaction block` error, but RMG then raised another error was due to a missing `END` marker for the `SPECIES` block.

Fixing that gave me the following error:
```
Traceback (most recent call last):
  File "/home/mjliu/Code/RMG-database/scripts/importChemkinLibrary.py", line 49, in <module>
    shortDesc = species.thermo.comment
  File "/home/mjliu/Code/RMG-Py/rmgpy/data/thermo.py", line 612, in loadEntry
    raise DatabaseError('Adjacency list and multiplicity of {0} matches that of existing molecule {1} in thermo library {2}.  Please correct your library.'.format(label, entry.label, self.name))
rmgpy.exceptions.DatabaseError: Adjacency list and multiplicity of CH3CHCHCHO matches that of existing molecule CH3CHCHCO in thermo library test.  Please correct your library.
```

At this point, the Chemkin file parsing is already complete, but RMG is complaining that two species in the thermo library it is trying to create are identical. You should resolve this by checking the adjacency lists for those two species in you species dictionary.

**Comment by AH9316** [comment]
Thanks @mliu49 !! It is really helpful, but after fixing these two problems, the RMG shows me another problem:
Traceback (most recent call last):
  File "importChemkinLibrary.py", line 47, in <module>
	molecule = species.molecule[0].toAdjacencyList(),
IndexError: list index out of range

Does RMG have a limit number of imported species?

**Comment by mliu49** [comment]
There's no limit on the number of imported species. The error is because there was a species missing from the dictionary file. Adding this to the species dictionary should fix the issue (and it ran to completion afterwards):
```
C4H6O25
1  O u0 p2 c0 {2,S} {5,S}
2  C u0 p0 c0 {1,S} {3,S} {6,S} {7,S}
3  C u0 p0 c0 {2,S} {4,D} {8,S}
4  C u0 p0 c0 {3,D} {5,S} {9,S}
5  C u0 p0 c0 {1,S} {4,S} {10,S} {11,S}
6  H u0 p0 c0 {2,S}
7  H u0 p0 c0 {2,S}
8  H u0 p0 c0 {3,S}
9  H u0 p0 c0 {4,S}
10 H u0 p0 c0 {5,S}
11 H u0 p0 c0 {5,S}
```
