### ISSUE TITLE
How to allow library species which are forbidden in RMG?

### ISSUE THREAD

**Issue by AH9316** [ReactionMechanismGenerator/RMG-Py#1582]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [x] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [x] An error message 

### Context
After importing thermo library and kinetic library, I want to test if I can use them as thermolibrary and seedmechanism to run a simulation. RMG shows me that:

Traceback (most recent call last):
  File "rmg.py", line 173, in <module>
	main()
  File "rmg.py", line 167, in main
	rmg.execute(**kwargs)
  File "/home/anguohu/anaconda2/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 603, in execute
	self.initialize(**kwargs)
  File "/home/anguohu/anaconda2/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 489, in initialize
	self.reactionModel.addSeedMechanismToCore(seedMechanism, react=False)
  File "/home/anguohu/anaconda2/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/model.py", line 1483, in addSeedMechanismToCore
	database.kinetics.loadLibraries(path=path,libraries=[rxn.library])
  File "/home/anguohu/anaconda2/envs/rmg_env/lib/python2.7/site-packages/rmgpy/data/kinetics/database.py", line 235, in loadLibraries
	raise IOError("Couldn't find kinetics library {0}".format(library_file))
IOError: Couldn't find kinetics library /home/anguohu/anaconda2/envs/rmg_env/share/rmgdatabase/kinetics/libraries/Unclassified/reactions.py

In order to let RMG find Unclassified reacions.py file, I create Unclassified directory and copy reactions.py and dictionary.txt from imported kinetic directory to Unclassified directory. And then, I run RMG again and I pass the above error, however, I get a new error:

Traceback (most recent call last):
  File "rmg.py", line 173, in <module>
	main()
  File "rmg.py", line 167, in main
	rmg.execute(**kwargs)
  File "/home/anguohu/anaconda2/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 603, in execute
	self.initialize(**kwargs)
  File "/home/anguohu/anaconda2/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 489, in initialize
	self.reactionModel.addSeedMechanismToCore(seedMechanism, react=False)
  File "/home/anguohu/anaconda2/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/model.py", line 1516, in addSeedMechanismToCore
	raise ForbiddenStructureException("Species constraints forbids species {0} from seed mechanism {1}. Please reformulate constraints, remove the species, or explicitly allow it.".format(spec.label, seedMechanism.label))
rmgpy.exceptions.ForbiddenStructureException: Species constraints forbids species C from seed mechanism imported_USC_Mechii. Please reformulate constraints, remove the species, or explicitly allow it.

### Question
1. Why I put imported kinetic library(named imported_USC_Mechii)  in seedmechanism, the RMG try to find reaction.py in Unclassified directory?
2. How to allow forbids species C? 

I attach imported thermo library, kinetic library and test input file below.
[imported_thermo_kinetic_input.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3110196/imported_thermo_kinetic_input.zip)

**Comment by AH9316** [comment]
I notice that the imported kinetic library is different from the original RMG kinetic library, below is the imported kinetic library
![rmg_problem1](https://user-images.githubusercontent.com/49660649/56628330-44b01600-65fe-11e9-8e18-1e1d0b4574f0.png)

Below is original RMG kinetic library
![RMG_problem2](https://user-images.githubusercontent.com/49660649/56628332-4679d980-65fe-11e9-950f-576639b8274b.png)

Question:         
a. what is “autoGenerated”?
b. why the longDesc of imported kinetic library shows that originally from unclassified reaction library? Is this why RMG look for reaction.py from Unclassified directory?
c. the index number of entry, python should start from 0, but RMG kinetic library start from 1, does it a matter for RMG simulation?

**Comment by alongd** [comment]
To allow library species which are forbidden in RMG, add a `generatedSpeciesConstraints` block to your input file (see http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/input.html#species-constraints). Specifically, specify `allowed=['input species','seed mechanisms','reaction libraries'],`

Addressing some the other questions:
- `autoGenerated` implies that the library was machine-written. I'm uncertain whether it has any significance or actually does something.
- I'm not sure about the unclassified library description (while not ideal, it shouldn't be a concern for using this library)
- The indices must be unique, but a library is functional with any (non-negative?) integer indices, even if not consecutive. They can start at whatever number. I do agree, though, that this should be more consistent, but, again, no reason to worry.

**Comment by mliu49** [comment]
To provide some more context:
- I believe `autoGenerated` has to do with when we automatically generate reaction libraries during RMG runs for the purpose of restarting the run. @mjohnson541 would be able to comment on exactly what the flag implies.
- When loading Chemkin files, we load any reaction which does not have RMG generated comments as an "Unclassified" LibraryReaction. Unfortunately, I don't know why we chose to do this. In the `loadChemkinFile.py` script, we automatically add the "source" library to the description. This could definitely be improved.
- Entries were originally indexed from 1. This was changed a while ago to begin indexing at 0 (i.e. consistent with Python indexing). We didn't go back to and change existing files, but all programmatically written database files will start at 0 now.

**Comment by AH9316** [comment]
Thank you for your response. Is there any other way to solve the problem that RMG try to find imported kinetic library from "Unclassified" directory? 

I notice that if we only use one imported kinetic library, it is ok to create an Unclassified directory in "kinetic/library directory" and copy reaction.py and dictionary.txt to "Unclassified directory". However, if we want to use more than one imported kinetic library as seed mechanism and RMG try to read all these imported kinetic libraries from Unclassified directory, I think that would be a problem because we only can have one reaction.py and one dictionary.txt in this directory.
