### ISSUE TITLE
Improvements needed to importChemkinLibrary.py and loadChemkinFile()

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1584]
As highlighted by #1581 and #1582, there are a number of improvement which should be made to `importChemkinLibary.py` and the Chemkin file parser. Note that `importChemkinLibrary.py` is located in `RMG-database/scripts`, but I thought I would post the issue here for visibility.

- [ ] Check for and ignore comment lines when searching for the main input sections ([code location](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/chemkin.pyx#L862))
- [ ] Check that species in the Chemkin file have adjacency lists provided in the dictionary (this could be implemented in `chemkin.pyx`, or we could catch the error and provide a helpful message [here](https://github.com/ReactionMechanismGenerator/RMG-database/blob/master/scripts/importChemkinLibrary.py#L45))
- [ ] Don't append the source library to the long description in the kinetics library entry if reaction.library is "Unclassified" ([code location](https://github.com/ReactionMechanismGenerator/RMG-database/blob/master/scripts/importChemkinLibrary.py#L66))
- [ ] Add `readComments` argument to `importChemkinLibrary.py` which can be passed to `loadChemkinFile` so we ignore comments when loading non-RMG files.

**Comment by NUSCondy** [comment]
Hi @mliu49 ,
Any updates on this script? Since I also want to import the library using this script but encounter many errors.
