### ISSUE TITLE
Annoyance/confusion from multiple testing databases

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#1586]
### Motivation or Problem
It can be annoying that there is `data/test_data/thermo` **AND** `testdata/testing_database/thermo` in the RMG-Py project
that both need to be kept up to date and in sync with the actual RMG-database.
Any chance this could be simplified or consolidated?

**Comment by mliu49** [comment]
I agree. I don't see any reason why we need to keep `data/test_data/thermo`.
