### ISSUE TITLE
filterReaction doesn't work

### ISSUE THREAD

**Issue by AH9316** [ReactionMechanismGenerator/RMG-Py#1589]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [x] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

### Context
We try to use filterReaction to speed up the simulation, however, when we add filterReaction=True to model block, it doesn't work and somehow it makes simulation crash. We attach input files and log files we get from 2 propane silumations.
[simulation_log_file.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3119814/simulation_log_file.zip)

### Question
1. Why did the model crash with filterReaction and the model that at the same conditions but without filterReaction worked well?

2. Another general question: if we get a chemkin file based on a blended fuel,  such as 80% propane and 20% toluene; and then we use this chemkin to do the ignition delay time(IDT) simulations with different fuel composition, such as 70% propane and 30% toluene.  How does the fuel composition in RMG affect other simulations using chemkin file from RMG but with different fuel composition?

3. We can use RMG to merge 2 models. If we merge 2 models from pure propane RMG simulation and pure toluene RMG simulation, respectively, we should get a model or chemkin file that include propane and toluene. Compare to blended fuel RMG simulation, is this a better way or can we get a better mechanism with the merge tool?

**Comment by mjohnson541** [comment]
1) I can't reproduce the IO errors locally.  I think they may be related to how you're running RMG on your server, but I don't think setting filterReactions=True would have an effect on that.  

2) This is a really complicated question.  RMG attempts to determine all of the reactions that are important for the particular reactors you ask for and provides few guarantees outside that.  However, I wouldn't think 80%:20% to 70%:30% fuel ratios would enormously change the involved reactions.  

3)  Blended fuel RMG simulation is a significantly better way to do this when feasible.  Simply merging the two models you miss any cross reactions which can be quite important.  One other approach people have used is to merge the models and then run them in RMG for a while to generate the cross reactions.

**Comment by AH9316** [comment]
For the No. 3 solution, do you mean that we can merge 2 models and import the merged model to RMG, and then running RMG with the merged model, for example, set merged model as reaction library?

**Comment by mjohnson541** [comment]
Yes, although you should set them as seed mechanisms rather than reaction libraries.
