### ISSUE TITLE
RMG v2.4.0 (?) Release Planning

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1591]
With the RMG-cat merge completed, I think we should have a new release soon. Potential target release date could be end of May. Please feel free to provide your own thoughts.

First, regarding the release number, I'm leaning towards `2.4.0`. The RMG-cat merge is a major new feature, but it didn't introduce any backward compatibility issues, so I'm not sure if it would necessitate jumping to `3.0.0`. Also, thinking ahead, it would be nice to transition to Python 3 and fix our variable naming inconsistencies for the `3.0.0` release, which would definitely involve breaking changes. Of course, this is also open for discussion.

Next, we need to identify any issues/PRs which we want to include in this release. Potential list:
- [ ] Update IPython notebooks and examples #1541
- [ ] Multiprocessing #1459 
- [ ] Chemical identity comparison #1329 
- [ ] Uncertainty user experience fixes (PR coming soon)
- [ ] Database cleanup? @mjohnson541 

Please use this issue thread to comment on the status of currently open PRs and whether or not they can/should be included in this release. RMG-database PRs can also be discussed here rather than creating a separate RMG-database issue.

**Comment by mliu49** [comment]
Another topic for discussion: Would we like to begin official support for Docker with this release?

For people not in the Green Group who may not know about this, we have been considering Docker as a way to offer a host-independent method of installing RMG. This can be especially useful for installing on HPC clusters which may already have support for Docker images. Somewhat surprisingly, there were already a couple of RMG images on Docker Hub. For testing, I've created a semi-official one which can be pulled: https://hub.docker.com/r/mliu49/rmg.

The main benefit would be offering a streamlined option for running RMG on a wider variety of systems, including non-ubuntu linux systems and windows, at the cost of adding another system which we would need to manage and support.

What this would entail:
- Finalize dockerfile for building RMG image
- Develop and document recommended workflow for using RMG via Docker
- Develop workflow for creating Docker images (ideally automated, but not strictly necessary)

**Comment by rwest** [comment]
Docker sounds like a decent idea, (though I'm not volunteering my own time to support it. I think @skrsna has done some docker stuff)

I think 2.4.0 is reasonable. Nice to have 3.0 be the Python 3 version. 

May sounds like a good target

**Comment by alongd** [comment]
I think we should merge #1496 and https://github.com/ReactionMechanismGenerator/RMG-database/pull/296
Might as well also do #1575, which is small

**Comment by goldmanm** [comment]
Is it worthwhile to get in commits necessary for the Arkane paper? Like @mjohnson541 's quantum hindered rotors, and my reorganizing the output of Arkane?

**Comment by alongd** [comment]
I agree, let's try to get it in

**Comment by mliu49** [comment]
# RMG-Py v2.4.0 Release Notes (draft)
- Heterogeneous catalysis!
  - RMG-cat fork has been merged #1573
    - Introduce SurfaceReactor
    - Thermo estimation for adsorbed species
    - Surface reaction generation and kinetics estimation
  - Introduce Van der Waals bonds (order 0) and quadruple bonds (order 4) #1542
- Arkane
  - Automatically detect rotor symmetry #1526
  - Introduce new YAML files for storing and loading species statmech data #1402, #1551 
  - Don't create species dictionary file if there are no structures #1528
  - Improvements to network explorer tool #1545
  - Improved class inheritance for quantum log file classes #1571
  - Automatic determination of optical isomers and symmetry using `symmetry` package #1571
  - Parse CCSD(T) energies from Molpro output #1592
- Miscellaneous features
  - New `enumerate_bonds` method of Molecule to generate dictionary of bond types #1525
  - Introduce `RMGObject` parent class to support YAML dumping and loading #1402, #1540
  - Add support for fluorine atomtypes #1543
  - Introduce `ArrheniusBM` class for Blower-Masel kinetics #1461 
  - Allow defining and using co-solvents for solvent libraries #1558
- Bug fixes
  - Various fixes for supporting mono-atomic molecules in Arkane #1513, #1521
  - Ensure `keras_backend` is set consistently #1535
  - Fix handling of disconnected graphs in VF2 isomorphism algorithm #1538
  - Ignore hydrogen bonds when converting to RDKit molecule #1552
  - Other miscellaneous bugs #1546, #1556, #1600
- Backward incompatible changes
  - Hydrogen bonds are now order 0.1 (instead of 0) #1542
- Other
  - Windows binaries are no longer officially supported. The new recommended way to use RMG on Windows computers is via a virtual machine or through the Linux subsystem. See documentation for updated installation instructions. #1531, #1534
  - Documentation updates #1544, #1567
  - Logging/exception improvements #1538, #1562
  - PEP-8 improvements #1566, #1592, #1596
  - Solver output files (png/csv) now report moles instead of mole fractions #1542
  - Replace global RMGDatabase object if the database is reloaded #1565
  - Print ML generated quote upon completion of RMG jobs #1573
  - Infrastructure for automatically generated reaction rate trees #1461

# RMG-database v2.4.0 Release Notes (draft)
(note that the tags here are odd because this issue is in the RMG-Py repo; the final release notes will be in the RMG-database repo so they will be normal)
- Heterogeneous catalysis!
  - RMG-cat fork has been merged ReactionMechanismGenerator/RMG-database#309
  - New kinetics families
    - Surface_Adsorption_Single
    - Surface_Adsorption_vdW
    - Surface_Adsorption_Dissociative
    - Surface_Dissociation
    - Surface_Abstraction
    - Surface_Adsorption_Double
    - Surface_Dissociation_vdW
    - Surface_Adsorption_Bidentate
    - Surface_Bidentate_Dissociation
    - Surface_Recombination (deprecated, use Surface_Dissociation instead)
  - New thermo group types
    - adsorptionNi
    - adsorptionPt
  - New thermo libraries
    - surfaceThermoNi
    - surfaceThermoPt
- New kinetics families
  - 1,2_NH3_elimination ReactionMechanismGenerator/RMG-database#326
  - 1,3_NH3_elimination ReactionMechanismGenerator/RMG-database#326
- New kinetics libraries
  - HydrazinePDep ReactionMechanismGenerator/RMG-database#326
- New transport libraries
  - OneDMinN2 ReactionMechanismGenerator/RMG-database#326
- Kinetics training reaction additions
  - 1,2_shiftC ReactionMechanismGenerator/RMG-database#306
  - Intra_R_Add_Endocyclic ReactionMechanismGenerator/RMG-database#306, ReactionMechanismGenerator/RMG-database#258
  - Intra_R_Add_Exocyclic ReactionMechanismGenerator/RMG-database#306, ReactionMechanismGenerator/RMG-database#258
  - Intra_ene_reaction ReactionMechanismGenerator/RMG-database#306
  - R_Addition_COm ReactionMechanismGenerator/RMG-database#306
  - R_Addition_MultipleBond ReactionMechanismGenerator/RMG-database#306, ReactionMechanismGenerator/RMG-database#258
  - R_Recombination ReactionMechanismGenerator/RMG-database#306,  ReactionMechanismGenerator/RMG-database#326
  - Intra_H_migration ReactionMechanismGenerator/RMG-database#306
  - H_Abstraction ReactionMechanismGenerator/RMG-database#326
- Kinetics library additions
  - primaryNitrogenLibrary ReactionMechanismGenerator/RMG-database#326
  - Lai_Hexylbenzene ReactionMechanismGenerator/RMG-database#258
- Thermo library additions
  - CBS_QB3_1dHR, thermo_DFT_CCSDTF12_BAC ReactionMechanismGenerator/RMG-database#319
  - primaryNS ReactionMechanismGenerator/RMG-database#326
  - Lai_Hexylbenzene ReactionMechanismGenerator/RMG-database#258
- Thermo group additions
  - ring, polycyclic, radical ReactionMechanismGenerator/RMG-database#258
- Changes
  - [adjlist] kinetics/libraries/Klippenstein_Glarborg2016 ReactionMechanismGenerator/RMG-database#308
  - [labels] thermo/libraries/CBS_QB3_1dHR, Narayanaswamy ReactionMechanismGenerator/RMG-database#306
  - [units] kinetics/libraries/Sulfur/GlarborgMarhsall, Nitrogen_Dean_and_Bozzelli, primaryNitrogenLibrary, primarySulfurLibrary ReactionMechanismGenerator/RMG-database#311
  - [units] R_Addition_MultipleBond/training, R_Recombination/training ReactionMechanismGenerator/RMG-database#312
  - [adjlist] kinetics/libraries/GRI-Mech3.0-N ReactionMechanismGenerator/RMG-database#313
  - [adjlist] thermo/libraries/GRI-Mech3.0-N, GRI-Mech3.0 ReactionMechanismGenerator/RMG-database#313
  - [rates] Disproportionation/training, R_Addition_MultipleBond/training ReactionMechanismGenerator/RMG-database#326
  - [labels] kinetics/libraries/NOx2018 ReactionMechanismGenerator/RMG-database#326
  - [labels, attributes] kinetics/libraries/Nitrogen_Dean_and_Bozelli ReactionMechanismGenerator/RMG-database#326
  - [labels] kinetics/librariesNitrogen_Glarbog_Gimenez_et_al, Nitrogen_Glarborg_Zhang_et_al  ReactionMechanismGenerator/RMG-database#326
  - [labels, adjlist] thermo/libraries/BurcatNS ReactionMechanismGenerator/RMG-database#326
  - [labels] thermo/libraries/NOx2018, NitrogenCurran ReactionMechanismGenerator/RMG-database#326
  - [labels] transport/libraries/NOx2018 ReactionMechanismGenerator/RMG-database#326

**Comment by mliu49** [comment]
Please feel free to edit the draft release notes above. I would also appreciate it if everyone could help keep this up to date as we merge more PRs before the release.

**Comment by mliu49** [comment]
Release is done!
