### ISSUE TITLE
Arithmetic underflow in spectral fortran code

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#16]
<pre>
 _modes.f90:58.44:

 qt = ((2 * 3.141592654 * mass) / (6.626e-34 * 6.626e-34))**(dim/2.0) * V
                                           1
Warning: Arithmetic underflow at (1)
</pre>

this is with gnu fortran gfortran, and may be because the -r8 flag is not recognized?

**Comment by JacksonBurns** [comment]
This has since been resolved by using a modern fortran compiler. Closing as _very_ stale.
