### ISSUE TITLE
Inaccurate error messages in arkane.log

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1602]
Just noticed that all of the `NotImplementedError` messages are identical in the `arkane.log.Log` class: https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/arkane/log.py#L56.

It would be ideal to update those before the release.

I would also suggest adding a note to the message that "this method should be implemented by a subclass" or something to that effect.

**Comment by goldmanm** [comment]
fixed by #1603
