### ISSUE TITLE
Restart error

### ISSUE THREAD

**Issue by PWstmrlnd** [ReactionMechanismGenerator/RMG-Py#1606]
### How To Reproduce
Steps to reproduce the behavior.

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): (e.g. Windows 10, Ubuntu 18, macOS 10.13, etc.)
 - Installation method: (e.g. installation from binary or source, with or without anaconda)
 - RMG version information:
   
   - RMG-Py: 
   - RMG-database:

**Comment by PWstmrlnd** [comment]
_**Bug Description:** Restart fails during load of restart file, giving a "Type Error"
**How to Reproduce:** _Run with "_rmg.py input.py -r_" from a halted file.
**Expected Behavior:** I expected the restart to run the interrupted job. Initially, I thought I could restart with revised input.py file but that failed. Eventually, I tried running with the original input.oy and the run still failed in the same way.
**Installation Information:** 

- OS: macOS 10.14.5 (18F132) on MacBookPro (Retina, 13-inch, Mid 2014), 3 GHz Intel Core i7, memory of 16 GB 1600 MHz DDR3, Apple 1TB SSD.
- Installation method: Installation from binary using anaconda
- RMG version information:
1. - RMG-Py: 2.3.0, build py27h1d22016_1
2. - RMG-database: 2.3.0

**Additional context:**
I had started a job on Friday at 22:38 and it stopped abruptly this morning (Monday) with the message:
...
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "C=Cc1c[c]cc2ccccc12(4499) <=> C=Cc1cc2cc3[CH]C2C=Cc31(5726)".
Killed: 9

_I did not execute any action to kill it (like control z). This evening I duplicated the folder, renamed it, modified the input.py file, tried to run with "_rmg.py input.py -r_", and it proceeded well until it began loading the restart file, failing with the output below. I also try using the unaltered folder and unaltered input.py._

Loading previous restart file...
Traceback (most recent call last):
  File "/Users/mcninch/anaconda2/envs/rmg_env/bin/rmg.py", line 173, in <module>
    main()
  File "/Users/mcninch/anaconda2/envs/rmg_env/bin/rmg.py", line 167, in main
    rmg.execute(**kwargs)
  File "/Users/mcninch/anaconda2/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 603, in execute
    self.initialize(**kwargs)
  File "/Users/mcninch/anaconda2/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 483, in initialize
    self.initializeRestartRun(os.path.join(self.outputDirectory,'restart.pkl'))
  File "/Users/mcninch/anaconda2/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 1429, in initializeRestartRun
    self.loadRestartFile(path)
  File "/Users/mcninch/anaconda2/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 1500, in loadRestartFile
    rmg_restart = cPickle.load(f)
  File "/Users/mcninch/anaconda2/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/pdep.py", line 83, in __init__
    pairs=pairs
  File "rmgpy/reaction.py", line 117, in rmgpy.reaction.Reaction.__init__
TypeError

**Comment by PWstmrlnd** [comment]
Happened again but after only about 18 hrs.

**Comment by rwest** [comment]
“Killed: 9” suggests the OS killed the process because it used all available memory. 

I think the warning about significant corrections means the pressure dependence code was struggling, and probably needed a lot of energy grains to resolve things, which means a big matrix, and a lot of memory. 

Probably pruning of some sort will help. 

The failure of the restart mechanism is unfortunate, but I expect unrelated. I am not sure restarting is well-maintained, or often used by developers.

**Comment by mjohnson541** [comment]
In general RMG's restart files take a long time to generate, can crash during generation and tend to not be very reliable methods of restart.  This is primarily a result of that fact that the developer who originally built the feature didn't write tests for it and the fact that not many developers use the feature.  At this point it really should be deprecated.   

We've been working on a much simpler and lighter solution using saved seed mechanisms for core and edge, saved filter matrices and pdep network files.  However, only the seed mechanism saving is fully implemented in current RMG so far.  In the near future we expect to be able to restart non-pdep runs easily from saved core and edge seed mechanisms and filter matrices.  Pdep reloading is a bit farther off.  However, for the moment we don't really recommend use of RMG's restart files.

**Comment by PWstmrlnd** [comment]
Bummer -- but thanks. Better times ahead!
---
*Phillip R. "Phil" Westmoreland*
Professor, Department of Chemical and Biomolecular Engineering, NCSU
2036 Engineering Building I, Box 7905; NCSU; Raleigh, NC 27695-7905
Office: (919) 515-7121; Fax (919) 515-3465
prwestmo@ncsu.edu <phil.westmoreland@ncsu.edu>;
https://www.cbe.ncsu.edu/people/prwestmo
Calendar:
http://www.google.com/calendar/embed?src=prwestmo%40ncsu.edu&ctz=America/New_York
All email in connection with State business is subject to the NC Public
Records Law and may be disclosed to third parties.
