### ISSUE TITLE
Explicit valence for atom # 2 N, 4, is greater than permitted

### ISSUE THREAD

**Issue by rookieSu** [ReactionMechanismGenerator/RMG-Py#1610]
Hello everyone:
  when I use EmbedMolecule, there is a problem:"Explicit valence for atom # 2 N, 4, is greater than permitted", Can you give me a hand to fix the problem.
  The follow is my mol file:
  3D Atomistic
     RDKit          3D

 28 29  0  0  0  0  0  0  0  0999 V2000
   -3.3389    0.3275    0.2775 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.7266   -0.9911   -0.2218 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2565   -0.8208   -0.3808 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9344    0.5551    0.0018 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1699    1.2563    0.3983 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.4647    1.1983   -0.0004 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.6991    0.4988   -0.4034 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.8689    1.4265   -0.2798 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.2582    2.7428    0.2275 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7883    2.5721    0.3888 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2988    0.0090    0.2719 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7209    0.8772   -0.1138 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7287   -0.8660   -0.1113 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2988    0.0090    0.2719 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7209    0.8772   -0.1138 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7287   -0.8660   -0.1113 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2988    0.0090    0.2719 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7209    0.8772   -0.1138 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7287   -0.8660   -0.1113 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2988    0.0090    0.2719 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7209    0.8772   -0.1138 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7287   -0.8660   -0.1113 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2988    0.0090    0.2719 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7209    0.8772   -0.1138 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7287   -0.8660   -0.1113 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2988    0.0090    0.2719 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7209    0.8772   -0.1138 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7287   -0.8660   -0.1113 H   0  0  0  0  0  0  0  0  0  0  0  0
  3  2  1  0
  4  3  1  0
  5  4  2  0
  1  2  2  0
  1  5  1  0
  4  6  1  0
  8  7  1  0
  9  8  2  0
 10  9  1  0
  6  7  2  0
  6 10  1  0
  1 11  1  0
 11 13  1  0
 11 12  1  0
  2 14  1  0
 14 16  1  0
 14 15  1  0
  3 17  1  0
 17 19  1  0
 17 18  1  0
  8 20  1  0
 20 22  1  0
 20 21  1  0
  9 23  1  0
 23 25  1  0
 23 24  1  0
 10 26  1  0
 26 28  1  0
 26 27  1  0
M  CHG  2   3  -1  10  -1
M  END
                                                             thanks

**Comment by mjohnson541** [comment]
I think you're on the wrong repository this is the issues page for RMG-Py not rdkit.

**Comment by rookieSu** [comment]
thanks for your answer, can you tell me how to fix it?

**Comment by rookieSu** [comment]
> I think you're on the wrong repository this is the issues page for RMG-Py not rdkit.

thanks for your answer, can you tell me how to fix it?

**Comment by mliu49** [comment]
Sorry, we don't know enough about RDKit to provide an appropriate solution to your problem.

I would suggest posting to the RDKit issues page: https://github.com/rdkit/rdkit/issues
