### ISSUE TITLE
Building models for fuel blends

### ISSUE THREAD

**Issue by rlawson** [ReactionMechanismGenerator/RMG-Py#1611]
I want to create a model for a gasoline surrogate with components n-heptane, isooctane and toluene in the ratio 20%, 60% and 20% respectively. I believe I can just specify this as the initial moles with oxygen and nitrogen (air) and generate a model after a couple of days. 

However, since it is a fuel blend, I realize it might take a long time to build an appreciable amount of species and reactions for the model. In this case will it better to first build models for toluene-air, heptane-air and isooctane-air mixtures before building a final model using these three as seed mechanisms (or reaction library) so that only the cross-reactions are evaluated?

**Comment by alongd** [comment]
Interesting question. The only thing that I can think about is that each seed will end up with different pressure-dependent networks, and perhaps from that perspective it might be better to just run everything together. I'm not entirely sure whether this is a big deal or not, but anyway you could make high-P limit models for each fuel, then only specify a P-dep block in the grand input file (if you end up trying both approaches, let us know what you observed). It does sound like a practical approach if you'd like to run the model for the blend several time (different conditions? different tolerance?), then it would be faster to have the seeds you suggested.

**Comment by mjohnson541** [comment]
This approach has been used before, and can work effectively.  The primary issue is the run when you combine them as seed mechanisms.  The bad news is that RMG won't know what stuff already reacted in the other jobs, so it will rereact a lot of species, which will take time, the good news is that RMG should now be aware of where the seed mechanism reactions came from (family and template), which means I believe you shouldn't get duplicate reactions from rereacting species.
