### ISSUE TITLE
Why did I get "ImportError: No module named graph"?

### ISSUE THREAD

**Issue by baoku6600** [ReactionMechanismGenerator/RMG-Py#1614]
General area which your question is related to.
 - [ ] Dependencies
### Context
A clear and concise description what you're trying to do.
 I want to run the code ： from .graph import Vertex, Edge, Graph, getVertexConnectivityValue
but there is no graph.py  in the folder RMG-Py\rmgpy\molecule\
### Question

The erro information：

Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

runfile('C:/Users/Paul/GAOptimization/Test1.py', wdir='C:/Users/Paul/GAOptimization')
Loading RMG-Py from C:\Users\Paul/Code/RMG-Py\rmgpy\__init__.pyc
Traceback (most recent call last):

  File "<ipython-input-1-2b3fa1407539>", line 1, in <module>
    runfile('C:/Users/Paul/GAOptimization/Test1.py', wdir='C:/Users/Paul/GAOptimization')

  File "D:\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 95, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/Paul/GAOptimization/Test1.py", line 15, in <module>
    from rmgpy.molecule import Molecule

  File "C:\Users\Paul/Code/RMG-Py\rmgpy\molecule\__init__.py", line 33, in <module>
    from .molecule import *

  File "C:\Users\Paul/Code/RMG-Py\rmgpy\molecule\molecule.py", line 48, in <module>
    from .graph import Vertex, Edge, Graph, getVertexConnectivityValue

ImportError: No module named graph

### Installation Information
Describe your installation method and system information if applicable.
 - Windows 10
 - Installation method: installation from source, without anaconda
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:42:17) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

**Comment by alongd** [comment]
The classes you're looking for are in `graph.pyx` (not `graph.py`), but that shouldn't make a difference, the python import should work all the same.
Did you [compile ](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html)RMG?

**Comment by mliu49** [comment]
See question 2: http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/faq.html#running-rmg

Also, note that installation without Anaconda is no longer supported and may not be possible at all. RMG is also not guaranteed to work on Windows. Even if you aren't planning to run RMG in its entirely and would only like to use modules independently, they may not function properly without the necessary dependencies.

**Comment by mliu49** [comment]
I'm assuming that the issue has been addressed.
