### ISSUE TITLE
Report reactants and products in a consistent deterministic order

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#1616]
### Motivation or Problem
Whenever I re-run an RMG simulation and then `diff` the log files or chemkin files to see what has changed, I have a ton of changes like this:
<img width="482" alt="Screen Shot 2019-06-05 at 12 03 05 PM" src="https://user-images.githubusercontent.com/93807/58971724-07f14600-878a-11e9-95d3-65e0ca93b9f3.png">
where it is just a reaction is written as
`16 + 34 <=> 7` one time but
`34 + 16 <=> 7` the next.

### Desired Outcome
I'd like the log files and chemkin files to come out identical if the models are chemically identical, so that what shows up in a `git diff` is actually a difference.

### Possible solutions
We could sort by species ID, eg. we always put the lowest number first, like
`16 + 34 <=> 7`, for example.

Or for library and seed reactions it could preserve the order as originally written (make it easier to look up original sources)

For template reactions we might use the labels (eg. the molecule with *1 always goes first) so that reactions of the same type are written consistently (eg. `abstractee + abstractor =>`  or `alkene + radical =>`).

**Comment by mliu49** [comment]
I tried sorting by species ID recently. It seemed to work very well, but resulted in an unexpected change to one of the unit tests for the explorer feature of Arkane. I haven't had a chance to look more into what caused the change yet.

**Comment by rwest** [comment]
Is there a reason they're shuffled in the first place? I would have thought they'd be generated in a deterministic order.

**Comment by mliu49** [comment]
#388 and #409 are related.

We sort the reactants and products, but because Species do not have comparison methods and we don't provide a sorting key, they will be sorted by object ID. Supposedly that corresponds to its memory address, but it's not clear why that is so non-deterministic.

**Comment by rwest** [comment]
Wow. A couple of four-year-old issues!  that even look like they have solutions proposed?
Thanks for digging those out. I should have done a better search myself.
Whoever fixes this can close three issues at once :-)

**Comment by mliu49** [comment]
I think this should be fixed now.

Species sorting now uses comparison methods (implemented in 0c0c7ed13c5eac36a2b4d073b91156e448e5c3d7), which use the new `sorting_key` property (implemented in c90c407ad93eb32de7cc5a6c0cd2d8192a4b5145). This will provide deterministic sorting, although the current implementation depends on the species label and index, which can change depending on thermo libraries and the order that species are generated.
