### ISSUE TITLE
No DUPLICATE mark for P-dep and Disproportionation reactions

### ISSUE THREAD

**Issue by jimchu10** [ReactionMechanismGenerator/RMG-Py#1624]
### Bug Description
When running RMG P-dep jobs, no DUPLICATE marks will be given in the output Chemkim files for same reactions duplicate in P-dep network and disproportionation reactions

### How To Reproduce
By running any RMG P-dep jobs

### Expected Behavior
RMG should be able to recognize these DUPLICATE reactions and mark them.

### Installation Information
Describe your installation method and system information.
 - OS: Ubuntu 18
 - Installation method: (e.g. installation from binary or source, with or without anaconda)
 - RMG version information: 2.3.0
   - RMG-Py: 8ce334df5df71f96f82b5a5681f4319aba2ac7dc
   - RMG-database: bcfb15fe11cee9675673ad4827d2768c88c1288f

### Additional Context
Example:
! Reaction index: Chemkin #116; RMG #339
! Template reaction: Disproportionation
! Flux pairs: C3H7(41), C3H6(57); O2(4), HO2(12); 
! Matched reaction 15 C3H7-2 + O2 <=> HO2 + C3H6-2 in Disproportionation/training
! This reaction matched rate rule [O2b;C/H2/Nd_Csrad]
! family: Disproportionation
C3H7(41)+O2(4)=HO2(12)+C3H6(57)                     1.833000e+13 0.000     14.850   

! Reaction index: Chemkin #117; RMG #360
! PDep reaction: PDepNetwork #5
! Flux pairs: C3H7(41), C3H6(57); O2(4), HO2(12); 
C3H7(41)+O2(4)=HO2(12)+C3H6(57)                     1.000e+00 0.000     0.000    
    PLOG/ 0.098692  1.293e+12 -0.274    3.725    /
    PLOG/ 0.392901  2.401e+12 -0.327    4.664    /
    PLOG/ 1.564168  5.567e+11 -0.124    5.313    /
    PLOG/ 6.227065  1.119e+10 0.372     5.531    /
    PLOG/ 24.790392 2.617e+07 1.117     5.302    /
    PLOG/ 98.692327 2.047e+04 1.969     4.761    /

**Comment by rwest** [comment]
Are you sure Chemkin (I assume that's the goal) requires DUPLICATE tags?  One of them is pressure-depnedent and one is not, and often that means they are not considered duplicates by Chemkin.
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/85c81eafd0ad4f592242473e889fffe583ebd3c6/rmgpy/chemkin.pyx#L1815

However, both are written without an `(+M)`, so it's definitely a confusing example. Can you try it in a few versions of Chemkin?

(How to deal with Cantera is another issue...)
