### ISSUE TITLE
g++ not detected warning when trying to run RMG

### ISSUE THREAD

**Issue by abeigzad** [ReactionMechanismGenerator/RMG-Py#1633]
### Topic
General area which your question is related to.
 - [x] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

### Context
Hi, I just setup a linux virtual machine from windows and as per instructions "To continue with installing RMG, follow the instructions for Linux and Mac OSX systems." skipped step 3.1.2. However, I now get the following warning:

WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.

### Question
Could you please advise what I should have done?

### Installation Information
Describe your installation method and system information if applicable.
 - OS (include version if known): (e.g. Windows 10, Ubuntu 18, macOS 10.13, etc.)
 - Installation method: (e.g. installation from binary or source, with or without anaconda)
 - RMG version information:
   
   - RMG-Py: 
   - RMG-database:

**Comment by mliu49** [comment]
Hi there, I went ahead and reformatted your issue to put your message in the body instead of the title.

It would be helpful to get a bit more context.
1) It seems that you were able to successfully set up the virtual machine. Did you install Ubuntu or a different Linux distribution?
2) Did you install the binary version (section 3.2.1 in the documentation) or the source version (section 3.3.1)?

To directly address the warning you received, you can try to install g++. If you are on Ubuntu 16 or 18, you can do using the following command:
```
sudo apt install g++
```
You will be prompted to enter your password. See if you still get the warning after installing that.

**Comment by abeigzad** [comment]
Hi, thanks for the response.

Yes, I'd installed ubuntu. At the end of setting up the virtual machine documentation the user is directed to either basic or developer, which I picked

binary version (3.2.1).


1- Does this mean the install wasn't proper?

2- Is the order of installing the g++ screw anything up?

3- I saw the above command under linux subsystem installation, does it mean I also should have done/do these?

sudo apt install gcc
sudo apt install g++
sudo apt install make
sudo apt-get install libxrender1

Regards,



________________________________

**Comment by abeigzad** [comment]
Hi Max,


I tried to install g++ and got the following error:

(base) abeigzad@abeigzad-VirtualBox:~$ sudo apt install g++
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

I would also appreciate any insight you may have on the email (with respect to other packages installation) in the chain below.
Thanks so much.


Ashkan


________________________________

**Comment by JacksonBurns** [comment]
This installation method is deprecated and this should no longer be an issue with the current Docker deployment strategy.

Closing as stale.
