### ISSUE TITLE
importing mechanism

### ISSUE THREAD

**Issue by rlawson** [ReactionMechanismGenerator/RMG-Py#1642]
I'm in the process of importing a gasoline surrogate mechanism from LLNL into RMG. Most of the reactions have the following format:

H+O2<=>O+OH        3.547E+15     -0.406     1.660E+04
REV/ 1.027E+13    -0.015       -1.330E+02 /
O+H2<=>H+OH       5.080E+04      2.670     6.292E+03
REV/ 2.637E+04    2.651    4.880E+03 /

If I import this mechanism into RMG will I be able to use it with this particular format?

**Comment by mjohnson541** [comment]
The import scripts should work on it, but if the reverse rate is non-zero they appear to ignore the explicit reverse rate and calculate the reverse from thermochemistry.  If the reverse rate is zero it makes the reaction irreversible.

**Comment by rlawson** [comment]
Thanks. Also, I run into another issue using the molecule search. I was trying to draw the structure but I keep getting "invalid molecule". I've attached the document I'm getting the structure from.  For example when I draw AC8H17O2 I get an invalid molecule but AC8H17 works fine. 
[Species dictionary_Thermo groups.pdf](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3333613/Species.dictionary_Thermo.groups.pdf)

**Comment by mliu49** [comment]
Currently, the molecule drawer requires manual specification of lone pairs, so you would need to add in appropriate lone pairs for the oxygen atoms. That would likely explain why you could not get the oxygenated molecule to work.
