### ISSUE TITLE
Negative rate coefficient at 500 K in Klippenstein_Glarborg2016 library

### ISSUE THREAD

**Issue by ajuluc** [ReactionMechanismGenerator/RMG-Py#1654]
We are looking for reaction rate coefficients for the Klippenstein_Glaborg2016 kinetic library. The specific reaction shown below is invalid at T = 500 K and P = 100 atm. 

```#Reaction 567
pdep_arrhenius('CH2CHOO <=> CO2 + CH3',
[(0.01, 'atm'), 5.090000e+33, -7.95, 31290.0],
               [(0.01, 'atm'), 4.200000e+122, -39.75, 43640.0],
               [(0.1, 'atm'), 1.210000e+118, -33.13, 73790.0],
               [(0.1, 'atm'), 1.960000e+29, -6.29, 30920.0],
               [(0.316, 'atm'), 8.560000e+32, -7.21, 33550.0],
               [(0.316, 'atm'), 5.100000e-66, 21.37, -11110.0],
               [(1.0, 'atm'), 3.270000e+33, -7.22, 34990.0],
               [(1.0, 'atm'), 1.760000e-47, 15.85, -5283.0],
               [(3.16, 'atm'), 3.490000e-79, 25.01, -21020.0],
               [(3.16, 'atm'), 3.820000e+32, -6.8, 35690.0],
               [(10.0, 'atm'), 8.160000e+32, -6.76, 37270.0],
               [(10.0, 'atm'), 4.620000e+00, 2.1, 17170.0],
               [(31.6, 'atm'), 7.010000e+37, -8.06, 42200.0],
               [(31.6, 'atm'), 3.490000e+14, -1.58, 26470.0],
               [(100.0, 'atm'), -2.510000e+03, 1.41, 14420.0],
               [(100.0, 'atm'), 4.050000e-09, 5.14, 10480.0])
#  Goldsmith et al., 2015, J. Phys. Chem. A 2015, 119, 7766-7779 (DOI: 10.1021/acs.jpca.5b01088)
```

However, when we go into the kinetic search results on the rmg website, it shows an error for  reaction 6 saying : 

```ValueError: On entry to DGELSD parameter number 6 had an illegal value```

### Expected Behavior
We expect to see the 2 results in the kinetics search results for 6 to have a better understanding of the reaction rate coefficients

### Installation Information

 - MacOS Mojave Version 10.14.5
 - Installed with source from anaconda 
 - RMG version information:

RMG version 2.3.0
   The current git HEAD for RMG-Py is:
        83ad0f24f6918975e5d803c4c1e75077b570b5f9
        Fri Mar 22 12:55:16 2019 -0400

The current git HEAD for RMG-database is:
        cdad234f86dad6c0c22390c7944b313ce317dd02
        Fri Feb 1 11:56:09 2019 -0500

**Comment by mliu49** [comment]
Thanks for posting this. As you mentioned, this rate is invalid around 500 K. The plot below shows the rate for the MultiArrhenius fit at 100 atm.

![image](https://user-images.githubusercontent.com/10817103/61384698-1cdbf180-a87f-11e9-836b-bbfed5d1d9f1.png)

The website broke because we try to fit Arrhenius parameters to the PDepArrhenius rate evaluated at the highest pressure, which (presumably) failed due to the negative rate.

To resolve this, we could consider refitting the MultiArrhenius fit at 100 atm with a lower bound of 0.

Original source of the rate: https://pubs.acs.org/doi/suppl/10.1021/acs.jpca.5b01088/suppl_file/jp5b01088_si_001.txt

Location in RMG-database: https://github.com/ReactionMechanismGenerator/RMG-database/blob/master/input/kinetics/libraries/Klippenstein_Glarborg2016/reactions.py#L10417

**Comment by ajuluc** [comment]
Hi Max thanks a lot for the detailed description of how to resolve this issue. Just as a reminder going forward if I get into trouble with such errors do I have to estimate the kinetics at that specific temperature and pressure by suppressing it or basically just setting it A to 0 ?  Furthermore, is there a database where I can get the plots of the rate constants vs temperature for the reaction kinetics libraries?

**Comment by mliu49** [comment]
RMG can calculate the rate without any problem. I think the error was completely on the website end.

We don't have a database of plots, and the website typically the fastest way to get a plot, though it was clearly not an option in this case.

I plotted the rate manually using a jupyter notebook.

**Comment by ajuluc** [comment]
Notes thanks for the quick response. Do you mind please sharing the notebook with me. I’ll close this issue now.

**Comment by mliu49** [comment]
I uploaded a notebook here: https://github.com/mliu49/misc_scripts/blob/master/Kinetics/plot_kinetics.ipynb

**Comment by mliu49** [comment]
Actually, I'll leave this issue open until we actually fix the invalid rate.

**Comment by ajuluc** [comment]
Thanks again Max for all the help I'll be using the notebook to evaluate some rate constants whenever I run into such issues going forward.

**Comment by rwest** [comment]
@cfgoldsmith, once you're back, do you happen to have the raw k(T,P) data that could be re-fit to some expression that doesn't go negative?
Or even better, the ability and inclination to re-fit it?
