### ISSUE TITLE
running arkane/mainTest inadvertantly deletes files 

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1662]
### Bug Description
When I run `nosetest arkane/mainTest.py`, the test deletes the directory `
examples/arkane/species/N4H6/N4H6/` as well as the three files contained within it. 

This is not the intended behavior of a unittest. 

### How To Reproduce

1. run `nosetest arkane/mainTest`
1. run `git status` and see if three files are removed.

### Expected Behavior

These three files should not be removed during the test. One potential solution might be to not have an additional directory for the quantum files.

### Installation Information
most recent rmgpy and database on ubuntu 18.04

**Comment by alongd** [comment]
closed by https://github.com/ReactionMechanismGenerator/RMG-Py/commit/86f4bf9f492b5cdbddcc8f29bf43d4e708518748#diff-5630b5cd4472ab5a5f56c67b5403a4fd
