### ISSUE TITLE
RDKit   Not found

### ISSUE THREAD

**Issue by quandewang** [ReactionMechanismGenerator/RMG-Py#1667]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [ ] Dependencies

### Context
I am installing RMG on win 10 linux subsystems using anaconda. Just in the last make step，the following errors occur:
Checking vital dependencies...

Package        Version        Location
symmetry       1.16           /home/wqd198686/anaconda2/envs/rmg_env/bin/symmetry
RDKit                         Not found. Please install RDKit version 2015.03.1 or later with InChI support.
OpenBabel      2.4.1          /home/wqd198686/anaconda2/envs/rmg_env/lib/python2.7/site-packages/openbabel.pyc
lpsolve55                     /home/wqd198686/anaconda2/envs/rmg_env/lib/python2.7/site-packages/lpsolve55.so
pyrdl                         /home/wqd198686/anaconda2/envs/rmg_env/lib/python2.7/site-packages/py_rdl/__init__.pyc

There are missing dependencies as listed above. Please install them before proceeding.

Using Anaconda, these dependencies can be individually installed from the RMG channel as follows:

    conda install -c rmg [package name]

You can alternatively update your environment and install all missing dependencies as follows:

    conda env update -f environment_[linux/mac/windows].yml  # Choose the correct file for your OS

### Question
I already installed RDkit. Should I also activate rdkit or activate rmg_env during make? It seems that the instructions  conda install -c rmg rdkit also donot work.

### Installation Information
 - Windows 10 Ubuntu 18 subsystem
 - Installation method: installation from source, with anaconda)

   For installation from source, get git commit using `git describe --tags`
   -->
   - RMG-Py: 2.4.0-67-gf0d7d9f63

**Comment by amarkpayne** [comment]
You just need to activate the rmg environment with `conda activate rmg_env`. You MUST do this before running `make`. You also run `conda install -c rmg rdkit` with the rmg environment activated, otherwise this will just install rdkit into the base environment. If this doesn't work copy and paste your terminal output for when you run the above commands.

**Comment by amarkpayne** [comment]
Actually, you should try installing rdkit from the rdkit channel (again with the rmg environment activated)

`conda install -c rdkit rdkit`

**Comment by quandewang** [comment]
Thanks，it works now.
