### ISSUE TITLE
Unexpected behavior in Arkane kinetic fitting

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1671]
### Bug Description
If a user of arkane does not input temperature ranges for high-pressure kinetics, Arkane will space the values between 298 and 2500 K using equal spacing in 1/T (located in generateKinetics of kinetics.py)

If the user specifies Tmin, Tmax, and Tcount, then Arkane will space the points out equally in T space (located in __init__ in kinetics.py).

The difference in spacing also goes against what the original commit message says (beaafb5e31fccafcd2f4e8827b096). I would think that to be consistent, we should either use T or 1/T spacing for both. My personal preference is 1/T spacing. Unless people have opposition, I cam implement this change.

**Comment by alongd** [comment]
I agree we should use consistent 1/T spacing

**Comment by amarkpayne** [comment]
I think this issue has been resolved by the merged PR. If I am wrong please feel free to reopen this.
