### ISSUE TITLE
Travis not working?

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1673]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 
 - [x] PR issues

### Context
Testing a PR with travis

### Question
Is Travis's RMG-tests consistantly failing? When I restart #1672 on travis, I get the following errors (which fail after 16 seconds)

```
The command "eval git clone --depth=50 --branch=rmgpy-fix_kinetic_fitting_arkane https://github.com/ReactionMechanismGenerator/RMG-tests.git ReactionMechanismGenerator/RMG-tests " failed 3 times.

The command "git checkout -qf 49da1b50da700ee91c7788120eed0774e45f9e3f" failed and exited with 128 during .
```

**Comment by mliu49** [comment]
You can't restart RMG-tests builds directly. You have to restart the `push` build for the RMG-Py branch.

**Comment by amarkpayne** [comment]
> You can't restart RMG-tests builds directly. You have to restart the `push` build for the RMG-Py branch.

Can confirm. I ran into this a while back and it took me a while to figure it out
