### ISSUE TITLE
Minimal Example Does Not Run on Current Master

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/RMG-Py#1674]
### Bug Description
After 22 species have been added into the core, I get the following error:
```
After model enlargement:
    The model core has 22 species and 55 reactions
    The model edge has 325 species and 1197 reactions


Saving current model core to Chemkin file...
Traceback (most recent call last):
  File "../../../rmg.py", line 181, in <module>
    main()
  File "../../../rmg.py", line 175, in main
    rmg.execute(**kwargs)
  File "/home/ampayne/RMG/.worktrees/RMG-Py-wt2/rmgpy/rmg/main.py", line 874, in execute
    self.saveEverything()
  File "/home/ampayne/RMG/.worktrees/RMG-Py-wt2/rmgpy/rmg/main.py", line 1539, in saveEverything
    self.notify()
  File "/home/ampayne/RMG/.worktrees/RMG-Py-wt2/rmgpy/util.py", line 110, in notify
    observer.update(self)
  File "rmgpy/chemkin.pyx", line 2266, in rmgpy.chemkin.ChemkinWriter.update
    saveChemkinFiles(rmg)
  File "rmgpy/chemkin.pyx", line 2165, in rmgpy.chemkin.saveChemkinFiles
    saveChemkin(rmg.reactionModel,
  File "rmgpy/chemkin.pyx", line 2143, in rmgpy.chemkin.saveChemkin
    saveChemkinFile(path, speciesList, rxnList, verbose = False, checkForDuplicates=False) # We should already have marked everything as duplicates by now
  File "rmgpy/chemkin.pyx", line 1990, in rmgpy.chemkin.saveChemkinFile
    f.write(writeKineticsEntry(rxn, speciesList=species, verbose=verbose))
  File "rmgpy/chemkin.pyx", line 1689, in rmgpy.chemkin.writeKineticsEntry
    assert 0.999 < kinetics.A.getConversionFactorFromSItoCmMolS() / 1.0e6 ** (numReactants - 1) < 1.001, """
AssertionError: 
              Gas phase reaction 
C4H6(46)=C4H6(203)                                  
              with kinetics 
Arrhenius(A=(6.28654e+07,'m^3/(mol*s)'), n=-0.211676, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.00579809229276, var=0.287312654976, Tref=1000.0, N=3, correlation='Root_N-1R->H_N-1CClNOSSi->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R_Sp-4R!H=3R!H',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CClNOSSi->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R_Sp-4R!H=3R!H
    Total Standard Deviation in ln(k): 1.0891372184
Exact match found for rate rule [Root_N-1R->H_N-1CClNOSSi->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R_Sp-4R!H=3R!H]
Euclidian distance = 0
family: R_Recombination""")
              with 1 reactants was expected to have
              kinetics.A.getConversionFactorFromSItoCmMolS() = 1.0
              but instead it is 1000000.0
```

I am not sure if this is a problem is something just with the Chemkin writer or if it is indicative of a larger problem. I'll do some more debugging soon.

### How To Reproduce
Run the minimal example in the examples folder with current master in the database and RMG-Py
(technically I am running this on my isodesmic branch, both database and Py, but both of these branches only affect Arkane and are otherwise update to date with master).

**Comment by amarkpayne** [comment]
Some quick follow-up observations: The reaction family is R_Recombination but I don't think it should be. The species are:

**C4H6(46)**
![CH2 CH C=C(46)](https://user-images.githubusercontent.com/25854331/62626419-5d1a1700-b8f5-11e9-9fe3-05ca8206d4de.png)

**C4H6(203)**
![C1=CCC1(203)](https://user-images.githubusercontent.com/25854331/62626450-70c57d80-b8f5-11e9-8776-6931f2b604a0.png)

**Comment by alongd** [comment]
The R_Recombination family was indeed modified recently

**Comment by amarkpayne** [comment]
> The R_Recombination family was indeed modified recently

I was wondering the same thing. It is probably not a coincidence

**Comment by mjohnson541** [comment]
Looks like in some cases R_Recombination is now sometimes matching single species as a result of atg4.  It's concerning this didn't show up in RMG-tests, do we not have any of these birads in RMG-tests?

**Comment by mjohnson541** [comment]
Shouldn't be difficult to fix, just need to find the right spot.

**Comment by amarkpayne** [comment]
I haven't taken a look at ATG4, so I don't know how much it works. Was this change supposed to happen though?

https://github.com/ReactionMechanismGenerator/RMG-database/blob/3fa118761ba276f90c193613262aff77ef26b3b7/input/kinetics/families/R_Recombination/groups.py#L10

It was eventually changed to this by the end of the PR though:

https://github.com/ReactionMechanismGenerator/RMG-database/blob/fbe159df29d1143eeb2013f38c565eb3aa75a296/input/kinetics/families/R_Recombination/groups.py#L10

**Comment by mliu49** [comment]
We run a modified minimal example with a higher tolerance on RMG-tests. Presumably it doesn't run far enough to add a birad to the core. All of the other tests limit max radicals to 1...

**Comment by mliu49** [comment]
@mjohnson541, I think somewhere around [here in __generateReactions](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/data/kinetics/family.py#L1881) you should compare the number of species against the new `reactantNum` or `productNum` (depending on direction) and return early if it doesn't match.

**Comment by mjohnson541** [comment]
@amarkpayne it's a purposeful change, autogenerated trees have one template regardless of the number of reactants.
