### ISSUE TITLE
initial mole fractions

### ISSUE THREAD

**Issue by rlawson** [ReactionMechanismGenerator/RMG-Py#1699]
Concerning the simple reactor system, does RMG re-normalize supposing I input initial moles instead of mole fractions.

**Comment by mliu49** [comment]
Yes, RMG will normalize whatever you put for initial mole fractions so they sum to 1.

**Comment by rlawson** [comment]
THank you. As a follow up question, assuming I'm running a simple reactor (fuel-air mixture) with a multicomponent fuel eg 99.5% ethane + 1% heptane. With such low concentration of heptane, what do you recommend in regards to model_tolerances in order to capture the effect of heptane (goal is to run some ignition delay simulations).
