### ISSUE TITLE
AtomTypeError when generating a molecule containing [N+][O-] from InChI but no error when generating it from SMILES

### ISSUE THREAD

**Issue by yunsiechung** [ReactionMechanismGenerator/RMG-Py#1700]
### Bug Description
I have InChI and SMILES of a molecule containing [N+][O-] group, that looks like this:

![image](https://user-images.githubusercontent.com/17207530/63373216-82773e00-c355-11e9-85b6-a9d971ddcc64.png)

`inchi = 'InChI=1S/C7H7NO3/c1-5-4-6(8(10)11)2-3-7(5)9/h2-4,9H,1H3'`
`smiles = 'Cc1cc(ccc1O)[N+]([O-])=O'`

When I create a molecule using InChI, I get the following AtomTypeError:

```AtomTypeError: Unable to determine atom type for atom N, which has 1 single bonds, 0 double bonds to C, 2 double bonds to O, 0 double bonds to S, 0 triple bonds, 0 benzene bonds, 0 lone pairs, and 0 charge. ```

It thinks nitrogen has double bond with each O, so total of 2 double bonds to O and 1 single bond to C when it has one double bond with only one oxygen. 

When I create a molecule using SMILES, I can successfully generate a molecule.

Same things happen on RMG website.
If you use SMILES, RMG website Molecule Search can generate the molecule correctly, with the exact same InChI as above. If you use InChI, Molecule Search gives:
```
Not Implemented
Invalid Molecule
```

### How To Reproduce
On jupyter notebook, this goes fine:
```
from rmgpy.molecule import Molecule
smiles = 'Cc1cc(ccc1O)[N+]([O-])=O'
molecule = [Molecule(SMILES=smiles)] 
```

But this gives AtomTypeError:
```
from rmgpy.molecule import Molecule
inchi = 'InChI=1S/C7H7NO3/c1-5-4-6(8(10)11)2-3-7(5)9/h2-4,9H,1H3'
molecule = Molecule(InChI=inchi)

AtomTypeError: Unable to determine atom type for atom N, which has 1 single bonds, 0 double bonds to C, 2 double bonds to O, 0 double bonds to S, 0 triple bonds, 0 benzene bonds, 0 lone pairs, and 0 charge.
```

### Expected Behavior
RMG should be able to correctly understand the partial charges that nitrogen and oxygen have for this kind of molecules from their InChI structures.

### Installation Information
Describe your installation method and system information.
 - Ubuntu 18.04.3 LTS
 - Installation from Source using Anaconda
 - RMG version information:
   
   - RMG-Py:  2.4.1-196-g3846fcce7
   - RMG-database:  2.4.0-14-ge461edb9

**Comment by mliu49** [comment]
#1301 is very related.

As for potential resolution methods, I confirmed that parsing the InChI you provided using RDKit works correctly. We can consider changing the default backend for reading InChI to RDKit, but we would need to confirm that it doesn't break more things than it fixes. RDKit is already the default backend for writing InChI (though I don't recall the exact reason).

Something else we could try implementing is to catch AtomTypeErrors and try the other backend (around [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/translator.py#L488). I just noticed that I forgot to implement error catching when reading identifiers, so this should be fixed regardless.

**Comment by cgrambow** [comment]
The issue is that Open Babel prefers the form with two double bonds on N by default, although it is possible to convert to the dative bond form. I think a simple fix for this issue would be to catch errors that occur when running `_rdkit_translator` or `_openbabel_translator` in the `molecule.translator._read` so that all backends are tried.

**Comment by cgrambow** [comment]
Ugh, @mliu49 was faster than me

**Comment by mliu49** [comment]
Lol, by 19 seconds.
