### ISSUE TITLE
RMG model generation crashes due to key error in get_species_index

### ISSUE THREAD

**Issue by ajuluc** [ReactionMechanismGenerator/RMG-Py#1701]
### Bug Description
I have a very big input file with over 1400 species for iso-octane model generation. After RMG generates all the species by inserting it in the core and completes initialisation, RMG crashes with a key error for [C]C   in File "rmgpy/solver/base.pyx", line 400, in rmgpy.solver.base.ReactionSystem.get_species_index

### How To Reproduce
I run RMG on slurm using the input file of roughly 1400 species. After RMG adds all species to the core it stops and has a key error. The error message is given below.

```
After model enlargement:
    The model core has 1574 species and 4278 reactions
    The model edge has 215 species and 595 reactions


Initialization complete. Starting model generation.

conditions choosen for reactor 0 were: P = 0.00011512925465 bar, iC8H18 = 0.0082612, T = 550.0 K, 
Traceback (most recent call last):
  File "/home/ajulu.c/Code/RMG-Py/rmg.py", line 181, in <module>
    main()
  File "/home/ajulu.c/Code/RMG-Py/rmg.py", line 175, in main
    rmg.execute(**kwargs)
  File "/home/ajulu.c/Code/RMG-Py/rmgpy/rmg/main.py", line 664, in execute
    conditions = self.rmg_memories[index].get_cond(),
  File "rmgpy/solver/simple.pyx", line 166, in rmgpy.solver.simple.SimpleReactor.initializeModel
  File "rmgpy/solver/simple.pyx", line 183, in rmgpy.solver.simple.SimpleReactor.initializeModel
  File "rmgpy/solver/base.pyx", line 246, in rmgpy.solver.base.ReactionSystem.initializeModel
  File "rmgpy/solver/base.pyx", line 416, in rmgpy.solver.base.ReactionSystem.generate_reactant_product_indices
  File "rmgpy/solver/base.pyx", line 400, in rmgpy.solver.base.ReactionSystem.get_species_index
KeyError: Species(index=291, label="H2CC", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[3.28155,0.00697643,-2.38528e-06,-1.21078e-09,9.82042e-13,48319.2,5.92036], Tmin=(200,'K'), Tmax=(1000,'K')), NASAPolynomial(coeffs=[4.27807,0.00475623,-1.63007e-06,2.54623e-10,-1.4886e-14,48014,0.639979], Tmin=(1000,'K'), Tmax=(6000,'K'))], Tmin=(200,'K'), Tmax=(6000,'K'), E0=(401.202,'kJ/mol'), Cp0=(33.2579,'J/(mol*K)'), CpInf=(83.1447,'J/(mol*K)'), label="""H2CC""", comment="""Thermo library: Klippenstein_Glarborg2016"""), conformer=Conformer(E0=(401.202,'kJ/mol'), modes=[]), molecule=[Molecule(SMILES="[C]=C")], molecularWeight=(26.0373,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85))
```
### Expected Behavior
RMG ought to have begun model generation

### Installation Information
Describe your installation method and system information.
 - MacOS Mojave V. 10.14.6 
 - Installation from source with anaconda 
 - RMG-Py: 2.4.1-41-g1369f9e2a
 - RMG-database: 2.4.0-7-g5cf1e123

### Additional Context
Input file 
[ic8.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3527084/ic8.txt)

**Comment by rwest** [comment]
I edited the issue text slightly. I don't think the thermo library is the problem

**Comment by amarkpayne** [comment]
I haven't gotten time to look at this too in depth, but I think it would be an interesting coincidence if the issue is not related to the fact that the species in question is a carbene.
```
species(
    label='H2CC',
    reactive=True,
    structure=adjacencyList('''
        multiplicity 3
        1 C u0 p0 c0 {2,D} {3,S} {4,S}
        2 C u2 p0 c0 {1,D}
        3 H u0 p0 c0 {1,S}
        4 H u0 p0 c0 {1,S}
        ''')
    )
```

I don't think it is the only one specified in the input file though. I am curious to know what would happen if we remove just this species from the input file and re-run the job. Would it crash due to a similar species?

**Comment by ajuluc** [comment]
Thanks Mark for noting that. So initially when I made the input file there were a number of species which were tagged as duplicates. However, upon subsequent corrections tagged as `duplicate species errors`, the input file passed and model generation begun. Nonetheless, I'm tempted to say that you're right since the thermolibrary already has this specie I think removing it from the actual input file might actually make it work. Let me try that and see what happens. Thanks for the feedback.

**Comment by ajuluc** [comment]
It's working now. Removing the `H2CC` carbene specie from the input file made it work. Although, I still don't understand what or why that happened since `H2CC` is already in the thermoLibrary. Thanks again for the help.

**Comment by mliu49** [comment]
Triplet carbenes are globally forbidden by default (see RMG-database/input/forbiddenStructures.py).

I think this is likely somehow related to it being forbidden and improperly removed from some list.

**Comment by ajuluc** [comment]
I didn't know about the forbidden structures until now and thanks for pointing me to the forbiddenStructures.py file where it shows the issue # for Carbene https://github.com/ReactionMechanismGenerator/RMG-Py/issues/514 
Although mine was a singlet carbene I think. However, @alongd already made comments about it restricting  the addition of the `H2CC` specie which was the exact issue I had with the key error in the Klippenstein_Glaborg2016 thermoLibrary.

**Comment by rwest** [comment]
You could try checking your `generatedSpeciesConstraints( allowed=['input species'])` option in your input file (cc. @shenghuiqin )
