### ISSUE TITLE
How to get finished RMG model species png if I have species_dictionary file, 

### ISSUE THREAD

**Issue by shenghuiqin** [ReactionMechanismGenerator/RMG-Py#1718]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [x] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

### Question
I ran RMG setting ```generateHTML=False``` and finished model generation,
now I want to have all the species png, Is there a method to do that?
thank you for your time.

**Comment by amarkpayne** [comment]
There might be faster ways to do this, but you can try loading in the species_dictionary/Chemkin file (see `loadChemkinFile` in chemkin.pyx) and then either using the `MoleculeDrawer` class in rmgpy.molecule.draw or I think rmgpy species have a `__repr_png_` method. Let me know how it goes.

**Comment by amarkpayne** [comment]
@shenghuiqin any luck in getting this working? If so I'll go ahead and close this issue

**Comment by mliu49** [comment]
Sorry I missed this earlier. You can use `RMG-Py/scripts/generateChemkinHTML.py` to generate molecule images and the HTML document for any mechanism.

**Comment by shenghuiqin** [comment]
sorry,  I was trapped by something else these days, thank you both. 👍
