### ISSUE TITLE
Website Molecule Search Error Reading InChI and SMILES Strings

### ISSUE THREAD

**Issue by cjmcgill** [ReactionMechanismGenerator/RMG-Py#1720]
### Bug Description
Website molecule search is truncating an input Inchi string. The Inchi string I input is

`InChI=1S/C17H17IN2O2/c1-11(2)12-7-8-14(18)17(22)15(9-12)20-19-10-13-5-3-4-6-16(13)21/h3-11,21H,1-2H3,(H,20,22)/b19-10+`

When the molecule is drawn, the Inchi reproduced, and the atom table generated it is instead showing the Inchi string

`InChI=1S/C17H17IN2O2/c1-11(2)12-7-8-14(18)17(22)15(9-12)20-19-10-13-5-3-4-6-16(13)21/h3-11,21H,1-2H3,(H,20,22)`

This Inchi string is a tautomer of the input Inchi.

Strangely it seems to do the same thing for the same molecule with SMILES.

`CC(C)c1ccc(I)c(O)c(=N/N=C/c2ccccc2O)c1`

to

`CC(c1ccc(c(c(=NN=Cc2ccccc2O)c1)O)I)C`

This seems similar to issue #1440 which says it resulted in using RDKit functionality here. I've moved this structure around in RDKit (inchi to structure to smiles to inchi) without it being affected. I am attaching the drawing generated by RDKit for this structure. This is consistent with the atom and bond array in the sdf file which was the original molecule source.

![drawing](https://user-images.githubusercontent.com/44245643/64702346-580e3180-d478-11e9-896c-b74f0f578b1c.png)

### How To Reproduce
Enter the Inchi or SMILES string at the molecule search page.

[link](https://rmg.mit.edu/molecule_search)

**Comment by mliu49** [comment]
This is expected (although perhaps not ideal) behavior, as RMG ignores the stereochemistry components of both InChI and SMILES because the internal representation does not support it. Since the stereochemistry information is lost as soon as you create an RMG molecule, it is currently impossible to retrieve it when you convert it back to an identifier.
