### ISSUE TITLE
`make clean` crashes if no build directory exists

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#1745]
### Bug Description
If you run `make clean` twice (or just remove the `build` folder before running it once) then it crashes.
```
$ make clean
Removing build directory...
Traceback (most recent call last):
  File "utilities.py", line 427, in <module>
    clean()
  File "utilities.py", line 280, in clean
    shutil.rmtree(directory)
  File "/Users/rwest/anaconda/envs/rmg3/lib/python3.7/shutil.py", line 485, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/Users/rwest/anaconda/envs/rmg3/lib/python3.7/shutil.py", line 483, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rwest/Code/RMG-Py/build/'
make: *** [clean] Error 1
```

### How To Reproduce
`rm -rf build ; make clean`

### Expected Behavior
It wouldn't crash

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): MacOS 10.14.6
 - Installation method: from source, in fresh anaconda environment
 - RMG version information:
   
   - RMG-Py: 2.3.0-990-g16a6b8b08
   - RMG-database: N/A

**Comment by mliu49** [comment]
Fixed by #1746.
