### ISSUE TITLE
Reactors no longer normalize mole fractions

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1750]
### Bug Description
RMG previously would normalize initial mole fractions specified in input files. This functionality was removed in #1331. It's not clear whether or not it was intentional.

I'm not sure whether this actually affects reactor simulations, since they are done with moles and concentrations. It seems that this effectively changes the initial basis from 1 mole total to whatever the actual numbers are.

### How To Reproduce
Take any example, e.g. superminimal, and change the mole fractions to random things, e.g.
```
    initialMoleFractions={
        'H2': 200,
        'O2': 100,
    },
```

Run the job, and check out the simulation profiles, which will show 200 moles of H2 initially.

### Expected Behavior
I'm not sure exactly what the expected behavior would be for a new user. The input key is called initialMoleFractions, so it seems unintuitive for the values to be effectively interpreted as initialMoles.

I might be somewhat biased since I'm used to the old behavior of normalizing mole fractions. It was very convenient for using easy numbers to specify reactant ratios.

**Comment by hwpang** [comment]
It looks like this issue is solved by  #1809.
