### ISSUE TITLE
Training reaction workflow broken by R_Recombination changes

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1764]
### Bug Description
Multiple steps of the training reaction addition workflow have been broken by the changes to R_Recombination:
1. Labeling of reactions was broken because `get_labeled_reactants_and_products` was unable to handle the single template in R_Recombination (already fixed by db6321cf6e3f7af623d11cf7746b658e9b92c43a in #1735)
2. Saving of training reactions is broken because we cannot generate initial maps for molecules with multiple identical labels (i.e. two atoms labeled with `'*'`). The relevant code is located in `KineticsFamily.save_training_reactions`. Note that generation of initial maps for molecules with duplicate labels is (and has always been) non-functional in general, but there were no use cases previously.

### How To Reproduce
Run the `kinetics_library_to_training.ipynb` for a kinetics library with R_Recombination reactions, e.g. `kislovB`.

### Expected Behavior
We should be able to add R_Recombination training reactions.

**Comment by mjohnson541** [comment]
R_Recombination uses SIDT now
