### ISSUE TITLE
Installation instructions to build from source need updating

### ISSUE THREAD

**Issue by Ting-Chen-Lee** [ReactionMechanismGenerator/RMG-Py#1772]
### Bug Description
The documentation to build from source still says to download Python 2.7, not Python 3.7+.
http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html#anacondadeveloper
this causes confusing problems for a new user.

**Comment by mliu49** [comment]
Sorry about that. Documentation updates are currently in pull request #1767. We will try to get that in and update the online documentation as soon as possible.
