### ISSUE TITLE
WSL permission denied when renaming seed folder

### ISSUE THREAD

**Issue by MingyuWAN** [ReactionMechanismGenerator/RMG-Py#1786]
### Bug Description
```
Making seed mechanism...
Traceback (most recent call last):
  File "/home/mingyu/RMG/RMG-Py/rmg.py", line 106, in <module>
    main()
  File "/home/mingyu/RMG/RMG-Py/rmg.py", line 100, in main
    rmg.execute(**kwargs)
  File "/home/mingyu/RMG/RMG-Py/rmgpy/rmg/main.py", line 749, in execute
    self.make_seed_mech()
  File "/home/mingyu/RMG/RMG-Py/rmgpy/rmg/main.py", line 1272, in make_seed_mech
    os.rename(seed_dir, os.path.join(temp_seed_dir))
PermissionError: [Errno 13] Permission denied: '/home/mingyu/species/tms_syngas_in_silicon/seed' -> '/home/mingyu/species/tms_syngas_in_silicon/seed_tmp'
```
I met this error message, which seems to be similiar with [#1123](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1123)
### How To Reproduce
The odd thing is that my model won't be disturbed with this error for the first run, but crashed like this when I ran it again. Even if I ran my model on a branch or create a new folder to store the input file (Since Alon mentioned cleaning the existing file might be helpful), this error would occur at any time, which is also the another thing that makes me confused. That is, for a same input file, this `rename seed error` is not fixed in the same place, it's possible that this error message took more or less time to occur for one run.

### Installation Information
Describe your installation method and system information.
 - Ubuntu 18.04
 - Installation method:  installation from source with anaconda)
 - RMG version information:
   
   - RMG-Py: latest
   - RMG-database: latest

**Comment by amarkpayne** [comment]
I believe I know why it only crashes the second time. I suspect that you are not generating the seed after each iteration (there is a flag for this in the input file), but correct me if I am wrong. In that case the seed mechanism is only generated after the first run. When you run again, we added code that tries to move the existing seed mechanism to a temporary location before writing the new seed. The rationale for this is that we don't want to delete old seed mechanisms before successfully saving the new one. This is why you encounter the renaming issue only after running the job the second time.

As for why you don't have permission to rename a folder, I would have to know more about your setup to say more, but looking at the permissions and user/group owner of the existing folder would be a good place to start (I'll also look at the issue you cite). Can you show me the output of `ls -l` from the folder where this job is being run?

**Comment by MingyuWAN** [comment]
```
(base) mingyu@LAPTOP-M9733T93:~/species/tms_syngas_in_silicon$ ls -l
total 2008
-rw-rw-rw- 1 mingyu mingyu  160496 Oct 24 16:50 RMG.log
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:50 chemkin
-rw-rw-rw- 1 mingyu mingyu    1815 Oct 24 16:45 input.py
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:46 kinetics_database
-rw-rw-rw- 1 mingyu mingyu  164479 Oct 24 16:50 output.html
-rw-rw-rw- 1 mingyu mingyu 1707626 Oct 24 16:50 output_edge.html
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:50 pdep
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:47 plot
-rw-rw-rw- 1 mingyu mingyu    1845 Oct 24 16:47 restart_from_seed.py
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:50 rms
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:47 seed
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:46 solver
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:50 species
-rw-rw-rw- 1 mingyu mingyu    5632 Oct 24 16:50 statistics.xls
```
This is the output

By the way, my seedMechanism is default like this
```
    seedMechanisms = [],
```

**Comment by amarkpayne** [comment]
Can you also show me `ls -la` ? From this you do own all of the files in this directory (though from this output I can't tell if you own the directory itself) so it is very curious that you are getting permission denied errors. I'll see if I can replicate this behavior in the Linux subsystem and do some research about renaming files in Windows (hopefully this isn't the issue). 

It is okay that the `seedMechanisms` line is an empty list. This just means that RMG is not loading in any seed mechanisms during the run. No matter what though RMG will generate a seed mechanism from the current run at the very end of an RMG job so that it is possible to restart the RMG job from the seed mechanism if need be.

**Comment by MingyuWAN** [comment]
```
(base) mingyu@LAPTOP-M9733T93:~/species/tms_syngas_in_silicon$ ls -al
total 2008
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:47 .
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:45 ..
-rw-rw-rw- 1 mingyu mingyu  160496 Oct 24 16:50 RMG.log
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:50 chemkin
-rw-rw-rw- 1 mingyu mingyu    1815 Oct 24 16:45 input.py
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:46 kinetics_database
-rw-rw-rw- 1 mingyu mingyu  164479 Oct 24 16:50 output.html
-rw-rw-rw- 1 mingyu mingyu 1707626 Oct 24 16:50 output_edge.html
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:50 pdep
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:47 plot
-rw-rw-rw- 1 mingyu mingyu    1845 Oct 24 16:47 restart_from_seed.py
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:50 rms
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:47 seed
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:46 solver
drwxrwxrwx 1 mingyu mingyu     512 Oct 24 16:50 species
-rw-rw-rw- 1 mingyu mingyu    5632 Oct 24 16:50 statistics.xls
```
Odd thing is that this error won't occor on the same iteration every time when I run

**Comment by MingyuWAN** [comment]
```
    Execution time (DD:HH:MM:SS): 00:00:15:55
    Memory used: 741.49 MB

Making seed mechanism...
Traceback (most recent call last):
  File "/home/mingyu/RMG/RMG-Py/rmg.py", line 106, in <module>
    main()
  File "/home/mingyu/RMG/RMG-Py/rmg.py", line 100, in main
    rmg.execute(**kwargs)
  File "/home/mingyu/RMG/RMG-Py/rmgpy/rmg/main.py", line 749, in execute
    self.make_seed_mech()
  File "/home/mingyu/RMG/RMG-Py/rmgpy/rmg/main.py", line 1272, in make_seed_mech
    os.rename(seed_dir, os.path.join(temp_seed_dir))
PermissionError: [Errno 13] Permission denied: '/home/mingyu/RMG/RMG-Py/examples/rmg/liquid_phase_constSPC/seed' -> '/home/mingyu/RMG/RMG-Py/examples/rmg/liquid_phase_constSPC/seed_tmp'
(rmg_env) mingyu@LAPTOP-M9733T93:~/RMG/RMG-Py/examples/rmg/liquid_phase_constSPC$ 
```
This is another try from`RMG-Py/example/rmg` that was chose at random and encounter the same error. 

In order to replicate this behavior one suggestion is that you could use an input file that will take a relatively long time, since I cannot tell when this error is going to occur.

**Comment by amarkpayne** [comment]
This appears to be a reoccurring problem with WSL itself where the system call for rename is broken when the directory is not empty. There are at least 3 of these issues open on their Github, so I don't think it is reasonable for us to wait for them to fix this, though from a cursory glance some of the comments make it seem that you need to make sure that your version of the subsystem is up to date. I might add a try except statement in our code where if the renaming does not work then we copy the files instead.

**Comment by MingyuWAN** [comment]
That makes sense, thank you Mark. I'll go through their Github.

**Comment by amarkpayne** [comment]
Thanks! I think opening an issue on WSL's GitHub is a good idea, just in case it is a problem we can fix and not actually a problem with WSL.

In the meantime, I have added a quick patch on the branch `wsl_permission_bug`. Can you check out the branch (make clean and make just in case) and then try running these models again? Run different models multiple times over until you either encounter the bug (hopefully not though) or are satisfied that the patch fixes the issue. Let me know how it goes!

**Comment by amarkpayne** [comment]
Hey @MingyuWAN , any luck testing out this branch? If the patch appears to fix your issue I can open a PR with these changes so that they get incorporated in master.

**Comment by MingyuWAN** [comment]
Sorry for the late reply. After several tests with this branch, I found that this is a great change and never had that error again! Thanks for your help!

**Comment by amarkpayne** [comment]
Thanks for testing this out @MingyuWAN ! In that case I'll go ahead and open a PR for this branch
