### ISSUE TITLE
Install Documentation Update

### ISSUE THREAD

**Issue by cjmcgill** [ReactionMechanismGenerator/RMG-Py#1787]
The installation documentation at [link](https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html) has a couple of lines that needs to be updated.

In step 5, it specifies the command `conda env create -f environment_linux.yml` but there is no longer an `environment_linux.yml` file. Documentation needs to be updated to say `environment.yml` instead.

In step 6, there needs to be a different command for some conda installs. Instead of `source activate rmg_env`, some linux installations will instead use `conda activate rmg_env`

**Comment by mliu49** [comment]
Thanks for posting! This is fixed in #1767.
