### ISSUE TITLE
Arkane not included in codecov

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/RMG-Py#1792]
### Bug Description
Currently, Arkane is not included in the code coverage report. I believe this is because the arkane folder and Arkane.py are not included as sources in .coveragerc.

It is possible that this is intentional (for example perhaps we want the coverage to reflect RMG-Py itself), but in case it is not I have created a branch called `arkane_coverage` which I believe fixes this issue. If we feel that this change is what we want I will open the PR.

**Comment by mliu49** [comment]
This reminded me that I had a work-in-progress branch for this issue. I just pushed what I had to the `coverage` branch. There's currently just a single wip commit: 69efc9409a9cfae0500d2621ac729a2ddaa8bb0a

This includes some additional changes compared to what you have in the PR. It might take me a bit to remember the reasons for each of the changes, but they might be useful to add on to the PR.
