### ISSUE TITLE
Training reactions now require rank, not checked by database tests.

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#1797]
### Bug Description
We have been working on adding stuff to the  database [(here).](https://github.com/MingyuWAN/RMG-database/commits/sih4)

Running `make test-database` passes all 1260 tests, and yet when we try building a model in RMG-Py we fail when loading the database with
```
Filling in rate rules in kinetics families by averaging...
Traceback (most recent call last):
  File "/Users/rwest/Code/Silicon/RMG-Py/rmg.py", line 111, in <module>
    main()
  File "/Users/rwest/Code/Silicon/RMG-Py/rmg.py", line 105, in main
    rmg.execute(**kwargs)
  File "/Users/rwest/Code/Silicon/RMG-Py/rmgpy/rmg/main.py", line 649, in execute
    self.initialize(**kwargs)
  File "/Users/rwest/Code/Silicon/RMG-Py/rmgpy/rmg/main.py", line 484, in initialize
    self.load_database()
  File "/Users/rwest/Code/Silicon/RMG-Py/rmgpy/rmg/main.py", line 430, in load_database
    family.fill_rules_by_averaging_up(verbose=self.verbose_comments)
  File "/Users/rwest/Code/Silicon/RMG-Py/rmgpy/data/kinetics/family.py", line 1271, in fill_rules_by_averaging_up
    self.rules.fill_rules_by_averaging_up(self.get_root_template(), {}, verbose)
  File "/Users/rwest/Code/Silicon/RMG-Py/rmgpy/data/kinetics/rules.py", line 495, in fill_rules_by_averaging_up
    kinetics = self.fill_rules_by_averaging_up(template, already_done, verbose)
  File "/Users/rwest/Code/Silicon/RMG-Py/rmgpy/data/kinetics/rules.py", line 495, in fill_rules_by_averaging_up
    kinetics = self.fill_rules_by_averaging_up(template, already_done, verbose)
  File "/Users/rwest/Code/Silicon/RMG-Py/rmgpy/data/kinetics/rules.py", line 495, in fill_rules_by_averaging_up
    kinetics = self.fill_rules_by_averaging_up(template, already_done, verbose)
  File "/Users/rwest/Code/Silicon/RMG-Py/rmgpy/data/kinetics/rules.py", line 504, in fill_rules_by_averaging_up
    if entry is not None and entry.rank > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

My guess is that we are missing a `rank` attribute on our new training reactions. 

**If** this is now a required attribute, then I think the database tests should check for it, and report which reactions are missing it.

**If** it is not meant to be a required attribute (some default should be assumed) then there's a bug in RMG.

### How To Reproduce
Add a training reaction with no `rank`.

### Expected Behavior
If missing a rank is an error then the database tests should detect it.
If it is not an error then RMG should not crash when averaging up the database.

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): (e.g. Windows 10, Ubuntu 18, macOS 10.13, etc.)
 - Installation method: (e.g. installation from binary or source, with or without anaconda)
 - RMG version information:
   
   - RMG-Py: 2.4.0-539-gf813e5c27
   - RMG-database: [2.4.0-57-g1a319a7](https://github.com/MingyuWAN/RMG-database/tree/1a319a78a230763ef084033ea534769dc79221fd)

**Comment by rwest** [comment]
Thanks Alon! Maybe just hyperlinks to it from the other places one might look (eg. the results of a search for "rank")

**Comment by mliu49** [comment]
This is somewhat Python 3 related, since None can no longer be compared to other types. In Python 2, None is not greater than 0, so I think entries with no rank get treated the same as rank 0.

We currently don't enforce entries to have a rank, but perhaps that would be good to add to the database test. We can also fix this comparison (like we have in other situations, e.g. 50ffd9efce3e7a74a9ae8f82b0cdba59ec650621) so that it retains similar behavior as before.

**Comment by PoojaNem** [comment]
I am currently working on verifying the kinetics of a mechanism produced using RMG. For the reaction C2H5 + i-C3H7  →  C2H6 + C3H6, RMG computes rate parameters using the node root of the Disproportionation reaction family (Root_Ext-2R!H-R_2R!H->C_4R->C). This particular rate rule has a rank of 11, and the link provided above does not include the rank 11 description. Can someone tell me what rank 11 for the rate rule means in RMG?
