### ISSUE TITLE
Commented example input.py file lacks some new additions

### ISSUE THREAD

**Issue by kspieks** [ReactionMechanismGenerator/RMG-Py#1801]
### Bug Description
The commented example input.py located in RMG-Py/examples/rmg/commented/input.py lacks some new additions

### Expected Behavior
I will update and organize this file which will help me learn about the different features that can be included in the input.py file when running a job

### Installation Information
Describe your installation method and system information.
 
   - RMG-Py: 
   - RMG-database:

**Comment by mliu49** [comment]
Fixed by #1806
