### ISSUE TITLE
PATH from windows is appended to WSL PATH

### ISSUE THREAD

**Issue by dranasinghe** [ReactionMechanismGenerator/RMG-Py#1813]
### Bug Description
When installing RMG on the Windows subsystem for Linux (WSL) I noticed in the Linux PATH windows program PATH are appended.  
eg. 
`/home/dranasinghe/RMG-Py:/home/dranasinghe/anaconda3/bin:/home/dranasinghe/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/PerkinElmerInformatics/ChemOffice2018/ChemScript/Lib:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Program Files (x86)/Bitvise SSH Client:/mnt/c/Program Files (x86)/Avogadro/bin:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/MATLAB/R2019a/bin:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Program Files/PuTTY:/mnt/c/Users/drana/AppData/Local/Microsoft/WindowsApps:/snap/bin `

As you can see there are windows program files in the PATH. I have launched  .exe form a Linux terminal which cool and problematic at the same time. I install Anaconda on windows to see whether it append to PATH; it did 't but I am afraid some program or library might interfere. 
### How To Reproduce
Install WSL and Ubuntu 18.04LTS or 16 LTS.
echo $PATH

### Expected Behavior
There only should be Linux system folders in the PATH. One can modify the .bashrc to declare new PATH. 

### Installation Information
Describe your installation method and system information.
 - Windows 10  WSL Ubuntu 18.04 LTS
 - Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Mon Mar 18 12:02:00 PST 2019 

### Additional Context
I did n't have these problems a year ago. I tried PATH on another system there windows python library is appended! 
`/home/sarahkha/.local/share/umake/bin:/home/sarahkha/bin:/home/sarahkha/.local/bin:home/sarahkha/pycharm/bin:/home/sarahkha/julia/bin:/home/sarahkha/jupyter/bin:/home/sarahkha/anaconda3/bin:/home/sarahkha/anaconda3/condabin:/home/sarahkha/molden5.9:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/PerkinElmerInformatics/ChemOffice2017/ChemScript/Lib:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files (x86)/Git Cola/bin:/mnt/c/Program Files (x86)/PharosSystems/Core:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Users/mitadm/Anaconda2:/mnt/c/Users/mitadm/Anaconda2/Library/bin:/mnt/c/Users/mitadm/Anaconda2/Scripts:/mnt/c/Users/mitadm/Anaconda2/envs/rmg_env/share/mingwpy/bin:/mnt/c/Users/mitadm/Anaconda3:/mnt/c/Users/mitadm/Anaconda3/Library/bin:/mnt/c/Users/mitadm/Anaconda3/Scripts:/mnt/c/Users/mitadm/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/mitadm/AppData/Local/GitHubDesktop/bin:/snap/bin:/home/sarahkha/RMG-Py/     `

**Comment by hwpang** [comment]
It seems to be a WSL problem and seems can be solved with: https://stackoverflow.com/questions/51336147/how-to-remove-the-win10s-path-from-wsl

But maybe it is worthy to add a small troubleshoot section in the installation documentation section to help user identify this issue in the future.

**Comment by amarkpayne** [comment]
@hwpang thanks for finding this! Would you mind adding a commit that addresses this in the documentation? If so you can tag me to review the PR.

**Comment by hwpang** [comment]
> @hwpang thanks for finding this! Would you mind adding a commit that addresses this in the documentation? If so you can tag me to review the PR.

Sure thing!

**Comment by JacksonBurns** [comment]
This installation method is no longer supported. Closing a stale.
