### ISSUE TITLE
Question regarding generatedSpeciesConstraints()

### ISSUE THREAD

**Issue by saud3001** [ReactionMechanismGenerator/RMG-Py#1816]
When using the following option:

```
generatedSpeciesConstraints(
    allowed=['input species','seed mechanisms','reaction libraries'],
    maximumCarbonAtoms=10,
    maximumOxygenAtoms=2,
    maximumNitrogenAtoms=2,
    maximumSiliconAtoms=2,
    maximumSulfurAtoms=2,
    maximumHeavyAtoms=10,
    maximumRadicalElectrons=2,
    maximumSingletCarbenes=1,
    maximumCarbeneRadicals=0,
    maximumIsotopicAtoms=2,
    allowSingletO2 = False,
)
```
Do we write `allowed=['input species','seed mechanisms','reaction libraries']` as is (verbatim) or do the `input species`, `seed mechanisms`, and `reaction libraries` need to be explicitly defined?

Thanks in advance!

**Comment by alongd** [comment]
Hi, you simply write these constraint types as is. No need to specify specific species from the input file or specific libraries to allow. You can also see how this section of the input file is defined in our [examples](https://github.com/ReactionMechanismGenerator/RMG-Py/tree/master/examples/rmg) (which should work "as is" without further modifications on the master branch).
