### ISSUE TITLE
RMG v3.0.0 Release Planning

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1830]
It's time to start preparing for the RMG v3.0.0 release. This is a major release, with the biggest changes being Python 3 support and API naming style changes.

There will be an accompanying paper highlighting some of the major changes since RMG v1.0, and I assume that the ongoing Arkane paper will most likely be updated to reference this release as well.

There are still a number of PR's which need to be merged, which are tagged with [For Next Release](https://github.com/ReactionMechanismGenerator/RMG-Py/pulls?q=is%3Aopen+is%3Apr+label%3A%22For+Next+Release%22).

This issue is for any release related discussion. Draft release notes will also be prepared here.

**Comment by mliu49** [comment]
# RMG-Py v3.0.0 Release Notes (draft)

This release represents a major milestone in RMG development and includes many backwards-incompatible changes, most notably Python 3 compatibility and major API changes. Users switching to RMG 3 will need to create new conda environments and update any scripts which access the API. We recommend using the `futurize` script from python-future for updating scripts for Python 3 and the provided `rmg2to3.py` script for updating scripts for RMG 3.

Python 3 #1724 
- RMG is now compatible with Python 3.7 and newer
- RMG v2.x versions will no longer be supported
- API changes
    - Method, function, and argument names have been standardized to use snake_case across RMG and Arkane
    - Input file related code was not changed, in order to continue support for existing syntax
    - Conversion script has been provided to aid transition (scripts/rmg2to3.py)
    - Standardized submodule names in the rmgpy.tools module #1794
- Accompanying changes
    - Reduction and scoop_framework modules have been removed
    - New/updated hash and comparison methods for Species/Molecule/Atom/Bond classes
    - DDE thermochemistry estimator has been replaced by chemprop
    - Update example IPython notebooks #1735
- Miscellaneous clean up and bug fixes following transition #1741, #1744, #1752, #1759, #1785, #1802, #1798, #1799, #1808 

Arkane
- Improvements and refactoring of job output file creation and content #1607 
- Fix kinetics fitting bug #1672 
- Improvements to automatic network exploration tool #1647
- Support for ND empirical and semi-empirical rotor calculations #1640
- Support for 2D quantum mechanical rotor calculations using Q2DTor #1640
- Support for providing absolute file paths #1685 
- Output RMG-style libraries #1769
- Check for error termination in Gaussian log files #1766
- Support for parsing Orca log files #1749
- Support for parsing MP2, double hybrid DFT, CCSD, and CCSD(T) energies from Gaussian log files #1815
- Support for TeraChem log files #1788 
- Miscellaneous bug fixes #1810

New features
- Additional options for heterocycles in MLEstimator #1621
- Automatic tree generation algorithm implementation completed #1486, #1675
- New simulation restart approach using seed mechanisms (old pickle-based method removed) #1641 
- Added new MBSampledReactor type for simulating molecular beam experiments (does not support model generation) #1669

Bug fixes
- Fix numpy rcond usage to restore support for older numpy versions #1670 
- Fix bug with duplicate library reactions when using RMG generated seed mechanisms #1676
- Move parse_command_line_arguments to facilitate importing in binary package #1717
- Fix issues with is_identical_to methods of kinetics models #1705 
- Fix cython issue with make_object definitions #1817

Miscellaneous
- Improvements to mergeModels.py script #1649 
- Miscellaneous performance improvements #1677, #1765, 
- Raise errors when NaN is encountered in solver #1679 
- Improvements to group additivity thermo estimates for aromatics and sulfur species #1731, #1751 
- Allow sulfur species to have valence 12 in resonance algorithm #1751 
- Add support for maxproc argument to generate_reactions module #1780 
- Display atom index when drawing groups #1758
- Update sensitivity example #1805
- Update commented input file #1806
- Logging changes #1721, #1755 
- Documentation updates #1680, #1709, #1767, #1781, #1784, #1807

Thanks to all contributors: ajocher, alongd, amarkpayne, cgrambow, dranasinghe, hwpang, kspieks, goldmanm, mjohnson541, mliu49, oscarwumit, rwest, rgillis8, sudoursa, xiaoruiDong, yunsiechung, zjburas

**Comment by mliu49** [comment]
# RMG-database v3.0.0 Release Notes (Draft)

Thermochemistry
- Add new models for chemprop estimator to replace dde models ReactionMechanismGenerator/RMG-database#351
- Revamp GAVs for oxygenated sulfur species ReactionMechanismGenerator/RMG-database#360
- Add polycyclic GAVs for various strained molecules ReactionMechanismGenerator/RMG-database#333

Kinetics
- New automatically generated tree for R_Recombination ReactionMechanismGenerator/RMG-database#334
- Refine root template for 1,2_NH3_elimination ReactionMechanismGenerator/RMG-database#350
- New DMSOxy kinetics family ReactionMechanismGenerator/RMG-database#360
- Add DMS related training reactions to H_abstraction ReactionMechanismGenerator/RMG-database#360

Bug fixes
- Fix drawing for 2+2_cycloaddition_Cd ReactionMechanismGenerator/RMG-database#345 
- Fix incorrect SMILES in solute database ReactionMechanismGenerator/RMG-database#348
- Fix incorrect adjacency list for HON in kinetics libraries ReactionMechanismGenerator/RMG-database#350
- Fix typo in solvent parameters ReactionMechanismGenerator/RMG-database#357

**Comment by goldmanm** [comment]
I am not sure how to get this in the binary for 3.0.0, but the isotopes script, located in `scripts/isotopes.py` was not in the [2.4.1 binary](https://anaconda.org/RMG/rmg/files) in the `bin` folder. Let me know if there's anything I can do to help with that.

**Comment by mliu49** [comment]
Good catch! It should be added to the list of scripts in `setup.py`: https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/setup.py#L203
