### ISSUE TITLE
restartFromSeed ERROR

### ISSUE THREAD

**Issue by guannandong** [ReactionMechanismGenerator/RMG-Py#1835]
### Topic
General area which your question is related to.
 - [ ] Running an RMG job
 - [ ] An error message 

### Context
Dear RMG developer, I'm trying to use the restart function through seed Mechanism by adding "restartFromSeed" in the beginning of my Input.py file. However, I got an unexpected error return. I've tried to debug by checking "rmgpy/rmg/main.py" and "rmgpy/rmg/input.py" as I tried to follow the error Traceback thread. 

The error response is 
"NameError: name 'restartFromSeed' is not defined"

I also attached a txt file with the full response history.
[error_log.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3907825/error_log.txt)

### Question
I followed the error response and checked "rmgpy/rmg/main.py" and "rmgpy/rmg/input.py", and I figured, from I'm capable, the "input.py" failed when trying to match and add 'restartFromSeed' into the dictionary variable "local_context".

### Installation Information
Describe your installation method and system information if applicable.
 - OS: macOS 10.14.6
 - Installation method: installed from binary, with anaconda
 - RMG version information: Version: 2.4.1;  Build: py27he38e130_2
   - RMG-Py: don't know
   - RMG-database: don't know

Thank you so much for your time!

Regards,
Guannan

**Comment by kspieks** [comment]
Hi Guannan, 
Thanks for asking us about this issue. My initial analysis is that the restart from seed feature was not added until after v2.4.1 (i.e. the function restartFromSeed was not implemented in this version and its lack of existence is the source of your error). Can you try checking out branch v2.5.0? Or possibly the current master if you want to switch to Python 3? I welcome additional feedback from the main developers.

**Comment by guannandong** [comment]
Hi kspieks,
Thanks for your reply. I followed the documentation on rmg.mit.edu and installed the latest stable version 2.4.1. How to access v2.5.0 or current master? I'm using Python 3 currently.

**Comment by kspieks** [comment]
I believe Python 3 versions of RMG should have restartFromSeed functionality (I've been using them with the same line `restartFromSeed(path='seed')` at the top of my input file). 
Can you go to your terminal, cd to RMG-Py,  type `git branch` in your terminal and post the result here to confirm what branch you are on? Can you also type `git log` and paste the most recent commit at the top of the results? (it'll be some long list of numbers and letters like this: 3f83cb9d8f15e41f3a21d0c057b6356bef5dd12f )
Kevin

**Comment by mliu49** [comment]
Hi @guannandong, you said that you installed the binary version of RMG 2.4.1, which was the most recent binary release. However, that version does not include the restartFromSeed feature. It is also not Python 3, just for your information. When you do the binary install, Anaconda creates an independent Python 2 environment, even if you installed Anaconda 3.

If you would like to use this feature right away, then I suggest installing RMG from source using the developer instructions. Otherwise, you'll need to wait for the RMG 3.0 release which will be in a few weeks.

**Comment by guannandong** [comment]
Thank you Max. That answered my question. And thank you too Kevin!
