### ISSUE TITLE
Extra redundant line in chem_annotated.inp file caused ChemkinError

### ISSUE THREAD

**Issue by ajuluc** [ReactionMechanismGenerator/RMG-Py#1837]
### Bug Description
So for my rmg model job on n-decane, the model crashes due to inability to explore model isomers. Upon deliberation with @mjohnson541, we expected it to most likely be collision violators hence why it crashed. It crashes without any collision violators file so we attempted to produce a collision limit violators notebook with @rwest to find which libraries actually violate violators.

### How To Reproduce
We ran the rmg model with the following thermo libraries as well as reaction libraries in the following order 
```
database(
    thermoLibraries = ['BurkeH2O2', 'Klippenstein_Glarborg2016' , 'CurranPentane','FFCM1(-)','primaryThermoLibrary', 'thermo_DFT_CCSDTF12_BAC', 'DFT_QCI_thermo', 'CBS_QB3_1dHR'],
    reactionLibraries = [('CurranPentane',False),('FFCM1(-)',False),('combustion_core/version5', False)],
    seedMechanisms = ['BurkeH2O2inN2','Klippenstein_Glarborg2016', 'C2H4+O_Klipp2017'],#we take out argon for this N2 bath gas file
    kineticsDepositories = ['training'],
    kineticsFamilies = 'default',
    kineticsEstimator = 'rate rules',
)
```
Now when we run the model in rmg the output file produces as error file in the annotated file with this extra line seen below. We get four lines of the description rather than three lines as standard, where the `Library reaction comment: Klippenstein_Glaborg2016` is redundant.
```
! Reaction index: Chemkin #203; RMG #194
! Library reaction: Klippenstein_Glarborg2016
! Flux pairs: HCOH(27), H2(13); HCOH(27), CO(6); 
! Reaction library: 'Klippenstein_Glarborg2016'
HCOH(27)=H2(13)+CO(6)                               6.560000e+13 0.000     49.465   

! Reaction index: Chemkin #204; RMG #195
! Library reaction: Klippenstein_Glarborg2016
! Flux pairs: HCOH(27), CH2O(9); 
! Reaction library: 'Klippenstein_Glarborg2016'
HCOH(27)=CH2O(9)                                    5.150000e+13 0.000     32.109  
```

### Expected Behavior
We should get three lines of the description before the actual reaction like below. So we suppress the reaction and get this which passes as an rmg object in the load_chemkin_file function
```
! Reaction index: Chemkin #203; RMG #194
! Library reaction: Klippenstein_Glarborg2016
! Flux pairs: HCOH(27), H2(13); HCOH(27), CO(6); 
HCOH(27)=H2(13)+CO(6)                               6.560000e+13  0.000   49.465   

! Reaction index: Chemkin #204; RMG #195
! Library reaction: Klippenstein_Glarborg2016
! Flux pairs: HCOH(27), CH2O(9); 
HCOH(27)=CH2O(9)                                    5.150000e+13 0.000     32.109  
```

### Installation Information
Describe your installation method and system information.
 - MacOS Version 10.14.6
 - Installation from source with anaconda 
 - RMG version information: 2.4.1
   

### Additional Context
For the collision violators limit notebook its linked here 
https://github.com/ajuluc/GTL/blob/f9b079f536db021450f963e492f8cb6af412f4f5/nc10/no_lowT/Collision_violators.ipynb
 with most if not all the violators coming from the Klippenstein_Glaborg2016 reaction library  

with collision limit factors such as these 
```
CH2O(9) + C2H5O3(56) => HCO(20) + CH2OH(25) + CH2OOH(35)
Arrhenius(A=(41000,'cm^3/(mol*s)'), n=2.5, Ea=(10.206,'kcal/mol'), T0=(1,'K'))
Kinetic library: Klippenstein_Glarborg2016
Direction: reverse
Violation factor: 1051133.80
Violation condition: 800 K, 1.0 bar
```

**Comment by amarkpayne** [comment]
@ajuluc Can you see if the ChemkinError issue due to the redundant line in chem_annotated.inp still persists on current master if you regenerate the Chemkin file? I believe that #1842 fixed this issue, but I want to confirm. If so I think this issue can be closed, though there are other issues that you mention in passing here that might be worth opening separate issues for.

**Comment by ajuluc** [comment]
Hi @amarkpayne  I was able to recover the original chemkin file and use the ```load_chemkin_file```command and it doesn't throw out `ChemkinError` anymore so I'll be closing this issue for good. As to the other issues that were mentioned such as the collision violators I will make a separate issue for that. Thanks again

**Comment by amarkpayne** [comment]
Thanks for checking this @ajuluc !
