### ISSUE TITLE
RMG attempts to explore non-existent isomers in product channels

### ISSUE THREAD

**Issue by ajuluc** [ReactionMechanismGenerator/RMG-Py#1839]
### Bug Description
During model generation for a pressure-dependent reaction, rmg explores isomers however on certain occasions, rmg attempts to explore isomers of a specific species but that species might be non-existent hence why it crashes and attempts to resurrect model.

### How To Reproduce
We start our rmg model generation with the following options for n-decane where we've introduced staging to attempt to prevent rmg from crashing and where we also set `maxNumObjsPerIter=3` that includes species, reactions or pdep network and we also attempt to prune our model species in the product channels.
```
model(
    toleranceKeepInEdge=0.05,
    toleranceInterruptSimulation=1e8,
    toleranceMoveToCore=0.5,
    filterReactions = True,
    filterThreshold = 5e8, # Default is 5e8
    maximumEdgeSpecies=100000,
    maxNumObjsPerIter = 1, # number of objects (species, reactions, PDepNetworks) that can be taken from one simulation
    minCoreSizeForPrune=100,
    minSpeciesExistIterationsForPrune=2,
    maxNumSpecies=500,
```

```
model(
    toleranceKeepInEdge=0.001,
    toleranceInterruptSimulation=1e8,
    toleranceMoveToCore=0.01,
    filterReactions = True,
    filterThreshold = 5e8, # Default is 5e8
    maximumEdgeSpecies=100000,
    maxNumObjsPerIter = 3, # number of objects (species, reactions, PDepNetworks) that can be taken from one simulation
    minCoreSizeForPrune=50,
    minSpeciesExistIterationsForPrune=2,
```
we get this error message 
```
Traceback (most recent call last):
  File "/scratch/ajulu.c//Code/RMG-Py/rmg.py", line 111, in <module>
    main()
  File "/scratch/ajulu.c//Code/RMG-Py/rmg.py", line 96, in main
    cProfile.runctx(command, global_vars, local_vars, stats_file)
  File "/scratch/ajulu.c/anaconda3/envs/rmg_py3/lib/python3.7/cProfile.py", line 20, in runctx
    filename, sort)
  File "/scratch/ajulu.c/anaconda3/envs/rmg_py3/lib/python3.7/profile.py", line 62, in runctx
    prof.runctx(statement, globals, locals)
  File "/scratch/ajulu.c/anaconda3/envs/rmg_py3/lib/python3.7/cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/scratch/ajulu.c/Code/RMG-Py/rmgpy/rmg/main.py", line 828, in execute
    self.reaction_model.enlarge(objectToEnlarge)
  File "/scratch/ajulu.c/Code/RMG-Py/rmgpy/rmg/model.py", line 551, in enlarge
    new_reactions.extend(pdep_network.explore_isomer(new_species))
  File "/scratch/ajulu.c/Code/RMG-Py/rmgpy/rmg/pdep.py", line 282, in explore_isomer
    raise Exception('Attempted to explore isomer {0}, but that species not found in product channels.'.format(isomer))
Exception: Attempted to explore isomer CC3H4(183), but that species not found in product channels.
```

### Expected Behavior
Model ought not to crash since it attempts to explore a non-existent species isomer in the product channel.

### Installation Information
Describe your installation method and system information.
 - MacOS Version 10.14.6 
 - Installation method: installation from source with anaconda
 - RMG version information:2.4.1

**Comment by mliu49** [comment]
This seems to be the same error as #1725. In that case, I had narrowed it down to interactions between thermodynamic pruning and pdep networks. However, in your case, it doesn't seem like you're using thermodynamic pruning, so I'm no longer sure about the cause of the error.

**Comment by mliu49** [comment]
Actually, is that the full model block? Could you provide your input file?

**Comment by ajuluc** [comment]
I'm not doing thermodynamic pruning however, here's the input file 
[nc10_lowT_remvd.py.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3923880/nc10_lowT_remvd.py.zip)
