### ISSUE TITLE
Addition of species constraint for new atomtype

### ISSUE THREAD

**Issue by dronekill** [ReactionMechanismGenerator/RMG-Py#1854]
### Question
We are in the process of extending RMG for new atom such as Aluminium, Galium, Boron etc. We want to restrict the number of atoms in the generated species. However, we are not aware of how to put this constraint in RMG. Could you please suggest something?

### Installation Information
Describe your installation method and system information.

    ubuntu 18
    Installation method: developer version
    RMG version information:
        RMG-Py: 2.4.0
        RMG-database: 2.4.0

**Comment by alongd** [comment]
RMG's input file has a species constraints block (see http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/input.html?highlight=constrain#species-constraints). I think you might want to see how it is coded and add similar constraints for the elements you're adding.

**Comment by mliu49** [comment]
You will need to update both the input file parser and the actual constraint handling code in [constraints.py](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/constraints.py)

**Comment by dronekill** [comment]
[constraints.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3991458/constraints.txt)
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3991459/input.txt)
We made changes to these two files as suggested but still were not able to get the required functionality. @mliu49 Could you please elaborate about the changes that needed in the input file parser?

**Comment by dronekill** [comment]
Change to input file parser is the key to solving this. Thanks again.
