### ISSUE TITLE
Completely identical duplicate reactions in RMG mechanism

### ISSUE THREAD

**Issue by cgrambow** [ReactionMechanismGenerator/RMG-Py#1873]
### Bug Description
RMG-generated mechanisms contain seemingly identical duplicate reactions. The following is just one example found in the Chemkin file:
```
! Reaction index: Chemkin #38; RMG #623
! Template reaction: R_Addition_MultipleBond
! Flux pairs: C4H8(90), C4H9(76); H(3), C4H9(76); 
! From training reaction 10 used for Cds-CsH_Cds-HH;HJ
! Exact match found for rate rule [Cds-CsH_Cds-HH;HJ]
! Euclidian distance = 0
! family: R_Addition_MultipleBond
H(3)+C4H8(90)=C4H9(76)                              3.010000e+08 1.600     2.400    
DUPLICATE

! Reaction index: Chemkin #40; RMG #1911
! Template reaction: R_Addition_MultipleBond
! Flux pairs: H(3), C4H9(76); C4H8(90), C4H9(76); 
! From training reaction 10 used for Cds-CsH_Cds-HH;HJ
! Exact match found for rate rule [Cds-CsH_Cds-HH;HJ]
! Euclidian distance = 0
! family: R_Addition_MultipleBond
H(3)+C4H8(90)=C4H9(76)                              3.010000e+08 1.600     2.400    
DUPLICATE
```
Since it's the same exact match, I wouldn't expect the reaction to appear twice in the mechanism.

### RMG version information:
- RMG-Py: 3.0.0-2-g957ee80ad
- RMG-database: 3.0.0-12-ga6deb396

**Comment by alongd** [comment]
related to  #1336 and #1823

**Comment by cgrambow** [comment]
In my mechanism with 3554 reactions, 76 reactions seem to be exact duplicates of each other with exactly the same kinetics. So I think this problem is quite significant because many reaction rates will be artificially increased.

**Comment by rwest** [comment]
Pull request #1856 addresses some duplicate issues. Maybe someone would like to review (and possibly merge) it, before investigating remaining duplicate problems.

**Comment by rwest** [comment]
See my last comment on #1856 however:
> Note that although I think this fixes a problem that we had in identifying the duplicate reactions and labeling them as such for valid chemkin files, it does not address the question as to why we were making two such reactions in the first place. That might require more investigation.
