### ISSUE TITLE
model generation not terminating with high termination coversion criteria for surface reaction

### ISSUE THREAD

**Issue by dronekill** [ReactionMechanismGenerator/RMG-Py#1880]
### Bug Description
Model Termination with Terminationconversion criteria above 0.9 doesn't proceed further. However, Terminationconversion criteria of less than 0.8 terminate successfully. Moreover, it has been observed that an increase in conversion value from 0.5 to 0.7 did not add new reactions to the model and at 0.99 conversion number of reactions increases exponentially.

### How To Reproduce
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/4152303/input.txt)
Library files are attached also.
[dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/4152315/dictionary.txt)
[reactions.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/4152316/reactions.txt)

### Expected Behavior
The model generation should complete.

### Installation Information
Developer version
 - Ubuntu 18.4.03
 - with anaconda
 - RMG version information:
   - RMG-Py: 3.0.0
   - RMG-database: 3.0.0

**Comment by mjohnson541** [comment]
Is that high of conversion thermodynamically favorable in your system? If it isn't by commenting the terminationTime criterion, you've essentially not set a termination criterion.

**Comment by dronekill** [comment]
Our thermodynamic data is correct, we have added various termination time criteria and noticed no extra reactions were created. We feel that CO physically adsorbed is creating the problem. RMG is not able to apply actions on CO. Can we define CO as a chemically bonded on catalyst surface and use thermodynamic data of physically adsorbed CO instead?

**Comment by mjohnson541** [comment]
@mazeau @rwest any idea why this might be happening?
