### ISSUE TITLE
Non-strict isomorphism check does not ignore electrons.

### ISSUE THREAD

**Issue by cgrambow** [ReactionMechanismGenerator/RMG-Py#1883]
`Molecule.is_isomorphic` has a `strict` option, which, according to the doc string, performs the isomorphism ignoring electrons if it is `False`. However, in the function, the multiplicity of `self` is compared to `other` regardless of what `strict` is set to. I would expect multiplicity differences to be ignored when `strict=False`. What is the intended behavior?

**Comment by mjohnson541** [comment]
The real point of strict = False is for telling if two molecule objects have the same order ignored bonds between atoms (and thus are the same Species). Typically we would like to consider species with different multiplicities as different species so the multiplicity check is applied when strict=False.

**Comment by rwest** [comment]
I guess that makes sense - it's merging all resonance structures, but not doing spin crossing - but I guess the doc string could be tweaked to clarify.
