### ISSUE TITLE
Another RMG test not passing error

### ISSUE THREAD

**Issue by jgiaccai** [ReactionMechanismGenerator/RMG-Py#1886]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [ ] An error message 

### Context
I just installed RMG-Py from source last night following the instructions here http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html

All seemed to go well until I ran the tests.  

It is quite possible I don't have my bash profile set up correctly.  

When trying to run the first test listed from the RMG-Py folder (make test in the Unit test suite) I get:  FAILED (errors=80)
make: *** [test] Error 1

There is a lot of text above the error message, stating that it can't find, e.g. cantera, rdkit, quantities, rmg-py, etc.  

### Question
How to fix?  

I've attached text files with the complete error message spit out and my bash profile.
[bash_profile.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/4171823/bash_profile.txt)
[RMGMakeTestError1.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/4171825/RMGMakeTestError1.txt)

### Installation Information
Describe your installation method and system information if applicable.
 - OS:  mac OS 10.14.6
 - Installation method: from source, with conda, seemed to go okay until I got to the tests...
 - RMG version information:
   
   - RMG-Py: 3.0.0-18-gee14e3532
   - RMG-database:

**Comment by amarkpayne** [comment]
Looking at the log, it appears that you were in the base conda environment instead of rmg_env. Try executing the following commands and see if this fixes you problem (the first command activates your environment, which you will need to do before anything and everything with RMG).

From your RMG-Py folder:
```
conda activate rmg_env
make test
```

**Comment by jgiaccai** [comment]
Yup, that was it.  All the tests pass now, (some were skipped in the first make test, but it still reported OK) so now I just get to figure out how to use RMG.  On to the fun stuff!

**Comment by amarkpayne** [comment]
Glad to hear! Don't worry about the tests that were skipped, this is normal. There are a few work-in-progress tests that we always skip over (until we finish working on them someday).
