### ISSUE TITLE
Binary installation instructions could lead to Python 2 version.

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#1891]
A user recently posted to rmg_dev with a problem that was caused by them inadvertently using an old version of RMG, compatible with Python 2.7.  In corresponding with them it transpired that 

> Previously, I was installing RMG-python according to the website below which is the binary installation. 
http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaUser.html 
>
>However, after reinstalling the RMG with the developer option, it works finely for me. I guess its the problem of the library package in the previous instruction which install RMG in python 2.7 version.

Looking at the [conda docs](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html#managing-python)

> When you create a new environment, conda installs the same Python version you used when you downloaded and installed Anaconda. If you want to use a different version of Python, for example Python 3.5, simply create a new environment and specify the version of Python that you want.

I guess if users already have Anaconda installed with Python 2.7 that the current instructions `conda create -c defaults -c rmg -c rdkit -c cantera -c pytorch -c conda-forge --name rmg_env rmg rmgdatabase` would lead it to stick with Python 2.7 versions of everything.

We should probably either add `python=3` to the `conda create` command, and/or add a bunch of explanations and warnings to the instructions.

Might be worth doing both.  I bet they're not the only person to have stumbled here, even if other people solved it themselves.

**Comment by JacksonBurns** [comment]
The environment file now specifies packages which only compatible with Python 3, so this is no longer a bug risk. Closing as completed.
