### ISSUE TITLE
Unexpected duplicate reactions appearing in pyrolysis model

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1895]
### Bug Description
I ran a pretty minimal n-butane pyrolysis model (file attached), and it ended up with multiple duplicate reactions which I don't think should be duplicates, since there is only one reasonable transition state for the reaction (also attached). The duplicate reactions appear to be hitting different nodes, but arrive at the same rate. 

It seems like there should be only two pairs of duplicates (terminal n-butyl to central n-butyl and a disprop reaction between terminal n-butyl and central n-butyl), giving a total of four duplicates. However, the mechanism reports 12 duplicates.

### How To Reproduce
Run the input file on RMG-Py at commit

### Expected Behavior
Reactions with only one transition state should not be duplicates. And reactions with two transition states should have two duplicates (not four).

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): pharos
 - Installation method: pharos with anaconda
 - RMG version information: Official/master as of Feb 20th, 2020
   
   - RMG-Py: 0198164c55a3dad187872ec72d64503b8c8c2a8f
   - RMG-database: d626e2bd535faf1cb4c3c1618cfff8ad1bbe3dd9

### Additional Context
files relevant to recreating issue

[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/4247974/input.txt)
[chem_annotated.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/4247975/chem_annotated.txt)

**Comment by alongd** [comment]
Could be related to #1336, #1823, #1873

**Comment by sevyharris** [comment]
I reran this input file while looking for simple examples that can replicate the duplicates issue in [1823](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/1823) but there were no duplicates as of commit 215eb1bef229d0f54217b6b8b6fff944c750180b, so I'm closing this issue.
