### ISSUE TITLE
more specific version info in RMG.log

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1896]
### Motivation or Problem
Difficult sometimes to trace which RMG-Py and RMG-database was used for a particular model. Currently, just the most recent RMG tag is printed at the header, but this is not enough to reproduce the work.

### Desired Solution
Have RMG jobs output the RMG-Py and RMG-database commit hashes at the start of the RMG-job.

### Potential Alternatives
Place that information in a separate file. Or make the user/developer guess which version. There could be a whole software program that reruns RMG at each commit to see if it gives the same answer.

**Comment by mliu49** [comment]
The commit hashes should already be output at the start of the job: https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/rmg/main.py#L1788

**Comment by JacksonBurns** [comment]
Requested feature is already in place, closing as resolved.
