### ISSUE TITLE
The InChI (or SMILES) to group descriptor conversion code

### ISSUE THREAD

**Issue by arnab37** [ReactionMechanismGenerator/RMG-Py#1901]
Hi,

Would it be possible to see the InChI (or SMILES) to group descriptor conversion code? I am trying to make a code for the same purpose in MATLAB (not relevant to RMG calcs), which has a lot of problems. I thought to ask RMG people whether they can share the code (Python is fine with me) or not. I would really appreciate if somebody lets me know about it.

Thanks,
Arnab

**Comment by alongd** [comment]
Take a look here:
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/converter.py
let us know if you have questions
