### ISSUE TITLE
How would one remove a certian reaction family during rmg calcs?

### ISSUE THREAD

**Issue by arnab37** [ReactionMechanismGenerator/RMG-Py#1903]
Hi,

Currently, I am doing a liquid reactor calculation of diphenyl ether. It is providing a few reactions which lead to the formations of unlikely products. I would like to know how to remove those reaction families. It would also be really helpful if somebody can provide an example input file for this case.

Thanks,
Arnab

**Comment by alongd** [comment]
Hi, see the documentation here:
http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/input.html#kinetics-families
(e.g., specifying `kineticsFamilies = ['!SubstitutionS']` will cause the run to not use the `SubstitutionS` family.
