### ISSUE TITLE
Maybe adding species filters to the output htmls

### ISSUE THREAD

**Issue by mazeau** [ReactionMechanismGenerator/RMG-Py#1904]
### Motivation or Problem
In extremely large models (especially when we're looking at the edge output), it would be nice to have a filter checkbox for species type (say, display only surface species or gas species) like we have for reaction families.  It would be even nicer to be able to filter species by whether they have radicals or not.  
@kblondal and I were talking about how this might make our lives a bit easier

### Desired Solution
Probably some tweaking in `rmgpy/rmg/output.py`

### Potential Alternatives
This feature could be deemed unnecessary in the majority of cases, and we could just leave it as is.

**Comment by amarkpayne** [comment]
Just to be clear, this is specifically about the output.html file, right?

**Comment by mazeau** [comment]
Yes

**Comment by amarkpayne** [comment]
Sorry, I forgot to follow-up with this. I think this is a great suggestion and would love to see this feature get added to RMG-Py. If you want this is something that we could potentially work on together at the next RMG developer hours. Alternatively, if you want to see this happen sooner feel free to start working on this. I am more than happy to review a PR for this, or even try to answer any questions if they come up, but I don't think I will have time to implement this myself until the next developer hours.

**Comment by mazeau** [comment]
I'll put it on my todo list.  Please let me know if there are any other criterias people may want to filter by!
