### ISSUE TITLE
RMG test failed

### ISSUE THREAD

**Issue by AH9316** [ReactionMechanismGenerator/RMG-Py#1913]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

### Context
I installed the developer version on my Mac(at the same time, I installed MOPAC) and then do the RMG test. It shows me that there is an error related to MOPAC as below:

ERROR: Test that generate_thermo_data() can load thermo from the previous MOPAC PM7 run.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/anguohu/RMG/RMG-Py/rmgpy/qm/mopacTest.py", line 238, in test_load_thermo_data
    self.qmmol1.generate_thermo_data()
  File "/Users/anguohu/RMG/RMG-Py/rmgpy/qm/molecule.py", line 359, in generate_thermo_data
    self.qm_data = self.generate_qm_data()
  File "/Users/anguohu/RMG/RMG-Py/rmgpy/qm/mopac.py", line 298, in generate_qm_data
    if self.verify_output_file():
  File "/Users/anguohu/RMG/RMG-Py/rmgpy/qm/mopac.py", line 215, in verify_output_file
    qm_data = self.parse()
  File "/Users/anguohu/RMG/RMG-Py/rmgpy/qm/molecule.py", line 332, in parse
    parser = self.get_parser(self.output_file_path)
  File "/Users/anguohu/RMG/RMG-Py/rmgpy/qm/mopac.py", line 230, in get_parser
    return cclib.parser.Mopac(output_file)
AttributeError: module 'cclib.parser' has no attribute 'Mopac'

### Question
I did functional-test and database-test and they passed. I wonder that if there is only MOPAC error and I don't need to run the quantum calculation, will it error effect the RMG simulation a lot?

### Installation Information
Describe your installation method and system information if applicable.
 - OS (include version if known): macOS 10.15.2
 - Installation method: I totally follow this guideline http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html
 - RMG version information: 3.0.0
   
   - RMG-Py: 
   - RMG-database:

**Comment by amarkpayne** [comment]
This is related to a known issue #1864, which is still being worked on.

In the meantime, your are correct that this test failing won't affect your RMG runs at all (unless you are trying to use MOPAC or the QMTP interface to calculate thermo on-the-fly, in which case this feature is currently broken until we fix this issue).
