### ISSUE TITLE
Problem to import the chem.inp file 

### ISSUE THREAD

**Issue by arnab37** [ReactionMechanismGenerator/RMG-Py#1919]
Hi,

I am trying to import a chem.inp file in ChemKin Pro (v 19.2) and getting the following error message:
----------------------------------------------------------------------------
Import Error: These keywords are invalid for CKReactorGenericClosed:
  Cl
  S
  Si
  He
  Ar
  Ne
  N
  OI /18.000/
  O
  CI /13.003/
  C
  T /3.016/
  D /2.014/

  H
  ELEMENTS
-------------------------------------------------------------------------

I am not sure if it is the right way to insert the chem.inp file in ChemKin or not. For now, I am clicking on "Import" under the "Project" menu.

The chem.inp file starts like the following:

-------------------------------------------------------------------------
ELEMENTS
	H
	D /2.014/
	T /3.016/
	C
	CI /13.003/
	O
	OI /18.000/
	N
	Ne
	Ar
	He
	Si
	S
	Cl
END

SPECIES
    Ar              
    He              
    Ne              
    N2              
    ethane(1)       
    C3H7(2)    
------------------------------------------------------------------------

I also want to mention that for the calculations sulfur, silicon, chlorine and a few other elements are never used. Please let me know what to do.

Thanks,
Arnab Bose

**Comment by alongd** [comment]
If I understand correctly (from the `CKReactorGenericClosed` Error), it looks like you opening the Chemkin file as a Chemkin Project/Reactor, and not as a chemical set. Please consult the Chemkin manual for how to run Chemkin.
Briefly, you should create a new project and insert the desired reactor, then load the chemical model.
There's no problem with having additional elements defined in the Chemkin file that don't participate in the mechanism.
