### ISSUE TITLE
Database changes force /ipython/data/parse_source/chem.inp to be continually updated

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/RMG-Py#1941]
### Bug Description
See #1939 for more details. Whenever we significantly change RMG-database, the comments in the chemkin file need to be updated or else this uncertainty IPython notebook example will be broken. It is not ideal to continually update this file, so we should come up with a better solution. Possibilities include:

1. Only update this file every major release. Add a note in the IPython file that the user must checkout that version of RMG-database or regenerate the file themselves for everything to work.

2. Delete the chemkin files and instead provide a script that runs the RMG job to regenerate the chemkin file. We could even add checks in the notebook that would automatically do this for the user.

**Comment by hwpang** [comment]
I think 2. is a good idea and very doable. I can add that part in the notebook in this week.

**Comment by JacksonBurns** [comment]
This was resolved in #1944. Closing as completed.
