### ISSUE TITLE
I have some problems on 'Create the RMG Anaconda environment'

### ISSUE THREAD

**Issue by qyyparadox** [ReactionMechanismGenerator/RMG-Py#1970]
### Topic
General area which your question is related to.
 - [ 1] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

### Context
I want to Create the RMG Anaconda environment, but failed

### Question
code:
C:\RMG\RMG-Py-master>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - muq2

### Installation Information
Describe your installation method and system information if applicable.
 - OS (include version if known): (e.g. Windows 10, Ubuntu 18, macOS 10.13, etc.)
Windows 10
 - Installation method: (e.g. installation from binary or source, with or without anaconda)
installation from binary or source
 - RMG version information:
   
   - RMG-Py:
 RMG-Py
   - RMG-database:

**Comment by mjohnson541** [comment]
Sorry for the delay. As of version 2.1.9 we no longer support running RMG directly on Windows OS's. We provide installation instructions for using the linux subsystem for Windows 10 or using a linux VM here:  http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/index.html
