### ISSUE TITLE
Re-installation problem with make

### ISSUE THREAD

**Issue by PWstmrlnd** [ReactionMechanismGenerator/RMG-Py#1972]
_Performing a Linux installation of developers version after failed basic installation (following instructions with local IT services but found it kept rewriting version 2.7). Everything seemed to be going fine until I went for "make" -- see puzzling errors below. I closed and re-opened the terminal window and go the same thing.
[Configuration is macOS Catalina 10.15.4, MacBook Pro (15-inch, 2019), 2.4GHz 8-core Intel Core i9, 32GB 2400MHz DDR4]_

(base) CBE-LT-026:~ mcninch$ cd RMG-Py
(base) CBE-LT-026:RMG-Py mcninch$ conda env create -f environment.yml

CondaValueError: prefix already exists: /Users/mcninch/anaconda3/envs/rmg_env

(base) CBE-LT-026:RMG-Py mcninch$ conda activate rmg_env
(rmg_env) CBE-LT-026:RMG-Py mcninch$ make
  File "utilities.py", line 283
    print(f'{directory} not found. Unable to clean up build directory.')
                                                                      ^
SyntaxError: invalid syntax
make: *** [pycheck] Error 1
(rmg_env) CBE-LT-026:RMG-Py mcninch$

**Comment by mjohnson541** [comment]
I think you need to remove the old conda environment and recreate it. It looks like your old environment is python 2, which is incompatible with the current RMG master.

**Comment by amarkpayne** [comment]
Looking at this really quick, I think that this error is because python 2 is likely installed in rmg_env.

Creating the environment failed because there was an existing environment already, but you should be able to update the environment instead. Try `conda activate rmg_env; conda env update -f environment.yml`. Verify that python 3 is installed after you do this

**Comment by PWstmrlnd** [comment]
_Happily, running conda env update fixed it. Python 3 and RMG 3 seem to be running fine. 
However, now I'm getting a message that C atom is in one of the RMG reaction libraries (JetSurf 2.0) but is disallowed. Is the fix to add C in the input as a reactive species?_

[after multiple "Ill-conditioned matrix" warnings, finally]
/Users/mcninch/anaconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/thermo/thermoengine.py:97: LinAlgWarning: Ill-conditioned matrix (rcond=1.08953e-21): result may not be accurate.
  thermo = wilhoit.to_nasa(Tmin=100.0, Tmax=5000.0, Tint=1000.0)
Traceback (most recent call last):
  File "/Users/mcninch/anaconda3/envs/rmg_env/bin/rmg.py", line 111, in <module>
    main()
  File "/Users/mcninch/anaconda3/envs/rmg_env/bin/rmg.py", line 105, in main
    rmg.execute(**kwargs)
  File "/Users/mcninch/anaconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/rmg/main.py", line 651, in execute
    self.initialize(**kwargs)
  File "/Users/mcninch/anaconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/rmg/main.py", line 540, in initialize
    self.reaction_model.add_reaction_library_to_edge(library)
  File "/Users/mcninch/anaconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/rmg/model.py", line 1593, in add_reaction_library_to_edge
    "explicitly allow it.".format(spec.label, reaction_library.label))
rmgpy.exceptions.ForbiddenStructureException: Species constraints forbids species C from reaction library JetSurF2.0. Please reformulate constraints, remove the species, or explicitly allow it.

**Comment by mjohnson541** [comment]
It looks like one of the species in JetSurF2.0 is forbidden. If you don't already have a generatedSpeciesConstraints block you should probably add this:  

```
generatedSpeciesConstraints(
    # allows exceptions to the following restrictions
    allowed=['input species', 'seed mechanisms', 'reaction libraries'],)
```

otherwise just add `allowed=['input species', 'seed mechanisms', 'reaction libraries']` to the arguments.
