### ISSUE TITLE
RMG is unable to read thermodata for surface species

### ISSUE THREAD

**Issue by dronekill** [ReactionMechanismGenerator/RMG-Py#1976]
### Question
We are trying to generate a surface mechanism for the hydrocarbons by using our thermodata in the form of NASA polynomial. However, it seems that the RMG is not able to read the thermodata for that specie and giving an error message as "Unable to determine thermo parameters for "C=C[Pt]">: no data for node R* or any of its ancestors.." We have already added the thermo library with this molecule in it. The screenshot of the error is attached. We want to know the location of this thermodata group, which RMG is trying to access and determine the thermodata so that we can make necessary changes.

### Installation Information
 - OS Ubuntu 18
 - Installation method: source, with anaconda
 - RMG version information:
   - RMG-Py: 3.0.0
   - RMG-database: 3.0.0
![Screenshot from 2020-06-09 10-35-45](https://user-images.githubusercontent.com/51900085/84110869-4d062300-aa43-11ea-97b4-210357f13469.png)

**Comment by kblondal** [comment]
This looks like the error I got a while back, which I commented about in RMG-database [PR#385](https://github.com/ReactionMechanismGenerator/RMG-database/pull/385) on Feb 24th. In short, when corrections that prevented radical adsorbates from being formed were implemented (in this branch then but may have been moved now @mazeau ?), I didn‘t get that error anymore. That might also be the case here.

**Comment by dronekill** [comment]
I tried with all Vdw families switched off but still getting the same error.
