### ISSUE TITLE
Arkane HinderedRotor output has incorrect quantum parameter

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1988]
When arkane runs a job, it places the __repr__ of many objects in an `output.py` file. When outputing the `quantum` and `semiclassical` parameter, it states these values are `None` even when the actual object has them set to either True or False.

It seems like the error is in the Prettify methods within arkane.output. The unittest [`test_prettify`](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/arkane/outputTest.py#L102) in arkane.outputTest shows the error very clearly. The input string has `quantum=True, semiclassical=False`. The 'expected' output of the prettify method has `quantum=None, semiclassical=None`.

I do not believe this is the intended way the prettify function should run. When the modified values are put into the [__init__](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/statmech/torsion.pyx#L123) of HinderedRotor, quantum is set to None and semiclassical is set to True (which is different than the original object with quantum as True and semiclassical as False. 

Also, small side question: what does Arkane default to: semiclassical, quantum, or something else? Is there any way to change that in the Arkane input file? (I didn't see any described in documentation, but may have missed it)

**Comment by mjohnson541** [comment]
Arkane used to default to semiclassical and after changes I believe in the last year-year and a half now defaults to quantum. However, they agreed pretty well in all the cases I tested.
