### ISSUE TITLE
Forbidden specie C

### ISSUE THREAD

**Issue by shikharnigam8** [ReactionMechanismGenerator/RMG-Py#1991]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ yes] An error message 

### Context
A clear and concise description what you're trying to do.
I added a reaction library called La2O3 for generating two site mechanism. 
![issue](https://user-images.githubusercontent.com/68756555/88509690-7a2c7780-cf96-11ea-95a9-776e5fac0f0f.png)
![issue](https://user-images.githubusercontent.com/68756555/88509715-887a9380-cf96-11ea-8140-c5a90342774f.png)

### Question
Write your question here.
But when i am running it, showing me an error of "species constraints forbids specie C from reaction library La2O3 
### Installation Information
Describe your installation method and system information if applicable.
 - OS (include version if known): (e.g. Windows 10, Ubuntu 18, macOS 10.13, etc.)
 - Installation method: (e.g. installation from binary or source, with or without anaconda)
 - RMG version information:
   
   - RMG-Py: 
   - RMG-database:

**Comment by mjohnson541** [comment]
So in your input file there's a Species Constraints block for example:  
```
generatedSpeciesConstraints(
    allowed=['input species','seed mechanisms','reaction libraries'],
    maximumCarbonAtoms=10,
    maximumOxygenAtoms=2,
    maximumNitrogenAtoms=2,
    maximumSiliconAtoms=2,
    maximumSulfurAtoms=2,
    maximumHeavyAtoms=10,
    maximumRadicalElectrons=2,
    maximumSingletCarbenes=1,
    maximumCarbeneRadicals=0,
    maximumIsotopicAtoms=2,
    allowSingletO2 = False,
)
```

The Species "C" violates one of these constraints in your input file's block. This individual instance is easily solved by adding `allowed=['input species','seed mechanisms','reaction libraries'],` to the block, but you should check to make sure these constraints aren't going to prevent any important chemistry.
