### ISSUE TITLE
Need to updated bindingEnergies in catalysis example input files

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#1995]
The binding energies for the reference case in the database are currently hard-coded into the RMG source code, at 
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/data/thermo.py#L1352

These were quite recently "corrected" to slightly different values in
https://github.com/ReactionMechanismGenerator/RMG-Py/commit/7b5b6bdae4b66bdf5e5ab74fdd738ecab4bde462

so they are now different from the ones in the RMG example input files at 
https://github.com/ReactionMechanismGenerator/RMG-Py/tree/master/examples/rmg/catalysis

We should update the input files to match.

**Comment by kblondal** [comment]
I see, I'll update that. 
The methane steam reforming example is on Ni111, should I update those values as well to be consistent with https://github.com/ReactionMechanismGenerator/RMG-database/pull/387/commits/05ee78b278b54f40713d2f58c5b30cd692f5319?

**Comment by rwest** [comment]
Oh, good idea.

**Comment by rwest** [comment]
Closed by #1996
