### ISSUE TITLE
Starting model generation didnt return any model

### ISSUE THREAD

**Issue by Felipe-Kraus** [ReactionMechanismGenerator/RMG-Py#2002]
After model enlargement:
    The model core has 678 species and 3168 reactions
    The model edge has 0 species and 0 reactions

Initialization complete. Starting model generation.

Generating initial reactions...
For reaction generation 1 process is used.
Morto

What's Morto ? Anyone help!?

**Comment by alongd** [comment]
Hi, to try and help you, please upload additional useful information such as your input file, the output file, and (if running on a server) the stdout/stderr file(s) or (if running via a local terminal) any traceback print that might have been outputted.

**Comment by Felipe-Kraus** [comment]
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/5074230/input.txt)

**Comment by Felipe-Kraus** [comment]
![Captura de tela de 2020-08-18 14-21-30](https://user-images.githubusercontent.com/69648267/90545025-653ea080-e15e-11ea-9e6e-6ddceabea055.png)

**Comment by Felipe-Kraus** [comment]
![Captura de tela de 2020-08-19 08-04-27](https://user-images.githubusercontent.com/69648267/90627942-1bec6080-e1f3-11ea-82ee-304562617f06.png)

**Comment by mjohnson541** [comment]
So in your input file 
terminationConversion={
        'BC5H10': 0.0011765,
    }, 
Should be a conversion not a mole fraction, and maximumEdgeSpecies=10000 is a little bit on the low side I usually run with 100,000, you also shouldn't include CurranPentane as both a reaction library and a seed mechanism. I'm not sure how any of these would cause this, unless it's something weird about including CurranPentane in both categories, I'm not sure why "Morto" got printed, the preset mapping warning might be a symptom of something, but it certainly shouldn't cause this problem.
