### ISSUE TITLE
Generate resonance structures for bidentate adsorbates

### ISSUE THREAD

**Issue by cfgoldsmith** [ReactionMechanismGenerator/RMG-Py#2005]
Bidentate adsorbates (or adsorbates that occupy two sites), can have two or more equivalent Kekule structures. RMG currently does not know to look for them, which, in turns, limits their reactivity.

Consider a gas-phase species with a triple bond, `A#B` (where A, B = C or N). The corresponding bidentate adsorbate is:

```
A = B
|   |
X   X

1 A u0 p0 c0 {2,D} {3,S}
2 B u0 p0 c0 {1,D} {4,S}
3 X u0 p0 c0 {1,S}
4 X u0 p0 c0 {2,S}
```
This adsorbate is equivalent to:
```
A - B
||  ||
X   X

1 A u0 p0 c0 {2,S} {3,D}
2 B u0 p0 c0 {1,S} {4,D}
3 X u0 p0 c0 {1,D}
4 X u0 p0 c0 {2,D}
```

Note that this resonance form doesn't exist for all bidentate species. For example, the bidentate adsorbate corresponding to ethene does not.
```
H2C - CH2
  |   |
  X   X
```
It is only when the corresponding gas-phase precursor has a triple bond. 

We need to add these resonance structures to the Resonance Module (and, in general, how to apply Resonance checks to adsorbates, etc).

**Comment by rwest** [comment]
Food for thought: how should thermo be estimated for these different resonance structures?
At the moment we look for resonance structures of the gas phase precursor, pick the lowest of those as the most representative, and use that as the thermo for the gas phase species. Then estimate the adsorption of that molecule structure using the adsorption estimation trees. I think this might get a bit more complicated.

**Comment by cfgoldsmith** [comment]
In response to Richard's question: my thinking is that we first find the resonance structure that has the smallest bond order for the two adsorbate-site bonds, and then we apply the thermodynamic correction (as discussed in your pull request #2006).
