### ISSUE TITLE
Q2DTor not tracked in git or checked in makefile, can lead to unit test failures.

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#2008]
### Bug Description
A `make clean; make; make test` on a freshly updated master branch was failing the unit test suite, due to problems with Q2DTor (`rmgpy/statmech/ndTorsionsTest.py`).   I think it was basically out of date. The fix seemed to be deleting it entirely from `external/Q2DTor` and then running `make q2dtor` to reinstall it.  This was not obvious from any of the instructions or error messages.

Is there any way for this external dependency to be updated or checked as part of the make process, or tracked as a submodule in git, or something? So that the usual "pull, make, test" workflow works.  Or at least some clues in the error messages? like the "checking dependencies" part of the Makefile?

Perhaps that's not simple, in which case this issue page will at least serve as instructions for others with the same problem.

### Error messages
For the benefit of people googling their error messages hoping to find a solution, here are the error messages:

```
======================================================================
ERROR: test_q2dtor_setup (rmgpy.statmech.ndTorsionsTest.TestHinderedRotor2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/statmech/ndTorsionsTest.py", line 73, in test_q2dtor_setup
    self.hd2d.get_ics_file()
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/statmech/ndTorsions.py", line 339, in get_ics_file
    cwd=self.q2dtor_dir)
  File "/Users/rwest/opt/anaconda3/envs/rmg3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/Users/rwest/Code/Cat/RMG-Py/external/Q2DTor/src/Q2DTor.py', 'r0', '--init']' returned non-zero exit status 1.
```

```
(rmg3) Richards-iMac:RMG-Py rwest$ nosetests rmgpy/statmech/ndTorsionsTest.py
/Users/rwest/Code/Cat/RMG-Py/rmgpy/tools/plot.py:37: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  mpl.use('Agg', warn=False, force=False)
.  File "/Users/rwest/Code/Cat/RMG-Py/external/Q2DTor/src/Q2DTor.py", line 230
    print "        - ERROR: Unknown software (%s)\n"%software
                                                   ^
SyntaxError: invalid syntax
E.
```

### Expected Behavior
A usual workflow of "git pull; make clean; make; make test" would work. Or a failure would give instructions on how to reinstall an updated q2dtor.

### Installation Information
Describe your installation method and system information.
 - Mac OS X Catalina 10.15.6
 - Installation method: from source with anaconda. Recently re-built anaconda environment, but pre-existing RMG-Py repository (frequently updated, but apparently with stale untracked files in /external/) 
 - RMG version information:
   - RMG-Py: 3.0.0-254-gbd01afeb2
   - RMG-database: 3.0.0-73-ge68fce4d4

**Comment by mjohnson541** [comment]
That's particularly strange because the Q2DTor we use is a specific branch I made that has never been modified since.

**Comment by rwest** [comment]
I'm not sure where/when my old copy came from, but the error message reports 
```python
File "/Users/rwest/Code/Cat/RMG-Py/external/Q2DTor/src/Q2DTor.py", line 230
    print "        - ERROR: Unknown software (%s)\n"%software
```
which is in Python 2.  The current one has an equivalent, in Python 3,  6 lines later:
```python
File "/Users/rwest/Code/Cat/RMG-Py/external/Q2DTor/src/Q2DTor.py", line 236
       print("        - ERROR: Unknown software (%s)\n"%software)
```
Perhaps it's incredibly unlikely anyone else will end up in this situation.

**Comment by mjohnson541** [comment]
Oh...I'm totally wrong...I made a new branch for py3. That's why this is happening.

**Comment by mjohnson541** [comment]
So I don't imagine it getting modified in the near future, but this should be a problem for anyone updating from py2 to py3 without deleting RMG-Py entirely. I think a check could be added to "checking dependencies". We could add something to change the branch to arkanepy3 during the make process if it is installed, but isn't that.
