### ISSUE TITLE
Mopac .out file missing from temp directory

### ISSUE THREAD

**Issue by aiscarruthers** [ReactionMechanismGenerator/RMG-Py#2023]
### Context
I'm trying to get use the QM functionality and I'm recieving this error message after a few other traceback lines:

File "/anaconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/qm/mopac.py", line 146, in run
    shutil.copy(tempOutFile, self.output_file_path)
  File "/anaconda3/envs/rmg_env/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/anaconda3/envs/rmg_env/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpk6hoa3b1/ICJNOTNMGFCUFQ-UHFFFAOYSA-N.out'

What's confusing about this to me is that MOPAC2016.exe is not throwing any error message and neither is the "stdout, stderr =  process.comunicate(input=comand)" line but for some reason, the .out file is not being created (or is somehow being deleted?). I did a search through all of my directories to see if maybe the .out file was being placed in some other directory but this isn't the case. 

### Question
Is there something I can do to fix this on my installation? I was reluctant to report this as a bug because I wasn't sure if I had installed something incorrectly. 

### Installation Information
Describe your installation method and system information if applicable.
 - Ubuntu subsystem on windows 10
 - Binary installation wt anaconda
 - RMG version information:
   - RMG v 3.0.0
   - RMG-database v 3.0.0

**Comment by mjohnson541** [comment]
You're running RMG v3.0.0 with RMG-database v1.0.2?  I would've thought they'd be incompatible. Can you try running RMG v3.0.0 with RMG-database v3.0.0?

**Comment by aiscarruthers** [comment]
Sorry, yes this was an error, I've since checked and they are both v3.0.0 I'll change the original question.

**Comment by ajocher** [comment]
Did you run into this error in the first run in a fresh directory, or did you rerun in the same directory? Can you try running the same case in a fresh directory?

**Comment by aiscarruthers** [comment]
Previously I was trying to run a custom case but have since tried using the Hexadiene example and the error is the same but for a different species. This error appears on both fresh attempts in new directories and reruns.

**Comment by JacksonBurns** [comment]
This installation method is no longer supported and the latest versions of MOPAC (#2417) do not have this issue. Closing as stale.
