### ISSUE TITLE
Creating a Combustion Model for N-Dodecane.

### ISSUE THREAD

**Issue by rahulkaruvingal** [ReactionMechanismGenerator/RMG-Py#2027]
### Topic
General area which your question is related to.
 
 - [ ] Running an RMG job

### Context
A clear and concise description what you're trying to do.

My aim is to generate the mechanism file for different fuels. As of now I am trying a combustion model for n-dodecane for 900k and 60bar . I am new to rmg. As much as I could understand from the documentation I tried to create an input file for the same. I have attached the screen shot of the input file 

![rmg](https://user-images.githubusercontent.com/59342705/93901123-7ac35f00-fcf6-11ea-91b8-4a2d2051f3bd.JPG)
![rmg2](https://user-images.githubusercontent.com/59342705/93901130-7b5bf580-fcf6-11ea-9a26-a815f984e27e.JPG)

### Question
1. I don't get CO2 as a species after the reaction is ended in the mechanism file. Is my input file right?
2. It takes a long time for the reaction to go on. How to reduce the time?
3. Can I get the ignition delay using rmg ? If yes then where can I find the documentation for that?

### Installation Information
Describe your installation method and system information if applicable.
 - OS (include version if known): (e.g. Windows 10, Ubuntu 18, macOS 10.13, etc.)
linux Centos
 - Installation method: (e.g. installation from binary or source, with or without anaconda)
with anaconda
 - RMG version information:
I use the latest version
   
   - RMG-Py: 
   - RMG-database:

**Comment by mjohnson541** [comment]
Your value for maximumEdgeSpecies=1000 is very low and most likely causing you to miss CO2 and other important stuff (unless it's a thermochemistry issue) I typically use maximumEdgeSpecies=100,000. 

Dodecane is a large molecule and the number of possible reactions for molecules in general scale combinatorically with the number of reaction sites so in general it's going to take RMG much longer than something smaller. Running in parallel on 4 or more cores will often speed you up by a factor of 2 or 3. Also if you give RMG more of the chemistry you expect to start with it (through reaction libraries or species) it tends to save it a lot of time exploring unimportant chemistries. 

RMG's internal simulation software isn't capable of running ignition simulations. Chemkin and Cantera are popular options.

**Comment by rahulkaruvingal** [comment]
Thank you very much for the reply. It works now but it takes very long. I can use the cluster systems to run it parallel. Do you have an example of how to run it in parallel? I do not know the command for running rmg in parallel. Could you please help me with that?

**Comment by mjohnson541** [comment]
See here in the documentation: http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/running.html#input-flags
