### ISSUE TITLE
Testing RMG after installing yields "No PyDAS solver installed" error

### ISSUE THREAD

**Issue by NTHames** [ReactionMechanismGenerator/RMG-Py#2029]
I am new to RMG and am receiving an error saying "No PyDAS solvers" are found on my test runs and my advising professor and I are unsure how to progress 

Where do I go to install PyDAS solvers/should I reinstall RMG?

My installation method and system information:
 Ubuntu 20.04.1 LTS shell on a Windows 10 computer
 Installed through source using Anaconda 3.7
 RMG version 3.0.0-290-g3c13a22bc

Just for completion, the output is:
> python setup.py build_ext main --inplace --build-temp .
> running build_ext
> 
> Checking for solvers before compiling...
> 
> No PyDAS solvers found. Please check that you have the latest version of PyDAS or that you have activated the appropriate conda environment.
> 
> Cannot compile RMG solver without PyDAS.
> make: *** [Makefile:18: solver] Error 1

**Comment by amarkpayne** [comment]
Hi @NTHames ! Just to confirm, did you activate the conda environment before running this? Try `conda activate rmg_env` followed by `make`

**Comment by amarkpayne** [comment]
If this does not work though, you can install pydas by first activating your conda environment (`conda activate rmg_env`) and then installing with `conda install -c rmg pydas `.

**Comment by NTHames** [comment]
> Hi @NTHames ! Just to confirm, did you activate the conda environment before running this? Try `conda activate rmg_env` followed by `make`

That worked! Thanks
