### ISSUE TITLE
Testing RMG Files after Installation yields "module Arkane.py" and "module rmg.py" was never imported errors

### ISSUE THREAD

**Issue by NTHames** [ReactionMechanismGenerator/RMG-Py#2031]
I am an undergraduate PChem research student and am unfamiliar with RMG and Linux in general.
After installing RMG through source, I ran the "make eg1" and "make eg2" commands and both of them resulted in the error "Coverage.py warning: Module Arkane.py was never imported. (module-not-imported)" and "Coverage.py warning:Module rmg.py was never imported. (module-not-imported)" preceded by a DependencyError saying I need the program MOPAC.

How do I import Arkane.py and rmg.py? Would they both be imported if I installed MOPAC or is that something separate?

I am running on Ubuntu 20.04, installed by source, RMG version 3.0.0-290-g3c13a22bc

This is the full message:

> raise DependencyError('\n'.join(stderr.split('\n')[0:9]))
> rmgpy.exceptions.DependencyError: 
> 
>            MOPAC is a semiempirical quantum chemistry program
> 
>            To install the MOPAC license, use the command
>            'MOPAC2016.exe <license-key>'
>            e.g., 'MOPAC2016.exe 1234567a1234567'
> 
>           For more information, see: HTTP://OpenMOPAC.net/Manual/running_MOPAC.html
> Coverage.py warning: Module Arkane.py was never imported. (module-not-imported)
> Coverage.py warning: Module rmg.py was never imported. (module-not-imported)
> make: *** [Makefile:105: eg2] Error 1
>

**Comment by mjohnson541** [comment]
Cases that come to mind: 
1) This is an environmental variable error in terminal in any directory that isn't RMG-Py try
```
conda activate rmg_env
python -c "import rmgpy"
```
Where does it error first if at all?

2) This is related to compilation
go to the RMG-Py folder and run: 
```
conda activate rmg_env
make clean
make 
make test
make eg1
```

where does it error first if at all?

**Comment by NTHames** [comment]
I'm not sure which one of these did it, but I ran both and it worked! Thank you so much!

**Comment by NTHames** [comment]
Okay, I came back todayand it does not seem to be working any more.
When I went to run one of the example files in /RMG-Py/examples/arkane since I plan on using arkane for my research
I used the command `$ python Arkane.py INPUTFILE` in the in directory that the input file was in and this was the output:
> python: can't open file 'Arkane.py': [Errno 2] No such file or directory

I did what you said again, then when I ran the 'make test' command I realized that I needed to scroll up to see the error messages. Please excuse my inexperience.
There were several times that this popped up:
> ERROR: root: Unable to generate identifier for this molecule:

Whenever there was (what I assume is) a matrix that represents a molecule and its bonding info
I believe the issue is because I added the RMG-Py directory to the PYTHONPATH and PATH incorrectly, do you have any suggestions?

I ran the `export PYTHONPATH:=YourFolder/RMG-Py/:$PYTHONPATH` (replacing the YourFolder with the pathway) with rmg_env active and in the RMG-Py folder

**Comment by amarkpayne** [comment]
Hi @NTHames ! Just to make sure, is the extra colon right after `export PYTHONPATH` a typo? The correct expression should be `export PYTHONPATH=YourFolder/RMG-Py/:$PYTHONPATH`

**Comment by NTHames** [comment]
Yes, it was, thanks for pointing that out! I'll edit the post to fix that

**Comment by amarkpayne** [comment]
Oh, also an important distinction: PYTHONPATH only controls what you can access (import) from within python itself. For example, it allows statements like `import rmgpy` or `import arkane` to work from within python. However, PATH is the environment variable responsible for finding file locations from the command prompt. If you add `export PATH=YourFolder/RMG-Py/:$PATH` then the following statement will work from the Linux commandline: `Arkane.py INPUTFILE`. Note that you don't need to call python before calling Arkane.py, as the header in this file has a shebang directing the OS to call python. In fact calling python may or may not cause problems in finding the file Arkane.py, I am not sure off of the top of my head.

Once you update this in your bashrc, remember to either resource your bashrc or close and open up a new terminal

**Comment by NTHames** [comment]
I have done the `export Path=.../:$PATH` then closed/opened my terminal as you said, but it is still coming up with "Arkane.py: command not found"

**Comment by amarkpayne** [comment]
What happens if you try to call the file directly using its full path? `/path/to/your/folder/RMG-Py/Arkane.py INPUTFILE` ?

**Comment by NTHames** [comment]
That worked! I had to use a different path, the one I was using before was /anaconda3/RMG/RMG-Py/ and the one that worked I added home/User to the start. I assume that I will need to do this to my PYTHONPATH and PATH pathways to fix it?

This is such a relieve, thanks Mark!

**Comment by amarkpayne** [comment]
Yes, if I understand what you are telling me the you are correct, using the same path that worked from the terminal is what you need in your .bashrc file. Let me know how it goes!

**Comment by NTHames** [comment]
I did the whole `export PATH` and `export PYTHONPATH` thing, and when I ran `Arkane.py input.py` it worked!
Then I went to a different folder, opened that in terminal, activated the environment, and `Arkane.py input.py` did not work. Not sure how that happens

**Comment by amarkpayne** [comment]
Just to be clear, when you day you did `export PATH`, was this adding this to your .bashrc file or was this executing this command from the terminal?

**Comment by NTHames** [comment]
I was executing in my terminal, I didn't know that I had to add to my .bashrc file. How do I do that?

**Comment by amarkpayne** [comment]
That'll do it then, otherwise you'll have to execute those export statement every time you open a new terminal. Your .bashrc file gets executed every time you open a terminal, so that is why adding these statements here works. To add them to your .bashrc file, do the following:

1. Open a terminal and execute `cd` (this changes the directory to your home directory in case you weren't there already)
2. Start editing your file by launching a command line based text editor: `nano .bashrc`
3. Scroll to the bottom of the file and add the two export statements for PATH and PYTHONPATH
4. When you are ready to save the file press 'ctrl+x'. Press 'y' when prompted to confirm that you want to save your changes (as opposed to discarding them).
5. After saving the file, you should be returned to the normal command line. For the changes to take effect, you'll need to exit out and open a new terminal

6. (Optional) You can verify that this all worked by executing `echo $PYTHONPATH` and verify that your RMG folder is there

**Comment by NTHames** [comment]
That worked!
You're the best!
