### ISSUE TITLE
Weird error halts calculation: "species [C-]=[O+]Oc1ccccc1"

### ISSUE THREAD

**Issue by PWstmrlnd** [ReactionMechanismGenerator/RMG-Py#2032]
Job crashed with an error I haven't see before:
**rmgpy.exceptions.ResonanceError: Could not determine representative localized structures for species [C-]=[O+]Oc1ccccc1**
I've attached the log file with its middle snipped out to get down to 10 MB and the error tracing attached at the end: 
[RMG.log](https://github.com/ReactionMechanismGenerator/RMG-Py/files/5397077/RMG.log)

If it isn't a bug appearance, how can I avoid it?

**Comment by mjohnson541** [comment]
Looks like a react or resonance bug. Hard to diagnose without knowing the exact reactants and family. Probably need to add a couple logging.error statements in the rmgpy/data/family.py generate_reactions function to identify those during the run.
