### ISSUE TITLE
Should continuously test example input files

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#2040]
### Motivation or Problem
As revealed in https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2033, the example input files that are bundled with RMG are not all tested in our automated unit-, functional-, or regression-test suites, and can cease to work without being detected. 

### Desired Solution
We should test that they at least all load and start without crashing; perhaps complete a single iteration. Or run for a set number of minutes before being terminated.

### Potential Alternatives
Could be a separate test suite, like rmg-tests, or could be just part of the travis tests for this repo.

### Possible extensions
Testing any examples or snippets that are in the documentation would be nice too! But perhaps too hard.

**Comment by JacksonBurns** [comment]
This is a good idea - adding to long-term board, since it's not critical.
