### ISSUE TITLE
When is Conda Repo updated?

### ISSUE THREAD

**Issue by hanchak** [ReactionMechanismGenerator/RMG-Py#2042]
Hello,

Installing RMG onto Ubuntu yielded the mpl.use(warn=False) error.  This issue was fixed on Github.  However, the Conda repo channel RMG has not been updated yet.

Question: When is the next planned update of the Conda repo?

Thanks,
Mike

**Comment by mjohnson541** [comment]
We just released v3.1.0 today which should not have the mpl.use(warn=False) error anymore.
