### ISSUE TITLE
unsupported format string passed to rmgpy.species.Species.__format__

### ISSUE THREAD

**Issue by hanchak** [ReactionMechanismGenerator/RMG-Py#2043]
Running a Decalin decomposition reaction...Anaconda Python 3 and newest RMG from Conda on Ubuntu VM.

Came across this error at 54 minutes in:

-------------------------------------------------------------------------------------------------------------

After model enlargement:
    The model core has 46 species and 217 reactions
    The model edge has 4576 species and 26244 reactions

Saving current model core to Chemkin file...
Chemkin file contains 217 reactions.
Saving annotated version of Chemkin file...
Chemkin file contains 217 reactions.
Saving current model core to HTML file...
Updating RMG execution statistics...
    Execution time (DD:HH:MM:SS): 00:00:54:08
    Memory used: 1679.37 MB
Generating plots of execution statistics...
Attempting to prune...
Pruning 3788 species whose rate ratios against characteristic rate did not exceed the minimum threshold of 0.05

Traceback (most recent call last):
  File "/home/thor/anaconda3/envs/rmg_env/bin/rmg.py", line 111, in <module>
    main()
  File "/home/thor/anaconda3/envs/rmg_env/bin/rmg.py", line 105, in main
    rmg.execute(**kwargs)
  File "/home/thor/anaconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/rmg/main.py", line 925, in execute
    model_settings.min_species_exist_iterations_for_prune)
  File "/home/thor/anaconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/rmg/model.py", line 1257, in prune
    logging.info('Pruning species {0:<56}'.format(spec))
TypeError: unsupported format string passed to rmgpy.species.Species.__format__

------------------------------------------------------------------------------------------------------------------------

I checked the Github code and the same format specifier exists as the conda version. Any ideas?

Thanks,
Mike

**Comment by rwest** [comment]
Thanks for reporting this, Mike. Hopefully #2044 fixes it.

**Comment by hanchak** [comment]
Thank you for the quick reply.  On my end, I removed the ":<56" format specifier. 

Best regards, Mike
