### ISSUE TITLE
MOPAC load problem in RMG

### ISSUE THREAD

**Issue by NUSCondy** [ReactionMechanismGenerator/RMG-Py#2049]
Sir,  I have applied for the licence for the Mopac module and it's tested to be okay. I have set the environment variables but it seems there are still problems raised by RMG.

**Comment by rwest** [comment]
Could you give more details? describe the problem? Please be as detailed as possible.

**Comment by NUSCondy** [comment]
Dear Richard,

Thank you for your reply!

To make sure mopac is installed, I run a mopac example and it shows that mopac is already installed.

[cid:19e14dc8-a1df-487f-843d-c9b5b2148b53]
However, when I try to run an RMG job with mopac, it seems that mopac could not be loaded.
[cid:cea23b78-5e2e-4d58-a40b-b6b0826c2dc6]
Looking forward to your reply!

Best Regards,
Qiren
Department of Mechanical Engineering,  FoE, NUS
________________________________
发件人: Richard West <notifications@github.com>
发送时间: 2021年1月12日 12:13
收件人: ReactionMechanismGenerator/RMG-Py <RMG-Py@noreply.github.com>
抄送: Zhu Qiren <qirenzhu@u.nus.edu>; Author <author@noreply.github.com>
主题: Re: [ReactionMechanismGenerator/RMG-Py] MOPAC load problem in RMG (#2049)

        - External Email -



Could you give more details? describe the problem? Please be as detailed as possible.

―

**Comment by NUSCondy** [comment]
Dear Richard,

Sorry about that. Below shows the mopac run:
          (rmg_env) e2s2@e2s2-Super-Server:/opt/mopac$ mopac Exampledataset.mop

                   MOPAC Job: "Exampledataset.mop" ended normally on Jan 12, 2021, at 12:16.

And the RMG job error report is:
Warning: Generate Output HTML option was turned on. Note that this will slow down model generation.
Warning: Edge species saving was turned on. This will slow down model generation for large simulations.
Setting the quantum mechanics scratchDirectory to /home/e2s2/Documents/Xuneng/QMscratch/pm6

Loading thermodynamics library from GRI-Mech3.0.py in /home/e2s2/RMG-database/input/thermo/libraries...
Loading thermodynamics library from primaryThermoLibrary.py in /home/e2s2/RMG-database/input/thermo/libraries...
Loading thermodynamics group database from /home/e2s2/RMG-database/input/thermo/groups...
Loading transport library from NOx2018.py in /home/e2s2/RMG-database/input/transport/libraries...
Loading transport library from OneDMinN2.py in /home/e2s2/RMG-database/input/transport/libraries...
Loading transport library from GRI-Mech.py in /home/e2s2/RMG-database/input/transport/libraries...
Loading transport library from PrimaryTransportLibrary.py in /home/e2s2/RMG-database/input/transport/libraries...
Loading transport group database from /home/e2s2/RMG-database/input/transport/groups...
Loading kinetics library GRI-Mech3.0 from /home/e2s2/RMG-database/input/kinetics/libraries/GRI-Mech3.0/reactions.py...
Loading kinetics library combustion_core/version5 from /home/e2s2/RMG-database/input/kinetics/libraries/combustion_core/version5/reactions.py...
Loading frequencies group database from /home/e2s2/RMG-database/input/statmech/groups...
Loading Platts additivity group database from /home/e2s2/RMG-database/input/solvation/groups...
Adding rate rules from training set in kinetics families...
Trying MopacMolPM6 attempt 1 of 10 on molecule C=C=CC1C=CC=CC1=C.
Traceback (most recent call last):
  File "/home/e2s2/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/home/e2s2/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/e2s2/RMG-Py/rmgpy/rmg/main.py", line 672, in execute
    self.initialize(**kwargs)
  File "/home/e2s2/RMG-Py/rmgpy/rmg/main.py", line 495, in initialize
    self.load_database()
  File "/home/e2s2/RMG-Py/rmgpy/rmg/main.py", line 419, in load_database
    family.add_rules_from_training(thermo_database=self.database.thermo)
  File "/home/e2s2/RMG-Py/rmgpy/data/kinetics/family.py", line 1222, in add_rules_from_training
    reactant.thermo = thermo_database.get_thermo_data(reactant, training_set=True)
  File "/home/e2s2/RMG-Py/rmgpy/data/thermo.py", line 1289, in get_thermo_data
    thermo0 = quantum_mechanics.get_thermo_data(original_molecule)  # returns None if it fails
  File "/home/e2s2/RMG-Py/rmgpy/qm/main.py", line 216, in get_thermo_data
    thermo0 = qm_molecule_calculator.generate_thermo_data()
  File "/home/e2s2/RMG-Py/rmgpy/qm/molecule.py", line 359, in generate_thermo_data
    self.qm_data = self.generate_qm_data()
  File "/home/e2s2/RMG-Py/rmgpy/qm/mopac.py", line 309, in generate_qm_data
    success = self.run()
  File "/home/e2s2/RMG-Py/rmgpy/qm/mopac.py", line 129, in run
    self.test_ready()
  File "/home/e2s2/RMG-Py/rmgpy/qm/mopac.py", line 123, in test_ready
    raise DependencyError('\n'.join(stderr.split('\n')[0:9]))
rmgpy.exceptions.DependencyError:

           MOPAC is a semiempirical quantum chemistry program

           To install the MOPAC license, use the command
           'MOPAC2016.exe <license-key>'
           e.g., 'MOPAC2016.exe 1234567a1234567'

          For more information, see: HTTP://OpenMOPAC.net/Manual/running_MOPAC.html

**Comment by rwest** [comment]
When you succesfully tested mopac you were in `/opt/mopac` so it probably ran the version of mopac that you have there. When you ran RMG it probably tried to use one in your `rmg_env` anaconda environment, like `..../anaconda3/envs/rmg_env/bin/mopac`, which perhaps hasn't had the license installed yet.

If you delete the one in the conda environment it should discover the one in /opt/mopac (I think it is designed to check there, after checking your `$MOPAC_DIR`).  Or you could install the license in the one in your conda environment. (from where you run your RMG job, *not* `/opt/mopac`, try running `which mopac` to see where it is)

**Comment by NUSCondy** [comment]
Dear Richard,

Thank you so much for your explanation. Just as you said, there already exists a mopac in the rmg_env, which is ~/anaconda3/envs/rmg_env/opt/mopac/MOPAC2016.exe. So the file .bashrc file should be changed to use this one.

While for the miniconda3, it's a little bit complicated. There is a file named mopac in miniconda3/envs/rmg_env/bin/, which is used to specify the executable file's location, and the executable file is in ~/miniconda3/pkgs/mopac-2017-1/opt/mopac/MOPAC2016.exe. I specify the location of the executable file in the mopac then solve the problem.

Thank you again for your help!
