### ISSUE TITLE
Suggestion to delete a debug line in `chemkin.pyx`

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#2050]
[This line](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/7e7879b7fb9c46a406bc8feccc1c9a33bce16add/rmgpy/chemkin.pyx#L1119) is being printed too many times and out of context while debugging tests. See below. I suggest to remove it, unless there are objections.

![image](https://user-images.githubusercontent.com/16158262/102509344-1ca4de80-408f-11eb-9350-38f998651fb9.png)

**Comment by rwest** [comment]
While at it, a `try:` / `catch KeyError:` block instead of the `if` / `else` block would avoid checking the dictionary twice. (Currently it checks the dictionary once to see if it's there, then checks it again to get it).

**Comment by JacksonBurns** [comment]
Removing abandoned and stale labels since this was resolved successfully in #2102
