### ISSUE TITLE
Pre-exponential coefficients in surface reaction families

### ISSUE THREAD

**Issue by bjkreitz** [ReactionMechanismGenerator/RMG-Py#2051]
### Motivation or Problem

The typical pre-exponential coefficient in the surface reaction families is 1e21 cm2/mol/s, which comes from 1e13 1/s (transition state theory) divided by 1e-8 mol/cm2 (as a guess for the surface site density). However, the surface site density changes with metal and facet. As an example, the actual surface site density for a Ni111 facet is around 3e-9 mol/cm2. Thus, the pre-exponential coefficients would be around 3e21 cm2/mol/s, which is higher by a factor of 3. This is also consistent with transition state calculations. 

### Desired Solution

A better estimate of the pre-exponential coefficient is provided if we divide 1e13 1/s  by the actual site density of the investigated metal facet. The surface site density is already provided in the input.py file. RMG should use this value from the input file to calculate the pre-exponential coefficients and the default estimate in the surface reaction families should be 1e13 1/s.

**Comment by rwest** [comment]
I think this could be expanded in scope, so it's not just that default value, but perhaps all pre-exponential factors get scaled by the surface site density when scaling to different metals?

**Comment by rwest** [comment]
I think this would be akin to representing the reaction rates internally on a "per site" basis rather than a "per surface area" basis, which is something we keep discussing.
