### ISSUE TITLE
adjacencyList for perchlorates

### ISSUE THREAD

**Issue by jskrainka** [ReactionMechanismGenerator/RMG-Py#2052]
adjacency lists:

Hi all,

I hope this is an okay platform to discuss this issue. I'm attempting to estimate the kinetics of common aqueous ion dissociation using the liquid reactor models. I'm happy with the results for sulfuric acid and trichloroisocyanuric acid, but when I try to model perchloric acid I receive: 
`rmgpy.exceptions.AtomTypeError: Unable to determine atom type for atom Cl, which has 1 single bonds, 3 double bonds (3 to O, 0 to S, 0 others), 0 triple bonds, 0 quadruple bonds, 0 benzene bonds, 0 lone pairs, and +0 charge.`

Here is my adjacencyList:
species(                 
    label='HClO4',         
    reactive=True,       
    structure=adjacencyList("""
    1 Cl u0 p0 c0  {2,D} {3,D} {4,D} {5,S}
    2 O  u0 p2 c0  {1,D}
    3 O  u0 p2 c0  {1,D}
    4 O  u0 p2 c0  {1,D}
    5 O  u0 p2 c0  {1,S} {6,S}
    6 H  u0 p0 c0  {5,S}
    """)
) 
I've triple-checked each atom's valence shells are satisfied, but I could've missed something. Shouldn't this default to AtomType['Val7'] for Cl? Do i need to provide more context for the program or for you all?

### Installation Information
Describe your installation method and system information if applicable.
 - macOS Catalina 10.15.4
 - conda source forge install
 - RMG up-to-date and I haven't messed with any of the source code

**Comment by jskrainka** [comment]
Could it be that I need to indicate resonance somehow?

**Comment by alongd** [comment]
Hi, I don't think it's a resonance issue, I believe we only have chlorine atoms types implemented as `Cl1s`, meaning that RMG will only allow it to have zero or one single bonds. We currently don't support hyper-valent chlorine. To allow it, you'll need to modify the atomType file under `rmgpy/molecule` folder. This should be done carefully of course (there are several places in this file which will require editing). Feel free to make the modification and open a pull request, or consult the developers with a feature request.

**Comment by jskrainka** [comment]
Thank you for your response! That makes sense. I'll try to put up a pull request for this feature when I get the time :)
