### ISSUE TITLE
Currently not working when DASPK is not available

### ISSUE THREAD

**Issue by mark-pfeifle** [ReactionMechanismGenerator/RMG-Py#2070]
There is currently a bug in rmgpy/solver/base.pyx: 

"    from pydas.daspk import DASSLError as DASxError"

in one of the first code lines. This should read 

"    from pydas.dassl import DASSLError as DASxError"

Otherwise, if daspk is not available, the program will still try to access pydas.daspk. 
This applies to the latest commit on master as of Feb 11 2021.

Best regards, 
Mark

**Comment by mark-pfeifle** [comment]
I've been automatically notified that this is a stale issue now. As far as I can see, the bug is still present in the code.

**Comment by JacksonBurns** [comment]
Hi @mark-pfeifle thanks for the followup! I am going to add the bug label to this so that it won't be bothered by the bot, and we will try and get toward resolving this.

**Comment by Julian-Ufert** [comment]
I changed the respective code line. Please pull the changes into the upstream.
