### ISSUE TITLE
"undefined symbol: _intel_fast_memcpy" error on "make test"

### ISSUE THREAD

**Issue by mefuller** [ReactionMechanismGenerator/RMG-Py#2092]
### Bug Description
`make test` fails (81 errors on 95 tests) while installing RMG-Py
Common theme seems to be the error `undefined symbol: _intel_fast_memcpy` showing up hundreds of times

### How To Reproduce
Followed steps on https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html up to `make test`

### Expected Behavior
Tests pass

### Installation Information
Describe your installation method and system information.
 - System: [RWTH Aachen computing cluster](https://help.itc.rwth-aachen.de/service/rhr4fjjutttf), CentOS or RHEL 7: kernel 3.10.0-1160.15.2.el7.x86_64
 - Installation method: Installation by Source Using Anaconda Environment
 - RMG version information:
   
   - RMG-Py: 3.0.0-398-g5a65011 (source)
   - RMG-database: 3.0.0-138-g53e0ee8

### Additional Information
Terminal output is attached
[maketest.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/6176467/maketest.txt)

Some quick searching makes me think this has to do with Intel vs GCC

**Comment by mjohnson541** [comment]
This looks related to the GNU compiler, but I have no experience with CentOS. If I'm remembering correct I think some people in the past had success running RMG on CentOS using Docker:  https://hub.docker.com/r/mliu49/rmg.
