### ISSUE TITLE
RMG generating a reaction with inconsistent units of Kinetic Parameter

### ISSUE THREAD

**Issue by shikharnigam8** [ReactionMechanismGenerator/RMG-Py#2100]
### Bug Description
I am generating a reaction mechanism for a higher carbon atom compound (C6).
Each time I run the RMG,  the simulation is terminating due to an Assertion Error. I noticed that this error is due to the inconsistent unit of the kinetic parameter. The simulation generates a unimolecular reaction during the process (see the message below). However, the unit of A parameter is that of the Bimolecular reaction. I am sure that this reaction is caused by the RMG and not given as part of the training reactions. As a result, the RMG is not able to generate the Chemkin file.
I checked all the training reactions of the libraries/families used in the simulation, and I found all of them have the correct unit. Could you please help me to fix this error.

### How To Reproduce
I am attaching the error msg in the additional context section. 

### Expected Behavior
The simulation should terminate without any Assertion Error as all the database is error free.

### Installation Information
Describe your installation method and system information.
 - OS:  Windows 10 with Ubuntu 18.04 LTS (Linux subsystem)
 - Installation method: Source with anaconda
 - RMG version information:
   
   - RMG-Py:  Latest version
   - RMG-database: Latest database

### Additional Context
Traceback (most recent call last):
  File "/home/vijay.che.iitbhu/RMG-Py/rmg.py", line 111, in <module>
    main()
  File "/home/vijay.che.iitbhu/RMG-Py/rmg.py", line 105, in main
    rmg.execute(**kwargs)
  File "/home/vijay.che.iitbhu/RMG-Py/rmgpy/rmg/main.py", line 728, in execute
    self.save_everything()
  File "/home/vijay.che.iitbhu/RMG-Py/rmgpy/rmg/main.py", line 1751, in save_everything
    self.notify()
  File "/home/vijay.che.iitbhu/RMG-Py/rmgpy/util.py", line 113, in notify
    observer.update(self)
  File "rmgpy/chemkin.pyx", line 2383, in rmgpy.chemkin.ChemkinWriter.update
  File "rmgpy/chemkin.pyx", line 2279, in rmgpy.chemkin.save_chemkin_files
  File "rmgpy/chemkin.pyx", line 2255, in rmgpy.chemkin.save_chemkin
  File "rmgpy/chemkin.pyx", line 2096, in rmgpy.chemkin.save_chemkin_file
  File "rmgpy/chemkin.pyx", line 1769, in rmgpy.chemkin.write_kinetics_entry
AssertionError: 
              Gas phase reaction 
C4H5(5)=h(9)+c4h4(13)                               
              with kinetics 
Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(50.7053,'kcal/mol'), T0=(1,'K'), comment="""
Ea raised from 205.0 to 212.2 kJ/mol to match endothermicity of reaction.""")
              with 1 reactants was expected to have
              kinetics.A.get_conversion_factor_from_si_to_cm_mol_s() = 1.0
              but instead it is 1000000.0

**Comment by mjohnson541** [comment]
From what I can see here this looks like a units issue in one of the libraries being used. What reaction libraries/seed mechanisms are you using?

**Comment by rwest** [comment]
...and can you confirm the structures of the species involved? (`C4H5(5)=h(9)+c4h4(13)`)

Running the model again with `verboseComments=True,`  in the `options()` block may help indicate which library it came from.

**Comment by shikharnigam8** [comment]
> From what I can see here this looks like a units issue in one of the libraries being used. What reaction libraries/seed mechanisms are you using?

@mjohnson541 Thanks Matt sir for replying. I would like to inform you that all the libraries/seed mechanisms are error free. None of the library is having the reaction with inconsistent unit.

**Comment by mjohnson541** [comment]
Okay, in that case we definitely need to know the molecular structures.

**Comment by shikharnigam8** [comment]
> ...and can you confirm the structures of the species involved? (`C4H5(5)=h(9)+c4h4(13)`)
> 
> Running the model again with `verboseComments=True,` in the `options()` block may help indicate which library it came from.

Thanks @rwest Sir for replying. I just submitted a new job with verboseComments=True. I will inform you once i get the results. 

Also i can't confirm you the species structure. But by looking at the reaction, it seems that C4H5 is a radical, C4H4 is alkene (probably CH2=C=C=CH2) with elimination of H radical.

**Comment by shikharnigam8** [comment]
> Okay, in that case we definitely need to know the molecular structures.

Sir, the species folder is empty. RMG did not produce the specie's structure and neither the output.html file for this simulation. Let me know if there is any other way to know the structure of the species.

**Comment by rwest** [comment]
Were any of them put in your input file? `C4H5(5)` is only the fifth species into the simulation, suggesting it is either in your input file or a seed mechanism.  And the naming of `c4h4(13)` (with the lower case lettering) is not something RMG would generate itself so is probably in one of your thermo libraries and/or seed mechanism?

**Comment by shikharnigam8** [comment]
> Were any of them put in your input file? `C4H5(5)` is only the fifth species into the simulation, suggesting it is either in your input file or a seed mechanism. And the naming of `c4h4(13)` (with the lower case lettering) is not something RMG would generate itself so is probably in one of your thermo libraries and/or seed mechanism?

Sir, C4H5 and C4H4 is present in the seed mechanism library. But they are part of another reaction, with correct units. (and not part of the reaction posing the error). Infact, the reaction posing the error is not present in any of my library/seed mechanism.

Also my simulation with verboseComments=True terminated just now. Pls let me know how to capture the error source.

**Comment by shikharnigam8** [comment]
> Were any of them put in your input file? `C4H5(5)` is only the fifth species into the simulation, suggesting it is either in your input file or a seed mechanism. And the naming of `c4h4(13)` (with the lower case lettering) is not something RMG would generate itself so is probably in one of your thermo libraries and/or seed mechanism?

No, neither of the species (C4H5 and C4H4) were put into my input file.

**Comment by rwest** [comment]
From the new run with verbose comments, please you paste the full error message stack trace and the last few tens of lines of output before it?

**Comment by rwest** [comment]
>  C4H5 and C4H4 is present in the seed mechanism library.

Please look them up in the dictionary for that seed mechanism and paste the adjacency lists here, to confirm their structures. Thanks

**Comment by shikharnigam8** [comment]
> > my simulation with verboseComments=True terminated just now. Pls let me know how to capture the error source.
> 
> From the new run with verbose comments, please you paste the full error message stack trace and the last few tens of lines of output before it?

**Error Message Stack Trace (from .err file)**
:root:Moving /scratch/vijay.che.iitbhu/cyclohexanone/Job_5_apr/RMG.log to /scratch/vijay.che.iitbhu/cyclohexanone/Job_5_apr/RMG_backup.log

Traceback (most recent call last):
  File "/home/vijay.che.iitbhu/RMG-Py/rmg.py", line 111, in <module>
    main()
  File "/home/vijay.che.iitbhu/RMG-Py/rmg.py", line 105, in main
    rmg.execute(**kwargs)
  File "/home/vijay.che.iitbhu/RMG-Py/rmgpy/rmg/main.py", line 728, in execute
    self.save_everything()
  File "/home/vijay.che.iitbhu/RMG-Py/rmgpy/rmg/main.py", line 1751, in save_everything
    self.notify()
  File "/home/vijay.che.iitbhu/RMG-Py/rmgpy/util.py", line 113, in notify
    observer.update(self)
  File "rmgpy/chemkin.pyx", line 2383, in rmgpy.chemkin.ChemkinWriter.update
  File "rmgpy/chemkin.pyx", line 2279, in rmgpy.chemkin.save_chemkin_files
  File "rmgpy/chemkin.pyx", line 2255, in rmgpy.chemkin.save_chemkin
  File "rmgpy/chemkin.pyx", line 2096, in rmgpy.chemkin.save_chemkin_file
  File "rmgpy/chemkin.pyx", line 1769, in rmgpy.chemkin.write_kinetics_entry
AssertionError: 
              Gas phase reaction 
C4H5(5)=h(9)+c4h4(13)                               
              with kinetics 
Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(50.7053,'kcal/mol'), T0=(1,'K'), comment="""
Ea raised from 205.0 to 212.2 kJ/mol to match endothermicity of reaction.""")
              with 1 reactants was expected to have
              kinetics.A.get_conversion_factor_from_si_to_cm_mol_s() = 1.0
              but instead it is 1000000.0


**Last Few lines of output (from RMG.log file):**
c6h12cho-5(310) => h(9) + CCC[CH][CH]CC=O(1614)
    c6h12cho-5(310) => h(9) + CCCC[CH]C=C[O](1629)
    c6h12cho-5(310) => h(9) + [CH2]CCC[CH]CC=O(1876)
    cyclohexanone(1) => [CH2]CCCC[C]=O(1649)
    cyclohexanone(1) => [CH2]CCCC([CH2])=O(1877)
    cyclohexanone(1) => [CH2]CCC(=O)C[CH2](1864)

After model enlargement:
    The model core has 312 species and 19375 reactions
    The model edge has 21957 species and 277953 reactions


Completed initial enlarge edge step.

Saving current model core to Chemkin file...

**Comment by shikharnigam8** [comment]
> > C4H5 and C4H4 is present in the seed mechanism library.
> 
> Please look them up in the dictionary for that seed mechanism and paste the adjacency lists here, to confirm their structures. Thanks

c4h4
1 C u0 p0 c0 {3,D} {5,S} {6,S}
2 C u0 p0 c0 {4,D} {7,S} {8,S}
3 C u0 p0 c0 {1,D} {4,D}
4 C u0 p0 c0 {2,D} {3,D}
5 H u0 p0 c0 {1,S}
6 H u0 p0 c0 {1,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {2,S}


ic4h5
multiplicity 2
1 C u0 p0 c0 {2,D} {4,S} {5,S}
2 C u0 p0 c0 {1,D} {6,S} {7,S}
3 C u0 p0 c0 {4,D} {8,S} {9,S}
4 C u1 p0 c0 {1,S} {3,D}
5 H u0 p0 c0 {1,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {3,S}
9 H u0 p0 c0 {3,S}

**Comment by rwest** [comment]
The comment `Ea raised from 205.0 to 212.2 kJ/mol to match endothermicity of reaction.` reveals that the reaction originally had an Ea of 205 kJ/mol which is 49.00 kcal/mol. The pre-exponential factor is `A=(1e+13,'cm^3/(mol*s)')` so my guess is you have imported this reaction in a seed mechanism or reaction library
```
ch3chcch(+M)<=>c4h4+h(+M) 1.00E+13 0.0 49000.0
LoW/ 2.00E+14 0.0 41000.0/ 
```
which can be found in the chemkin file attached to the paper by Fenard https://pubs.acs.org/doi/10.1021/ef502732c  and maybe others.

This is a third body fall-off reaction which is first order at high pressures but second order at low pressures.

If you want to just use the high pressure limit for the first order expression you should have `A=(1e+13,'s^-1')` not `A=(1e+13,'cm^3/(mol*s)')`.

Please check the units again in your seed mechanism or reaction library.

Perhaps there is a bug in the tool used to import it into RMG format (if it is one of our tools let us know so we can fix the bug).

**Comment by rwest** [comment]
(also note that their name "`ch3chcch`" implies an isomer that's different from your CH₂CHCCH₂ structure)

**Comment by shikharnigam8** [comment]
> The comment `Ea raised from 205.0 to 212.2 kJ/mol to match endothermicity of reaction.` reveals that the reaction originally had an Ea of 205 kJ/mol which is 49.00 kcal/mol. The pre-exponential factor is `A=(1e+13,'cm^3/(mol*s)')` so my guess is you have imported this reaction in a seed mechanism or reaction library
> 
> ```
> ch3chcch(+M)<=>c4h4+h(+M) 1.00E+13 0.0 49000.0
> LoW/ 2.00E+14 0.0 41000.0/ 
> ```
> 
> which can be found in the chemkin file attached to the paper by Fenard https://pubs.acs.org/doi/10.1021/ef502732c and maybe others.
> 
> This is a third body fall-off reaction which is first order at high pressures but second order at low pressures.
> 
> If you want to just use the high pressure limit for the first order expression you should have `A=(1e+13,'s^-1')` not `A=(1e+13,'cm^3/(mol*s)')`.
> 
> Please check the units again in your seed mechanism or reaction library.
> 
> Perhaps there is a bug in the tool used to import it into RMG format (if it is one of our tools let us know so we can fix the bug).

Sir, thanks a lot for such deep insight into the issue.
I changed the unit of that reaction to s^-1. I was not able to capture that particular reaction due to change of name of ch3chcch to C4H5, as i was not sure about its structure. This issue made me learn many new things.

Coming to the import tool, i did not use that. I imported the reactions manually ,as species dictionary file was not present for the chemkin.inp file ,which i was using to create the library. I will report you if there is any bug present in the tool.

**Comment by rwest** [comment]
Glad we could help. Good luck with the model, and let us know if you have more problems. I'm going to close this issue for now.
