### ISSUE TITLE
Github Actions could test documentation builds on pull requests

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#2104]
### Motivation or Problem
When building the documentation, Sphinx puts some warnings in the log file like [these](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2073#issuecomment-820578464), but it's easy to ignore them.

### Desired Solution
Github Actions would automatically build the documentation on each pull request, but would not publish it. Instead it would just collect the sphinx warnings, and post them as a comment on the pull request, or "fail" with them loudly in a log. 

Sphinx [sphinx-build](https://www.sphinx-doc.org/en/master/man/sphinx-build.html) has an option `-w` which saves the warnings to a file, and there are github actions like [this](https://github.com/marketplace/actions/comment-pull-request) that would allow you to write a comment. 

### Potential Alternatives
It could be part of the documentation.yml CI script, but behaves differently on PRs than pushes to master (i.e. on push to master it publishes, but on a pull request it just saves the warnings.)
Or it could be part of the current CI.yml tests.

**Comment by mjohnson541** [comment]
Can this be closed now?

**Comment by rwest** [comment]
What I was proposing has not been done. It could be closed as "won't do", or left open as a feature suggestion.
