### ISSUE TITLE
Undeclared duplicate reaction in CHEMKIN file 

### ISSUE THREAD

**Issue by arnab37** [ReactionMechanismGenerator/RMG-Py#2113]
I was using RMG-Py 3.0.0 for the ethane oxidation process. After the RMG calculation was over, I tried to run ChemKin using the Chem.inp file and found multiple undeclared duplicate reactions. Luckily, I found a thread of discussion (issue # 146) regarding this topic which indicated the following: if a reaction is reported multiple times in a library instead of being a MultipleArrhenius, or if a reaction is reported multiple times in different libraries, or both; then an 'undeclared duplicate reaction' may appear in Chem.inp file. A solution, as per the discussion (issue#146), is to remove the 'undeclared duplicate reactions'. Is it the only solution?

I was using the following library: 
thermoLibraries = ['primaryThermoLibrary', 'Klippenstein_Glarborg2016', 'DFT_QCI_thermo', 'CBS_QB3_1dHR','GRI-Mech3.0'],

There were undeclared duplicates for the following reactions:
C4H7(52)+C4H7(51)=C4H6(13)+C4H8(10)
C4H7(52)+C4H7(51)=C4H6(12)+C4H8(11) 
C4H7(54)+C4H7(51)=C4H6(12)+C4H8(10) 
C4H7(54)+C4H7(51)=C4H6(13)+C4H8(10)
C4H9(31)+C4H9(30)=C4H8(11)+nButane(4)

I am also attaching the chem.inp (converted to Chem.txt) file if someone wants to check it.

[Chem.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/6399687/Chem.txt)

**Comment by rwest** [comment]
I ran the Chem.txt through ck2yaml from Cantera and it also found undeclared duplicates.
```
(cantera) $ ck2yaml --input=Chem.txt
Wrote YAML mechanism file to 'Chem.yaml'.
Mechanism contains 161 species and 5672 reactions.
Validating mechanism...
FAILED
Undeclared duplicate reaction C4H7(52) + C4H7(54) <=> C4H6(12) + C4H8(10)
found on lines 3082 and 3264 of the kinetics input file.
```
The two lines in question are
```
C4H7(52)+C4H7(54)=C4H6(12)+C4H8(10)                 2.200000e+11 0.000     0.000    
C4H7(54)+C4H7(52)=C4H6(12)+C4H8(10)                 2.200000e+11 0.000     0.000    
```

Did you make a chem_annotated.inp that might tell us where the reactions came from?
Would save us from guessing.
If that doesn't help you might need to run again with `    verboseComments=True,` in your options block.

**Comment by arnab37** [comment]
I inspected a pair of reactions from chem_annotated.inp (attached as chem_annotated.txt). One reaction is an undeclared duplicate of the other one. I am not sure whether the rates are calculated in the same way or not. However, the rate expressions are the same.

The description of the reactions are given as follows:
------------------------------------------------------------------
! Reaction index: Chemkin #1351; RMG #235
! Template reaction: Disproportionation
! From training reaction 21 used for C_rad/H2/Cs;C/H2/Nd_Csrad
! Exact match found for rate rule [C_rad/H2/Cs;C/H2/Nd_Csrad]
! Euclidian distance = 0
! Multiplied by reaction path degeneracy 2.0
! family: Disproportionation
C4H9(30)+C4H9(31)=C4H8(11)+nButane(4)               2.900000e+12 0.000     0.000    
--------------------------------------------------------------------
--------------------------------------------------------------------
! Reaction index: Chemkin #1518; RMG #30201
! Template reaction: Disproportionation
! Flux pairs: C4H9(30), C4H8(11); C4H9(31), nButane(4); 
! From training reaction 21 used for C_rad/H2/Cs;C/H2/Nd_Csrad
! Exact match found for rate rule [C_rad/H2/Cs;C/H2/Nd_Csrad]
! Euclidian distance = 0
! Multiplied by reaction path degeneracy 2.0
! family: Disproportionation
C4H9(31)+C4H9(30)=C4H8(11)+nButane(4)               2.900000e+12 0.000     0.000
-----------------------------------------------------------------------

I think I should either remove one of them or write 'DUPLICATE' below the description of the later one. I think both of them are doable as the number of undeclared duplicates is not much (<10).

I think it would be a problem if the number of undeclared duplicates is large (say more than 50). A comparison of the strings of Reactant 1 of a reaction to the strings of Reactant 2 of another reaction, and doing the same for the products might help to thoroughly check if there are any undeclared duplicates or not. However, I am not sure as I know little about how undeclared duplicates are generated.

[chem_annotated.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/6401077/chem_annotated.txt)

**Comment by rwest** [comment]
Thanks for looking that up and posting the annotated chemkin file.
You can certainly continue with your current project by just marking them as duplicates (you need to mark both, not just the second of each pair). But that still begs the question as to why RMG generated them and didn't mark them as duplicates, so I think this is a bug we need to fix.  
One thing I notice is that in both cases, the reactants are in different orders (A + B and  B + A), which might be a clue.

**Comment by arnab37** [comment]
I wanted to update you that the corrected Chem_annotated.inp file ran successfully.

**Comment by rwest** [comment]
I'm reopening this because I don't think we solved the problem with RMG. RMG shouldn't have made a chemkin file with undeclared duplicates. I think @ericwein has another recent example.

**Comment by Fraixxer** [comment]
I am also using the current version of RMG and I faced the same problem. I had to annotate the cit and inp files by adding duplicate. Maybe this bug can be checked and addressed.

**Comment by wrongxin2023** [comment]
i also meet the same problem:
Undeclared duplicate reactions detected:
Reaction 590: hocho + oh => co + h2o + oh
Reaction 405: hocho + M <=> co + h2o + M
can you help me ?
