### ISSUE TITLE
to_cantera methods missing for surface reactions?

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#2117]
### Bug Description

I think the direct conversion from RMG reaction objects into Cantera reaction objects, introduced by Connie in https://github.com/ReactionMechanismGenerator/RMG-Py/pull/620 , is used only for sensitivity analysis?   Are there other uses?

Anyway, I think it is missing the ability to do surface reactions (SurfaceArrhenius, StickingCoefficient) properly. 

Creation of Cantera input files is (currently) done by translating the CHEMKIN input files, and functions OK for surface kinetics.

### Installation Information
RMG-Py 3.1

**Comment by JacksonBurns** [comment]
Resolved in mentioned and subsequent PRs.
