### ISSUE TITLE
RMG forbidding the species without addition of the constraints block in the input file.

### ISSUE THREAD

**Issue by shikharnigam8** [ReactionMechanismGenerator/RMG-Py#2125]
### Bug Description
I am running the inbuilt RMG example "ethane-oxidation". This example ran without any error. However, I face the following error on the addition of "combustion_core/version4" reaction library in the input file. The constraint block in the input file is not active.
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/6451997/input.txt)

On doing this, my simulation is terminating with an error saying "rmgpy.exceptions.ForbiddenStructureException: Species constraints forbids species CH from reaction library combustion_core/version4. Please reformulate constraints, remove the species, or explicitly allow it". 
@rwest 

### How To Reproduce
I have attached the input file.

### Expected Behavior
Since, the constraint block is not used in the input file, the simulation should terminate without any error. 

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): Linux Subsystem on Windows 10
 - Installation method: Source with anaconda
 - RMG version information:
   
   - RMG-Py: Latest version
   - RMG-database: Latest database

**Comment by rwest** [comment]
You could try
```
generatedSpeciesConstraints(
    allowed=['input species','seed mechanisms','reaction libraries'],
)
```

My guess is the `maximumCarbeneRadicals` is limiting you. 

Perhaps the defaults, and/or other tips, should be in the documentation.
(edit it [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/documentation/source/users/rmg/input.rst#species-constraints) )

You can figure them out from 
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/constraints.py

**Comment by shikharnigam8** [comment]
Of course, on explicitly adding the constraint block in the input file, the simulation is running fine. However, we are not sure about the source of this error, if we don't add the constraint block in the input file.
We further checked "forbiddenstructures.py" file, but we did not find any such specie there.
Could you help us to locate the error?
