### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory when running make eg1

### ISSUE THREAD

**Issue by danielokuo** [ReactionMechanismGenerator/RMG-Py#2128]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [x] An error message 

### Context
A clear and concise description what you're trying to do.

### Question
Write your question here.
I recently updated to the version 3.1.0 and tried to run the make eg1 minimal example and I got this error message

"FileNotFoundError: [Errno 2] No such file or directory: '/home/danielokuo/RMG/RMG-database/input/surface/libraries/metal.py'
Coverage.py warning: Module Arkane.py was never imported. (module-not-imported)
Coverage.py warning: Module rmg.py was never imported. (module-not-imported)
make: *** [Makefile:96: eg1] Error 1"

I am new to RMG I have not been able to fix this error and would appreciate any directions.

### Installation Information
Describe your installation method and system information if applicable.
 - OS (include version if known): Ubuntu 20.04.2 LTS
 - Installation method: installation from source, with anaconda
 - RMG version information: 3.1.0 
   
   - RMG-Py: 
   - RMG-database:

**Comment by mjohnson541** [comment]
That it's looking for '/home/danielokuo/RMG/RMG-database/input/surface/libraries/metal.py' suggests to me that you already have RMG installed from source, perhaps in the /home/danielokuo/RMG/RMG-Py and /home/danielokuo/RMG/RMG-database directories?

If that's the case you might have installed binary rmg into the environment confusing it and you would need to uninstall it by running, inside the rmg_env, `conda remove rmg`. You can simply update from source RMG by going into the appropriate directories (/home/danielokuo/RMG/RMG-Py and /home/danielokuo/RMG/RMG-database) and running: 

`git remote update`
`git pull`

Assuming you're on the master branch this should pull all of the latest changes.

**Comment by danielokuo** [comment]
Thanks Matt,

 Yes I have RMG installed from source, in the /home/danielokuo/RMG/RMG-Py
and /home/danielokuo/RMG/RMG-database directories

Then I get this

(rmg_env) ***@***.***VM:~/RMG/RMG-Py$ conda remove rmg
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target
environment:
  - rmg

**Comment by mjohnson541** [comment]
How did you update to rmg 3.1.0?

**Comment by danielokuo** [comment]
git clone https://github.com/ReactionMechanismGenerator/RMG-Py.git
git clone https://github.com/ReactionMechanismGenerator/RMG-database.git

**Comment by mjohnson541** [comment]
In what directories?

**Comment by danielokuo** [comment]
210  ls
  211  cd RMG-Py
  212  git pull https://github.com/ReactionMechanismGenerator/RMG-Py.git master
  213  cd .
  214  cd..
  215  cd ..
  216  RMG-database
  217  cd RMG-database
  218  git pull https://github.com/ReactionMechanismGenerator/RMG-database.git master

From this command history, I will say in the directories
danielokuo@okuo-VM:~/RMG/RMG-Py
danielokuo@okuo-VM:~/RMG/RMG-Py$

**Comment by danielokuo** [comment]
Sorry I meant From this command history, I will say in the directories
danielokuo@okuo-VM:/RMG/RMG-Py
danielokuo@okuo-VM:~/RMG/RMG-database

**Comment by mjohnson541** [comment]
Okay so you used git pull not git clone?

**Comment by danielokuo** [comment]
I think so

**Comment by mjohnson541** [comment]
Can you go into the appropriate directories (/home/danielokuo/RMG/RMG-Py and /home/danielokuo/RMG/RMG-database) and run:
```
git remote update
git pull
```

And then try again?

**Comment by danielokuo** [comment]
I guess I should deactivate (rmg_env) before running 

git remote update
git pull

right?

**Comment by mjohnson541** [comment]
It shouldn't matter

**Comment by danielokuo** [comment]
(base) danielokuo@okuo-VM:~/RMG/RMG-Py$ git remote update
Fetching official
remote: Enumerating objects: 261, done.
remote: Counting objects: 100% (132/132), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 79 (delta 56), reused 74 (delta 51), pack-reused 0
Unpacking objects: 100% (79/79), 29.46 KiB | 793.00 KiB/s, done.
From https://github.com/ReactionMechanismGenerator/RMG-Py
 + 2d234db46...998603809 solvation_thermo_GAV -> official/solvation_thermo_GAV  (forced update)
Fetching origin
(base) danielokuo@okuo-VM:~/RMG/RMG-Py$ git pull
Already up-to-date.
(base) danielokuo@okuo-VM:~/RMG/RMG-Py$ cd ..
(base) danielokuo@okuo-VM:~/RMG$ cd RMG-database/
(base) danielokuo@okuo-VM:~/RMG/RMG-database$ git remote update
Fetching official
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 29 (delta 11), reused 28 (delta 10), pack-reused 0
Unpacking objects: 100% (29/29), 129.08 KiB | 6.15 MiB/s, done.
From https://github.com/ReactionMechanismGenerator/RMG-database
 + ebdaf4c8...0155ed30 solvation_thermo_GAV -> official/solvation_thermo_GAV  (forced update)
Fetching origin
(base) danielokuo@okuo-VM:~/RMG/RMG-database$ git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> practice

(base) danielokuo@okuo-VM:~/RMG/RMG-database$

**Comment by danielokuo** [comment]
(base) danielokuo@okuo-VM:~/RMG/RMG-database$ git pull
There is no tracking information for the current branch.

Does this matter?

**Comment by mjohnson541** [comment]
try `git branch --set-upstream-to=origin/master`

**Comment by danielokuo** [comment]
(rmg_env) danielokuo@okuo-VM:~/RMG/RMG-Py$ git remote update
Fetching official
Fetching origin
(rmg_env) danielokuo@okuo-VM:~/RMG/RMG-Py$ git pull
Already up-to-date.

(rmg_env) danielokuo@okuo-VM:~/RMG/RMG-database$ git remote update
Fetching official
Fetching origin
(rmg_env) danielokuo@okuo-VM:~/RMG/RMG-database$ git pull
Already up-to-date.

Both RMG-Py and RMG-database seem up-to-date now

But it keeps giving this error 

"FileNotFoundError: [Errno 2] No such file or directory: '/home/danielokuo/RMG/RMG-database/input/surface/libraries/metal.py'
Coverage.py warning: Module Arkane.py was never imported. (module-not-imported)
Coverage.py warning: Module rmg.py was never imported. (module-not-imported)
make: *** [Makefile:96: eg1] Error 1"

When I run the minimal example 

make eg1

**Comment by mjohnson541** [comment]
Go into the RMG-Py directory and recompile:  

`make clean`
`make`

Then try again.

**Comment by danielokuo** [comment]
Hi everyone,

It seems the minimal example runs now but does not go on to completion.

Here is the output

MG execution initiated at Fri May 21 15:54:08 2021

#########################################################
# RMG-Py - Reaction Mechanism Generator in Python       #
# Version: 3.1.0                                        #
# Authors: RMG Developers ***@***.***)             #
# P.I.s:   William H. Green ***@***.***)           #
#          Richard H. West ***@***.***)             #
# Website: http://reactionmechanismgenerator.github.io/ #
#########################################################

The current git HEAD for RMG-Py is:
b'74b176a77bf1dc51c17cd0a43764231e6bbb5e04'
b'Mon May 17 21:30:35 2021 -0400'

The current git HEAD for RMG-database is:
b'2d6e6a46f59edc8bc9fdb7065bb4b822521b9c39'
b'Fri Jan 29 19:47:06 2021 +0000'

Reading input file "/home/danielokuo/RMG/RMG-Py/testing/eg1/input.py"...
# Data sources
database(
    thermoLibraries = ['primaryThermoLibrary'],
    reactionLibraries = [],
    seedMechanisms = [],
    kineticsDepositories = ['training'],
    kineticsFamilies = 'default',
    kineticsEstimator = 'rate rules',
)

# List of species
species(
    label='ethane',
    reactive=True,
    structure=SMILES("CC"),
)

# Reaction systems
simpleReactor(
    temperature=(1350,'K'),
    pressure=(1.0,'bar'),
    initialMoleFractions={
        "ethane": 1.0,
    },
    terminationConversion={
        'ethane': 0.9,
    },
    terminationTime=(1e6,'s'),
)

simulator(
    atol=1e-16,
    rtol=1e-8,
)

model(
    toleranceKeepInEdge=0.0,
    toleranceMoveToCore=0.1,
    toleranceInterruptSimulation=0.1,
    maximumEdgeSpecies=100000,
    filterReactions=True,
)

options(
    units='si',
    generateOutputHTML=True,
    generatePlots=False,
    saveEdgeSpecies=True,
    saveSimulationProfiles=True,
)

Warning: Generate Output HTML option was turned on. Note that this will
slow down model generation.
Warning: Edge species saving was turned on. This will slow down model
generation for large simulations.

Loading transport library from NOx2018.py in
/home/danielokuo/RMG/RMG-database/input/transport/libraries...
Loading transport library from OneDMinN2.py in
/home/danielokuo/RMG/RMG-database/input/transport/libraries...
Loading transport library from PrimaryTransportLibrary.py in
/home/danielokuo/RMG/RMG-database/input/transport/libraries...
Loading transport library from GRI-Mech.py in
/home/danielokuo/RMG/RMG-database/input/transport/libraries...
Loading transport group database from
/home/danielokuo/RMG/RMG-database/input/transport/groups...
make: *** [Makefile:96: eg1] Segmentation fault (core dumped)

**Comment by mjohnson541** [comment]
What was the output when you ran the below?
```
make clean
make
```

**Comment by danielokuo** [comment]
latter part of the output read

gcc -pthread -B /home/danielokuo/anaconda3/envs/rmg_env/compiler_compat
-Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall
-Wstrict-prototypes -fPIC -I. -I.
-I/home/danielokuo/anaconda3/envs/rmg_env/lib/python3.7/site-packages/numpy/core/include
-I/home/danielokuo/anaconda3/envs/rmg_env/include/python3.7m -c
build/rmgpy/solver/surface.c -o ./build/rmgpy/solver/surface.o
In file included from
/home/danielokuo/anaconda3/envs/rmg_env/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1823,
                 from
/home/danielokuo/anaconda3/envs/rmg_env/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from
/home/danielokuo/anaconda3/envs/rmg_env/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from build/rmgpy/solver/surface.c:628:
/home/danielokuo/anaconda3/envs/rmg_env/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2:
warning: #warning "Using deprecated NumPy API, disable it by " "#defining
NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   15 | #warning "Using deprecated NumPy API, disable it by " \
      |  ^~~~~~~
gcc -pthread -shared -B
/home/danielokuo/anaconda3/envs/rmg_env/compiler_compat
-L/home/danielokuo/anaconda3/envs/rmg_env/lib
-Wl,-rpath=/home/danielokuo/anaconda3/envs/rmg_env/lib -Wl,--no-as-needed
-Wl,--sysroot=/ ./build/rmgpy/solver/surface.o -o
/home/danielokuo/RMG/RMG-Py/rmgpy/solver/
surface.cpython-37m-x86_64-linux-gnu.so

Checking vital dependencies...

Package        Version        Location
lpsolve55
/home/danielokuo/anaconda3/envs/rmg_env/lib/python3.7/site-packages/
lpsolve55.cpython-37m-x86_64-linux-gnu.so
OpenBabel      3.1.0
 /home/danielokuo/anaconda3/envs/rmg_env/lib/python3.7/site-packages/openbabel/openbabel.py
pydqed         1.0.1
 /home/danielokuo/anaconda3/envs/rmg_env/lib/python3.7/site-packages/
pydqed.cpython-37m-x86_64-linux-gnu.so
pyrdl
/home/danielokuo/anaconda3/envs/rmg_env/lib/python3.7/site-packages/py_rdl/__init__.py
RDKit          2020.03.3
 /home/danielokuo/anaconda3/envs/rmg_env/lib/python3.7/site-packages/rdkit/__init__.py
symmetry       1.16
/home/danielokuo/anaconda3/envs/rmg_env/bin/symmetry

Everything was found :)
