### ISSUE TITLE
Exception ignored in: 'rmgpy.reaction.Reaction.get_free_energy_of_reaction' during unit tests.

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#2133]
### Bug Description

The unit test logs show a lot of errors like this:
```
ERROR:root:Problem with reactant Species(label="C6H6-5", molecule=[Molecule(smiles="C1=CC=CCC=1")], molecular_weight=(78.1117,'amu')) in reaction C6H6-5 <=> C6H6-6
658
Traceback (most recent call last):
659
  File "rmgpy/reaction.py", line 546, in rmgpy.reaction.Reaction.get_free_energy_of_reaction
660
    dGrxn -= reactant.get_free_energy(T)
661
  File "rmgpy/species.py", line 527, in rmgpy.species.Species.get_free_energy
662
    raise Exception('Unable to calculate free energy for species {0!r}: '
663
Exception: Unable to calculate free energy for species 'C6H6-5': no thermo or statmech data available.
664
Exception ignored in: 'rmgpy.reaction.Reaction.get_free_energy_of_reaction'
```

I think they are happening in `rmgpy/data/kinetics/familyTest.py`, around the "test that appropriate regularization dimensions have been identified ..." but it might be the test after that.

### How To Reproduce
Check any [recent CI logs](https://github.com/ReactionMechanismGenerator/RMG-Py/runs/2585451019?check_suite_focus=true) or try `nosetests --nocapture  --verbose --logging-level=DEBUG  rmgpy/data/kinetics/familyTest.py`

### Expected Behavior
If this isn't a problem, it shouldn't show up in the unit test logs. If it is a problem, it should be fixed. Perhaps the mini database that's kept in RMG-Py for unit testing is missing something that's in the real RMG-database?

### More general concern.
Why are exceptions being ignored during unit tests? Is this because it's buried in cython code that didn't have an exception checking flag in the pxd? or something else? or is it intentional?  Without looking deeper, my first impression is a bit concerning.

So things to look into and fix if they're broken
- [ ] why is this showing up in the log?
- [ ] why are we ignoring exceptions?
 
### Installation Information
Describe your installation method and system information.
 - OS: mac, linux
 - Installation method: developer in conda environment
 - RMG version information: latest

**Comment by JacksonBurns** [comment]
This issue is no longer reproduced in the current CI and the linked logs have expired and cannot be reproduced. Closing as stale, but this was likely resolved at some point and the issue was not properly linked to the corresponding PR. Please reopen if this is not the case.
