### ISSUE TITLE
Possibly change how we track multiplicity constraints in reverse templates.

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#2134]
### Motivation or Problem

If we are applying a family in reverse and the template reactants restrict multiplicity, we need to make sure that
a reverse product matches the multiplicity-constrained template reactant because the forward template products do not enforce the multiplicity restriction. Without this check, we get an UndeterminableKineticsError if the reverse products have a multiplicity that does not match the multiplicity constraint of the template reactants. 
This was addressed in https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2131 but as noted in the discussion toward the end of that pull request, it _might_ be preferable (instead of the changes introduced in that pull request) to track the multiplicity constraints of a template when applying recipe actions to generate the reverse template. 

### Desired Solution
We generate the reverse template by applying the recipe to the forward template. This is done mostly using atom type actions, etc. so for example if you have a Cs atom type (carbon with all single bonds) and apply a increment_bond then it becomes a Cd atom type (carbon with one double bond) in the reverse template for example. Could we do something similar with the overall group attributes like multiplicity? i.e. if you have multiplicity = [0,2] enforced for the forward template, then apply an increment_radical action you end up with multiplicity = [1,3] in the product template.

### Potential Alternatives
Leave the current implementation introduced in https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2131 

### Note:
David points out (in [this comment](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2131#issuecomment-842448550)) there may be considerable difficulties in doing the "desired solution" mentioned above, so we may change our mind and close this issue. But I wanted to have it on the issue tracker so it's not forgotten without a decision (the ongoing discussion on the tail of an already-merged pull request is going to drop off the radar soon).    I think one major challenge is to do with figuring out which product fragment should have the constraint if, for example, only one reactant fragment is constrained.  

Another alternative would be to enable product constraints in forward templates (then this would map neatly to/from reactant constraints in reverse templates).

**Comment by davidfarinajr** [comment]
We could also discuss a global forbidden structure or constraint for vdW adsorbates with radicals.  Most (if not all) of the multiplicity constrained templates are multiplicity 1 for vdw groups.  I think it would make sense to make a global constraint or group to forbid vdW with radicals.

**Comment by rwest** [comment]
David's comment https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2131#issuecomment-842448550 makes me think this isn't worth pursuing. Or at least not worth keeping an active issue.
