### ISSUE TITLE
MOPAC - Sorry, but cannot solve the Licence issue. 

### ISSUE THREAD

**Issue by laubapires** [ReactionMechanismGenerator/RMG-Py#2146]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [x] Dependencies
 - [ ] An error message 

### Context
Hello everyone, I'm facing a licence issue with MOPAC. I've already read other issues similar to this one, but I cannot correct it. 
I have the Licence and tried to activate it several ways - even installing MOPAC on my own. See for instance what I'm obtaining if I run:  ~/anaconda3/envs/rmg_env/opt/mopac$ ./MOPAC2016.exe  12345678910.mop
     Password detected, but the password has already been correctly installed.
     MOPAC is ready to run data sets.

This is the direction that appears when I type 'which mopac'. And I created this license file (.mop) and added it. Before, I tried the method "At the command level, run the command: mopac <password>". 
Even so, every time I run, I'm still getting "To install the MOPAC license, use the command, 'MOPAC2016.exe <license-key>'"

I have already tried it all. Sorry if it's a common mistake, but not is working out. 
Thanks. 

### Question
How can I add the license to MOPAC.  A trivial step, that became painful

### Installation Information
Describe your installation method and system information if applicable.
 - Windows 10 (WSL with Ubuntu 18)
 - Installation method: binary with anaconda
 - RMG version information: 3.1.0

**Comment by amarkpayne** [comment]
I just installed mopac on a WSL installation. Can you try the following steps and see if they work for you?

1. `conda activate rmg_env`
2. `mopac 12345678910` but replace 12345678910 with your own license key string

I wonder if calling `rmg_env/opt/mopac/MOPAC2016.exe` directly is causing a problem. The above steps worked for me in a new install, but if they don't work for you then we can keep debugging.

**Comment by amarkpayne** [comment]
Quick follow-up: there is a file `rmg_env/opt/mopac/Installation instructions.txt`. Do NOT follow these instructions, as conda already deals with some of the PATH issues that the instructions try to deal with. If you followed the instructions, specifically the part where you modify your .bashrc file, undo these changes. The only steps you need to follow in a clean installation of RMG are the two steps above, unless there is a new issue we are not currently aware of (and will help you debug through).

When you type `which mopac` from within your rmg_env it should return something that ends with `rmg_env/bin/mopac`.

**Comment by amarkpayne** [comment]
@laubapires were you able to resolve this issue? Can I go ahead and close this out?
