### ISSUE TITLE
Inconsistent species naming rules

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#2149]
### Motivation or Problem
A model was built which had an adsorbate species called "NO_ads" because that's the name given to it in the thermo library. Then the kinetics database was updated with some more reaction libraries, and in the new model the species was called "NO_X", because that's the name that was given in one of the libraries.

It's not very clear to the user what to expect, or why the name had changed.

### Desired Solution
I'm not sure what priority or rules I prefer, i.e. how should a name be chosen, but the status quo has confused at least one user. It can make post-processing annoying when your species names keep changing. But it's nice to be able to control them somehow.  I'm opening this "feature suggestion" as a tentative place for comments/discussion. What do _you_ think we should or could do?

### Potential Alternatives
* Keep the current method of determining a name, but document it somewhere.
* let people specify a naming convention, or even a dictionary of preferred names
* enforce a naming convention that doesn't depend on input file or current state of database.

**Comment by mjohnson541** [comment]
Looking at the code I'm not entirely sure if this is the case or not right now, but I think we should preserve names given in the input file. This allows users to ensure that certain species will always be named a certain way...which I think is the primary thing people care about. Arbitrary species name changes are a little bit annoying to deal with when they do matter, but often the library names are a readability improvement and you always have the option to specify them in the input file if you want to.
