### ISSUE TITLE
How to derive GAVs for thermo-group ?

### ISSUE THREAD

**Issue by TaikiKato** [ReactionMechanismGenerator/RMG-Py#2172]
### Topic
Computational GAVs Derivation for groups.py (Thermo-group)

### Context
New element addition to RMG-database

### Question
How to make GAVs for groups.py in thermo-group ?
Can RMG calculate thermodynamic GAVs & group hierarchy ?

### Installation Information
 - OS: Windows 10, WSL, Ubuntu 18.04
 - Installation method: Miniconda using & download from github files
 - RMG version information:
   - RMG-Py: 3.1.0-59-g74b176a77
   - RMG-database: 3.0.0-206-g833577ec

**Comment by TaikiKato** [comment]
I succeeded in thermo group.py making from this reference's table 8.
■ https://pubs.acs.org/doi/10.1021/jp030727k

So, If I have GAVs reference, I can make group.spy for new element.
But, I don't know how to derive these GAVs table information.

If you have some calculation method idea, 
please teach me some technical advices.

**Comment by mjohnson541** [comment]
RMG doesn't have an automatic way to generate the thermo groups.py group structures. I think we might have some scripts for fitting the thermo groups after you write them @hwpang @oscarwumit?
