### ISSUE TITLE
Google Actions CI: documentation testing

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#2176]
The documentation testing script at 
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/.github/workflows/docs.yml
checks for broken links in the documentation in the "Check documentation links" step.
A recent build spent about 6 hours here before the overall job timed out and was killed. 
We should add a timeout on that step somehow, or as an option to `sphinx-build` if there is one, so we don't waste so long of Github Actions cpu time.

**Comment by rwest** [comment]
Happened again last night. The step should time out and the next step should continue if that happens.

**Comment by JacksonBurns** [comment]
> Happened again last night. The step should time out and the next step should continue if that happens.

The idea being to make passing the link check optional?

**Comment by JacksonBurns** [comment]
This issue has not resurfaced, and was presumably due to a bug in some external code. I'm going to remove the stale and abandoned labels and treat this as solved, but if this issue comes up again please see the above ideas.
