### ISSUE TITLE
node labels split by newline in chem_annotated.inp

### ISSUE THREAD

**Issue by sevyharris** [ReactionMechanismGenerator/RMG-Py#2201]
### Bug Description
Some of the reaction tree node labels are getting split up when I try to read in the chem_annotated.inp file.

### How To Reproduce
1. Checkout a version of RMG-database that has the new reaction family trees. I used tree_gen_Disproportionation
2. Run RMG to generate the chem_annotated.inp file
3. Read the chem_annotated.inp using rmgpy.chemkin.load_chemkin_file
4. some of the node labels that are split onto separate lines in the chem_annotated.inp file have been split by spaces when you read them into the reaction objects. For example, when I used the ethane model, this node is split:
"Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-"

### Expected Behavior
I do not expect to see spaces in the node names when I read them in, but they are there for some of the long node names that  extend to more than one line in the chem_annotated.inp file.

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): Windows Subsystem Linux, Ubuntu 20.04.1 LTS
 - Installation method: source
 - RMG version information: 3.0.0-728-gcf94d44d9
   - RMG-Py: cf94d44
   - RMG-database: tree_gen_Disproportionation

### Additional Context
I found this while using rmgpy.tools.uncertainty to estimate reaction rate uncertainties for reaction rates using the new trees.

**Comment by JacksonBurns** [comment]
This installation method is no longer supported and this file format is no longer used. Closing as stale.
