### ISSUE TITLE
Library error

### ISSUE THREAD

**Issue by NUSCondy** [ReactionMechanismGenerator/RMG-Py#2213]
Hi,

I am using the latest version of RMG and database. I am trying to build a mechanism using the thermo library of 'Aramcomech_2.0'.
This lib is good before but now it shows:
**rmgpy.exceptions.ForbiddenStructureException: Species constraints forbids species CH from reaction library AramcoMech_2.0. Please reformulate constraints, remove the species, or explicitly allow it.**

Before the excited species cannot be recognized so I have already excluded them. I don't know CH cannot be permitted.

**Comment by alongd** [comment]
I'm happy this issue got solved. Please report the new one as a new GitHub Issue, and attach your RMG input file.
Good luck!
