### ISSUE TITLE
Arkane crashes trying to read halogens_G4.py statmech library

### ISSUE THREAD

**Issue by sevyharris** [ReactionMechanismGenerator/RMG-Py#2282]
### How To Reproduce
Steps to reproduce the behavior.

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): (e.g. Windows 10, Ubuntu 18, macOS 10.13, etc.)
 - Installation method: (e.g. installation from binary or source, with or without anaconda)
 - RMG version information:
   
   - RMG-Py: 
   - RMG-database:

**Comment by sevyharris** [comment]
accidentally posted this before I could finish rebuilding RMG to confirm this bug really exists. Looks like it runs just fine after all...

**Comment by kspieks** [comment]
I was also encountering this error. However, I later realized it happened because my RMG-Py branch was outdated while my RMG-database branch was up to date. Once I pulled both to the latest main, I could import things fine :)
