### ISSUE TITLE
Collision violators in Burke library

### ISSUE THREAD

**Issue by jtreese** [ReactionMechanismGenerator/RMG-Py#2286]
### Bug Description
Including seed mechanisms from the Burke library produces a collision violator error

### How To Reproduce
Include BurkeH2O2inArHe and BurkeH2O2inN2 in seed mechanisms and run diisobutylene input

### Expected Behavior
Shouldn't be collision violators in the seed mechanism

### Installation Information

 - OS : CentOS Linux release 7.9.2009 (Core)
 - Installation method: Source
 - RMG version information: 3.1.0-414-gc4ba26c4e
   - RMG-Py: c4ba26c4e0bde03d9d8d5867875e2df2ce5d4079
   - RMG-database: bbd3f21662dc816b54b2a1119445e94350f43c76

### Additional Context
Tried commenting out offending reactions and still crashed

error log
```
Traceback (most recent call last):
  File "/home/treese.j/.conda/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 308, in main
    python(**vars(ns))
  File "/home/treese.j/.conda/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 59, in python
    scope = runpy.run_path(script, run_name="__main__")
  File "/home/treese.j/.conda/envs/rmg_env/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/treese.j/.conda/envs/rmg_env/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/treese.j/.conda/envs/rmg_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/treese.j/rmg/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/home/treese.j/rmg/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/treese.j/rmg/RMG-Py/rmgpy/rmg/main.py", line 1113, in execute
    self.check_model()
  File "/home/treese.j/rmg/RMG-Py/rmgpy/rmg/main.py", line 1370, in check_model
    rxn_string = violator[0].to_chemkin()
  File "rmgpy/reaction.py", line 244, in rmgpy.reaction.Reaction.to_chemkin
  File "rmgpy/chemkin.pyx", line 1880, in rmgpy.chemkin.write_kinetics_entry
TypeError: 'NoneType' object is not iterable
```

Collision rate violator log 
```
*** Collision rate limit violators report ***
"Violation factor" is the ratio of the rate coefficient to the collision limit rate at the relevant conditions

! Library reaction: BurkeH2O2inN2
! Flux pairs: H(14), H2O2(17); HO2(16), H2O2(17);
H(14)+HO2(16)+M=H2O2(17)+M                          6.000e+14 1.250     -0.270


Direction: forward
Violation factor: 3.81
Violation condition: 550.0 K, 40.0 bar


! Library reaction: BurkeH2O2inN2
! Flux pairs: H(14), H2O2(17); HO2(16), H2O2(17);
H(14)+HO2(16)+M=H2O2(17)+M                          6.000e+14 1.250     -0.270


Direction: forward
Violation factor: 3.00
Violation condition: 1500.0 K, 40.0 bar
```

**Comment by sevyharris** [comment]
Attaching the input file:
[diiso.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/8351333/diiso.txt)

**Comment by sevyharris** [comment]
Rebuilding the latest version of RMG fixed the issue.

**Comment by PoojaNem** [comment]
@sevyharris and @jtreese, I cloned the latest version of RMG to my local system and generated a mechanism with it. This reaction is still present in my collision violator log file. 
<img width="323" alt="image" src="https://github.com/user-attachments/assets/fcc771ca-8f55-421c-a786-e7bf0f0acc6d" />
Could you please tell me what could be going wrong here.

**Comment by rwest** [comment]
I think the check for things exceeding the collision limits should probably only apply,  at least using the formula implemented here, for bimolecular things in the high-pressure limit.

The paper that inspired it and that provides the formula ([Combust Flame 2017](https://doi.org/10.1016/j.combustflame.2017.08.005)) 
contains the line " For pressure-dependent reactions, only the high-pressure limit bimolecular reactions were considered"

The detected violation is a 3-body reaction. So the "k" that is being compared is fundamentally different, with different units, and so it's not a meaningful comparison.

These tests were introduced in 
https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1361
with the `if len(self.reactants) >= 2:` in `check_collision_limit_violation` and no check for molecularity in `calculate_coll_limit`.


@alongd do you think I've guessed the situation correctly?

We should probably fix this in RMG.

But for now I think you can ignore the warning and assume that Burke's rate is OK.

(I would also note that including both BurkeH2O2inArHe and BurkeH2O2inN2 as seeds is not advisable and probably doing what is intended; I have no idea if you are doing so Pooja, but the original post by Julia in 2022 was)

**Comment by PoojaNem** [comment]
Thank you very much Prof. West for looking into the issue. I am using only BurkeH2O2inN2 as one of the reaction libraries (not seed) for the mechanism generation. 
While investigating, I have gone through the paper you mentioned above and the RMG code file (reaction.py) where this check was implemented.  As per the paper, only high-pressure bimolecular reactions should be checked for violations (if the reaction is pressure dependent) however, in the code, mean_sigma and epsilon calculation consider the length of reactants or product, which will be more than 2 species in the forward direction for the reaction under concern.
