### ISSUE TITLE
Update the documentation about running Arkane

### ISSUE THREAD

**Issue by jeehyunatrmg** [ReactionMechanismGenerator/RMG-Py#2292]
### Bug Description
on the RMG environment, when I tried to run Arkane via 
`python Arkane.py input.py`

I get an error message: "python: can't open file 'Arkane.py': [Errno 2] No such file or directory"

### How To Reproduce
`rmg`
`python Arkane.py input.py`

### Expected Behavior
I was expecting Arkane to calculate the pressure-dependent rate coefficient calculations.

When I directly assign the path where Arkane.py is located, I can execute Arkane calculations via 

`python ~/RMG-Py/Arkane.py input.py`

### Installation Information
Describe your installation method and system information.
 - OS (ubuntu on vmware workstation pro 15
 - Installation method: (with anaconda)
 - RMG version information:
   
   - RMG-Py: 3.1.0-462-g5d80ee39d
   - RMG-database: 3.0.0-513-geaf7c1a56

**Comment by xiaoruiDong** [comment]
Hi @jeehyunatrmg, which path are you on when you run `python Arkane.py input.py`? Inside `~/RMG-Py` or not? Did you add `~/RMG-Py` to your `$PATH` by something like `export PATH=$PATH:~/RMG-Py`?

**Comment by jeehyunatrmg** [comment]
Hi @xiaoruiDong. Thanks for reaching out! So I can see in my ~/.bashrc that 

```
export PYTHONPATH=~/RMG-Py/:$PYTHONPATH
export PATH=~/RMG-Py/:$PATH
```
So I think I already added ~/RMG-Py to my path. (Mainly, I followed the RMG installation guide on the RMG website.)

Please let me know if my statement is unclear! 

Thanks!

**Comment by xiaoruiDong** [comment]
Thanks for the clarification. I think what you can do is 
1. `chmod +x Arkane.py` to make the file executable.
2. In the folder you want to launch Arkane.py do `Arkane.py input.py` rather than `python Arkane.py input.py`
3. Or instead you can add an alias in your `.bashrc`, something like `alias run_arkane=python ~/RMG-Py/Arkane.py input.py`, so that you don't have to type in the whole thing when you want to launch Arkane

**Comment by jeehyunatrmg** [comment]
Thanks! Now it is running when I do` Arkane.py input.py` after doing step 1. 

I think there needs to be an update in 

http://reactionmechanismgenerator.github.io/RMG-Py/users/arkane/running.html

Currently, it is 

o execute an Arkane job, invoke the command

`python Arkane.py INPUTFILE`
The absolute or relative paths to the Arkane.py file as well as to the input file must be given. (_**I think I might have missed this section.**_)

A person like me (not familiar with programming) might have a hard time with this simple problem...

Thank you so much! It really helped! 

I will close the issue! :)

**Comment by xiaoruiDong** [comment]
Yeah, That is a good suggestion. We will try to update it soon. Many thanks @jeehyunatrmg

**Comment by jeehyunatrmg** [comment]
No! Those should be my words! Many thanks!
