### ISSUE TITLE
RMG version

### ISSUE THREAD

**Issue by Pegah-B** [ReactionMechanismGenerator/RMG-Py#2294]
### Topic
General area which your question is related to.
 - [x] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

### Question
I wanted to know where we could find older versions of RMG to download and install. I am using v.3.1.0 and I need to downgrade it to v.3.0.0 to get the same result as my coworker got before. 

### Installation Information
Describe your installation method and system information if applicable.
 - OS (include version if known): macOS 10.14
 - Installation method: installation from binary , with anaconda
 - RMG version information:
   
   - RMG-Py: 3.1.0
   - RMG-database: 3.1.0

**Comment by xiaoruiDong** [comment]
1. change the directory to the RMG-Py folder (where RMG is installed). E.g., `cd ~/RMG-Py/`
2. Run `git remote -v` to get the list of the remote repos you have access to and check if items with `ReactionMechanismGenerator/RMG-Py` is listed with both `(fetch)` and `(push)`. Find the alias of the remote (the first item in the row). It is usually `origin` or `official` if you don't change the default.
3. Download the v3.1.0 by `git pull ALIAS v3.1.0`. you have to replace ALIAS by the actual name, e.g., `git pull origin v3.1.0`
4. Change to version v3.1.0 by `git checkout -b origin/v3.1.0`. Double check if you are running at v3.1.0 by `git branch`
5. To change back to the branch you were running (I assume it is `main`), you can do `git checkout main`

**Comment by Pegah-B** [comment]
First, I have RMG installed from binary with anaconda. I did not have a "RMG-Py" folder; I had "anaconda 3" folder.  So, I tried to reinstall RMG this time directly from Github inside a new folder named "RMG-Py". I am not sure if did it correctly or not. Anyway, then, following your instruction, I got this message:

```
(base) :~/RMG-Git/RMG-Py$ git remote -v
origin  https://github.com/ReactionMechanismGenerator/RMG-Py.git (fetch)
origin  https://github.com/ReactionMechanismGenerator/RMG-Py.git (push)
(base) :~/RMG-Git/RMG-Py$ git pull origin/v3.1.0
fatal: 'origin/v3.1.0' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
```
It seems like I do not access to install the older version v.3.0.0. What should I do to install it?

**Comment by xiaoruiDong** [comment]
If you want to use the anaconda version. Please do `conda install -c rmg RMG=3.0.0`. If you want to use the source code downloaded from the github, Please try `git fetch origin` and `git checkout -b origin/v3.0.0`
