### ISSUE TITLE
mol.is_isomorphic returns False when the answer is True

### ISSUE THREAD

**Issue by kfir4444** [ReactionMechanismGenerator/RMG-Py#2298]
Hey all, I found a bug in is_isomorphic. I have the following Molecule objects:

cc = Molecule(smiles="[CH2][CH2]")

cc.atoms[0].decrement_radical()
cc.atoms[1].decrement_radical()
cc.get_bond(cc.atoms[0],cc.atoms[1]).order += 1
cc.update_multiplicity()
cc.is_isomorphic(Molecule(smiles = "C=C"))

Notice that both the multiplicity and the fingerprint are equal, so it seems to be an issue in Graph.is_isomorphic.
Thanks!

**Comment by xiaoruiDong** [comment]
Hi @kfir4444, the reason here is that the atomtypes are not actually updated after the recipe (`decrement_radical`) is applied.
You can do `cc.update()` (which includes` update_multiplicity` inside the function).
