### ISSUE TITLE
Pickle testing not thorough enough

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#2312]
Pull request #2308 fixed an issue where an object (in that case a `GroupAtom`) was not pickling all of its properties, which led to strange hard-to-debug behaviour. But it would be quite an easy thing to catch in a unit test. There was already a [test_pickle(self)](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/680268ed2d5cf1efbc2a262c90244e381fe70408/rmgpy/molecule/groupTest.py#L349) unit test that claims to "Test that a GroupAtom object can be successfully pickled and unpickled with no loss of information." but it clearly doesn't, quite, check everything. Probably an attribute was added after the unit test was made, and the test (and the `__reduce__` method)  weren't updated.

There may be other corners where pickling is not properly tested, and perhaps even some where it is broken.

Could/should we do some/all of:

1. audit all pickle unit tests and check they're up to date and complete?

2. devise a pickling unit test that is always up to date and complete and future-proof, and convert some/all of our pickling unit tests to use this mechanism?  

3. remind code authors and code reviewers to look out for unit tests, and to look out for `__reduce__` functions

**Comment by kspieks** [comment]
Thanks for bringing this up. @hwpang and I can look into this unit test to figure out the issue and try to update it
