### ISSUE TITLE
I am unable to create the rmg environment in anaconda

### ISSUE THREAD

**Issue by torstein-F** [ReactionMechanismGenerator/RMG-Py#2323]
Dear all,

I am trying to install RMG-Py following the instructions here:
http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html
I come to step 4 where the following commands are given:
```
cd RMG-Py
conda env create -f environment.yml
```
I have installed Anaconda and verified that it works.
The content of the folder RMG-Py is the following:
```
arkane              documentation    external     Makefile          rmg.py   setup.py              utilities.py
Arkane.py           environment.yml  ipython      README.md         rmgpy    testing
CODE_OF_CONDUCT.md  examples         LICENSE.txt  requirements.txt  scripts  trigger-rmg-tests.sh
```
When I execute the command
```
conda env create -f environment.yml
```
The following output is produced:
```
Collecting package metadata (repodata.json): done
Solving environment: \ (base) torstein@torstein-VirtualBox:~/Programs/rmg/RMG-Py$ 
```
but the rmg environment is not created, as verified by the command `conda info --envs`:
```
# conda environments:
#
base                  *  /home/torstein/anaconda3
snakes                   /home/torstein/anaconda3/envs/snakes
snowflakes               /home/torstein/anaconda3/envs/snowflakes
```
Does anyone have any idea on how I can solve this issue?
Thanks in advance for your help.

**Comment by mjohnson541** [comment]
That doesn't look like an issue on our end. That looks like something is terminating the process in the middle of solving the environment. Is your internet connection stable?

**Comment by torstein-F** [comment]
@mjohnson541 
I believe my internet connection is stable. Now I tried to run the command `conda env create -f environment.yml` again, and at the same time, in a different terminal window, I pinged www.google.com. I let ping run until the command `conda env create -f environment.yml` had terminated. The ping statistics showed 0% package loss:
```
--- www.google.com ping statistics ---
121 packets transmitted, 121 received, 0% packet loss, time 121405ms
rtt min/avg/max/mdev = 9.462/10.903/18.311/1.059 ms
```
