### ISSUE TITLE
Mid-chain beta-scission for radical in the third position

### ISSUE THREAD

**Issue by laubapires** [ReactionMechanismGenerator/RMG-Py#2331]
### Bug Description
Mid-chain beta-scission 1,3 is not leading to methane formation. 

### How To Reproduce
CC[CH]CCCCCC ---> [CH3] + ....

Even looking on the RMG website, it does not give anything (No results found.: Our database could not find any reactions between these two species which give new products.)

**Comment by xiaoruiDong** [comment]
Is this the [reaction](https://rmg.mit.edu/database/kinetics/reaction/reactant1=multiplicity%202%0A1%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B12,S%7D%20%7B13,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B4,S%7D%20%7B14,S%7D%20%7B15,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B5,S%7D%20%7B10,S%7D%20%7B11,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B7,S%7D%20%7B16,S%7D%20%7B17,S%7D%0A5%20%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B9,S%7D%20%7B20,S%7D%20%7B21,S%7D%0A6%20%20C%20u0%20p0%20c0%20%7B8,S%7D%20%7B9,S%7D%20%7B18,S%7D%20%7B19,S%7D%0A7%20%20C%20u0%20p0%20c0%20%7B4,S%7D%20%7B25,S%7D%20%7B26,S%7D%20%7B27,S%7D%0A8%20%20C%20u0%20p0%20c0%20%7B6,S%7D%20%7B22,S%7D%20%7B23,S%7D%20%7B24,S%7D%0A9%20%20C%20u1%20p0%20c0%20%7B5,S%7D%20%7B6,S%7D%20%7B28,S%7D%0A10%20H%20u0%20p0%20c0%20%7B3,S%7D%0A11%20H%20u0%20p0%20c0%20%7B3,S%7D%0A12%20H%20u0%20p0%20c0%20%7B1,S%7D%0A13%20H%20u0%20p0%20c0%20%7B1,S%7D%0A14%20H%20u0%20p0%20c0%20%7B2,S%7D%0A15%20H%20u0%20p0%20c0%20%7B2,S%7D%0A16%20H%20u0%20p0%20c0%20%7B4,S%7D%0A17%20H%20u0%20p0%20c0%20%7B4,S%7D%0A18%20H%20u0%20p0%20c0%20%7B6,S%7D%0A19%20H%20u0%20p0%20c0%20%7B6,S%7D%0A20%20H%20u0%20p0%20c0%20%7B5,S%7D%0A21%20H%20u0%20p0%20c0%20%7B5,S%7D%0A22%20H%20u0%20p0%20c0%20%7B8,S%7D%0A23%20H%20u0%20p0%20c0%20%7B8,S%7D%0A24%20H%20u0%20p0%20c0%20%7B8,S%7D%0A25%20H%20u0%20p0%20c0%20%7B7,S%7D%0A26%20H%20u0%20p0%20c0%20%7B7,S%7D%0A27%20H%20u0%20p0%20c0%20%7B7,S%7D%0A28%20H%20u0%20p0%20c0%20%7B9,S%7D%0A__product1=1%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B11,S%7D%20%7B12,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B4,S%7D%20%7B13,S%7D%20%7B14,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B5,S%7D%20%7B9,S%7D%20%7B10,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B6,S%7D%20%7B15,S%7D%20%7B16,S%7D%0A5%20%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B7,S%7D%20%7B17,S%7D%20%7B18,S%7D%0A6%20%20C%20u0%20p0%20c0%20%7B4,S%7D%20%7B19,S%7D%20%7B20,S%7D%20%7B21,S%7D%0A7%20%20C%20u0%20p0%20c0%20%7B5,S%7D%20%7B8,D%7D%20%7B22,S%7D%0A8%20%20C%20u0%20p0%20c0%20%7B7,D%7D%20%7B23,S%7D%20%7B24,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B3,S%7D%0A10%20H%20u0%20p0%20c0%20%7B3,S%7D%0A11%20H%20u0%20p0%20c0%20%7B1,S%7D%0A12%20H%20u0%20p0%20c0%20%7B1,S%7D%0A13%20H%20u0%20p0%20c0%20%7B2,S%7D%0A14%20H%20u0%20p0%20c0%20%7B2,S%7D%0A15%20H%20u0%20p0%20c0%20%7B4,S%7D%0A16%20H%20u0%20p0%20c0%20%7B4,S%7D%0A17%20H%20u0%20p0%20c0%20%7B5,S%7D%0A18%20H%20u0%20p0%20c0%20%7B5,S%7D%0A19%20H%20u0%20p0%20c0%20%7B6,S%7D%0A20%20H%20u0%20p0%20c0%20%7B6,S%7D%0A21%20H%20u0%20p0%20c0%20%7B6,S%7D%0A22%20H%20u0%20p0%20c0%20%7B7,S%7D%0A23%20H%20u0%20p0%20c0%20%7B8,S%7D%0A24%20H%20u0%20p0%20c0%20%7B8,S%7D%0A__product2=multiplicity%202%0A1%20C%20u1%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0A__res=True) you are looking for?
