### ISSUE TITLE
How to estimate dipole moment, polarizability, and rotational relaxation collision number

### ISSUE THREAD

**Issue by torstein-F** [ReactionMechanismGenerator/RMG-Py#2334]
Dear developers and users of RMG,
I have used RMG to estimate the transport properties gas phase species. I have noticed in the cases where the result is “Group additivity”, the values for dipole moment, polarizability and rotational relaxation collision number are all set to zero. For instance for methyl formate, I get these results:
Shape Index 	= 	2.00 
Epsilon 	= 	3137.52 J/mol
Sigma 	= 	5.23 angstroms
Dipole Moment 	= 	0.00 C∗m
Polarizability 	= 	0.00 angstroms3
Rotational Relaxation Collision Number 	= 	0.00
My question is therefore:
How can I estimate/calculate the values of the dipole moment, the polarizability, and the rotational relaxation collision number for a given gas phase species?
Thanks a lot in advance for your help.

**Comment by xiaoruiDong** [comment]
Hi! Thank you for being interested in using RMG to estimate the transport properties. Unfortunately, RMG currently doesn't have an estimator for predicting the properties you are looking for. If you are dealing with simple species, you probably can find their properties on cccbdb database. E.g., dipole moment on this page https://cccbdb.nist.gov/diplistx.asp or polarizability on https://cccbdb.nist.gov/pollistx.asp. If you know how to conduct quantum chemistry calculation, you can find these properties from the calculation results. E.g., searching for dipole moment in an Gaussian geometry optimization output file.
