### ISSUE TITLE
Checking vital dependencies...，There are missing dependencies as listed above.

### ISSUE THREAD

**Issue by quandewang** [ReactionMechanismGenerator/RMG-Py#2337]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG

### Context
when I try to install RMG, during the make process, 
Checking vital dependencies...

Package        Version        Location
lpsolve55                     /home/quande/anaconda3/envs/rmg_env/lib/python3.7/site-packages/lpsolve55.cpython-37m-x86_64-linux-gnu.so
OpenBabel      3.1.0          /home/quande/anaconda3/envs/rmg_env/lib/python3.7/site-packages/openbabel/openbabel.py
pydqed         1.0.1          /home/quande/anaconda3/envs/rmg_env/lib/python3.7/site-packages/pydqed.cpython-37m-x86_64-linux-gnu.so
pyrdl                         /home/quande/anaconda3/envs/rmg_env/lib/python3.7/site-packages/py_rdl/__init__.py
RDKit                         Not found. Please install RDKit version 2015.03.1 or later with InChI support.
symmetry       1.16           /home/quande/anaconda3/envs/rmg_env/bin/symmetry

There are missing dependencies as listed above. Please install them before proceeding.

Using Anaconda, these dependencies can be individually installed from the RMG channel as follows:

    conda install -c rmg [package name]

RDKit should be installed from the RDKit channel instead:

    conda install -c rdkit rdkit

You can alternatively update your environment and install all missing dependencies as follows:

    conda env update -f environment.yml

Be sure to activate your conda environment (rmg_env by default) before installing or updating.

### Question
Write your question here.
I tried to use these methods, but the problem is not solved. I am sure  to activate the conda environment (rmg_env by default) before installing or updating.

**Comment by xiaoruiDong** [comment]
Hi Dequan, I am surprised to see that RDKit was not installed...
1. Can you first try `conda list rdkit`to see if it is really missing? the script should return something like below (details may be different though). If no `rdkit` shows up, then it means that RDKit was not installed...
![image](https://user-images.githubusercontent.com/35771233/191667908-1f64173e-4936-457d-91e1-f07acd43832b.png)
2. If nothing show up in (1), can your try `conda install -c rmg rdkit`, and report if it works?
3. Or since you are still in the step of installing RMG. You can also try re-create the conda environment. E.g., `conda env remove -n rmg_env; conda env create -f environment.yml -n rmg_env` in the folder of RMG-Py.

**Comment by xiaoruiDong** [comment]
Yea, this is really weird and is not expected. Can you quickly try 
1. Activate the rmg_env by `conda activate rmg_env`
2. Check python binary by `which python` which ideally should return `/home/quande/anaconda3/envs/rmg_env/bin/python` or `/home/quande/anaconda3/envs/rmg_env/bin/python-jl`
3. If that is the case, can you try `python -c "import rdkit; from rdkit import Chem; print(rdkit.__version__); print(rdkit.__file__); print(Chem.inchi.INCHI_AVAILABLE);"` This should return three lines
```
2020.03.3.0
/home/quande/anaconda3/envs/rmg_env/lib/python3.7/site-packages/rdkit/__init__.py
True
```
4. If problem free in the first three steps; try `python -c "from rmgpy.molecule.converter import to_rdkit_mol; from rmgpy.molecule import Molecule; print(to_rdkit_mol(Molecule().from_smiles('C')).GetNumAtoms());"` this should return
```
1
```

If all the above steps work, I would not worry too much about the "RDKit missing" message. You can also try to run RMG-test by running `make test` and see if any error raises. This may take a while though.

**Comment by quandewang** [comment]
Thanks for your help. It seems like some small errors. I use the methods you provided, and the problem is solved.

**Comment by xiaoruiDong** [comment]
Sounds good.
