### ISSUE TITLE
Error reported calculating constants for branching reactions

### ISSUE THREAD

**Issue by Twilightpink** [ReactionMechanismGenerator/RMG-Py#2338]
Hello,

Good day!
I was trying to use Arkane for calculating rate constants using master equation for a set of reactions involving one barrierless reaction. I'd highly appreciate any suggestions on resolving this issue. I am attaching the error message screenshot and the files below.

Thanking in anticipation 

-Preethika
<img width="1440" alt="Screen Shot 2022-09-25 at 6 33 59 PM" src="https://user-images.githubusercontent.com/75770774/192152127-77eca545-6836-4c3c-81d4-296c465a4a11.png">

**Comment by mjohnson541** [comment]
Okay the primary thing I see is your network block. 
```
network(
    label = 'path2',
    isomers = ['CS3','S','CS4'],
    reactants =['CS3','S','CS2'],
    bathGas = {
        'nitrogen': 1.0,
    }
)
```
Isomers and reactants denote channels within the network. Isomers are individual species and reactants are groups of species. Each isomer and reactant channel (set of species) should have the same number of each atom. 
In our acetyl+O2 example this block looks like: 
```
network(
    label = 'acetyl + O2',
    isomers = [
        'acetylperoxy',
        'hydroperoxylvinoxy',
    ],
    reactants = [
        ('acetyl', 'oxygen'),
    ],
    bathGas = {
        'nitrogen': 1.0,
    }
)
```
You can see the full example here: https://github.com/ReactionMechanismGenerator/RMG-Py/blob/76e68348c0b3879c4f964787fee0f76ab3b4b899/examples/arkane/networks/acetyl%2BO2/input.py#L257

I'm not exactly sure why your block didn't error earlier though as a result of that. 

You also might try setting activeJRotor = True in the pressure dependence block.

**Comment by Twilightpink** [comment]
Dear @mjohnson541,

Thank you for the suggestion. My reactions are CS2 <=> CS3 +S and CS3 <=> CS4.
So the isomers would be CS3 and CS4, reactants would be CS2, S and CS3.
I also tried it with activeJRotor = True and is still ran into a similar error. I kindly request you to have a look into this and I sincerely appreciate your help. I am attaching the file for your reference.
[path2_updated.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/9641343/path2_updated.zip)

**Comment by mjohnson541** [comment]
Looking at your network visualization. It looks like one of your reactions isn't chemically balanced and something is messed up with the associated transition state. 
[network.pdf](https://github.com/ReactionMechanismGenerator/RMG-Py/files/9641459/network.pdf)

**Comment by Twilightpink** [comment]
Hi @mjohnson541,

Yes the network visualization is not correct because the SMILES code for S (sulphur) was wrong, otherwise the reactions are balanced. 

Thank you

**Comment by Twilightpink** [comment]
Hi @mjohnson541,

I was interested in computing rate coefficients for 2 different pathways of CS7 (CS7 => CS8) and (CS7 => CS12) but it shows me error stating : **ValueError: could not convert string to float: 'Delta=-4.46D-03'**
I am attaching the files for your reference. I followed the exact method used in acetyl+O2 input file. But not sure why this one doesn't work. It will be helpful if you could guide me through this.

Thank you

--Preethika
[CS7_branching.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/9659042/CS7_branching.zip)

**Comment by mjohnson541** [comment]
Can you post the full error trace?

**Comment by Twilightpink** [comment]
<img width="1358" alt="error_CS7_branching" src="https://user-images.githubusercontent.com/75770774/192621598-4342b645-a8e9-4904-a6b2-4f8aa17c8014.png">

**Comment by mjohnson541** [comment]
You labeled your pressure dependence block 'path2' and your network block 'path3' those should have the same names.

**Comment by Twilightpink** [comment]
I have renamed both the network and pressure dependence label as 'CS7-branch', yet I'm getting the same error. I am attaching the files and error message for your reference.
<img width="1440" alt="Screen Shot 2022-09-28 at 12 29 06 AM" src="https://user-images.githubusercontent.com/75770774/192629154-2c4a36e5-f015-4dd2-ac25-fbb611a6628e.png">
[CS7_branch_updated.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/9659451/CS7_branch_updated.zip)

**Comment by mjohnson541** [comment]
It looks like its having trouble parsing one of your gaussian files. There may be an issue with how gaussian printed the energy line in one of your files.

**Comment by Twilightpink** [comment]
Yes I checked that one and it is a parsing error due to an unexpected file structure. But may I please know what is the reason for this error: **Could not find a positive sum of states for TransitionState**?

**Comment by mjohnson541** [comment]
I think something has to be messed up with that transition state TS13-14 or one of the channels it is connected to. Perhaps most likely an issue with the energy of something. I would look at the network.pdf first. I think in theory it could be that that TS just has so high of barrier that the energy grains can't resolve the flux for RRKM, but I've never seen this error before.

**Comment by Twilightpink** [comment]
Hi @mjohnson541,
Going by the input E0 values in the respective reactant/product/TS .py files, it should work fine because the values for CS13, CS14 and TS13-14 are -223.146, -187.529 and -193.334 kJ/mol respectively. I am attaching the input and output files for the same. I have tried increasing the number of grains but still I'm getting the same error.

Thank you
[cs13-14.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/9671940/cs13-14.zip)

**Comment by sthakris** [comment]
@mjohnson541 : I want to calculate the the high pressure reaction rate of barrier less reaction. How can I calculate this. In the RMG documentation in website it is written as, 
**"The kinetics entry is particularly useful to specify rates of barrierless reactions (for which Arkane cannot yet calculate high-pressure limit rates)"**

@Twilightpink has mentioned that his/her reaction set also consist of one barrierless reaction. May be this may have caused the issue in calculating the pressure dependent rates. However, I am interested in calculating the rate constant for barrierless reaction. 

Could you please give your suggestions? As it is mentioned Arkane can not calculate rate constant for barrierless reaction.

**Comment by mjohnson541** [comment]
Arkane can't do variation transition state theory so it can't calculate rate constants for barrierless reactions, but it can integrate high pressure limit parameters either provided in the input file or estimated from RMG's databases for these reactions and use them in pressure dependent network calculations. 

There are a number of different codes that can do variational transition state theory. I think the most popular are tools from the MESS and Polyrate suites of codes.
