### ISSUE TITLE
RMG can't read training depository if the reaction entry has elementary_high_p property

### ISSUE THREAD

**Issue by sevyharris** [ReactionMechanismGenerator/RMG-Py#2341]
### Bug Description
I wrote a script to add my new DFT calculations into an existing reaction depository. When I save using the KineticsDepository class save function (inherited from the Database class), it adds the elementary_high_p as one of the properties for each entry. Then when I try to read the depository, RMG complains about not recognizing elementary_high_p as a property.

### How To Reproduce
I'm currently on an experimental branch of RMG (correlated_uncertainty). I'll create a minimal example soon to demonstrate this on the main branch or resolve this issue if it's just my weird version of RMG. I just ran into this and wanted to remind myself to do something about it even though I have a workaround.

**Comment by sevyharris** [comment]
Here's the example of how to reproduce it. You'll need to specify the RMG-database path (which it proceeds to break with the addition of a malformed training reaction), but it otherwise relies on inline code.

```
#!/usr/bin/env python
# coding: utf-8


# script to test error where depository save adds properties it later can't read



import os

import rmgpy.data.kinetics
import rmgpy.reaction
import rmgpy.species
import rmgpy.chemkin
import rmgpy.kinetics


ref_library_path = "/home/harris.se/rmg/RMG-database/input/kinetics/"
family = 'Disproportionation'
ref_database = rmgpy.data.kinetics.KineticsDatabase()
ref_database.load(
    ref_library_path,
    libraries=[],
    families=[family]
)
training_depo = ref_database.families[family].get_training_depository()
print(len(training_depo.entries), 'training reactions')


# define the species in the example
r1 = rmgpy.species.Species(smiles='[O]O')
r2 = rmgpy.species.Species(smiles='C[CH2]')
p1 = rmgpy.species.Species(smiles='OO')
p2 = rmgpy.species.Species(smiles='C=C')

my_reaction = rmgpy.reaction.Reaction()
my_reaction.reactants = [r1, r2]
my_reaction.products = [p1, p2]
my_reaction.elementary_high_p = True
my_reaction.kinetics = rmgpy.kinetics.Arrhenius(
    A=(100.07,'cm^3/(mol*s)'),
    n=3.43775,
    Ea=(48.6525,'kJ/mol'),
    T0=(1,'K'),
    Tmin=(298,'K'),
    Tmax=(2500,'K'),
    comment="""Fitted to 50 data points; dA = *|/ 1.15458, dn = +|- 0.0188838, dEa = +|- 0.102765 kJ/mol"""
)
print(my_reaction)

my_entry = rmgpy.data.base.Entry(
    label=str(my_reaction),
    item=my_reaction,
    data=my_reaction.kinetics
)



# add it to the training depo -- need to do it to the actual Disproportionation family
print(len(training_depo.entries))
training_depo.entries[1000] = my_entry
print(len(training_depo.entries))


# save the training depo
training_depo.save_dictionary(os.path.join(ref_library_path, 'families', family, 'training', 'dictionary.txt'))
training_depo.save(os.path.join(ref_library_path, 'families', family, 'training', 'reactions.py'))


# try to read it again

ref_library_path = "/home/harris.se/rmg/RMG-database/input/kinetics/"
family = 'Disproportionation'
ref_database = rmgpy.data.kinetics.KineticsDatabase()
ref_database.load(
    ref_library_path,
    libraries=[],
    families=[family]
)
training_depo = ref_database.families[family].get_training_depository()
print(len(training_depo.entries), 'training reactions')






```

**Comment by alongd** [comment]
I think that a training reaction shouldn't have an `elementary_high_p` attribute (this is used during model generation when ascribing rates to path reactions in networks, RMG should already know to assume that template reactions are elementary), so perhaps better to work on not saving it rather than working on reading it properly. I think that the same should be applied for the `allow_pdep_route` and the `allow_max_rate_violation` attribute in case they are saved as well when generating training reactions.

**Comment by sevyharris** [comment]
Okay, I will look into how the property got applied in the first place rather than trying to add it to the depository read function.
