### ISSUE TITLE
Runs fail due to Invalid k(E) values computed for path reaction.

### ISSUE THREAD

**Issue by kfir4444** [ReactionMechanismGenerator/RMG-Py#2347]
### Bug Description
Entire run fails due to Invalid k(E) values computed for path reaction.
I was running a model in RMG, and recived the following traceback:
```python
File "/home/kfir4444/Code/RMG-Py/rmgpy/pdep/network.py", line 841, in calculate_microcanonical_rates
    'Invalid k(E) values computed for path reaction "{0}".'.format(rxn), k_ratio, Keq_ratio)
rmgpy.exceptions.InvalidMicrocanonicalRateError: ('Invalid k(E) values computed for path reaction "[CH2]COCCOOC=COC=C(15350) <=> [CH2]COCCOOC(C=C)C=O(15448)".', 2.002077091766027, 1.0)
```
No, the model had core had 68 species and 1174 reactions, and the model edge had 15382 species and 32480 reactions prior to this, and I do not even know if that reaction would have made it to the core, which leads to wondering, whether this behavior is as intended.
### How To Reproduce
Input file will be granted by request.

### Expected Behavior
I would have wanted this reaction to be placed in the edge, and in another file, called `requires_refinement.txt` (or something of the sort) that I could use after this run.

### Installation Information
Describe your installation method and system information.
 - OS Ubuntu 22.04
 - source
 - RMG version information:
   
   - RMG-Py: 3.1.0-616-gd82b6eddf
   - RMG-database: 3.0.0-577-g0de0ae134

### Additional Context
I would like to  suggest a fix for this problem myself, just need a developers opinion if it's a bug or a feature :)

**Comment by mjohnson541** [comment]
What this error specifically means is that after using ILT to convert k(T) to k(E) the resulting k(E) values are inconsistent with the k(T) by at least a factor of 2. A similar check exists for Keq, however, the Keq check specifically exempts calculations run in RMG jobs. It seems like someone decided that failures in the rate coefficient check should stop the RMG job, but not the Keq check. 

As I don't think we've seen this error before, and we usually hear about stuff that stops a run pretty quickly, I think it would be worth investigating why this specific reaction has this problem. It seems likely something interesting is at work in the generated pdep network, the estimated k(T)s used by the network or the thermochemistry estimates in the network.

**Comment by kfir4444** [comment]
Thanks @mjohnson541!
I will try to investigate further using the restart_from_seed, which also leads to the same error, but either way, stopping the whole run just for that seems problematic...
I will save the failed files, so if you (or anyone else) would have better ideas for that than you might also want to take a look at it.
