### ISSUE TITLE
Converting chemkin to RMG library

### ISSUE THREAD

**Issue by NellyMitnik** [ReactionMechanismGenerator/RMG-Py#2352]
### Topic
I would like to convert a chemkin file (txt format) from a literature paper, into RMG library, WITHOUT a species_dictionary file.
### Context
The provided chemkin file in the literature basically has labels such as:  M6C6H8O , B3, C5H7-1s-O , R4C6H7O.
In most cases, the comment line has the following provided format: .ch2/ch2/ch3 , .c(//o)/o/ch3 (CH3OCO).
Each paper in the literature has its own labels for species. For example, M4 can represent different species in different literature papers.
I know there is a way to convert a chemkin file in RMG with a file of species_dictionary.txt. But, writing manually the species_dictionary.txt for all the species in a kinetic model provided by the paper, takes a lot of time.

### Question
Is there a way to convert chemkin file without the species_dictionary file?
(chemkin file from the literature is attached)

Thanks!

[1-s2.0-S0010218017301256-mmc3.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/10270281/1-s2.0-S0010218017301256-mmc3.txt)

**Comment by mjohnson541** [comment]
@rwest you had a tool to help with this...but I don't think it ever got merged...is it still viable?

**Comment by rwest** [comment]
Yes - thanks Matt.

The [importChemkin.py](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/importer/importChemkin.py) script on the [importer](https://github.com/reactionMechanismGenerator/RMG-py/tree/importer) branch of both RMG-Py and RMG-database is the place to start. I'm meaning to rejuvenate the project, but who knows when I'll actually find the time?

There's a short paper about it [here](https://web.northeastern.edu/comocheng/wordpress/wp-content/uploads/2015/06/Lambert-West-US-Combustion-Meeting-2015.pdf) and a snapshot of the working code and imported models [here](https://figshare.com/articles/dataset/Combustion_Mechanism_Importer_and_Kinetic_Models/4787893)
