### ISSUE TITLE
Published data from Arkane fails to run

### ISSUE THREAD

**Issue by kfir4444** [ReactionMechanismGenerator/RMG-Py#2356]
### Bug Description
I was trying to run an example from the paper [A workflow for automatic generation and efficient refinement of individual pressure-dependent networks](https://www.sciencedirect.com/science/article/abs/pii/S0010218022005259) 
and got an error:
```python
Error: The input file "$PATH/input.py" was invalid:
Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "$RMG_PATH/input.py", line 1448, in read_input_file
    exec(f.read(), global_context, local_context)
  File "<string>", line 23, in <module>
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "$ANACONDA_PATH/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 308, in main
    python(**vars(ns))
  File "$ANACONDA_PATH/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 59, in python
    scope = runpy.run_path(script, run_name="__main__")
  File "$ANACONDA_PATH/envs/rmg_env/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "$ANACONDA_PATH/envs/rmg_env/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File $ANACONDA_PATH/envs/rmg_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "$RMG_PATH/rmg.py", line 118, in <module>
    main()
  File "$RMG_PATH/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "$RMG_PATH/rmgpy/rmg/main.py", line 717, in execute
    self.initialize(**kwargs)
  File "$RMG_PATH/rmgpy/rmg/main.py", line 483, in initialize
    self.load_input(self.input_file)
  File "$RMG_PATH/rmgpy/rmg/main.py", line 258, in load_input
    read_input_file(path, self)
  File "$RMG_PATH/rmgpy/rmg/input.py", line 1448, in read_input_file
    exec(f.read(), global_context, local_context)
  File "<string>", line 23, in <module>
TypeError: 'NoneType' object is not subscriptable
```

### How To Reproduce
Download the first supplementary material from the paper and try to run it, or:
```python
title = ''

description = \
""" 
"""
database(
    thermoLibraries = ['Klippenstein_Glarborg2016','BurkeH2O2','primaryThermoLibrary','thermo_DFT_CCSDTF12_BAC','CBS_QB3_1dHR','DFT_QCI_thermo'],#,'Bu_methyl_propyl_ether','pme','explorerPME'],
    reactionLibraries = ['C2H4+O_Klipp2017','Klippenstein_Glarborg2016','BurkeH2O2inN2'],
    kineticsDepositories = 'default',
    kineticsFamilies = 'default',
    kineticsEstimator = 'rate rules',
)

species(
label='CCC([O])OC',
structure=SMILES('CCC([O])OC'),
)

species(
    label = 'N2',
    structure = SMILES('N#N'),
    molecularWeight = (28.04,"g/mol"),
    collisionModel = TransportData(sigma=(3.70,'angstrom'), epsilon=(94.9,'K')),
    reactive = False
)
species(
    label = 'H',
    structure = SMILES('[H]'),
)
species(
    label = 'COC(=O)CC',
    structure = SMILES('COC(=O)CC'),
)

species(
    label = 'C[O]',
    structure = SMILES('C[O]'),
)
species(
    label = 'CCC=O',
    structure = SMILES('CCC=O'),
)
species(
    label = 'C[CH2]',
    structure = SMILES('C[CH2]'),
)
species(
    label = 'COC=O',
    structure = SMILES('COC=O'),
)

#reaction(
#    label = 'CCC([O])OC <=> H + COC(=O)CC',
#    reactants = ['CCC([O])OC'],
#    products = ['H', 'COC(=O)CC'],
#    kinetics = Arrhenius(A=(1.69938e+08,'s^-1'), n=1.50865, Ea=(31.5652,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K'))
#)
#reaction(
#    label = 'CCC([O])OC <=> C[O] + CCC=O',
#    reactants = ['CCC([O])OC'],
#    products = ['C[O]', 'CCC=O'],
#    kinetics = Arrhenius(A=(1.33207e+12,'s^-1'), n=0.406003, Ea=(79.4291,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
#)
#reaction(
#    label = 'CCC([O])OC <=> C[CH2] + COC=O',
#    reactants = ['CCC([O])OC'],
#    products = ['C[CH2]', 'COC=O'],
#    kinetics = Arrhenius(A=(3.37454e+11,'s^-1'), n=0.569442, Ea=(19.9737,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K')),
#)

pressureDependence(
    label = 'MPEoxy',
    Tmin = (300.0,'K'), Tmax = (2000,'K'), Tcount = 12,
    Pmin = (0.1,'bar'), Pmax = (100,'bar'), Pcount = 7,
    maximumGrainSize = (0.5,'kcal/mol'), 
    minimumGrainCount = 500, 
    method = 'modified strong collision',
    interpolationModel = ('Chebyshev',6,4), 
    activeKRotor = True,
    rmgmode = False, 
    sensitivity_conditions = [[(1000, 'K'), (10, 'bar')]],
    sensitivity_perturbation = (4.0,'kcal/mol'),
)

explorer(
    source=['COC(=O)CC','H'],
    explore_tol=0.2,
    bathGas={'N2':1.0},
    maximumRadicalElectrons=1,
    #flux_tol=0.3,
    energy_tol=3.0,
)

```

### Expected Behavior
To finish exploring the PES and exporting data

### Installation Information
 - OS (include version if known): Ubuntu 22.3
 - Installation method: Source
 - RMG version information:
   
   - RMG-Py: 3.1.0-620-g2cdc2ea7c
   - RMG-database: 3.0.0-584-gbd1319070

### Additional Context
Thanks!

**Comment by alongd** [comment]
@kfir4444, did you run it with `rmg.py` or with `Arkane.py`?

**Comment by kfir4444** [comment]
@alongd Arkane

**Comment by mjohnson541** [comment]
It looks like it's having trouble interpreting line 23 of the input file.

**Comment by mjohnson541** [comment]
Is that `collisionModel = TransportData(sigma=(3.70,'angstrom'), epsilon=(94.9,'K')),`?

**Comment by kfir4444** [comment]
@mjohnson541 yes, seems like it.
But I also tried removing it (I am trying to use arkane to explore another pdep network, using your published inputs as a base for mine), and it didn't work either.

**Comment by mjohnson541** [comment]
If it isn't some issue with characters in the input file it's likely an issue with what Arkane has loaded when it runs the input file. I think some function/constructor is either not being loaded or called correctly and the key thing should be to figure out what function/constructor...once you know what function/constructor you can call it on the same inputs manually and it should give a useful error trace.

**Comment by mjohnson541** [comment]
You're sure you're up to date on main? I'll try to take a look at this next couple days.

**Comment by mjohnson541** [comment]
So on main I don't have an issue with the`TransportData`call. I do get the list index error...but that seems to occur after it has generated all of the expected files. It plots the pdep network properly. I think the results for that particular network are fine. 

However, [H] + COC(=O)CC as a source generates two pdep networks (add the H across the double bond two different ways)...we don't actually really care a whole lot about this in some examples like this one because the resulting networks often become identical during exploration...but it should be generating data for both networks...however it seems like the second network has no isomers in it...

**Comment by mjohnson541** [comment]
It seems they're all removed by the energy filter resulting in a network with no isomers causing that error. The barriers in the first network are consistent with the reactions and species energies...however the second network barriers don't seem to match the data it's created from.
