### ISSUE TITLE
Switch CI + Documentation Build to use Mamba instead of Conda

### ISSUE THREAD

**Issue by JacksonBurns** [ReactionMechanismGenerator/RMG-Py#2365]
### Motivation or Problem
CI and Documentation GitHub workflows take 1 hour+ to run in some cases - about half of this time is spent configuring the conda environment, solving the dependencies especially.

### Desired Solution
Switch the package resolved to Mamba in the workflows, [as shown in here](https://github.com/mamba-org/provision-with-micromamba).

### Potential Alternatives
Build times on CI aren't the biggest problem in the world but this is a "nice to have".

**Comment by mjohnson541** [comment]
I don't know what the best way to do it is, but I've done done this for Pynta within the setup-miniconda action here: https://github.com/zadorlab/pynta/blob/master/.github/workflows/CI.yml

**Comment by JacksonBurns** [comment]
Resolved with #2377
