### ISSUE TITLE
Arkane Arrhenius fits are significantly off?

### ISSUE THREAD

**Issue by vhanut** [ReactionMechanismGenerator/RMG-Py#2371]
### Topic
 - [ ] Arkane (formerly CanTherm)

### Context
Running kinetic calculation using the example provided in examples/arkane/reactions/rate_demo. The arrhenius fits from arkane differ significantly from those reported in literature. Is this normal behaviour ? What is the best way to verify the RMG installation? I see most of the examples have input files but not sample outputs. 

The rates I get are for example 

kinetics(
    label = 'CH4 + NH2 <=> CH3 + NH3',
    kinetics = Arrhenius(
        A = (1.90178e+15, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (95.3449, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (1591, 'K'),
        Tmax = (2084, 'K'),
        comment = 'Fitted to 25 data points; dA = *|/ 1.0272, dn = +|- 0, dEa = +|- 0.40133 kJ/mol',
    ),
)

Literature(A = 7.7e13, Ea = 71.3 Kj/mol) -> https://doi.org/10.1002/kin.10131
kinetics(
    label = 'C2H6 + NH2 <=> C2H5 + NH3',
    kinetics = Arrhenius(
        A = (2.10992e+15, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (87.1213, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (1770, 'K'),
        Tmax = (2150, 'K'),
        comment = 'Fitted to 25 data points; dA = *|/ 1.01895, dn = +|- 0, dEa = +|- 0.302537 kJ/mol',
    ),
)
Literature(A = 1.1e12 cm3/mol/s, Ea = 41.8 kJ/mol) https://www.sciencedirect.com/science/article/pii/S0009261499000962

Thanks for your help!

**Comment by sthakris** [comment]
@xiaoruiDong : Is it possible to calculate the rate constant of barrierless (homo-sci) reaction with arkane.
