### ISSUE TITLE
DatabaseError: Families list must either all or none have prefix "!", but not a mix 

### ISSUE THREAD

**Issue by sthakris** [ReactionMechanismGenerator/RMG-Py#2372]
I was running a rmg job wil loading different families 

# Data sources
database(
    thermoLibraries = ['NOx2018', 'thermo_DFT_CCSDTF12_BAC', 'primaryThermoLibrary', 'CHN', 'CHON'],
    reactionLibraries = [("primaryNitrogenLibrary", False), ("Nitrogen_Dean_and_Bozzelli", False)],
    #reactionLibraries = [],
    seedMechanisms = ['seedNM'],
    kineticsDepositories = ['training'],
    kineticsFamilies = ['default', 'ch_pyrolysis', '!1,3_sigmatropic_rearrangement', 'Intra_RH_Add_Endocyclic', 'Intra_RH_Add_Exocyclic', 'Intra_R_Add_ExoTetCyclic', 'R_Addition_CSm', 'lone_electron_pair_bond', '1,2_XY_interchange', 'XY_elimination_hydroxyl', 'XY_Addition_MultipleBond'],
    kineticsEstimator = ['rate rules'],
)

I used the ! syntax as suggested in the RMG website input file preparation which suggest having ! in front of a familiy will not load/ignore that family. But the comment output by RMG is something else. Please seek below the error. 

rmgpy.exceptions.DatabaseError: Families list must either all or none have prefix "!", but not a mix

HOW to REPRODUCE : take any rmg case and just add !1,3_sigmatropic_rearrangement' which is in a default family list. 
You can also do !default and you will get same error. 

Can you please have a look it is something opposite to what is said in the RMG documentation in input file preparation

**Comment by hwpang** [comment]
If none of the families listed contains `!` in front, only the families listed are loaded. If all of the families listed contains `!` in front, all families will be loaded except for the ones you listed with `!`.

**Comment by sthakris** [comment]
In addition to the above issue. When I am loading the families without  !. I get

RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 2567, in get_kinetics_for_template
    if method.lower() == 'group additivity':
AttributeError: 'list' object has no attribute 'lower'

Further looking in to RMG.log file it points to 
Error: Error getting kinetics for reaction TNM(1) <=> [O-][N+](=O)[CH-][N+](=O)O[N+](=O)[O-](88).
.
.
.
molecule=[Molecule(smiles="[O-][N+](=O)[CH-][N+](=O)O[N+](=O)[O-]"), Molecule(smiles="[O-][N+](=O)[CH-][N+](=O)O[N+](=O)[O-]"), Molecule(smiles="[O-][N+](=O)[CH-][N+](=O)O[N+](=O)[O-]"), Molecule(smiles="[O-][N+](=O)[CH-][N+](=O)O[N+](=O)[O-]")], molecular_weight=(151.036,'amu'), energy_transfer_model=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85)))], family='1,3_sigmatropic_rearrangement', template=['Root'])

So when I comment the family pointed above by !1,3_sigmatropic_rearrangement, to avoid the error or skip it. 
It gives the previously mentioned error. 
I also looked on smiliar issue in git hub. It should be the missing rate from family or data base error. Correct me here if I am wrong.
