### ISSUE TITLE
Update reaction family

### ISSUE THREAD

**Issue by NUSCondy** [ReactionMechanismGenerator/RMG-Py#2373]
Dear Sir/Madam,

I am writing to ask how could us user to update the reaction family instead of the pre-defined reaction families? For example, I want to focus on R+O2=>RO2, this reaction family. The O2 addition is not available in RMG, right? If no, how could I add this to improve the performance of RMG?

Best regard!

**Comment by mjohnson541** [comment]
RMG considers the R + O2 => RO2 reaction to be a radical recombination. So the relevant family is R_Recombination. To improve that family you would create a library, convert the library reactions to training reactions and then retrain the tree using the associated notebooks in the ipython folders for RMG-Py and RMG-database.
