### ISSUE TITLE
Simplify the RMG anaconda Dependencies 

### ISSUE THREAD

**Issue by ChrisBNEU** [ReactionMechanismGenerator/RMG-Py#2375]
### Motivation or Problem
Made for the March 2023 Hack-a-thon at northeastern, may spawn other smaller issues for individual dependencies. 
The conda dependencies take a very long time to resolve, and are often simply incompatible with other packages. Packages like numpy, rdkit, cantera, etc. can be updated to a newer version or made more flexible. 

### Desired Solution
Run through the environment dependencies and determine which ones can be made less strict, switched to a new channel, or just updated.
```
name: rmg_env
channels:
  - defaults
  - rmg
  - conda-forge
  - cantera
dependencies:
  - cairo
  - cairocffi
  - cantera::cantera=2.5
  - conda-forge::cclib >=1.6.3
  - rmg::chemprop
  - coolprop
  - coverage
  - cython >=0.25.2
  - rmg::diffeqpy
  - ffmpeg
  - rmg::gprof2dot
  - graphviz
  - h5py
  - jinja2
  - jupyter
  - rmg::lpsolve55
  - markupsafe
  - matplotlib >=1.5
  - rmg::mopac
  - mpmath
  - rmg::muq2
  - networkx
  - nomkl
  - nose
  - rmg::numdifftools
  - numpy >=1.10.0
  - conda-forge::openbabel >= 3
  - pandas
  - psutil
  - rmg::pydas >=1.0.2
  - pydot
  - rmg::pydqed >=1.0.1
  - rmg::pyjulia
  - pymongo
  - pyparsing
  - rmg::pyrdl
  - rmg::pyrms
  - python >=3.7
  - pyyaml
  - rmg::quantities
  - rmg::rdkit >=2020.03.3.0
  - scikit-learn
  - scipy
  - rmg::symmetry
  - xlrd
  - xlwt
```

### Additional Context
[Relevant PR on ARC from kfir](https://github.com/ReactionMechanismGenerator/ARC/pull/566/files)

**Comment by JacksonBurns** [comment]
Also attempting to roll this into #2366

**Comment by JacksonBurns** [comment]
I'll just add that the updates described in this issue have been rolled into a number of other PRs and described in other issues. I will close this as 'resolved' just to indicate that this _precise_ issue has been addressed, but that it's part of a larger development effort in RMG.
