### ISSUE TITLE
AtomEnergyCorrectionError: Missing atom energies for LevelOfTheory

### ISSUE THREAD

**Issue by sthakris** [ReactionMechanismGenerator/RMG-Py#2397]
Hi, I was trying to calculate the rate constant for my case using Arkane. All the calculations were done by Gaussian. I get the following error.

"AtomEnergyCorrectionError: Missing atom energies for LevelOfTheory(method='b3lyp',basis='631+g',software='gaussian') "

In another closed issue #2179 on thermo, I see similar issue. But it is written there The issue is that the RMG-database only supports  
"LevelOfTheory(method='wb97xd',basis='augccpvtz',software='gaussian')"

Question, is do Arkane only support above method and basis for gaussian. 
Can you please provide your suggestion?

**Comment by kspieks** [comment]
Thanks for the question. I acknowledge my wording for this previous GitHub issue may have been confusing. In #2179, I intended to say that RMG-database supports `LevelOfTheory(method='wb97xd',basis='augccpvtz',software='gaussian')` so specifying `LevelOfTheory(method='wb97xd',basis='augccpvtz',software='qchem')` (i.e. different QM software) was the source of the error. Regarding your question, RMG-database supports all levels of theory that are found in the summary table on our website [here](http://reactionmechanismgenerator.github.io/RMG-Py/users/arkane/input.html#model-chemistry). If for some reason this table is ever out of date, 1. please let us know so we can update it but also 2. these [lines](https://github.com/ReactionMechanismGenerator/RMG-database/blob/master/input/quantum_corrections/data.py#L75-L370
) in RMG-databse will always have the latest information for which atom energy corrections are supported.
