### ISSUE TITLE
mopac issue + non reacting species issue

### ISSUE THREAD

**Issue by Fraixxer** [ReactionMechanismGenerator/RMG-Py#2404]
Please, I am trying to involve quantum calculations in my mechanism generation but I can't use mopac. Since  mopac is now open  source I downloaded it into  my rmg_env but it doesn't work. Though it was successfully installed into my rmg_env with conda install -c conda-forge mopac but when I test it with which mopac it just points me to the directory  without showing the mopac version installed. However, when I navigate the folders I still see mopac 2016 file in bin under rmg_env.  Please, how can I get it to work. 

Second question: I also realized some of the species or radicals in my mechanism do not react though rmg has generated thermo data for those species. Please, what could be the cause.

**Comment by JacksonBurns** [comment]
Hi @Fraixxer could you split this into two separate issues, i.e. take the second question and open a new issue? Also, please provide some more details in this new issue -- what is the species, as much of the mechanism as you have, etc.

Could you also provide a specific error (the output from your terminal, for instance) related to the mopac issue?
