### ISSUE TITLE
Question: Inconsistencies between docs string and the documentations. 

### ISSUE THREAD

**Issue by kfir4444** [ReactionMechanismGenerator/RMG-Py#2405]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [x] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

### Context
I am trying to create the `HinderedRotor` object.

### Question
Hey, In the [documentations](http://reactionmechanismgenerator.github.io/RMG-Py/users/arkane/input.html#with-hindered-free-rotors), towards the end of the paragraph, there is a bit of code the related to creating the `HinderedRotor` object:
```python
rotors = [
    HinderedRotor(scanLog=Log('ethane_scan_1.log'), pivots=[1,5], top=[1,2,3,4], symmetry=3, fit='best'),
    #HinderedRotor(scanLog=ScanLog('C2H6_rotor_1.txt'), pivots=[1,5], top=[1,2,3,4], symmetry=3, fit='best'),
    #FreeRotor(pivots=[1,5], top=[1,2,3,4], symmetry=3),
]
```
However, in the documentations for the `HinderedRotor` class, it seems like the input should be different:
```python
help(HinderedRotor)
>>> Help on class HinderedRotor in module rmgpy.statmech.torsion:

> class HinderedRotor(Torsion)
>  |  HinderedRotor(inertia=None, symmetry=1, barrier=None, fourier=None, rotationalConstant=None, quantum=True, semiclassical=True, frequency=None, energies=None)
>  |  
>  |  A statistical mechanical model of a one-dimensional hindered rotor.
>  |  The attributes are:
>  |  
>  |  ======================== ===================================================
>  |  Attribute                Description
>  |  ======================== ===================================================
>  |  `inertia`                The moment of inertia of the rotor
>  |  `rotationalConstant`     The rotational constant of the rotor
>  |  `symmetry`               The symmetry number of the rotor
>  |  `fourier`                The :math:`2 x N` array of Fourier series coefficients
>  |  `barrier`                The barrier height of the cosine potential
>  |  `quantum`                ``True`` to use the quantum mechanical model, ``False`` to use the classical model
>  |  `semiclassical`          ``True`` to use the semiclassical correction, ``False`` otherwise
>  |  ======================== ===================================================
>  |  
>  |  Note that the moment of inertia and the rotational constant are simply two
>  |  ways of representing the same quantity; only one of these can be specified
>  |  independently.

```
There is seemed to be an inconsistency between the two representations of the object. Is this intentional, or am I missing something?
Thanks :)

### Installation Information
Describe your installation method and system information if applicable.
 - OS (include version if known): Ubuntu 22
 - Installation method: source with anaconda
 - RMG version information:
   
   - RMG-Py: 3.1.0-634-g402abd161
   - RMG-database: 3.0.0-584-gbd1319070

**Comment by mjohnson541** [comment]
RMG uses a different constructor when running the input file than it does in the raw code. I suspect this is the corresponding constructor: https://github.com/ReactionMechanismGenerator/RMG-Py/blob/1c1b9b052b53886e025264d8169103b2922ee623/arkane/statmech.py#L237.

**Comment by kfir4444** [comment]
Thanks @mjohnson541,
Should it not be `hinderedRotor` instead of `HinderedRotor` then?

**Comment by mjohnson541** [comment]
It's related to how RMG defines functions when reading input files: https://github.com/ReactionMechanismGenerator/RMG-Py/blob/1c1b9b052b53886e025264d8169103b2922ee623/arkane/statmech.py#L354

**Comment by kfir4444** [comment]
Ok, thanks @mjohnson541!
