### ISSUE TITLE
Python 3.7 End-of-Life and Upgrading to Python 3.11

### ISSUE THREAD

**Issue by JacksonBurns** [ReactionMechanismGenerator/RMG-Py#2445]
Python 3.7 is reaching end of life [this summer](https://devguide.python.org/versions/) and will no longer receive security updates. Ultimately because we distribute on Docker now we can continue to ship the outdated Python version for a while before things actually _stop_ working, but it will atrophy.

We will need to increment our minor version of Python, preferably to 3.11 for the speed improvements and longest support window. I say this rather than just shooting for 3.8, since I believe the additional effort of incrementing 4 minor versions will not be much worse than 1 (see below).

I anticipate that this will be an absolute nightmare, but a (forced) opportunity for some cleanup.
 - `pydas` and `pydqed` were originally written in Python 2.7, hacked to get into Python 3.7, and will likely go kicking and screaming into Python 3.11
 - `pyjulia` and `diffeqpy` are both presumably locked to Python 3.7
 - Our _remarkably_ outdated build of chemprop (0.0.1) only supports 3.7, though chemprop v2 will support 3.11 and newer.
 - many of the packages we built and 'maintain' on the conda rmg channel expect Python 3.7 and will need to be rebuilt (just especially the ones mentioned above)
 - Cython will need to be incremented to 0.29 (from 0.27)

This might take long enough that we end up targeting 3.12, which promises some very nice parallelism improvements so maybe that isn't such a bad thing.

Some things we should get done (wrt clearing tech debt) before attempting this:
 - release v3.2.0 via #2311 
 - #975 delete what we aren't using so don't have to try and upgrade it for no purpose
 - #2380 as broken as nose is now, it will be even more broken-er in Python 3.11
 - environment updates, including #2375, #2379 (and its PR #2443), and #2322 which should hopefully make it easier to upgrade by reducing # of dependencies and their complexity
 - Fix #2442 (and #2429 by consequence) so that we can validate results with RMS reactors in 3.11 versions

**Comment by JacksonBurns** [comment]
#2429 was resolved by @JacksonBurns in the process of assisting @hwpang, who is resolving #2442 via #2446

**Comment by rwest** [comment]
Regarding chemprop. You wrote above and in the environment.yml file:
- "Our remarkably outdated build of chemprop (0.0.1) only supports 3.7, though chemprop v2 will support 3.11 and newer."
- "Our build of this is version 0.0.1 (!!) and we are using parts of the API that are now gone. Need a serious PR to fix this."

How significant are the changes needed, and who is best to work on it? I'm rather unfamiliar with chemprop and RMG's use of it. Could someone start a draft PR to continue discussion?

**Comment by JacksonBurns** [comment]
#2456 may end up being related - we have a custom build of `rdkit` on the `rmg` conda channel that should also be replaced before attempting to increment to Python 3.11.

**Comment by rwest** [comment]
Should this be a "project" with multiple issues or and PRs?

**Comment by JacksonBurns** [comment]
> #2456 may end up being related - we have a custom build of `rdkit` on the `rmg` conda channel that should also be replaced before attempting to increment to Python 3.11.

It wasn't

**Comment by JacksonBurns** [comment]
> Should this be a "project" with multiple issues or and PRs?

It could be, I just don't love the projects interface - open to trying it though.

**Comment by JacksonBurns** [comment]
Our build of symmetry should be replaced with [this](https://github.com/MBI-Theory/symmetry).

**Comment by JacksonBurns** [comment]
Migrating this to [GitHub Project Board](https://github.com/orgs/ReactionMechanismGenerator/projects/11/views/1?layout=board).
