### ISSUE TITLE
CI for Mac frequently timing out

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#2453]
The continuous integration test runners for MacOS keeps timing out on the installing Julia dependencies step. 

This PR for example is marked to auto merge once the tests pass, but twice in a row the MacOS test has hung for 6 hours then timed out:
https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/5158881342

If we keep the MacOS test as a requirement for merging, it is going to hold everything up, unless we can figure out why that step is hanging and fix it.

**Comment by JacksonBurns** [comment]
From what I have seen there is no consensus on why this happens, and all the solutions people have are random (see [here](https://github.com/actions/runner/issues/2063) and [here](https://github.com/actions/runner/issues/1326), for example). I'm fine with removing the requirement that the macos CI passes for PRs to be merged, but leaving it on as a "nice to have" for PRs and something that will at least run successfully overnight to hopefully catch any serious problems.

**Comment by JacksonBurns** [comment]
Resolved in #2456 which now allows the Mac Runner to fail. If possible, re-evaluate requiring this runner to pass in the future if the GitHub mac runners become more consistent (see https://github.com/actions/runner/issues/2063).
