### ISSUE TITLE
RDKit should be upgraded, potentially requiring API changes

### ISSUE THREAD

**Issue by JacksonBurns** [ReactionMechanismGenerator/RMG-Py#2462]
We currently use an RMG channel build of RDKit, which we should replace with one of the official builds from conda-forge.

Unfortunately this transition will require first getting everything _else_ to Python 3.11 so that we can then resolve an updated version of RDKit, and then we can see where the API breaks.

**Comment by JacksonBurns** [comment]
See #1850 and the associated PR for previous efforts with changing RDKit versions.

**Comment by JacksonBurns** [comment]
Still needed - can do on self-hosted now.

**Comment by xiaoruiDong** [comment]
I am willing to help fix potential API breaks after we upgrade to Python 3.11.
