### ISSUE TITLE
Enable Consistency checking for Molecule objects with Reaction Bonds

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#2465]
Right now we broadly have to turn off consistency checking to generate Molecules with reaction bonds, however, we should be able to apply some of the consistency checking.

**Comment by JacksonBurns** [comment]
@mjohnson541 could you provide an example/some lines of code where the behavior you describe is taking place?

**Comment by mjohnson541** [comment]
This isn't exactly unintended behavior...I needed a 2D representation of the transition state that was independent of template...so I represented the forming/breaking bonds as a new bond type...however, adding that to RMG is different than making RMG understand these bonds electronically...so right now I turn off the consistency checker when creating them so it doesn't get upset about bond orders/electrons, however, it would be better to adapt the consistency checker to handle these representations and throw errors when appropriate...perhaps the simplest case would be: 
1 H u0 p0 c0 {R,2}
2 H u0 p0 c0 {R,1}
But starting from any reactants and replacing the breaking/forming bonds with R bonds is technically valid...this does mean that there are multiple valid representations, which isn't ideal long term...but at the moment I'm primarily using this for 3D to 2D extractions where the electronic representation is handled with a consistent algorithm...

To clarify, for the moment this is only being used downstream in Pynta, but I plan to use the datasets I'm generating to build tools reliant on this representation that will integrate with RMG.
