### ISSUE TITLE
Error when Running Halogen Example

### ISSUE THREAD

**Issue by timmallo** [ReactionMechanismGenerator/RMG-Py#2467]
### Bug Description
When running the halogen example, I get a kinetics error, not finding a reverse reaction.

### How To Reproduce
1. Download RMG using Docker
2. Copy the input file code from Github for the Halogen Example
3. Make a directory in Docker to place the copied input file
4. Copy input file from Github into the new directory
5. Run the example input file using the command "python-jl /rmg/RMG-Py/rmg.py input.py"

### Expected Behavior
The job ran perfectly fine for about 45 minutes before returning an error. 

### Installation Information
Describe your installation method and system information.
 - OS: Windows 10 (Using Command Prompt/Docker)
 - Installation method: Docker
 - RMG version information: 3.1.1

### Additional Context
Error: Debugging why no reaction was found...
Error: Checking whether the family's forbidden species have affected reaction generation...
Error: Still experiencing error: Expecting one matching reverse reaction, not 2 in reaction family F_Abstraction for forward reaction C#C[CH]F + [O]C=C([O])C=C(F)F <=> [CH]C#C + [O]C=C(C=C(F)F)OF.

Traceback (most recent call last):
  File "/miniconda/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 308, in main
    python(**vars(ns))
  File "/miniconda/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 59, in python
    scope = runpy.run_path(script, run_name="__main__")
  File "/miniconda/envs/rmg_env/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/miniconda/envs/rmg_env/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/miniconda/envs/rmg_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/rmg/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/rmg/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/rmg/RMG-Py/rmgpy/rmg/main.py", line 1026, in execute
    trimolecular_react=self.trimolecular_react)
  File "/rmg/RMG-Py/rmgpy/rmg/model.py", line 685, in enlarge
    procnum=procnum)
  File "/rmg/RMG-Py/rmgpy/rmg/react.py", line 172, in react_all
    return react(spc_fam_tuples, procnum), [fam_tuple[0] for fam_tuple in spc_fam_tuples]
  File "/rmg/RMG-Py/rmgpy/rmg/react.py", line 66, in react
    reactions = list(map(_react_species_star, spc_fam_tuples))
  File "/rmg/RMG-Py/rmgpy/rmg/react.py", line 79, in _react_species_star
    return react_species(*args)
  File "/rmg/RMG-Py/rmgpy/rmg/react.py", line 94, in react_species
    reactions = get_db('kinetics').generate_reactions_from_families(species_tuple, only_families=only_families)
  File "/rmg/RMG-Py/rmgpy/data/kinetics/database.py", line 546, in generate_reactions_from_families
    successful = family.add_reverse_attribute(rxn)
  File "/rmg/RMG-Py/rmgpy/data/kinetics/family.py", line 1880, in add_reverse_attribute
    "{1}.".format(self.label, str(rxn)))
rmgpy.exceptions.KineticsError: Did not find reverse reaction in reaction family F_Abstraction for reaction C#C[CH]F + [O]C=C([O])C=C(F)F <=> [CH]C#C + [O]C=C(C=C(F)F)OF.

**Comment by rwest** [comment]
Sorry - we added the example to RMG-Py before the relevant updates to the database were merged into RMG-database. You could try a different branch of the database like halogens_kinetics_paper, or wait a while for us to get it merged.

**Comment by JacksonBurns** [comment]
@timmallo I think when you pulled the docker container you likely used `docker pull reactionmechanismgenerator/rmg:latest` instead of `docker pull reactionmechanismgenerator/rmg:3.1.1`. The `latest` tag is _not_ intended for general use and is a developer tool.

I will clarify this inside the Docker image itself.

**Comment by timmallo** [comment]
I believe I used docker pull reactionmechanismgenerator/rmg:3.1.1 . I did not know the latest tag existed.

**Comment by timmallo** [comment]
I used the file on github, copied the text, and manually added it to the docker container.

**Comment by JacksonBurns** [comment]
> I used the file on github, copied the text, and manually added it to the docker container.

Ah I apologize, I should have re-read the original post. @rwest's comment still stands - we will get the new version out asap.

**Comment by timmallo** [comment]
All good! Thank you both for the help and speedy responses!

**Comment by JacksonBurns** [comment]
This issue will be resolved by the release of v3.2.0 and the corresponding Docker image - I have linked this issue to the PR, and it will automatically close after the release since the issue will be resolved.
