### ISSUE TITLE
choose different units in output files

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#248]
In the input file, one can specify units in the options section, but right now only SI-units are allowed. They are also set by default, so in practice one cannot choose the units used in the output.

``` python
options(
    units='si',
)
```

This would be a new welcomed feature, since many people (still) reason in kcal rather than kJ for energies.

A new keyword could be "kcal", which would convert all energy related quantities (e.g. Ea's, enthalpies, entropies, Cp's) to kcal, rather than the default unit.

``` python
options(
    units='kcal',
)
```

As rmg-py already uses the quantities module for unit conversion, this should not be a very complicated job, as far as I understand.

**Comment by JacksonBurns** [comment]
Support for more unit types in the output file would be a nice to have - adding this to the Long-Term projects board, but closing the issue for now.
