### ISSUE TITLE
Improve `detecting_cutting_label` to specialize in adjacency list

### ISSUE THREAD

**Issue by hwpang** [ReactionMechanismGenerator/RMG-Py#2520]
### Motivation or Problem
See https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2518 for the issue and https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2519 for a quick fix.

### Desired Solution
Currently, `detecting_cutting_label` is written for smiles-like string. It can be improved to be robust against adjacency list to handle "R" in the species label to replace the current quick fix https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2519.

**Comment by JacksonBurns** [comment]
@hwpang is this issue resolved by #2519 or is there a more thorough patch needed?

**Comment by hwpang** [comment]
@JacksonBurns #2519 is only a quick patch and a more thorough patch is needed. Currently, `detecting_cutting_label` is only written for smiles-like string but is used on adjacency list, which causes the issue described in #2518.
