### ISSUE TITLE
Running RMG with methylcyclohexane especially at low temperature

### ISSUE THREAD

**Issue by MS-VT** [ReactionMechanismGenerator/RMG-Py#2521]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [x] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

### Context
I want to extend an existing reaction mechanism (the basis chemistry of the DLR Concise reaction mechanism) with new reaction pathways for methylcyclohexane. 
I defined an ranged reactor for a broad range of temperature (600-1200) and pressure (1-40 bar). I already tried several options, including: anchor reactor, branching, minimizing tolerance move to core, minimzing pressure range, increasing the maximumEdgeSpeices to 200000, ... .

As thermo libraries I used:
- DLR Concise (always for all cases)
- primaryThermoLibrary (always for all cases)
- Glarborg/C3 (sometimes)

As reaction libraries I used:
- DLR Concise (always for all cases)
- Glarborg/C3 (sometimes)

The case would run for eternity if I didn't stop it. I stoped it after ~ 2 weeks running.

### Question
How can I adjust the input-file so that the case sucessfully generates a mechanism? 

### Installation Information
 - RMG version information:
   - RMG-Py: 3.10
   - RMG-database: 3.1.0

Thanks a lot for new sugesstions  to solve this issue.

One of the input files of my cases:
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/12212686/input.txt)

**Comment by alongd** [comment]
Hi, what termination criteria are you using?
(also, are you studying pyrolysis or oxidation?)

**Comment by mjohnson541** [comment]
Is your issue simply that the run doesn't complete? 

Having the run complete is very overrated, RMG tolerances don't operate like solver tolerances. Being converged to a flux tolerance of 0.01 isn't as well defined of a thing as it sounds. If you have reasonable settings (as noted in the docs) usually it's better to run out with those settings, sample models every so many species and stop when the properties you are interested in converge. 

If you're interested more details on why this is the case are available in this paper: https://chemrxiv.org/engage/chemrxiv/article-details/643b666008c86922ff143507.

**Comment by MS-VT** [comment]
Thanks for the quick answer. Yes my issue is, that it dosen't complete. How can I know if my model is apropiate enough to describe for example the chemical igintion delay times? Testing the cheminkin files which are produced for these conditions?
I don't understand the last sentence with "sample models". In my input files I have only one component (methylcyclohexane or something else) and air. 

Thanks for the paper I will have a look on that.

**Comment by mjohnson541** [comment]
So as RMG runs it saves Chemkin and RMS files each iteration. Every so many iterations (after reaching an expected size) we take a mechanism file and run the simulations we are interested, when the target properties we are interested stop changing we consider the RMG run converged with respect to that property.

**Comment by JacksonBurns** [comment]
Closing as resolved, lacking any indication otherwise.
