### ISSUE TITLE
Docker Installation Issues

### ISSUE THREAD

**Issue by vbarber820** [ReactionMechanismGenerator/RMG-Py#2528]
### Bug Description
When following the instructions for docker install in the User guide, I am unable to run rmg jobs. I get a long error message that begins with: 

Invalid instruction at 0x7f3d95496518: 0x62, 0xf1, 0x7d, 0x08, 0x76, 0xc1, 0xc5, 0xf8, 0x44, 0xc0, 0xc5, 0xfb, 0x93, 0xc0, 0xa8

and ends with:
main at julia (unknown line)
unknown function (ip: 0x7f3e202b7d8f)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x556abafe5098)
Allocations: 14823093 (Pool: 14818814; Big: 4279); GC: 21
Illegal instruction

### How To Reproduce
Steps to reproduce the behavior.
1. Install Docker on Windows 11 Pro
2. in powershell, docker pull reactionmechanismgenerator/rmg:3.2.0
3. docker run --name rmgcontainer -v "C:\Users\rmguser\myrmgfiles:/rmg/RMG-Py/myrmgfiles" -it reactionmechanismgenerator/rmg:3.2.0
4. cd examples/rmg/minimal
5. python-jl rmg/RMG-Py/rmg.py input.py

### Expected Behavior
run the minimal example

### Installation Information
Describe your installation method and system information.
 - OS Windows 11
 - Installation method: Docker
 - RMG version information: 3.2.0 (error persists with "latest" tag as well)
 

### Additional Context
Same procedure is working as expected for 3.1.1

**Comment by JacksonBurns** [comment]
@vbarber820 I have pushed a new `reactionmechanismgenerator/rmg:3.2.0` to Docker that no longer has the invalid instruction error. Please download and give this a shot on your end and let us know if anything goes wrong. If the problem persists or a new one pops up, please feel free to re-open this or make a new issue!

For @ReactionMechanismGenerator/rmg-py-devs in the future, I had to downgrade the Julia version to between 1.8.5 and <1.9 as well as change the branch of RMS to `for_rmg`, as we did in #2523.

**Comment by rwest** [comment]
I think I'm missing something.
Docker image is built automatically each night. Is part of that build not testing it?

And the 3.2.0 "release" is essentially you labeling an automatically built image to the the official release one?

**Comment by JacksonBurns** [comment]
Yeah I don't know why this happened - the minimal example is run in the nightly, and the previous build of 3.2.0 was the one from GitHub actions that I just labeled as 3.2.0. Maybe I am misremembering and I actually built 3.2.0 locally based on the wrong commit :shrug: ?
