### ISSUE TITLE
SMILES strings are wrong for some gas-phase species

### ISSUE THREAD

**Issue by bjkreitz** [ReactionMechanismGenerator/RMG-Py#2536]
### Bug Description
There seems to be an issue with the conversion of adjacency lists to SMILES strings. Some SMILES strings do not represent the correct adjacency list. 

### How To Reproduce
Generate the SMILES string from the following adjacency list: 

```
multiplicity 3
1 *3 C u1 p1 c0 {2,S}
2 *3 C u1 p1 c0 {1,S}
```

using the RMG website Molecule Search tool, results in [CH2][CH2]. Feeding this SMILES string back to RMG yields the following adjacency list:

```
multiplicity 3
1 C u1 p0 c0 {2,S} {3,S} {4,S}
2 C u1 p0 c0 {1,S} {5,S} {6,S}
3 H u0 p0 c0 {1,S}
4 H u0 p0 c0 {1,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
```

The correct smiles string would be [C][C]. This issue occurred for several gas-phase species, which have many free electrons.  

### Expected Behavior
RMG should return the correct SMILES strings.

**Comment by JacksonBurns** [comment]
@bjkreitz could you include some example code to demonstrate how you are feeding this string back to RMG?

**Comment by bjkreitz** [comment]
You can test this using the RMG website. I'm not feeding the SMILES string back to RMG. I was working on an unrelated PR, where I was looking at `get_desorbed_molecules` function in `molecule.py`. The function printed out completely wrong SMILES strings, although the adjacency list are correct, which made me think that the function was wrong. Using the website tool reproduced the error.

**Comment by JacksonBurns** [comment]
Ok, when I run on RMG-website the SMILES string `[C][C]` is converted into this:
```
multiplicity 7
1 C u3 p0 c0 {2,S}
2 C u3 p0 c0 {1,S}
```
and `[CH2][CH2]` is converted into this:
```
multiplicity 3
1 C u1 p0 c0 {2,S} {3,S} {4,S}
2 C u1 p0 c0 {1,S} {5,S} {6,S}
3 H u0 p0 c0 {1,S}
4 H u0 p0 c0 {1,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
```

Now when running in RMG-Py from the docker container, I get this:
```
(rmg_env) root@8e8b9955bf56:/rmg/RMG-Py# python-jl
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:12:33) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from rmgpy.molecule import Molecule
>>> cc = Molecule(smiles="[C][C]")
>>> cc
Molecule(smiles="[C][C]")
>>> ch2ch2 = Molecule(smiles="[CH2][CH2]")
>>> ch2ch2
Molecule(smiles="[CH2][CH2]")
>>> cc.get_desorbed_molecules()
[]
>>> ch2ch2.get_desorbed_molecules()
[]
>>> cc.to_adjacency_list()
'multiplicity 7\n1 C u3 p0 c0 {2,S}\n2 C u3 p0 c0 {1,S}\n'
>>> ch2ch2.to_adjacency_list()
'multiplicity 3\n1 C u1 p0 c0 {2,S} {3,S} {4,S}\n2 C u1 p0 c0 {1,S} {5,S} {6,S}\n3 H u0 p0 c0 {1,S}\n4 H u0 p0 c0 {1,S}\n5 H u0 p0 c0 {2,S}\n6 H u0 p0 c0 {2,S}\n'
>>> 
```
RMG-Py does seem to be correctly returning the adjacency list in each case.

Am I doing this backwards? Are we supposed to be able to initialize a molecule from the adjacency list and then convert to SMILES (and that is what is broken here?)?

**Comment by JacksonBurns** [comment]
Ah apologies I think I finally understand. You are trying to do this: `adjacency list --RMG-website--> SMILES --RMG-Py--> adjacency list` and the two adjacency lists do not match.

Now with the adjacency list you provided I get:
```python
>>> cc_from_adj = Molecule()
>>> cc_from_adj.from_adjacency_list("multiplicity 3\n1 *3 C u1 p1 c0 {2,S}\n2 *3 C u1 p1 c0 {1,S}")
Molecule(smiles="[CH2][CH2]")
```

RMG-website calls `Molecule.from_adjacency_list` in the background, so RMG-Py and RMG-website behave the same.

As you mentioned it seems that doing it 'backwards' resulted in a workable adjacency list. If you think that the adjacency list you provided _should_ map to the expected smiles (`[C][C]`), then I think there actually is a bug. Otherwise, this must be an ill-formed adjacency list (and this issue can be closed). Please let us know which is the case (or otherwise), and thanks for your patience!

**Comment by bjkreitz** [comment]
I think that I have to explain the issue in more detail. Apologies for making this not clear in the beginning. I discovered this issue while going through the `molecule.py` file and the `get_desorbed_molecules` function. When we want to estimate the thermo properties of an adsorbate, we desorb it to get the thermo properties of the gas-phase precursor and apply adsorption corrections. In order to desorb a species binding through e.g. C, the bonds with the surface are broken and an unpaired electron (single bond), two unpaired electrons (double bond) or an unpaired electron and a lone pair (triple bond) are added to the carbon atom. 

In case a thermo estimate was used for an adsorbate, RMG writes the SMILES string of the corresponding gas-phase species into the output.html file. For the adsorbate `[Pt]#CC#[Pt]`, which has two Pt-C triple bonds, the gas-phase species has the following adjacency list:

```
multiplicity 3
1 *3 C u1 p1 c0 {2,S}
2 *3 C u1 p1 c0 {1,S}
```

leading to the following SMILES string in the output.html file `[CH2][CH2]`. This SMILES string is obviously wrong for the gas-phase species that is used for the thermo estimate. I think that this is not an issue during the mechanism generation since SMILES strings are only used for the output. However, this is can be confusing when looking at the output and could be identified as an error. 

The reason why we get the wrong SMILES strings is because RDkit has an issue with lone pairs on the C atom. 

Using only unpaired electrons results in 

```
multiplicity 3
1 *3 C u3 p0 c0 {2,S}
2 *3 C u3 p0 c0 {1,S}

```
giving the SMILES string of `[C][C]`, which is a more correct representation of the gas-phase species that is used. However, we would use the wrong thermo estimate of the gas-phase species since the lone pair structure is more stable (I think?). What should we do?

**Comment by hwpang** [comment]
@bjkreitz Thanks for bringing up this issue! I believe this is a problem at the translator and should not affect the gas-phase thermo estimation. The wrong SMILES string RMG wrote into the output.html comes from calling the `to_smiles` attribute under `Molecule`, which uses the `to_smiles` function at `rmgpy.molecule.translator`.

```
from rmgpy.molecule.molecule import Molecule
from rmgpy.molecule.translator import to_smiles

cc_adjulist = """
multiplicity 3
1 *3 C u1 p1 c0 {2,S}
2 *3 C u1 p1 c0 {1,S}
"""

cc = Molecule().from_adjacency_list(cc_adjulist)

cc.to_smiles() # uses rdkit backend and gives the wrong smiles [CH2][CH2]

to_smiles(cc, backend="rdkit") # uses rdkit backend and gives the wrong smiles [CH2][CH2]

to_smiles(cc, backend="openbabel") # uses openbabel backend and gives the correct smiles [C][C]

cc.atoms # returns [<Atom 'C.'>, <Atom 'C.'>], meaning the incorrect Hs only exists in rdkit generated SMILEs, not in the molecule object
```

The thermo estimation of the gas-phase species should base on the Molecule object, so the thermo estimation should be correct.

**Comment by rwest** [comment]
Could we fix the rdkit back-end, so that both back-ends (rdkit and openbabel) give the right SMILES?
That would be a preferable fix than making it choose the back-end that works right, and worth aiming for if possible.
It sounds like Bjarne has identified the problem as being to do with the lone pairs?

**Comment by rwest** [comment]
To elaborate further - RDKit must have *some* way to represent C#C, and ideally calling to_rdkit (or whatever our function is called) on a Molecule that represents it would get there.

**Comment by JacksonBurns** [comment]
Thanks for the comments, all. We met about this offline and now have a working patch going in #2545 that should solve this problem at a general level. I will request your reviews as well @bjkreitz and @rwest
