### ISSUE TITLE
[Running an RMG job] Error "ERROR: Unable to dlopen(cxxpath) in parent!" when checking the operation of RMG immediately after installation

### ISSUE THREAD

**Issue by Filozofafa** [ReactionMechanismGenerator/RMG-Py#2540]
### Context
Good day! I installed RMG using Anaconda on YouTube video https://www.youtube.com/watch?v=kn7eeHAYbt4&t=563s . When trying to initialize a superminimal task, the terminal throws the following error:
```
(rmg_env) anoon@anoon-VirtualBox:~/RMG/RMG-Py/examples/rmg/superminimal$ rmg.py input.py
ERROR: Unable to dlopen(cxxpath) in parent!
Message: /home/anoon/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cantera/../../../libstdc++.so.6s a live Julia runtime.

Note: Use `LibJulia` to fully control the initialization of
the Julia runtime.

Parameters
==========

init_julia : bool
If True, try to initialize the Julia runtime. If this code is
being called from inside an already running Julia, the flag should
be passed as False so the interpreter isn't re-initialized.

Note that it is safe to call this class constructor twice in the
same process with `init_julia` set to True, as a global reference
is kept to avoid re-initializing it. The purpose of the flag is
only to manage situations when Julia was initialized from outside
this code.

runtime : str
Custom Julia binary, e.g. "/usr/local/bin/julia" or "julia-1.0.0".

debug : bool
If True, print some debugging information to STDERR
: cannot open shared object file: File name too long
``` 

### Question
What do I need to do to successfully run the solution of the problem in RMG? I have recently started to get acquainted with Ubuntu OS and RMG, please help with the problem. Thank you in advance!
### Installation Information
Describe your installation method and system information if applicable.
 - OS Ubuntu 23.04
 - Installation from source, with anaconda
 - RMG version 3.1.0
 - RMG-Py

**Comment by Filozofafa** [comment]
> Hi @Filozofafa! Were you able to resolve the issue? If so, what was the solution? If not, we would be happy to help fix it.

Good afternoon! Unfortunately, at first I thought that there was a solution to the problem, but later it turned out that the problem was not solved. Closed the problem too soon:)

**Comment by JacksonBurns** [comment]
Got it, let's take a look.

That tutorial video is a little bit out of date (our apologies on that), so I reccomend you start by following the latest installation instructions found here: https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html

An easier alternative is to use our suggested installation method Docker, which makes the installation process much easier. The instructions for that can be found here: https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/index.html#recommended-install-docker

Please let us know how this goes!

**Comment by Filozofafa** [comment]
> Got it, let's take a look.
> 
> That tutorial video is a little bit out of date (our apologies on that), so I reccomend you start by following the latest installation instructions found here: https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html
> 
> An easier alternative is to use our suggested installation method Docker, which makes the installation process much easier. The instructions for that can be found here: https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/index.html#recommended-install-docker
> 
> Please let us know how this goes!

Hello! Thank you very much! The problem was solved by installing RMG at this link: https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html

**Comment by JacksonBurns** [comment]
You are very welcome, thanks for using RMG!
