### ISSUE TITLE
ImportErrors during make test after install on Mac M1 system

### ISSUE THREAD

**Issue by tdprice-858** [ReactionMechanismGenerator/RMG-Py#2544]
### Bug Description
I installed RMG on my apple M1 machine per the instruction on http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html. RMG installed without issue. However, when attempting to run `make test` I got numerous errors related to ImportError and ModuleNotFoundError.
ex) 
ImportError while importing test module '/Users/tdprice/Desktop/Desktop/RMG-Py/test/arkane/commonTest.py'.
ImportError: cannot import name 'convert_imaginary_freq_to_negative_float' from 'arkane.common' (/Users/tdprice/miniconda3/envs/rmg_env/lib/python3.7/site-packages/arkane/common.py

Interestingly, the `make eg1` ran fine. And I have ran my own simulation without any related issues.

### How To Reproduce
`make test`
### Expected Behavior
Successful completion of the test.

### Installation Information
Describe your installation method and system information.
 - macOS Big Sur version 11.7.9 (chip: Apple M1)
 - Installation method: Installation by source through miniconda
 - RMG version information: 3.1.0; Build: py37he38e130_383; 
   git describe --tags = 3.2.0-113-g2212786fb

**Comment by JacksonBurns** [comment]
Hi @tdprice-858 thanks for trying out RMG!

This bug seems to crop up when there are version issues. I noticed in your installation information that you listed 3.1.0 and 3.2.0 - could you clarify exactly which version of RMG you are using? Or did you install using the `main` branch?

**Comment by tdprice-858** [comment]
Hi @JacksonBurns, thanks for the quick response!

I installed using the main branch. When I check the version with `conda list -f rmg` I get 3.1.0.
If I use the command `git describe --tags` I see 3.2.0-113-g2212786fb.

**Comment by JacksonBurns** [comment]
Sure thing!

It seems like you actually have _two_ RMGs on your machine - one is the source installation (verison 3.2.0+latest commits) and one is the RMG binary build from conda (version 3.1.0). If you are installing from source, you don't need the 3.1.0 binary from conda. I would suggest doing this to fix it:
 1. remove your existing conda environment with `conda remove -n rmg_env --all` (or whatever the environment is called besides `rmg_env`)
 2. Build a new conda environment using the `environment.yml` file included with the source code for RMG that you downloaded
 3. Pick up the build instructions again from [Step 8: activate conda environment](https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html#:~:text=Activate%20conda%20environment)

This should make it so that you don't have the older copy of RMG floating around. Let me know if this works or if other issues arise!

**Comment by tdprice-858** [comment]
This seems to have worked, however, I am getting an error still when running the `make test`.

`FAILED test/rmgpy/rmg/mainTest.py::TestProfiling::test_make_profile_graph - AssertionError: assert False
ERROR test/rmgpy/rmg/mainTest.py::TestProfiling::test_make_profile_graph - FileNotFoundError: [Errno 2] No such file or directory: ’/Users/tdprice/Desktop/Desktop/R...
===================================== 1 failed, 1869 passed, 32 skipped, 34 deselected, 37 warnings, 1 error in 473.28s (0:07:53) =====================================
make: *** [test] Error 1`

Here is the traceback....

`=============================================================================== ERRORS ================================================================================
_____________________________________________________ ERROR at teardown of TestProfiling.test_make_profile_graph ______________________________________________________

cls = <class 'mainTest.TestProfiling'>

    @classmethod
    def teardown_class(cls):
        """A function that is run ONCE after all unit tests in this class."""
    
        if cls.display_found:  # Remove output PDF
>           os.remove(os.path.join(cls.test_dir, "RMG.profile.dot.pdf"))
E           FileNotFoundError: [Errno 2] No such file or directory: '/Users/tdprice/Desktop/Desktop/RMG-py/rmgpy/../test/rmgpy/test_data/mainTest/RMG.profile.dot.pdf'

test/rmgpy/rmg/mainTest.py:354: FileNotFoundError
============================================================================== FAILURES ===============================================================================
________________________________________________________________ TestProfiling.test_make_profile_graph ________________________________________________________________

self = <mainTest.TestProfiling object at 0x7f8e1b3f2bd0>, mock_logging = <MagicMock name='logging' id='140249117351184'>

    @patch("rmgpy.rmg.main.logging")
    def test_make_profile_graph(self, mock_logging):
        """
        Test that `make_profile_graph` function behaves properly given the current display state
        """
        profile_file = os.path.join(self.test_dir, "RMG.profile")
        make_profile_graph(profile_file)
        if self.display_found:  # Check that the profile graph was made
>           assert os.path.exists(os.path.join(self.test_dir, "RMG.profile.dot.pdf"))
E           AssertionError: assert False
E            +  where False = <function exists at 0x7f8e58ee5d40>('/Users/tdprice/Desktop/Desktop/RMG-py/rmgpy/../test/rmgpy/test_data/mainTest/RMG.profile.dot.pdf')
E            +    where <function exists at 0x7f8e58ee5d40> = <module 'posixpath' from '/Users/tdprice/miniconda3/envs/rmg_env/lib/python3.7/posixpath.py'>.exists
E            +      where <module 'posixpath' from '/Users/tdprice/miniconda3/envs/rmg_env/lib/python3.7/posixpath.py'> = os.path
E            +    and   '/Users/tdprice/Desktop/Desktop/RMG-py/rmgpy/../test/rmgpy/test_data/mainTest/RMG.profile.dot.pdf' = <function join at 0x7f8e681a6dd0>('/Users/tdprice/Desktop/Desktop/RMG-py/rmgpy/../test/rmgpy/test_data/mainTest', 'RMG.profile.dot.pdf')
E            +      where <function join at 0x7f8e681a6dd0> = <module 'posixpath' from '/Users/tdprice/miniconda3/envs/rmg_env/lib/python3.7/posixpath.py'>.join
E            +        where <module 'posixpath' from '/Users/tdprice/miniconda3/envs/rmg_env/lib/python3.7/posixpath.py'> = os.path
E            +      and   '/Users/tdprice/Desktop/Desktop/RMG-py/rmgpy/../test/rmgpy/test_data/mainTest' = <mainTest.TestProfiling object at 0x7f8e1b3f2bd0>.test_dir

test/rmgpy/rmg/mainTest.py:336: AssertionError
`

**Comment by tdprice-858** [comment]
@JacksonBurns Thank you for all the help! I have been able to proceed without issue on my own simulation.
