### ISSUE TITLE
Scope of pressure dependence block in RMG

### ISSUE THREAD

**Issue by PoojaNem** [ReactionMechanismGenerator/RMG-Py#2546]
I have recently started to work on RMG and am trying to understand intricacies involved in the process of generating kinetic models. After several attempts, I could generate a mechanism for butane fuel for which laminar flame speed result for freely propagating flame closely conforms with the available experimental data. However, I do have some difficulty understanding pressure dependent reactions generated by RMG for this case. Below are my concerns along with RMG input.py and chem.cti (Cantera output) files. It will be helpful if someone can provide clarification for the same. 
**Concern 1:**
Pressure dependence is turned off in my RMG input.py file. But the final output (chem.cti) still has reactions marked as pdep_arrhenius (Reaction 3, line 1056), falloff (Reaction 1, line 1044) and three body reactions (Reaction 16, line 1123). Is it normal? As per my understanding all the three forms of the reactions are pressure dependent and should not be in the final model if pressure dependence is off. Also, these reactions can be a part of the model if available in the seed mechanism, but my input file does not have any seed mechanism.
**Concern 2:**
Is the “pressureDependence” block in input.py file only for the reactions marked as pdep_arrhenius or does it have any effect on other pressure dependent reaction types (falloff and three body)?
**Concern 3:**
There are identical reactions in the final model: Reaction 3 (line 1056, pdep_arrhenius) and Reaction 4 (line 1062, arrhenius). Both reactions are from the same reaction library CurranPentane (index 189, line 2244 and index 190, line 2275) and marked duplicate. However, in the RMG generated model these are not duplicate. In addition, converting chem.cti to chem.yaml in Cantera doesn’t throw any duplicate error.    
[chem.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/12671039/chem.txt)
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/12671045/input.txt)

**Comment by hwpang** [comment]
@PoojaNem Thanks for bringing this issue to our attention!
**Concern 1:**
When the pressure dependence is turned off in the RMG input.py file, it only means that RMG will not generate the pressure dependence networks itself. However, if pressure dependent reactions exist in the reaction libraries specified in the input.py and all the species involved in these reactions are in the core, RMG will add these reactions from the edge to the core. RMG doesn't filter out the pressure dependence networks in the reaction libraries specified in the input.py when the pressure dependence is turned off. So in your case, these pressure dependent reactions are likely sourced from the reaction libraries. If you look at the `chem_annotated.inp` file RMG generates, it should indicate the source of these reactions.

**Concern 2:**
RMG's pressureDependence block only generates pressure network in the format of Chebyshev. In your case, the other format of pressure dependent reaction types are likely sourced from the reaction libraries specified in the input.py file.

**Concern 3:**
I'm a little confused by this question and would like more details. Do you mean that these two reactions are not marked as duplicate in the `chem_annotated.inp` RMG generates? I think there have been many discussions on the problem of marking the duplicates of pressure dependent reactions, but I'm not sure what is the conclusion on this. I will tag some people who have extensively worked on pressure dependent system, and hopefully they can input on this matter, @rwest @alongd @mjohnson541.

**Comment by rwest** [comment]
Chiming in on point 3 (where I was tagged):

You could argue that if one is pressure dependent and one is not, then the two reactions are:
`A + B (+M) <=> C (+M)`
and
`A + B <=> C`
and they are not the same so should not be considered duplicates.

I _think_ this is how both RMG and Cantera think.  I'm not sure about how Chemkin thinks, i.e. whether it would want `DUPICATE` flags. I do know that it's nigh-on impossible to satisfy both Chemkin and Cantera in this regard, and much time has been spent trying.  
There are many issues on the issue tracker [here](https://github.com/ReactionMechanismGenerator/RMG-Py/issues?q=duplicate+sort%3Aupdated-desc), some closed, some open, some abandoned.

There is also this open Pull Request which maybe should be rebased and reviewed again, as it may be related.
https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1856

**Comment by PoojaNem** [comment]
Thank you very much @hwpang and @rwest for the clarification.

**Comment by JacksonBurns** [comment]
I'll close this as completed given the above comment. Thanks for your contributions, everyone!
