### ISSUE TITLE
NetworkError: No unimolecular isomers left to explore!

### ISSUE THREAD

**Issue by wenjunzhong** [ReactionMechanismGenerator/RMG-Py#2556]
Hello RMG developers,
When I run input.py to generate the mechanism, I always get an error: NetworkError: No unimolecular isomers left to explore, what's the problem? How do you modify  it?

**Comment by wenjunzhong** [comment]
Hi,I am delighted to receive your response. I have enclosed my input file (input.py) in the attachments. Furthermore, I have noticed that while using a mechanism from the RMG library as my seed mechanism, I can successfully generate a new mechanism. However, when I attempt to import other researchers' mechanisms using the ImportChemkinLibrary function to incorporate them into the RMG library, and then use them as my seed mechanism to generate a new mechanism, an error occurs ：NetworkError : No unimolecular isomers left to explore!&nbsp;I have tried substituting several researchers' mechanisms, but the error persists. It is possible that I might be encountering an issue when using the ImportChemkinLibrary function to convert the mechanism files. So I have also included my "inp" file (otomo.inp)and "dictionary" file (dictionary-otomo.txt) in the attachments.&nbsp;If you have the time and it's convenient for you, I would greatly appreciate any insights or suggestions you may have.Of course, if this is inconvenient for you, I completely understand.Thank you once again for your assistance, and I look forward to hearing your thoughts.


Warm regards,


wenjunzhong


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReactionMechanismGenerator/RMG-Py"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月12日(星期四) 晚上11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ReactionMechanismGenerator/RMG-Py] NetworkError: No unimolecular isomers left to explore! (Issue #2556)





 
Hi @wenjunzhong could you provide the input file you are using so we can attempt to debug the issue? If it contains information you cannot share, please only share as much as you can.

**Comment by JacksonBurns** [comment]
Hello @wenjunzhong unfortunately the files did not attach correctly, could you send them to our organizational email please: rmg_dev@mit.edu

My apologies for the inconvenience.

Jackson

**Comment by JacksonBurns** [comment]
For the other developers, here are the files that were provided, for future reference:

[dictionary-otomo.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/12930678/dictionary-otomo.txt)
[otomo.inp.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/12930686/otomo.inp.txt)
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/12930687/input.txt)

**Comment by wenjunzhong** [comment]
Hi,thank&nbsp;you&nbsp;for&nbsp;your&nbsp;prompt&nbsp;response&nbsp;and&nbsp;assistance.&nbsp;I&nbsp;have&nbsp;come&nbsp;across&nbsp;a&nbsp;new&nbsp;issue&nbsp;and&nbsp;I&nbsp;was&nbsp;wondering&nbsp;if&nbsp;you&nbsp;could&nbsp;help&nbsp;me&nbsp;with&nbsp;it.&nbsp;When&nbsp;I&nbsp;run&nbsp;`rmg.py&nbsp;input.py`&nbsp;using&nbsp;the&nbsp;`input.txt`&nbsp;file&nbsp;you&nbsp;provided&nbsp;to&nbsp;generate&nbsp;the&nbsp;mechanism,&nbsp;I&nbsp;encounter&nbsp;an&nbsp;error&nbsp;in&nbsp;the&nbsp;code:&nbsp;AssertionError: Reaction system T is above pressure_dependence range.


Afterwards,&nbsp;I&nbsp;adjusted&nbsp;the&nbsp;temperature&nbsp;range&nbsp;of&nbsp;the&nbsp;pressure-dependent&nbsp;module&nbsp;to&nbsp;be&nbsp;between&nbsp;200&nbsp;and&nbsp;2200K.&nbsp;Upon&nbsp;re-running&nbsp;the&nbsp;file,&nbsp;I&nbsp;encountered&nbsp;the&nbsp;same&nbsp;error&nbsp;as&nbsp;before:&nbsp;NetworkError: No unimolecular isomers left to explore! I&nbsp;have&nbsp;been&nbsp;unable&nbsp;to&nbsp;identify&nbsp;the&nbsp;source&nbsp;of&nbsp;the&nbsp;issue.Could&nbsp;you&nbsp;please&nbsp;let&nbsp;me&nbsp;know&nbsp;what&nbsp;modifications&nbsp;you&nbsp;made&nbsp;in&nbsp;the&nbsp;previous&nbsp;file?
I&nbsp;have&nbsp;attached&nbsp;the&nbsp;modified&nbsp;`input.txt`&nbsp;file&nbsp;with&nbsp;the&nbsp;adjusted&nbsp;temperatures.

I&nbsp;apologize&nbsp;for&nbsp;the&nbsp;inconvenience&nbsp;of&nbsp;reaching&nbsp;out&nbsp;again.&nbsp;Your&nbsp;assistance&nbsp;is&nbsp;greatly&nbsp;appreciated, I apologize if this has caused you any inconvenience.&nbsp; Once&nbsp;again,&nbsp;thank&nbsp;you&nbsp;for&nbsp;your&nbsp;help.&nbsp;I&nbsp;look&nbsp;forward&nbsp;to&nbsp;hearing&nbsp;your&nbsp;insights.

Warm&nbsp;regards,



wenjunzhong


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReactionMechanismGenerator/RMG-Py"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月17日(星期二) 晚上11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ReactionMechanismGenerator/RMG-Py] NetworkError: No unimolecular isomers left to explore! (Issue #2556)





 
For the other developers, here are the files that were provided, for future reference:
 
dictionary-otomo.txt
 otomo.inp.txt
 input.txt
