### ISSUE TITLE
IndexError: list index out of range ；Output file /home/XXX/RMG/RMGcal/hexadienepyrolysis/QMscratch/pm3/LSAIKWFIJPVRGV-UHFFFAOYSA-N.log does not exist.

### ISSUE THREAD

**Issue by liqiang4567** [ReactionMechanismGenerator/RMG-Py#2558]
When I used RMG to calculate the pyrolysis of 1, 3-Hexadiene in the example, gaussian09 was used to calculate the thermodynamic data, and the following error occurred. May I ask how to solve it?

**error.log:**
Traceback (most recent call last):
  File "/home/xxx/software/anaconda3/envs/rmg/bin/rmg.py", line 118, in <module>
    main()
  File "/home/xxx/software/anaconda3/envs/rmg/bin/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/xxx/software/anaconda3/envs/rmg/lib/python3.7/site-packages/rmgpy/rmg/main.py", line 673, in execute
    self.initialize(**kwargs)
  File "/home/xxx/software/anaconda3/envs/rmg/lib/python3.7/site-packages/rmgpy/rmg/main.py", line 496, in initialize
    self.load_database()
  File "/home/xxx/software/anaconda3/envs/rmg/lib/python3.7/site-packages/rmgpy/rmg/main.py", line 420, in load_database
    family.add_rules_from_training(thermo_database=self.database.thermo)
  File "/home/xxx/software/anaconda3/envs/rmg/lib/python3.7/site-packages/rmgpy/data/kinetics/family.py", line 1269, in add_rules_from_training
    reactant.thermo = thermo_database.get_thermo_data(reactant, training_set=True, metal_to_scale_to=metal)
  File "/home/xxx/software/anaconda3/envs/rmg/lib/python3.7/site-packages/rmgpy/data/thermo.py", line 1343, in get_thermo_data
    thermo0 = quantum_mechanics.get_thermo_data(original_molecule)  # returns None if it fails
  File "/home/xxx/software/anaconda3/envs/rmg/lib/python3.7/site-packages/rmgpy/qm/main.py", line 224, in get_thermo_data
    thermo0 = qm_molecule_calculator.generate_thermo_data()
  File "/home/xxx/software/anaconda3/envs/rmg/lib/python3.7/site-packages/rmgpy/qm/molecule.py", line 363, in generate_thermo_data
    self.qm_data = self.generate_qm_data()
  File "/home/xxx/software/anaconda3/envs/rmg/lib/python3.7/site-packages/rmgpy/qm/gaussian.py", line 265, in generate_qm_data
    success = self.run()
  File "/home/xxx/software/anaconda3/envs/rmg/lib/python3.7/site-packages/rmgpy/qm/gaussian.py", line 100, in run
    return self.verify_output_file()
  File "/home/xxx/software/anaconda3/envs/rmg/lib/python3.7/site-packages/rmgpy/qm/gaussian.py", line 170, in verify_output_file
    qm_data = self.parse()
  File "/home/xxx/software/anaconda3/envs/rmg/lib/python3.7/site-packages/rmgpy/qm/molecule.py", line 340, in parse
    qm_data = parse_cclib_data(cclib_data, radical_number + 1)  # Should `radical_number+1` be `self.molecule.multiplicity` in the next line of code? It's the electronic ground state degeneracy.
  File "/home/xxx/software/anaconda3/envs/rmg/lib/python3.7/site-packages/rmgpy/qm/qmdata.py", line 101, in parse_cclib_data
    rotational_constants = (cclib_data.rotcons[-1], 'cm^-1')
**IndexError: list index out of range**

**out.log:**
Original composition:
HXD13 = 0.0006829
CH4 = 0.104
H2 = 0.0156
N2 = 0.8797

Normalized mole fractions:
HXD13 = 0.0006829116777896902
CH4 = 0.10400177843041115
H2 = 0.015600266764561672
N2 = 0.8797150431272375

Setting the quantum mechanics scratchDirectory to /home/xxx/RMG/RMGcal/hexadienepyrolysis/QMscratch/pm3
Creating directory /home/xxx/RMG/RMGcal/hexadienepyrolysis/QMfiles/pm3 for QM files.
Creating directory /home/xxx/RMG/RMGcal/hexadienepyrolysis/QMscratch/pm3 for QM files.

1350 K
Loading transport library from GRI-Mech.py in /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/transport/libraries...
Loading transport library from NOx2018.py in /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/transport/libraries...
Loading transport library from OneDMinN2.py in /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/transport/libraries...
Loading transport library from PrimaryTransportLibrary.py in /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/transport/libraries...
Loading transport group database from /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/transport/groups...
Loading frequencies group database from /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/statmech/groups...
Loading Platts additivity group database from /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/solvation/groups...
Loading thermodynamics library from primaryThermoLibrary.py in /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/thermo/libraries...
Loading thermodynamics library from GRI-Mech3.0.py in /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/thermo/libraries...
Loading thermodynamics group database from /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/thermo/groups...
Adding rate rules from training set in kinetics families...
Output file **/home/xxx/RMG/RMGcal/hexadienepyrolysis/QMscratch/pm3/LSAIKWFIJPVRGV-UHFFFAOYSA-N.log does not exist.**
**Trying GaussianMolPM3 attempt 1 of 36 on molecule C=C=CC1C=CC=CC1=C.**
but this /home/xxx/RMG/RMGcal/hexadienepyrolysis/QMscratch/pm3/LSAIKWFIJPVRGV-UHFFFAOYSA-N.log  is exist.

**Comment by JacksonBurns** [comment]
Hi @liqiang4567 thank you for using RMG.

Can you try installing an older version of cclib, something like `conda install -c conda-forge cclib==1.6.0` and see if the solution is resolved? The latest versions of `cclib` have been causing problems for us.

**Comment by liqiang4567** [comment]
Thank you for your reply. When I updated cclib=1.6.0, conda made rmg version 3.0.0 (previously 3.1.0), running rmg=3.0.0, the following error message appeared

WARNING:root:No normalization for BCUT2D_MWHI
WARNING:root:No normalization for BCUT2D_MWLOW
WARNING:root:No normalization for BCUT2D_CHGHI
WARNING:root:No normalization for BCUT2D_CHGLO
WARNING:root:No normalization for BCUT2D_LOGPHI
WARNING:root:No normalization for BCUT2D_LOGPLOW
WARNING:root:No normalization for BCUT2D_MRHI
WARNING:root:No normalization for BCUT2D_MRLOW
Traceback (most recent call last):
  File "/home/qli/software/anaconda3/envs/rmg/bin/rmg.py", line 48, in <module>
    from rmgpy.rmg.main import RMG, initialize_log, process_profile_stats, make_profile_graph
  File "/home/qli/software/anaconda3/envs/rmg/lib/python3.7/site-packages/rmgpy/rmg/main.py", line 68, in <module>
    from rmgpy.rmg.listener import SimulationProfileWriter, SimulationProfilePlotter
  File "/home/qli/software/anaconda3/envs/rmg/lib/python3.7/site-packages/rmgpy/rmg/listener.py", line 34, in <module>
    from rmgpy.tools.plot import SimulationPlot
  File "/home/qli/software/anaconda3/envs/rmg/lib/python3.7/site-packages/rmgpy/tools/plot.py", line 37, in <module>
    mpl.use('Agg', warn=False, force=False)
TypeError: use() got an unexpected keyword argument 'warn'

**Comment by liqiang4567** [comment]
Thank you for your reply. I installed cclib=1.6.0, but the error is still as  follows

Warning: Initial mole fractions do not sum to one; normalizing.

Original composition:
HXD13 = 0.0006829
CH4 = 0.104
H2 = 0.0156
N2 = 0.8797

Normalized mole fractions:
HXD13 = 0.0006829116777896902
CH4 = 0.10400177843041115
H2 = 0.015600266764561672
N2 = 0.8797150431272375

Setting the quantum mechanics scratchDirectory to /home/xxx/RMG/RMGcal/hexadienepyrolysis/QMscratch/pm3
Creating directory /home/xxx/RMG/RMGcal/hexadienepyrolysis/QMfiles/pm3 for QM files.
Creating directory /home/xxx/RMG/RMGcal/hexadienepyrolysis/QMscratch/pm3 for QM files.

1350 K
Loading transport library from GRI-Mech.py in /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/transport/libraries...
Loading transport library from NOx2018.py in /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/transport/libraries...
Loading transport library from OneDMinN2.py in /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/transport/libraries...
Loading transport library from PrimaryTransportLibrary.py in /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/transport/libraries...
Loading transport group database from /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/transport/groups...
Loading frequencies group database from /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/statmech/groups...
Loading Platts additivity group database from /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/solvation/groups...
Loading thermodynamics library from primaryThermoLibrary.py in /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/thermo/libraries...
Loading thermodynamics library from GRI-Mech3.0.py in /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/thermo/libraries...
Loading thermodynamics group database from /home/xxx/software/anaconda3/envs/rmg/share/rmgdatabase/thermo/groups...
Adding rate rules from training set in kinetics families...
Output file /home/xxx/RMG/RMGcal/hexadienepyrolysis/QMscratch/pm3/LSAIKWFIJPVRGV-UHFFFAOYSA-N.log does not exist.
Trying GaussianMolPM3 attempt 1 of 36 on molecule C=C=CC1C=CC=CC1=C.


> Hi @liqiang4567 thank you for using RMG.
> 
> Can you try installing an older version of cclib, something like `conda install -c conda-forge cclib==1.6.0` and see if the solution is resolved? The latest versions of `cclib` have been causing problems for us.

![图片1](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/76583592/979a8c01-d626-44a7-9a1e-f4e0cc96c0bc)

**Comment by JacksonBurns** [comment]
Hi @liqiang4567 I apologize that this did not fix the issue.

I have done more investigation, and this issue has actually been reported before in #1864 and we were unable to resolve it then, either. We are limited in our ability to test on Gaussian due to licensing constraints.

Which version of RMG are you using, and by what method was it installed? This may work on RMG v3.1.0, as reported in the linked pull request.

**Comment by liqiang4567** [comment]
> Hi @liqiang4567 I apologize that this did not fix the issue.
> 
> I have done more investigation, and this issue has actually been reported before in #1864 and we were unable to resolve it then, either. We are limited in our ability to test on Gaussian due to licensing constraints.
> 
> Which version of RMG are you using, and by what method was it installed? This may work on RMG v3.1.0, as reported in the linked pull request.

Thank you for your reply. The RMG I used is 3.1.0, and the error in quantumMechanics using gaussian and mopac is the same.

Installation is according to https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaUser.html

Commands:

conda create -c defaults -c rmg -c rdkit -c cantera -c pytorch -c conda-forge --name rmg_env rmg rmgdatabase

![图片1](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/76583592/6d957dde-7674-46a9-a126-b3eefe540b7b)
