### ISSUE TITLE
Potential Bug in Critical Pressure Estimation

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#2569]
I was contacted and asked about a potential issue with the critical pressure estimation in RMG. Critical pressure is computed using Joback method described: 

Joback & Reid (1987): (https://doi.org/10.1080/00986448708960487[)](https://doi.org/10.1080/00986448708960487))
Joback’s thesis https://dspace.mit.edu/handle/1721.1/15374

They suggested that RMG is using the equations from the thesis and the groups from the paper, which is a problem for critical pressure because it uses different sign conventions for the group additive term (in the thesis the group terms are added, in the paper they are subtracted). 

I took a cursory look at this and it looks like they are correct. I checked the history this system has been touched a few times making me a bit surprised this difference hasn't been noticed. In theory it can be fixed by simply changing the sign in the equation to negative.

**Comment by rwest** [comment]
https://github.com/ReactionMechanismGenerator/RMG-database/commit/22c2ec91f2be4ca5d878034f3f0df6f14b958c7e
