### ISSUE TITLE
toRDKitMol sanization issues

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#257]
Running an ethylnitrite example and it crashes because the new calculateCyclicSymmetryNumber calls molecule.toRDKitMol (https://github.com/GreenGroup/RMG-Py/blob/master/rmgpy/molecule/symmetry.py#L340)

Turns out we generate saturated compounds when calculating thermo for radical species by calling estimateRadicalThermoViaHBI in data/thermo.py.  We sometimes produce saturated compounds that are not approved by RDKit.  The radical and saturated compound in question are:

Radical:

```
1 C 0 0 {2,S} {6,S} {7,S} {8,S}
2 C 1 0 {1,S} {3,S} {9,S}
3 O 0 2 {2,S} {4,S}
4 N 0 1 {3,S} {5,D}
5 O 0 2 {4,D}
6 H 0 0 {1,S}
7 H 0 0 {1,S}
8 H 0 0 {1,S}
9 H 0 0 {2,S}
```

Saturated Compound:

```
1  C 0 0 {2,S} {3,S} {4,S} {5,S}
2  N 0 0 {1,S} {4,S} {6,S} {7,S}
3  C 0 0 {1,S} {8,S} {9,S} {10,S}
4  O 0 2 {1,S} {2,S}
5  H 0 0 {1,S}
6  O 0 3 {2,S}
7  H 0 0 {2,S}
8  H 0 0 {3,S}
9  H 0 0 {3,S}
10 H 0 0 {3,S}
```

Which generates an explicit valence > 4 for N error.  Any thoughts on how to fix this problem? 

Typing the following in the command line:

``` python
    from rmgpy.molecule import Molecule
    mol = Molecule(SMILES="C1([NH+](O1)[O-])C")
    mol.toRDKitMol()
```

will lead straight to the problem.

**Comment by mliu49** [comment]
The `calculateCyclicSymmetryNumber` method no longer converts to RDKitMol, so this issue should no longer apply. In general, we use OpenBabel for generating identifiers for nitrogen compounds to avoid this issue.
