### ISSUE TITLE
Error: Invalid k(E) values computed for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC1CC2[C]=CC1C2(6089)". Error: Increasing number of grains did not decrease error enough (Current badness: 0.3, previous 0.3).

### ISSUE THREAD

**Issue by liqiang4567** [ReactionMechanismGenerator/RMG-Py#2572]
Hello, when I used RMG 3.1.0 to calculate heptane-eg5 in the example, the following error occurred, how can I solve it? The input files and some of the output files are listed below.

input.py

# Data sources
database(
    thermoLibraries = ['primaryThermoLibrary'],
    reactionLibraries = [],
    seedMechanisms = [],
    kineticsDepositories = ['training'], 
    kineticsFamilies = 'default',
    kineticsEstimator = 'rate rules',
)

# Constraints on generated species
generatedSpeciesConstraints(
maximumRadicalElectrons = 1,
)

# List of species
species(
    label='n-heptane',
reactive=True,
    structure=SMILES("CCCCCCC"),
)

species(
    label='Ar',
    reactive=False,
    structure=SMILES("[Ar]"),
)

simpleReactor(
    temperature=(1000,'K'),
    pressure=(400,'Pa'),
    initialMoleFractions={
        "n-heptane": 0.02,
        "Ar": 0.98,
    },
    terminationConversion={
        'n-heptane': 0.99,
    },
    terminationTime=(1e6,'s'),
)

simpleReactor(
    temperature=(1500,'K'),
    pressure=(400,'Pa'),
    initialMoleFractions={
        "n-heptane": 0.02,
        "Ar": 0.98,
    },
    terminationConversion={
        'n-heptane': 0.99,
    },
    terminationTime=(1e6,'s'),
)

simpleReactor(
temperature=(2000,"K"),
pressure=(400,"Pa"),
initialMoleFractions={
"n-heptane": 0.02,
"Ar": 0.98,
},
terminationConversion={
"n-heptane": 0.99,
},
terminationTime=(1e6,"s"),
)

simulator(
    atol=1e-16,
    rtol=1e-8,
)

model(
    toleranceMoveToCore=0.02,
    toleranceInterruptSimulation=0.02
)

pressureDependence(
    method='modified strong collision',
    maximumGrainSize=(0.5,'kcal/mol'),
    minimumNumberOfGrains=250,
    temperatures=(300,3000,'K',8),
    pressures=(0.001,100,'bar',5),
    interpolation=('Chebyshev', 6, 4),
)

options(
    units='si',
    generateOutputHTML=True,
    generatePlots=True,
    saveEdgeSpecies=True,
    saveSimulationProfiles=True,
)

RMG.log:

Path reactions:
    [CH2]C(CC=C)C1C=C=CC1(5521) <=> C1=CCC=C1(3385) + [CH2]C=CC=C(3232)      701.292 kJ/mol
    [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CC[CH]CC1C=C=CC1(6086)      792.773 kJ/mol
    [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC[CH]C1C=C=CC1(6087)      792.773 kJ/mol
    [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC1CC2=CCC1[CH]2(6088)      812.541 kJ/mol
    [CH2]C(CC=C)C1C=C=CC1(5521) <=> C1=CCC(C2C[CH]CC2)C=1(5531)      688.903 kJ/mol
    [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC1CC2[C]=CC1C2(6089)      828.649 kJ/mol
    [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC1CC2[C]=CCC21(6090)      674.678 kJ/mol
    [CH2]C(CC=C)C1C=C=CC1(5521) <=> [CH2]C1CC(C2C=C=CC2)C1(6091)      691.832 kJ/mol
    H(9) + C=CCC(=C)C1C=C=CC1(6092) <=> [CH2]C(CC=C)C1C=C=CC1(5521)      762.965 kJ/mol
    [C]1=CCC=C1(5155) + C=CCC=C(180) <=> [CH2]C(CC=C)C1C=C=CC1(5521)      632.838 kJ/mol
    [CH2]C=C(50) + C=CC1C=C=CC1(3384) <=> [CH2]C(CC=C)C1C=C=CC1(5521)      716.257 kJ/mol
    [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CC(27) + C=C[C]1C=C=CC1(5888)      748.773 kJ/mol
    [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CC[C](C)C1C=C=CC1(6093)      735.517 kJ/mol
    [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC(C)[C]1C=C=CC1(6094)      754.174 kJ/mol
    [CH2]C(CC=C)C1C=C=CC1(5521) <=> [CH2]C=CC(C)C1C=C=CC1(5519)      752.082 kJ/mol
    [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC(C)C1[CH]C=C=C1(6095)      689.322 kJ/mol
    [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC(C)C1[C]=C=CC1(6096)      743.652 kJ/mol
    C=[C]CC(C)C1C=C=CC1(5440) <=> [CH2]C(CC=C)C1C=C=CC1(5521)      709.906 kJ/mol
    [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC(C)C1C=C=[C]C1(6097)      676.188 kJ/mol
    [CH]=CCC(C)C1C=C=CC1(6098) <=> [CH2]C(CC=C)C1C=C=CC1(5521)      707.892 kJ/mol
Net reactions:
========================================================================

Calculating densities of states for PDepNetwork #5868 network...
Using 732 grains from 298.18 to 1827.43 kJ/mol in steps of 2.09 kJ/mol to compute densities of states
Calculating phenomenological rate coefficients for [CH]=CCC(C)C1C=C=CC1(6098) <=> [CH2]C(CC=C)C1C=C=CC1(5521)...
Using 303 grains from 298.18 to 929.97 kJ/mol in steps of 2.09 kJ/mol to compute the k(T,P) values at 302.617 K
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CC[CH]CC1C=C=CC1(6086)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC[CH]C1C=C=CC1(6087)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C1=CCC(C2C[CH]CC2)C=1(5531)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC(C)[C]1C=C=CC1(6094)".
Using 307 grains from 298.18 to 938.33 kJ/mol in steps of 2.09 kJ/mol to compute the k(T,P) values at 324.619 K
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CC[CH]CC1C=C=CC1(6086)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC[CH]C1C=C=CC1(6087)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C1=CCC(C2C[CH]CC2)C=1(5531)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC(C)[C]1C=C=CC1(6094)".
Using 315 grains from 298.18 to 955.07 kJ/mol in steps of 2.09 kJ/mol to compute the k(T,P) values at 374.997 K
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CC[CH]CC1C=C=CC1(6086)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC[CH]C1C=C=CC1(6087)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C1=CCC(C2C[CH]CC2)C=1(5531)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC(C)[C]1C=C=CC1(6094)".
Using 330 grains from 298.18 to 986.45 kJ/mol in steps of 2.09 kJ/mol to compute the k(T,P) values at 470.374 K
Using 358 grains from 298.18 to 1045.03 kJ/mol in steps of 2.09 kJ/mol to compute the k(T,P) values at 649.057 K
Using 414 grains from 298.18 to 1162.18 kJ/mol in steps of 2.09 kJ/mol to compute the k(T,P) values at 1000.02 K
Using 526 grains from 298.18 to 1396.48 kJ/mol in steps of 2.09 kJ/mol to compute the k(T,P) values at 1706.11 K
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CC[CH]CC1C=C=CC1(6086)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC[CH]C1C=C=CC1(6087)".
Using 694 grains from 298.18 to 1747.94 kJ/mol in steps of 2.09 kJ/mol to compute the k(T,P) values at 2761.25 K
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CC[CH]CC1C=C=CC1(6086)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC[CH]C1C=C=CC1(6087)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC1CC2=CCC1[CH]2(6088)".
Warning: For path reaction [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC1CC2[C]=CC1C2(6089):
Warning:     Expected kf(2761.25 K) = 1.35939e+08
Warning:       Actual kf(2761.25 K) = 6.65688e+07
Warning:     Expected Keq(2761.25 K) = 25.3721
Warning:       Actual Keq(2761.25 K) = 0
Warning: Increasing number of grains, decreasing grain size and trying again. (Current badness: 0.3)
Using 1387 grains from 298.18 to 1747.94 kJ/mol in steps of 1.05 kJ/mol to compute the k(T,P) values at 2761.25 K
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CC[CH]CC1C=C=CC1(6086)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC[CH]C1C=C=CC1(6087)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC1CC2=CCC1[CH]2(6088)".
Warning: For path reaction [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC1CC2[C]=CC1C2(6089):
Warning:     Expected kf(2761.25 K) = 1.35939e+08
Warning:       Actual kf(2761.25 K) = 6.64357e+07
Warning:     Expected Keq(2761.25 K) = 25.3721
Warning:       Actual Keq(2761.25 K) = 0
Warning: Increasing number of grains, decreasing grain size and trying again. (Current badness: 0.3)
Using 2772 grains from 298.18 to 1747.41 kJ/mol in steps of 0.52 kJ/mol to compute the k(T,P) values at 2761.25 K
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CC[CH]CC1C=C=CC1(6086)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC[CH]C1C=C=CC1(6087)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC1CC2=CCC1[CH]2(6088)".
Warning: For path reaction [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC1CC2[C]=CC1C2(6089):
Warning:     Expected kf(2761.25 K) = 1.35939e+08
Warning:       Actual kf(2761.25 K) = 6.6234e+07
Warning:     Expected Keq(2761.25 K) = 25.3721
Warning:       Actual Keq(2761.25 K) = 0
Warning: Increasing number of grains, decreasing grain size and trying again. (Current badness: 0.3)
Using 5542 grains from 298.18 to 1747.15 kJ/mol in steps of 0.26 kJ/mol to compute the k(T,P) values at 2761.25 K
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CC[CH]CC1C=C=CC1(6086)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC[CH]C1C=C=CC1(6087)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC1CC2=CCC1[CH]2(6088)".
Warning: For path reaction [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC1CC2[C]=CC1C2(6089):
Warning:     Expected kf(2761.25 K) = 1.35939e+08
Warning:       Actual kf(2761.25 K) = 6.61331e+07
Warning:     Expected Keq(2761.25 K) = 25.3721
Warning:       Actual Keq(2761.25 K) = 0
Warning: Increasing number of grains, decreasing grain size and trying again. (Current badness: 0.3)
Using 11082 grains from 298.18 to 1747.02 kJ/mol in steps of 0.13 kJ/mol to compute the k(T,P) values at 2761.25 K
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CC[CH]CC1C=C=CC1(6086)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC[CH]C1C=C=CC1(6087)".
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC1CC2=CCC1[CH]2(6088)".
Warning: For path reaction [CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC1CC2[C]=CC1C2(6089):
Warning:     Expected kf(2761.25 K) = 1.35939e+08
Warning:       Actual kf(2761.25 K) = 6.60827e+07
Warning:     Expected Keq(2761.25 K) = 25.3721
Warning:       Actual Keq(2761.25 K) = 0
Error: Invalid k(E) values computed for path reaction "[CH2]C(CC=C)C1C=C=CC1(5521) <=> C=CCC1CC2[C]=CC1C2(6089)".
Error: Increasing number of grains did not decrease error enough (Current badness: 0.3, previous 0.3). Something must be wrong with network PDepNetwork #5868
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =       90
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      120
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      120
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      120
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      120
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      105
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      120
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      125
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      125
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      125
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      115
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      110
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      110
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      110
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      110
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      110
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      110
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      110
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      110
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      110
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      110
 dbolsm(). more than (i1)=itmax iterations solving bounded least squares problem.
 error number =    22, message level =     1
 i1 =      120

**Comment by JacksonBurns** [comment]
@liqiang4567 thanks for the thorough report!

@xiaoruiDong do you have any idea what might be wrong here?
