### ISSUE TITLE
How to unload kinetic parameters of reverse reactions?

### ISSUE THREAD

**Issue by Filozofafa** [ReactionMechanismGenerator/RMG-Py#2576]
### Context
I am working with a large model (about 950 reactions), and I need to upload kinetic data for all reactions. From the chem.inc file I can download all the data on the kinetics of direct reactions at once, but for reverse reactions I can't find all these data in one place.

### Question
Where can I find the kinetic parameters of the feedback reactions in order to unload them immediately, and not engage in manual interrupting?

**Comment by JacksonBurns** [comment]
@Filozofafa thanks for using RMG!

From what software or tool did you retrieve the `chem.inc` file? RMG includes some tools for importing data from some other related software, but not all.

**Comment by Filozofafa** [comment]
> @Filozofafa thanks for using RMG!
> 
> From what software or tool did you retrieve the `chem.inc` file? RMG includes some tools for importing data from some other related software, but not all.

Good day! Are there any tools in RMG that allow you to automatically download the parameters of feedback reactions (underlined in the picture)? I can easily pull the parameters of direct reactions from the check.inp file, but I have to manually rewrite the parameters of reverse reactions, which is quite problematic if there are about 10,000 reactions in the resulting model.
![2023-11-22 124712](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/144851267/e026cc13-ebbc-4804-8481-701f1f999126)
