### ISSUE TITLE
Attempting to explore isomer that is not found in product channels.

### ISSUE THREAD

**Issue by kfir4444** [ReactionMechanismGenerator/RMG-Py#2577]
### Bug Description
When trying to produce a model for a system, an explored isomer is not found in the products channel. This issue persist, even with different parameters, such as:
```python
    toleranceKeepInEdge=0.0005,
    toleranceMoveToCore=0.005,
```

```python
    toleranceKeepInEdge=0.001,
    toleranceMoveToCore=0.01,
```

The same error occurs with different isomeres:
```
Traceback (most recent call last):
  File "/home/kfir/mambaforge/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 308, in main
    python(**vars(ns))
  File "/home/kfir/mambaforge/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 59, in python
    scope = runpy.run_path(script, run_name="__main__")
  File "/home/kfir/mambaforge/envs/rmg_env/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/kfir/mambaforge/envs/rmg_env/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/kfir/mambaforge/envs/rmg_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kfir/Code/RMG-Py//rmg.py", line 118, in <module>
    main()
  File "/home/kfir/Code/RMG-Py//rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/kfir/Code/RMG-Py/rmgpy/rmg/main.py", line 995, in execute
    self.reaction_model.enlarge(objectToEnlarge)
  File "/home/kfir/Code/RMG-Py/rmgpy/rmg/model.py", line 642, in enlarge
    new_reactions.extend(pdep_network.explore_isomer(new_species))
  File "/home/kfir/Code/RMG-Py/rmgpy/rmg/pdep.py", line 285, in explore_isomer
    raise Exception('Attempted to explore isomer {0}, but that species not found in product channels.'.format(isomer))
Exception: Attempted to explore isomer C=S1=CN=1(795), but that species not found in product channels.
```
When the tolerance changes, the problematic isomer changes, so it may be an issue with core and edge.

### How To Reproduce
input file will be provided as necessary.

### Expected Behavior
Model finishes running.

### Installation Information
Describe your installation method and system information.
 - ubuntu 22.04
 - Installation method: (e.g. installation from binary or source, with or without anaconda) source
 - RMG version information:
    
   - RMG-Py: 3.2.0-173-gffeb7bbac
   - RMG-database: 3.2.0

**Comment by alongd** [comment]
related to #1725

I can think of bypassing the issue, but it won't solve it (just return an empty list for `new_reactions` maybe instead of raising an error, and report the skipped product)

But if we can visualize the network and understand what it's trying to compute, maybe we can start to see where the algorithm fails

**Comment by kfir4444** [comment]
> related to #1725
> 
> I can think of bypassing the issue, but it won't solve it (just return an empty list for `new_reactions` maybe instead of raising an error, and report the skipped product)
> 
> But if we can visualize the network and understand what it's trying to compute, maybe we can start to see where the algorithm fails

I ended up making that bypass, but we need to see if it makes sense and why does the error occurs in the first place 😄

**Comment by kfir4444** [comment]
Quick update, when making the bypass I got an error:
```
'Invalid k(E) values computed for path reaction "C=[S]1=S=S1C=N(8861) <=> HCN(101) + [CH2]S1=S=S=1(8603)".', 0.4696176812673157, 2.415101454432865e+18
```
similar to #2347. Could these issues be related?

**Comment by alongd** [comment]
Hard to tell, since we don't know what caused the 1st one.
Would be maybe helpful to visualize the network before this error, and see what RMG wanted but couldn't get
