### ISSUE TITLE
AssertionError during an RMG job run

### ISSUE THREAD

**Issue by PoojaNem** [ReactionMechanismGenerator/RMG-Py#2578]
**An error message:** assert spc.name not in phasesys.phases[phase_label].names, spc.name
AssertionError: C7H14-2

**Context:**
I am trying to generate chemical kinetic model for methylcyclohexane combustion with air using JetSurf2.0 mechanism included in the RMG database. Shortly after starting the simulation RMG throws an error (image attached below for the reference) with species C7H14-2. 
<img width="851" alt="image" src="https://github.com/ReactionMechanismGenerator/RMG-Py/assets/131012151/991a94c4-ec23-4134-adec-f1fa6709c487">

**Question:**
Can someone help me understand what is this error and its source. I have verified JetSurf2.0 dictionary and it does include species C7H14-2. Also, is there any documentation available to understand commonly encountered errors in RMG?

**Comment by JacksonBurns** [comment]
Related to #2548 

@hwpang could you comment?
