### ISSUE TITLE
How is this dynamic parameter obtained in the 1, 2_insertion_carbene family

### ISSUE THREAD

**Issue by liqiang4567** [ReactionMechanismGenerator/RMG-Py#2579]
In the 1, 2_insertion_carbene family, how are the kinetic parameters of this reaction obtained? In the kinetic/families/1, 2_insertion_carbene path, rules.py is an empty file that does not define how to compute dynamics rules, In the kinetic/families/1, 2_insertion_carbene/training path, reactive. py also has no [carbene;Cs_H] and [carbene; The kinetic parameter of C_methane], and where did the last three parameters come from? Hope to have an answer, thank you.

![image](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/76583592/dae4e845-5eb9-4139-9c5e-3fc84fcf74b1)

rules.py
![image](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/76583592/04abf91a-801c-4441-9a5c-db96475174c3)

**Comment by JacksonBurns** [comment]
@mjohnson541 do you know this off hand?

**Comment by JacksonBurns** [comment]
Closing as 'answered'.
