### ISSUE TITLE
How do I generate a correct model using rmg?

### ISSUE THREAD

**Issue by liqiang4567** [ReactionMechanismGenerator/RMG-Py#2590]
Hello, I want to test the ability of RMG using the mechanism of RMG3.1.0 generating C12H26, I used the following input.py input, ran for 36 hours, generated 206 species and 2522 reactions, and it is not finished yet. Look at the species concentration change and nothing changes. When will the model be ready? What indicators should I look at?

![image](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/76583592/1bc533bf-6da7-4b32-b2b2-4725591afccc)

[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/13763298/input.txt)

simulation_1_204.png
![simulation_1_204](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/76583592/4e7132b7-e65a-4cd4-ba1b-d9d7bdc36c27)

**Comment by liqiang4567** [comment]
I also have a question: this C12H26 conversion rate has repeatedly reached 0.8 or more (set the termination condition), why this model has not stopped?

![image](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/76583592/d3f97f06-521b-4655-854c-d1da6ef92b65)

![image](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/76583592/592d49a7-34fb-4ea5-9004-b7700a7ea59b)

**Comment by JacksonBurns** [comment]
Hi @liqiang4567 thanks for using RMG!

For the first question, RMG is just still running the reaction generation step and not yet completed. To get it to run faster, consider using multiple processes. You can check the documentation here: http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/running.html#input-flags the `-n` flag.

For the second question, `terminationConversion` only controls when a single simulation stops, not the overall model generation.

**Comment by liqiang4567** [comment]
Thank you for your reply, then how to control the whole model generation stop

**Comment by JacksonBurns** [comment]
@liqiang4567 you may specify the `maxNumSpecies` value to control how many species are allowed, which you can set to a number that correlates to how long you want the simulation to run (like we do here: https://github.com/ReactionMechanismGenerator/RMG-Py/blob/main/test/regression/fragment/input.py#L82). You can also set the total allowed runtime in you call to RMG with the `--walltime` flag as shown in the documentation here: http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/running.html?highlight=wall+time. Hope this helps!

**Comment by liqiang4567** [comment]
thank you for your reply
