### ISSUE TITLE
Warning: Force Constant Matrix Missing Ignoring rotors

### ISSUE THREAD

**Issue by cassguff** [ReactionMechanismGenerator/RMG-Py#2591]
I'm sure this is an issue on my end, but I can't figure out what it is. I am running a pretty basic Arkane run for _n_-butane and get the warning "Force Constant Matrix Missing Ignoring rotors...". I have checked the frequency Gaussian file and it does contain the force constant matrix. I have attached the Gaussian files, species file, and input file here for reference (with the .py files as normal text files since I can't attach a .py file).

[butane_energy.log](https://github.com/ReactionMechanismGenerator/RMG-Py/files/13851021/butane_energy.log)
[butane_freq.log](https://github.com/ReactionMechanismGenerator/RMG-Py/files/13851045/butane_freq.log)
[butane_scan.log](https://github.com/ReactionMechanismGenerator/RMG-Py/files/13851049/butane_scan.log)
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/13851052/input.txt)
[butane_HinderedRotor.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/13851053/butane_HinderedRotor.txt)

What else could be causing this error?

**Comment by alongd** [comment]
Hi, see the details here:
http://reactionmechanismgenerator.github.io/RMG-Py/users/arkane/input.html?highlight=iop#with-hindered-free-rotors
You need to add the `iop(7/33=1)` keyword to the Gaussian input so Gaussian prints the Hessian

**Comment by cassguff** [comment]
Thank you. I was using that keyword, but I did not realize it had to be
just a freq job for it to work. I was running opt freq jobs. Splitting that
up solved the problem.
