### ISSUE TITLE
Error: Model Resurrection has failed

### ISSUE THREAD

**Issue by liqiang4567** [ReactionMechanismGenerator/RMG-Py#2592]
Hello, when I used RMG 3.1.0 generation mechanism, I used an already completed mechanism as a seed mechanism to generate a new mechanism, an error occurred as follows, how can I solve it?

RMG.log
Adding species C=CCCC=CCCCCC(1011) to model core

Summary of Model Enlargement
---------------------------------
Added 1 new core species
    C=CCCC=CCCCCC(1011)
Created 0 new edge species
Moved 1 reactions from edge to core
    C19H34O2(1) <=> C=CCCCCC(=O)OC(270) + C=CCCC=CCCCCC(1011)
Added 0 new core reactions
Created 0 new edge reactions

After model enlargement:
    The model core has 918 species and 23090 reactions
    The model edge has 113 species and 234 reactions

Error: Trying to step from time 0.0 to 0.009999999999999998 resulted in a solver (DASPK) error: DASPK returned with an IDID = -7, Repeated convergence test failures occurred on the last attempted step in DDASPK.  An inaccurate or ill-conditioned Jacobian or preconditioner may be the problem.  If you are absolutely certain you want to continue, you should restart the integration.
Resurrecting Model...
Error: Model Resurrection has failed
Error: Core species names: ['H(3)', 'O(4)', 'OH(5)', 'H2(6)', 'H2O(7)', 'HO2(8)', 'H2O2(9)', 'CO(10)', 'CO2(11)', 'HCO(12)', 'CH3(13)', 'CH4(14)', 'CH2O(15)', 'O2CHO(16)', 'HO2CHO(17)', 'OCHO(18)', 'CH3O3(19)', 'CH3O3(20)', 'CH4O3(21)', 'HOCH2O(22)', 'CH3O(23)', 'CH3OH(24)', 'CH3O2(25)', 'CH3O2H(26)', 'CH2OH(27)', 'C2H5(28)', 'CH2(29)', 'CH2(S)(30)', 'C2H4(31)', 'C2H2(32)', 'CH(33)', 'C(34)', 'HCOOH(35)', 'C2H6(36)', 'C2H5O2(37)', 'C2H6O2(38)', 'C2H3(39)', 'CH3CHO(40)', 'C2H5O(41)', 'C2H5O2(42)', 'C2H4O(43)', 'C2H3O(44)', 'CH3CO(45)', 'CH2CHO(46)', 'CH3CO3(47)', 'C2H4O3(48)', 'CH2CO(49)',.................]
Error: Core species moles: array([ 6.68869688e-14, -3.47574126e-16, -1.00043396e-12, -6.17920453e-21,
       -5.80604105e-16,  2.42255852e-11,  1.56673047e-16, -2.57576720e-25,
       -3.70221827e-16, -1.08166095e-13,  2.54587925e-13, -1.62258379e-22,
        5.17369004e-14, -3.44136880e-14,  2.62010197e-19, -1.23832961e-17,
       -7.55077179e-30, -6.58581327e-17, -8.50269229e-28, -3.97718709e-14,
       -6.08223915e-21,  3.38125012e-22, -6.12548628e-14, -2.30529828e-21,
       -4.44279571e-17,  4.33458322e-16,  3.88568741e-26,  4.19582539e-26,
       -5.22617274e-14, -2.32987191e-18, -6.30744690e-36,  6.16419357e-42,
        1.10611717e-14,  2.95873103e-23,  8.63501817e-14, -9.12088754e-22,.........................])
Error: Volume: 0.0059599905735137956
Error: Core species net rates: array([ 3.14123274e+03,  7.76506046e-09, -2.56477069e-04,  3.52383099e-11,
       -2.45002836e-08,  1.10941479e-02, -7.55748853e-08,  1.11574382e+01,
        8.34988115e-06, -3.14126464e+03,  7.86303986e+02,  4.92351114e-12,
       -2.19111740e-04, -1.64530249e-04, -2.76286457e-11, -7.16192450e-08,
       -6.34034693e-20, -5.53012851e-07,  1.11605338e-14, -3.64692195e+02,
        1.10936503e-10, -2.12887774e-13,  1.83416484e-03,  2.85806378e-13,
        1.13166336e-05,  2.09920866e-08, -6.76396197e-15, -7.03495641e-13,
       -2.74180416e-06, -8.63004402e-11, -1.00095234e-13, -1.17634323e-35,............................])
Error: Edge species net rates: array([], dtype=float64)
Error: Network leak rates: array([], dtype=float64)
Warning: Reaction thresholds/flags for Reaction System 1 was not updated due to simulation failure

For reaction generation 10 processes are used.

Summary of Secondary Model Edge Enlargement
---------------------------------
Added 0 new core species
Created 0 new edge species
Added 0 new core reactions
Created 0 new edge reactions

After model enlargement:
    The model core has 918 species and 23090 reactions
    The model edge has 113 species and 234 reactions

Saving current model core to Chemkin file...
Chemkin file contains 23096 reactions.
Saving annotated version of Chemkin file...
Chemkin file contains 23096 reactions.
Updating RMG execution statistics...
    Execution time (DD:HH:MM:SS): 00:00:04:22
    Memory used: 972.32 MB

Conducting simulation of reaction system 1...
At time 0.0000e+00 s, species C=CCCC=CCCCCCCCC(=O)OC(1010) at 0.12372080934102458 exceeded the minimum rate for simulation interruption of 0.01
At time 0.0000e+00 s, species C=CCCC=CCCCCCCCC(=O)OC(1010) at rate ratio 0.12372080934102458 exceeded the minimum rate for moving to model core of 0.01
terminating simulation due to interrupt...
conditions choosen for reactor 0 were: T = 728.9275193347344 K, 

Adding species C=CCCC=CCCCCCCCC(=O)OC(1010) to model core

Summary of Model Enlargement
---------------------------------
Added 1 new core species
    C=CCCC=CCCCCCCCC(=O)OC(1010)
Created 0 new edge species
Moved 1 reactions from edge to core
    C19H34O2(1) <=> C4H8-1(122) + C=CCCC=CCCCCCCCC(=O)OC(1010)
Added 0 new core reactions
Created 0 new edge reactions

After model enlargement:
    The model core has 919 species and 23091 reactions
    The model edge has 112 species and 233 reactions

**Comment by mjohnson541** [comment]
So occasionally in RMG runs the simulation crashes simply due to the intermediate mechanism configuration. We resolved this issue by allowing it when the simulation fails to simply take the highest flux species at the last point in the simulation (including t=0), which usually allows the RMG run to right itself after a couple simulation failures. However, if the thermochemistry or kinetic parameters are bad enough they can also cause simulation crashes that will not be fixed as RMG adds more species causing RMG to repeatedly run Model Resurrection.  

Usually repeated Model Resurrections is a result of poor thermochemistry and sometimes poor kinetics. Our simulation software RMS: https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl has debugging tools that can be used to diagnose the parameters most likely to contribute to simulation crashes.

**Comment by JacksonBurns** [comment]
Closing this as resolved for the time being, thanks for the input @mjohnson541 !
