### ISSUE TITLE
reactants, products = rxn_string.split('=>')

### ISSUE THREAD

**Issue by REACTION3** [ReactionMechanismGenerator/RMG-Py#2593]
File "/rmg/RMG-Py/rmgpy/data/rmg.py", line 103, in load
    kinetics_depositories
  File "/rmg/RMG-Py/rmgpy/data/rmg.py", line 172, in load_kinetics
    depositories=kinetics_depositories
  File "/rmg/RMG-Py/rmgpy/data/kinetics/database.py", line 112, in load
    self.load_libraries(os.path.join(path, 'libraries'), libraries)
  File "/rmg/RMG-Py/rmgpy/data/kinetics/database.py", line 243, in load_libraries
    library.load(library_file, self.local_context, self.global_context)
  File "/rmg/RMG-Py/rmgpy/data/kinetics/library.py", line 458, in load
    reactants, products = rxn_string.split('=>')
ValueError: not enough values to unpack (expected 2, got 1)
How to resolve it?

**Comment by JacksonBurns** [comment]
@REACTION3 are you running RMG inside a docker container or from a local install?

**Comment by REACTION3** [comment]
from a docker container

**Comment by JacksonBurns** [comment]
Ok, it is unlikely there is any problem with the database inside the docker container. Could you paste the contents of your input file here?

**Comment by REACTION3** [comment]
it is too long. but some part is:

entry(
    index = 1098,
    label = "O2 + H <=> OH + O",
    degeneracy = 1,
    kinetics = Arrhenius(A=(1.800000e+14,'cm^3/(mol*s)'), n=-0.097, Ea=(11.030,'cal/mol'), T0=(1,'K')),
    shortDesc=u"""""",
)
entry(
    index = 1099,
    label = "O + H2 <=> H + OH",
    degeneracy = 1,
    duplicate =True,
    kinetics = MultiArrhenius(
        arrhenius = [
            Arrhenius(A=(3.000e+12,'cm^3/(mol*s)'), n=0.000, Ea=(7.963,'cal/mol'), T0=(1,'K')),
            Arrhenius(A=(8.000e+14,'cm^3/(mol*s)'), n=0.000, Ea=(19.180,'cal/mol'), T0=(1,'K')),
        ],
    ),
    shortDesc=u"""""",
)
    
entry(
    index = 1101,
    label = "OH + H2 <=> H + H2O",
    degeneracy = 1,
    kinetics = Arrhenius(A=(2.167000e+08,'cm^3/(mol*s)'), n=1.520, Ea=(3.460,'cal/mol'), T0=(1,'K')),
    shortDesc=u"""""",
)
entry(
    index = 1102,
    label = "OH + OH <=> H2O + O",
    degeneracy = 1,
    kinetics = Arrhenius(A=(4.000000e+04,'cm^3/(mol*s)'), n=2.420, Ea=(-1.928,'cal/mol'), T0=(1,'K')),
    shortDesc=u"""""",
)
entry(
    index = 1103,
    label = "H + HO2 <=> H2 + O2",
    degeneracy = 1,
    kinetics = Arrhenius(A=(4.660000e+06,'cm^3/(mol*s)'), n=2.087, Ea=(-1.450,'cal/mol'), T0=(1,'K')),
    shortDesc=u"""""",
)
entry(
    index = 1104,
    label = "H + HO2 <=> OH + OH",
    degeneracy = 1,
    kinetics = Arrhenius(A=(7.080000e+13,'cm^3/(mol*s)'), n=0.000, Ea=(0.300,'cal/mol'), T0=(1,'K')),
    shortDesc=u"""""",
)
entry(
    index = 1105,
    label = "O + HO2 <=> OH + O2",
    degeneracy = 1,
    kinetics = Arrhenius(A=(1.630000e+13,'cm^3/(mol*s)'), n=0.000, Ea=(-0.445,'cal/mol'), T0=(1,'K')),
    shortDesc=u"""""",
)

**Comment by JacksonBurns** [comment]
Do you have any irreversible reactions in your input file?

**Comment by REACTION3** [comment]
yes,
entry(
    index = 1129,
    label = "HCO + HO2 => CO2 + H + OH",
    degeneracy = 1,
    reversible = False,
    kinetics = Arrhenius(A=(3.000000e+13,'cm^3/(mol*s)'), n=0.000, Ea=(0.000,'cal/mol'), T0=(1,'K')),
    shortDesc=u"""""",
)
similar to this

**Comment by JacksonBurns** [comment]
@xiaoruiDong could you look at this to confirm? I suspect that there is a mis-formatted reaction based on the error, apparently a unimolecular reaction that is expected to be bimolecular?

**Comment by REACTION3** [comment]
File "/rmg/RMG-Py/rmgpy/data/kinetics/library.py", line 458, in load
    reactants, products = rxn_string.split('=>')
ValueError: not enough values to unpack (expected 2, got 1)
how can we get rid of this error?

**Comment by xiaoruiDong** [comment]
Hi @REACTION3, we weren't able to reproduce the error you encountered.

The contents you attached look good. When I compiled a library with them ([toy_library.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/14029676/toy_library.zip)), the database could be correctly loaded with the latest `main` branches for RMG-Py and RMG-database.

Suggestion:
- first you can try to solely load this toy library (don't assign other library names in `reactionLibraries`) and see if you still get the same error.
- If no error arises with the toy library, then double-check the kinetic libraries you used, especially if any of those are not native libraries in the RMG database. Pay special attention to the field of `label`, and see if any of the reactions label misses `=>` or `<=>`.
- If the previous steps don't help and you still need help locating the issue. If all libraries you used are RMG native libraries, please provide the list of library names here, and we will check them in detail. If you include a library compiled by yourself and you feel comfortable sharing it, please share it with us so we can try to reproduce the error with your files.
