### ISSUE TITLE
Removed kinetic group additivity methods are still referenced in codebase

### ISSUE THREAD

**Issue by jonwzheng** [ReactionMechanismGenerator/RMG-Py#2605]
### Bug Description

A commit from last August (https://github.com/ReactionMechanismGenerator/RMG-Py/commit/9f293bec90a093cf23b42089bb7bb0b14e05a2a7) removed various deprecated code, including functions in `rmgpy/data/kinetics/groups` and `rmgpy/data/kinetics/family` related to computing rate coefficients using group additivity methods. Specifically, the method named `estimate_kinetics_using_group_additivity` in both of those files.

However, references to these methods are still available in the codebase. For example, in `rmgpy/data/kinetics/family`: `get_kinetics_for_template` includes the option to use group additivity methods. This template method is called in `get_kinetics` and uses group additivity if `kinetics_estimator` is not provided, or if `group_additivity` is provided as the estimator.

In `rmgpy/rmg/main.py`, the docstring mentions that `group_additivity` is a valid kinetic estimator method even though this does not seem to be the case anymore. And `rmgpy/rmg/model.py` considers the case if `kinetics_estimator` is group additivity.

### Expected Behavior
Code should run without calling a removed method that leads to an AttributeError.

### Additional Context
We could either revert these changes, or we could commit to removing all references to group additivity. Previous discussion (see https://github.com/ReactionMechanismGenerator/RMG-Py/issues/975#issuecomment-400842324 and codebase pre-commit) indicated that group additivity should be deprecated for kinetics, however it has been available and a default method on the RMG Website. It might be helpful to figure out if the group additivity methods are so bad that we should just remove them altogether, or if they might be potentially useful for users on the website.

**Comment by JacksonBurns** [comment]
I think Bill would want these to stay - I'm pretty sure he had us use RMG website to do group additivity estimates during his kinetics class.

**Comment by jonwzheng** [comment]
Addressed by #2612
