### ISSUE TITLE
RMG cannot generate resonance structures for the fragment "C[C]1C=CC=CC1=CC=CR"

### ISSUE THREAD

**Issue by donerancl** [ReactionMechanismGenerator/RMG-Py#2642]
### Bug Description
Resonance structures cannot be generated from specific fragment "C[C]1C=CC=CC1=CC=CR" , despite success for the same smiles without the "R" and for other fragments with resonance.

### How To Reproduce
```
from rmgpy.molecule.fragment import Fragment
f = Fragment().from_smiles_like_string("C[C]1C=CC=CC1=CC=CR")
f.generate_resonance_structures()
```
result
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_1087842/3088769613.py in <module>
      1 f = Fragment().from_smiles_like_string("C[C]1C=CC=CC1=CC=CR")
----> 2 f.generate_resonance_structures()

~/RMG-Py/rmgpy/molecule/molecule.cpython-37m-x86_64-linux-gnu.so in rmgpy.molecule.molecule.Molecule.generate_resonance_structures()

~/RMG-Py/rmgpy/molecule/molecule.cpython-37m-x86_64-linux-gnu.so in rmgpy.molecule.molecule.Molecule.generate_resonance_structures()

~/RMG-Py/rmgpy/molecule/resonance.cpython-37m-x86_64-linux-gnu.so in rmgpy.molecule.resonance.generate_resonance_structures()

~/RMG-Py/rmgpy/molecule/resonance.cpython-37m-x86_64-linux-gnu.so in rmgpy.molecule.resonance.generate_resonance_structures()

~/RMG-Py/rmgpy/molecule/resonance.cpython-37m-x86_64-linux-gnu.so in rmgpy.molecule.resonance._generate_resonance_structures()

~/RMG-Py/rmgpy/molecule/resonance.cpython-37m-x86_64-linux-gnu.so in rmgpy.molecule.resonance._generate_resonance_structures()

~/RMG-Py/rmgpy/molecule/resonance.cpython-37m-x86_64-linux-gnu.so in rmgpy.molecule.resonance.generate_kekule_structure()

~/RMG-Py/rmgpy/molecule/resonance.cpython-37m-x86_64-linux-gnu.so in rmgpy.molecule.resonance.generate_kekule_structure()

AttributeError: 'NoneType' object has no attribute 'label'
```

### Expected Behavior
successful molecule example:
```
m = Molecule().from_smiles("C[C]1C=CC=CC1=CC=C")
m.generate_resonance_structures()
```
result
```
[Molecule(smiles="C=CC=C1C=CC=C[C]1C"),
 Molecule(smiles="C=C[CH]c1ccccc1C"),
 Molecule(smiles="[CH2]C=Cc1ccccc1C"),
 Molecule(smiles="C=CC=C1C=C[CH]C=C1C"),
 Molecule(smiles="C=CC=C1[CH]C=CC=C1C")]
```

successful fragment example:
```
f = Fragment().from_smiles_like_string("[CH2]C=CC=CR")
f.generate_resonance_structures()
```
result
```
[Molecule(smiles="[CH2]C=CC=CR"),
 Molecule(smiles="C=C[CH]C=CR"),
 Molecule(smiles="C=CC=C[CH]R")]
```
### Installation Information
Describe your installation method and system information.
 - OS (include version if known): (e.g. Windows 10, Ubuntu 18, macOS 10.13, etc.)
 - Installation method: (e.g. installation from binary or source, with or without anaconda)
 - RMG version information:
   
   - RMG-Py: 
   - RMG-database: 

### Additional Context
These are the resonance structures 
![image](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/47831564/bb4f8468-d87c-40c3-b113-a7473667a847)

**Comment by donerancl** [comment]
This happens because `generate_kekule_structure` returns []... looking into it more

**Comment by JacksonBurns** [comment]
Thanks for the report and ongoing investigation! I think regardless of the reason why this _specific_ fragment molecule is unable to generate resonance structures (presumably because of some bug), we should probably change the default behavior to always at least return the molecule itself (which, based on the provided examples, is happening only when other structures can also be found).
