### ISSUE TITLE
New kinetics library？

### ISSUE THREAD

**Issue by OJ-0908** [ReactionMechanismGenerator/RMG-Py#2645]
I created a new library, but an error occurred during the running process, as follows:

"multiplicity -187
1 O u0 p2 c0 {2,D}
2 N u0 p0 c0 {1,D} {3,D} {4,S}
3 O u0 p2 c0 {2,D}
4 H u0 p0 c0 {2,S}"
...
rmgpy.exceptions.AtomTypeError: Unable to determine atom type for atom N, which has 1 single bonds, 2 double bonds (2 to O, 0 to S, 0 others), 0 triple bonds, 0 quadruple bonds, 0 benzene bonds, 0 lone pairs, and +0 charge."
The adjacency list mentioned in the error message was not found in the newly created reactive library, which confused me. This problem has been bothering me for some time. If anyone is familiar with this error and can provide suggestions for modification, I would be very grateful.

**Comment by JacksonBurns** [comment]
Hi @OJ-0908 did you generate this library with some kind of script or manually? Please mention the script, if so.

Just from the error, the molecule you have specified here is invalid. The Nitrogen atom has a total valency of 5 (2 double bonds + 1 single bond), which is not the allowed valency of 3 for neutral, closed shell nitrogen.

**Comment by OJ-0908** [comment]
> Hi @OJ-0908 did you generate this library with some kind of script or manually? Please mention the script, if so.
> 
> Just from the error, the molecule you have specified here is invalid. The Nitrogen atom has a total valency of 5 (2 double bonds + 1 single bond), which is not the allowed valency of 3 for neutral, closed shell nitrogen.
Thank you very much for your response. Although I have verified the adjacency list of the input molecule and even re-entered a new mechanism file, similar issues still seem to arise. I will provide the mechanism details, and if you have time, I would greatly appreciate your assistance in reviewing it.
[dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/14831162/dictionary.txt)
[dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/14831164/dictionary.txt)
I've been troubled by this issue for quite some time, and I would be extremely grateful if you could offer some suggestions or advice.

**Comment by xiaoruiDong** [comment]
Hi @OJ-0908, I checked your dictionary file with `rmgpy.chemkin.load_species_dictionary`. I can load the second dictionary file without issues. For the first one, you may want to change the adjacency list of the following molecules:

```
NO2
multiplicity 2
1 O u0 p2 c0 {2,D}
2 N u0 p1 c0 {1,D} {3,S}
3 O u1 p2 c0 {2,S}

t-ONNH
multiplicity 2
1 O u1 p2 c0 {2,S}
2 N u0 p1 c0 {1,S} {3,D}
3 N u0 p1 c0 {2,D} {4,S}
4 H u0 p0 c0 {3,S}

c-ONNH
multiplicity 2
1 O u1 p2 c0 {2,S}
2 N u0 p1 c0 {1,S} {3,D}
3 N u0 p1 c0 {2,D} {4,S}
4 H u0 p0 c0 {3,S}

ONHN
multiplicity 2
1 N u0 p0 c+1 {2,D} {3,S} {4,S}
2 O u0 p2 c0 {1,D}
3 N u1 p2 c-1 {1,S}
4 H u0 p0 c0 {1,S}

t-HNN(O)OH
1 N u0 p1 c0 {2,D} {5,S}
2 N u0 p0 c+1 {1,D} {3,S} {4,S}
3 O u0 p2 c0 {2,S} {6,S}
4 O u0 p3 c-1 {2,S}
5 H u0 p0 c0 {1,S}
6 H u0 p0 c0 {3,S}

c-HNN(O)OH
1 N u0 p1 c0 {2,D} {5,S}
2 N u0 p0 c+1 {1,D} {3,S} {4,S}
3 O u0 p2 c0 {2,S} {6,S}
4 O u0 p3 c-1 {2,S}
5 H u0 p0 c0 {1,S}
6 H u0 p0 c0 {3,S}
```
A side note: RMG cannot distinguish cis and trans molecules.

**Comment by OJ-0908** [comment]
Thank you very much for your response. I have reorganized the cis and trans molecules, categorizing them as the same type of species. Now, the program is running smoothly. Once again, I appreciate your assistance.

**Comment by xiaoruiDong** [comment]
I am glad it works!
