### ISSUE TITLE
Error Running Arkane with Gaussian Output Files

### ISSUE THREAD

**Issue by OJ-0908** [ReactionMechanismGenerator/RMG-Py#2650]
Topic
 - [√ ] Arkane (formerly CanTherm)
Issue:
Based on the example in Arkane at RMG-Py/examples/arkane/reactions/CH3OH+HCO, we have provided Gaussian output files for the reactants and the transition state (TS), as well as the corresponding Python files. However, when running the input file with Arkane.py, we encountered an error：
#                                                              #
# Automated Reaction Kinetics and Network Exploration (Arkane) #
#                                                              #
#   Version: 3.2.0                                             #
#   Authors: RMG Developers (rmg_dev@mit.edu)                  #
#   P.I.s:   William H. Green (whgreen@mit.edu)                #
#            Richard H. West (r.west@neu.edu)                  #
#   Website: http://reactionmechanismgenerator.github.io/      #
#                                                              #
################################################################

The current git HEAD for RMG-Py is:
        036ab3f8ca0f94f567b50b0b83110bab0a14a35f
        Wed Aug 16 15:56:48 2023 -0400

The current git HEAD for RMG-database is:
        b7ff16364a07c9a51a34303aa28407a83455a3e4
        Tue Aug 8 09:37:08 2023 -0400

Databases not found. Making databases
Loading frequencies library from halogens_G4.py in /rmg/RMG-database/input/statmech/libraries...
Loading frequencies group database from /rmg/RMG-database/input/statmech/groups...
Loading transport library from OneDMinN2.py in /rmg/RMG-database/input/transport/libraries...
Loading transport library from NIST_Fluorine.py in /rmg/RMG-database/input/transport/libraries...
Loading transport library from PrimaryTransportLibrary.py in /rmg/RMG-database/input/transport/libraries...
Loading transport library from GRI-Mech.py in /rmg/RMG-database/input/transport/libraries...
Loading transport library from NOx2018.py in /rmg/RMG-database/input/transport/libraries...
Loading transport group database from /rmg/RMG-database/input/transport/groups...
Loading species NH2...
Loading transition state ts...
Loading species HO2...
Loading reaction NH2 + HO2 <=> NH3 + O2...
Traceback (most recent call last):
  File "/rmg/RMG-Py/Arkane.py", line 59, in <module>
    arkane.execute()
  File "/rmg/RMG-Py/arkane/main.py", line 180, in execute
    self.job_list = self.load_input_file(self.input_file)
  File "/rmg/RMG-Py/arkane/main.py", line 162, in load_input_file
    self.level_of_theory = load_input_file(self.input_file)
  File "/rmg/RMG-Py/arkane/input.py", line 656, in load_input_file
    exec(f.read(), global_context, local_context)
  File "<string>", line 26, in <module>
  File "/rmg/RMG-Py/arkane/input.py", line 296, in reaction
    products = sorted([species_dict[spec] for spec in products])
  File "/rmg/RMG-Py/arkane/input.py", line 296, in <listcomp>
    products = sorted([species_dict[spec] for spec in products])
KeyError: 'NH3'

I have provided all the necessary files for the calculation in the attachment and am seeking guidance and assistance. This is an important step for me in learning how to use Arkane.
[Reaction.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/14942481/Reaction.zip)

**Comment by jonwzheng** [comment]
Hi! Sorry that you are having issues with using Arkane. From the user documentation available [here](https://reactionmechanismgenerator.github.io/RMG-Py/users/arkane/input.html#reaction), a species file must be defined for all reactants _and_ all products in your reaction.
You should define product files as you did for the reactants (so `NH3.py`, etc) 
even though conventional TST just uses information about the partition function of the TS and reactants, the product information may be used for the tunneling corrections

**Comment by JacksonBurns** [comment]
Closing as solved for now, lacking user input. Feel free to reopen!
