### ISSUE TITLE
Output which frequencies are removed for hindered rotors?

### ISSUE THREAD

**Issue by cassguff** [ReactionMechanismGenerator/RMG-Py#2654]
The Arkane output.py files contain for each conformer/species the harmonic oscillator frequencies, along with some information about any hindered rotors that were specified (inertia, symmetry, barrier). Is there a way for me to have it also output which frequencies corresponded to each hindered rotor that were removed from the harmonic oscillator frequency list?

**Comment by cassguff** [comment]
Or alternatively, is there a setting or something I can change so that it does not recalculate the frequencies after the internal frequencies are determined? So that the harmonic oscillator frequencies are simply the same ones from my Gaussian file just with the hindered rotor frequencies removed from the list?

**Comment by JacksonBurns** [comment]
re-ping @jonwzheng please let me know if you have seen this before! Thanks
