### ISSUE TITLE
How to solve the problem where the desired component does not exist in the library?

### ISSUE THREAD

**Issue by mioxchan** [ReactionMechanismGenerator/RMG-Py#2659]
This is my first time using RMG. When I input the component: ammonium dinitrate, the result shows an error. The component I need does not exist in the library. How can I solve this problem?
![6d45a50aa053bf6461fee5cd9564fb5](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/169242209/d5f6322d-eeea-41d5-bda3-8283b7f9be30)
![589e7ef7cbd2e4b16f0093fdb7fb26f](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/169242209/1c4871cd-8316-40c2-86a4-9c4d4be1e4ea)
![5641b324c2578ed5744ff2ae17c1514](https://github.com/ReactionMechanismGenerator/RMG-Py/assets/169242209/1e458409-efa5-400e-b854-57833e13a155)

**Comment by JacksonBurns** [comment]
@mioxchan thanks for using RMG! I believe this error is because, while your molecule as a whole is neutral its component fragments are not, which RMG is not able to handle. @rwest could you confirm?

**Comment by rwest** [comment]
I think that's right, Jackson. 
[This](https://rmg.mit.edu/database/molecule/1%20%20N%20u0%20p1%20c0%20%7B9,S%7D%20%7B10,S%7D%20%7B11,S%7D%0A2%20%20O%20u0%20p2%20c0%20%7B3,D%7D%0A3%20%20N%20u0%20p0%20c+1%20%7B2,D%7D%20%7B4,S%7D%20%7B5,S%7D%0A4%20%20O%20u0%20p3%20c-1%20%7B3,S%7D%0A5%20%20N%20u0%20p1%20c0%20%7B3,S%7D%20%7B6,S%7D%20%7B12,S%7D%0A6%20%20N%20u0%20p0%20c+1%20%7B5,S%7D%20%7B7,D%7D%20%7B8,S%7D%0A7%20%20O%20u0%20p2%20c0%20%7B6,D%7D%0A8%20%20O%20u0%20p3%20c-1%20%7B6,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A10%20H%20u0%20p0%20c0%20%7B1,S%7D%0A11%20H%20u0%20p0%20c0%20%7B1,S%7D%0A12%20H%20u0%20p0%20c0%20%7B5,S%7D%0A) representation works: `N.O=[N+]([O-])N[N+](=O)[O-]` 
which I found by entering the SMILES from https://www.chemeo.com/cid/80-144-3/Ammonium-Dinitrate
In this case the two fragments are both neutral (the H is moved across).
Although this representation doesn't crash RMG, I would not expect RMG to do a good job (at all) at predicting its properties or reactions. 

In general, RMG does not yet support ions.

**Comment by JacksonBurns** [comment]
@rwest thanks for confirming!

@mioxchan please see the link in the answer above which works for a variation in the species you requested. Note though that RMG won't be able to make good estimates for this and species like it, since RMG doesn't really work with ions. This won't change in the near term.

**Comment by mioxchan** [comment]
@rwest  @JacksonBurns 
Thanks    Your response was timely. 
I showed a great interest in it.   May I ask where beginners like me can systematically learn RMG？

**Comment by JacksonBurns** [comment]
I'm happy to help! I recommend looking at the example input files in the documentation (https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/examples.html) and also our video tutorial series from last year (https://youtu.be/S4aHvLShcAY?feature=shared).
