### ISSUE TITLE
Error message when generating mechanism

### ISSUE THREAD

**Issue by DiegoGuajardoP** [ReactionMechanismGenerator/RMG-Py#2665]
### Topic
General area which your question is related to.
 - [x] Installation of RMG
 - [x] Running an RMG job
 - [x] Dependencies
 - [x] An error message 

### Context
Hi everyone,

I just installed the developers version of RMG for Linux and when running the superminimal example to see if everything is right  I got the following error message:
```
"warning: unknown data in line table prologue at offset 0x0000d950: parsing ended (at offset 0x0000db7d) before reaching the prologue end at offset 0x0000e0da
warning: unknown data in line table prologue at offset 0x0000ca57: parsing ended (at offset 0x0000cc84) before reaching the prologue end at offset 0x0000d1c6
┌ Warning: Error requiring `Enzyme` from `LinearSolve`
│   exception =
│    LoadError: ArgumentError: Package LinearSolve does not have Enzyme in its dependencies:
│    - You may have a partially installed environment. Try `Pkg.instantiate()`
│      to ensure all packages in the environment are installed.
│    - Or, if you have LinearSolve checked out for development and have
│      added Enzyme as a dependency but haven't updated your primary
│      environment's manifest file, try `Pkg.resolve()`.
│    - Otherwise you may need to report an issue with LinearSolve"
```

### Question
The mechanism was generated but I am just wondering what i missed during the installation.

### Installation Information
Installation by Source Using Anaconda Environment for Linux

**Comment by JacksonBurns** [comment]
Hi @DiegoGuajardoP this is just a warning from one of our upstream dependencies. Re-doing the installation process (or at least the RMS part) may fix this in the future.

For now, since this is just a warning and the mechanism was still generated, you can safely ignore this issue!
