### ISSUE TITLE
Cannot import Cython packages when using Docker container in Charliecloud

### ISSUE THREAD

**Issue by cassguff** [ReactionMechanismGenerator/RMG-Py#2677]
Because of some computer permissions changing in our system, I am no longer able to use Docker directly but can use Docker images in Charliecloud. I have previously had no issues running RMG with Docker, so this is likely not an RMG issue, but I am wondering if anyone has any insight.

I pulled the docker container and am able to run it, but when I do tests (I am just testing arkane using one of the built-in examples), it was missing a bunch of the dependencies (eg numpy, Cython). I installed each of these as they came up (using pip), but then I get 
ModuleNotFoundError: No module named 'rmgpy.rmgobject'

It seems it's able to import other modules from rmgpy but only if they have the .py, and rmgobject is cython. At least that's my guess as to why it is not finding this module but is finding others. I've confirmed Cython is installed. I'm not sure how to fix or get around this issue. I'm still pretty new to using docker and charliecloud.

**Comment by JacksonBurns** [comment]
I'm not familiar with charliecloud, but from their documentation you might be best off trying to re-build the image using our Dockerfile, see: https://hpc.github.io/charliecloud/tutorial.html#build-from-dockerfile
