### ISSUE TITLE
`muq` to be updated for Python 3.11+

### ISSUE THREAD

**Issue by jonwzheng** [ReactionMechanismGenerator/RMG-Py#2678]
See #2671. We are changing our `muq` dependency from the `rmg` channel to `conda-forge`. Unfortunately the `conda-forge` version does not have binaries for python=3.11+. 

The options we discussed are (quoting Jackson)

1. we are going to poke the developers of muq to see if they are willing to take up the conda binary building again and get versions out that supporting python 3.11+
2. when we upgrade python versions, we can either add retroactive support for Python 3.10 and/or just require users to install muq themselves 

I'm currently talking with the MUQ team on Option 1 to see if they can proceed, but Option 2 seems likely; will keep updates in this issues thread...

**Comment by JacksonBurns** [comment]
I'll tentatively assign myself, assuming we eventually have to do 2 as part of #2635

**Comment by jonwzheng** [comment]
It looks like we'll thankfully be able to go with Option 1; the feedstock maintainer is currently & actively fixing the build recipes :) The timeline I heard was within the next few days, but even if it's next week it should be good to go with the RMG Python version bump. Will keep you posted with future updates.

**Comment by JacksonBurns** [comment]
As of this hour, there are now `muq` binaries for every minor Python version we will target available on conda forge: https://anaconda.org/conda-forge/muq/files :tada:

I'll close this as completed, thanks for opening it up to track. Could you also pass along our thanks to the developers over there for taking care of this? Thanks!
