### ISSUE TITLE
Alternative installation of RMG-Py on Red Hat systems instead of Debian

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#272]
The linux installation instructions are written for Debian (like Ubuntu) systems. On Red Hat, `apt-get` will not work; the equivalent is `yum`, the wrapper around the Red Hat Package Manager (rpm). Moreover, the dependencies have slightly different names as well. Here's an overview of what I found so far:

| Debian | Red Hat |
| --- | --- |
| g++ | gcc-c++ |
| gfortran | gcc-gfortran |
| python-dev | python-devel |
| liblapack-dev | lapack-devel |
| libpng-dev | libpng-devel |
| build-essential | make automake gcc gcc-c++ kernel-devel* |
| matplotlib | python-matplotlib |
| sqlite3 libsqlite3-dev | sqlite-devel |
| libboost-dev libboost-python-dev libboost-regex-dev | boost-devel |

*cf. http://unix.stackexchange.com/questions/1338/what-is-the-fedora-equivalent-of-the-debian-build-essential-package

**Comment by JacksonBurns** [comment]
The current installation instructions have implemented this update. Closing as resolved (or stale, take your pick).
