### ISSUE TITLE
Pathflux diagram 

### ISSUE THREAD

**Issue by PoojaNem** [ReactionMechanismGenerator/RMG-Py#2720]
Hello Everyone,

I recently used the Generate Flux Diagram tool of RMG to understand the formation of species in Iso-dodecane combustion. 
Below is the image of the final flux diagram. I would appreciate it if someone could help me understand why some species are encircled (e.g.shown with orange arrows) whereas others are not (e.g.shown with blue arrows). Is there any difference between the two notations? Does it represent the relative concentrations of the species?
<img width="497" alt="image" src="https://github.com/user-attachments/assets/82495aca-8c41-450a-a636-209dc5ed167d">

Thank you

**Comment by JacksonBurns** [comment]
@donerancl do you know this?

**Comment by donerancl** [comment]
@JacksonBurns @PoojaNem the thicker the circle around the species, the higher concentration, I think. So I would think no circle means very low concentration.

**Comment by PoojaNem** [comment]
Thank you very much @donerancl and @JacksonBurns
