### ISSUE TITLE
New gprof2dot needs to be imported differently again (has no attribute 'Main')

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#297]
In #239 Nick reported the newer version of gprof2dot needed to be imported differently, so in #240 he fixed it by changing `from gprof2dot import gprof2dot` into `import gprof2dot` (b4f79725ed1ce5e326a91f54a329a770d7d722e8)

Connie was running an older version of gprof2dot and changed it back in ae84b9b3979329fb7e9745e844af1a0bcf1d6b44. Richard reverted the change in c211f3bb559a002f0a8c3a6539974968e33ed990 and told Connie to upgrade.

As our luck would have it, four days later they release new version of gprof2dot that breaks things again!

Previous working Travis build installs version 2014.03.12:
```
Downloading/unpacking gprof2dot (from -r requirements.txt (line 20))
  Downloading gprof2dot-2014.03.12.tar.gz
  Running setup.py (path:/home/travis/virtualenv/python2.7_with_system_site_packages/build/gprof2dot/setup.py) egg_info for package gprof2dot
```

Recent failing Travis build installs version 2014.09.29 (today's date)
```
Downloading/unpacking gprof2dot (from -r requirements.txt (line 20))
  Downloading gprof2dot-2014.09.29.tar.gz
  Running setup.py (path:/home/travis/virtualenv/python2.7_with_system_site_packages/build/gprof2dot/setup.py) egg_info for package gprof2dot
```

This leads to the following error at the end of running `$ make eg1`:
```python
Traceback (most recent call last):
  File "rmg.py", line 143, in <module>
    makeProfileGraph(stats_file)
  File "/home/travis/build/GreenGroup/RMG-Py/rmgpy/rmg/main.py", line 1154, in makeProfileGraph
    m = gprof2dot.Main()
AttributeError: 'module' object has no attribute 'Main'
```

We should
 * [ ] implement a fix,
 * [ ] wrap this import with try/except blocks that log helpful warning messages about upgrading gprof2dot,
 * [ ] change the minimum version in the requirements.txt file.

**Comment by connie** [comment]
No longer an issue due to anaconda dependency management.
