### ISSUE TITLE
openSuSE Install Instructions

### ISSUE THREAD

**Issue by DetlevCM** [ReactionMechanismGenerator/RMG-Py#326]
The actual git clone and compile instructions are identical to the ones given for Debian in the main manual - what differs however is the packages.

This is for a "vanilla" freshly installed 64Bit OpenSuSE 13.2 - the 32Bit version may need 32Bit identifiers on packages.

zypper and pip must be run as root - i.e. sudo.
installing all of the below (and any dependencies indicate by zypper) will result in RMG-Py running the minimal example successfully (appears to be a full working copy)

``` bash
## First the non-Python dependencies
sudo zypper install git gcc gcc-c++ gcc-fortran lapack-devel


## Python Stuff , python-setuptools present in standard install
sudo zypper install python-devel python-openbabel python-pip
sudo zypper install python-numpy python-scipy python-Cython python-nose python-matplotlib python-Sphinx python-psutil libpng16-devel


## We need to add a communty repository, devel:languages:python - This is Version Dependent

## For 13.2
## URL: http://download.opensuse.org/repositories/devel:/languages:/python/openSUSE_13.2/
sudo zypper ar -f http://download.opensuse.org/repositories/devel:/languages:/python/openSUSE_13.2/devel:languages:python.repo
sudo zypper refresh

## For Leap 42.1
## URL: ttp://download.opensuse.org/repositories/devel:/languages:/python/openSUSE_Leap_42.1/
sudo zypper ar -f http://download.opensuse.org/repositories/devel:/languages:/python/openSUSE_Leap_42.1/devel:languages:python.repo
sudo zypper refresh

sudo zypper install python-quantities python-guppy python-xlwt
sudo zypper install freetype freetype2-devel ## not sure which one we need


## These are for RDKit - it seems we do not need an equivalent of build essential
sudo zypper install flex bison cmake sqlite3 sqlite3-devel boost-devel libboost_random1_54_0 libboost_regex1_54_0-32bit
# -> slightly concerned that regex is 32bit and the rest 64bit


sudo pip2.7 install numpy --upgrade
## bizarrely it is missing a header when installed from YaST
## IF it does not install because Pip offers the same version, force reinstall with:
sudo sudo pip2.7 install numpy --upgrade

# deal with RMG requirements - add the missing packages
sudo pip2.7 install MarkupSafe Jinja2 argparse
sudo pip2.7 install git+https://code.google.com/p/jrfonseca.gprof2dot
sudo pip2.7 install pyparsing==1.5.7 pydot coverage
```

This then needs to be followed by the standard install instructions for RMG-Py, for convenience, reproduced here again - from http://greengroup.github.io/RMG-Py/users/rmg/installation/linux.html .
Assuming you have created an SSH Key for Github and added it:

``` bash
cd ~
git clone https://github.com/GreenGroup/PyDAS.git
git clone https://github.com/GreenGroup/PyDQED.git
cd PyDAS; make F77=gfortran; sudo make install; cd ..
cd PyDQED; make F77=gfortran; sudo make install; cd ..

cd ~
git clone https://github.com/rdkit/rdkit.git
cd rdkit
export RDBASE=`pwd`
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RDBASE/lib
export PYTHONPATH=$PYTHONPATH:$RDBASE
cd External/INCHI-API
./download-inchi.sh
cd ../../
mkdir build
cd build
cmake .. -DRDK_BUILD_INCHI_SUPPORT=ON
make
make install
```

As per original instructions, set up rdkit variables:

``` bash
export RDBASE=$HOME/rdkit # CHECK THIS (maybe you put RDKit somewhere else)
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RDBASE/lib
export PYTHONPATH=$PYTHONPATH:$RDBASE  # (or some other way to make sure it's on your Python path)
```

Now install RMG:

``` bash
git clone https://github.com/GreenGroup/RMG-database.git
git clone https://github.com/GreenGroup/RMG-Py.git
cd RMG-Py
make
```

**Comment by DetlevCM** [comment]
Updated initial setup - was missing RMG requirements, has been updated, now works:

These are the packages needed under OpenSuSE 13.2 "vanilla":

| Regular Packages | ||
| git | | lapack-devel |
| gcc | gcc-c++ | gcc-fortran |
| flex | bison | cmake |
| sqlite3 | sqlite3-dev | boost-devel |
| libboost_random1_54_0 | libboost_regex1_54_0-32bit | |


| Python Packages | | |
| python-devel | python-openbabel | python-pip | 
| python-numpy | python-scipy | python-Cython  |
| python-nose | python-matplotlib | python-Sphinx |
| python-psutil | python-lipng16-devel |

Numpy bizarrely missed a header and must be reinstalled/rebuilt using:
```
pip2.7 install numpy --upgrade
```

These pacakges reuqire that a repository is added
```
URL: http://download.opensuse.org/repositories/devel:/languages:/python/openSUSE_13.2/
```
| python-quantities | python-guppy | python-xlwt |
| freetype | freetype2-devel | |

From the RMG requirements list, we need:

| MarkupSafe | Jinja2 | argparse |
| git+https://code.google.com/p/jrfonseca.gprof2dot | | |
| pyparsing==1.5.7 | pydot | coverage |

**Comment by JacksonBurns** [comment]
Use of conda has negated this issue. Closing as fixed/stale.
