### ISSUE TITLE
calculateCyclicSymmetryNumber gave wrong result when dealing with 'C1(C(C(C(C(C1C2CCC2)C3CCC3)C4CCC4)C5CCC5)C6CCC6)C7CCC7'

### ISSUE THREAD

**Issue by KEHANG** [ReactionMechanismGenerator/RMG-Py#332]
I'm trying to calculate the cyclic symmetry number for the following molecule: C1(C(C(C(C(C1C2CCC2)C3CCC3)C4CCC4)C5CCC5)C6CCC6)C7CCC7, whose structure is
![image](https://cloud.githubusercontent.com/assets/2739496/6044224/f166f8a8-ac5f-11e4-885e-a497ce9a10af.png)

My script is simply :
from rmgpy.molecule.symmetryTest import *

def main():
    molecule = Molecule().fromSMILES('C1(C(C(C(C(C1C2CCC2)C3CCC3)C4CCC4)C5CCC5)C6CCC6)C7CCC7')
    # calculate it 10 times
    for i in range(10):
        symNum = calculateCyclicSymmetryNumber(molecule)
        print 'SymNum: ', symNum
    print('********************')

if **name** == "**main**":
    main()

But the results is very strange: first they are not 12, which is the right answer; second, results are not reproducible, meaning running this script 10 times gives 10 different results. Enoch also confirmed that.

**Comment by connie** [comment]
Please rerun it and check what happens after making a species object and using the generateResonanceIsomers function.

**Comment by goldmanm** [comment]
I added this to a list of molecules that I'm writing unit tests for. Even with resonance isomers, I ran it multiple times and obtain a Total symmetry number of 3 each time. 

I am not sure if the unreliability is due to resonance  (especially since there aren't any radicals in the molecule), so I am not sure what is causing it.

**Comment by mliu49** [comment]
Fixed by #1333.
