### ISSUE TITLE
Training reactions are automatically duplicated now

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#334]
Possibly due to https://github.com/GreenGroup/RMG-Py/pull/324

**Comment by connie** [comment]
It appears that this behavior does not affect H-Abstraction training reactions, but does affect the R_Recombination reactions.  I'm guessing because you can have recombination of the radical with A + B = C or B + A = C.  But I think the reactions in the training reactions are supposed to be the total reaction rate, so it should not be duplicated, is this correct?

The reaction in question: CH3O2 <=> O2 + CH3  in R_Recombination/training

**Comment by connie** [comment]
Looks like the error has been around for a while, and probably not related to https://github.com/GreenGroup/RMG-Py/pull/324

**Comment by nickvandewiele** [comment]
I tried (395fde0b052fe00fc305261bf9e494aa0f4b133d) to read in the `NNH = N2 + H` from GRI-Mech3.0-N mentioned in #276 and check the `duplicate` attributes of each reaction. Currently, they return `False`, implying that the attribute is not read. I don't see how this attribute stored in a reaction library gets transferred to the Reaction object in memory. Maybe I'm doing this in the wrong way?

**Comment by nickvandewiele** [comment]
see 994d0b3 for fix that read the duplicate attribute of reaction libraries.

**Comment by connie** [comment]
Thought I fixed this before but must have not committed it.

**Comment by connie** [comment]
Though I think the duplicates from training reactions affect only R_recombination due to matching in both directions.
