### ISSUE TITLE
RMG generated mechanism turns all irreversible library reactions into reversible ones

### ISSUE THREAD

**Issue by enochd** [ReactionMechanismGenerator/RMG-Py#345]
I have a reaction library that I am using to generate RMG models. It contains several irreversible reactions. Since these reactions are important, RMG throws them into my core mechanism, but it does not retain the irreversiblity of the reaction. For example, this library reaction: `CH3OCH2+O2 => CH3OCH2O2` shows up as `S(103)(+M)=oxygen(3)+C2H5O(98)(+M)` This is the case for all other originally irreversible reactions.

**Comment by connie** [comment]
Fixed by the pull request.
