### ISSUE TITLE
CoreEdgeReactionModel.reactionDict family keys do not implement __eq__ nor __hash__

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#349]
`CoreEdgeReactionModel.reactionDict` stores the reactions in the reaction model via a 3-dimensional dictionary:

``` python
self.reactionDict[family][reactant1][reactant2]
```

with 
- family an implementation of `rmgpy.data.base.Database` (`rmgpy.data.kinetics.library.KineticsLibrary`, `rmgpy.data.kinetics.family.KineticsFamily`)
- reactant1, reactant2 belonging to `rmgpy.species.Species` 

A dictionary allows for a much faster search of the list of reactions when we want to check whether a candidate reaction is already present in the reaction model.

However, I believe there is a risk of false negatives because the family implementations do not have methods to compare instances (the hash and comparator methods).

Without adding these comparator methods, python will not be able to compare two family objects, and will consider them distinct if they exist as distinct objects in memory. Presumably, this did not seem to result in problems before because the family key was always a reference to the same object. However, in applications like parallel computing where objects are serialized and deserialized into new objects on a (remote) process this is a problem. 

Regardless of the application where serialization is necessary, using objects as dictionary keys without properly implementing comparator methods is a recipe for disaster.

**Comment by rwest** [comment]
Your analysis sounds right to me. I think it has not been a problem until now, because there's always only one database in memory and one instance of each family. But wouldn't hurt to have robust comparator methods. There's a chance it may already be a problem when loading from a restart file - I can't remember how we unpickle things in that case.

**Comment by nickvandewiele** [comment]
The branch https://github.com/nickvandewiele/RMG-Py/commits/comparator_db tries to address this and currently uses the name of the Database as a way of discriminating between Database objects.

**Comment by nickvandewiele** [comment]
I'm now working towards comparator methods for objects representing the generic concept of molecules (species, molecule, resonance isomer) in RMG-Py. The advantages of this are pretty straightforward:

* a centralized location where we compare species, and no need to *compare* species in other places, modules
* creating dicts of `Species` without having to worry about duplicate keys

Implementing this, is trickier than comparing simple databases if you want to avoid calling the expensive (NP hard) graph isomorphism algorithm or any equivalent algorithms such like canonicalization as much as possible.

The `rmgpy.molecule.Molecule.isIsomorphic()` method already implements a basic form of fingerprinting by checking the molecular formula. This could be extended further.

**Comment by rwest** [comment]
Further thoughts:

* Sometimes we may want to know if it's the same instance of a species, sometimes we want to know if it's isomorphic with a species, sometimes we want to compare it with a molecule, etc. etc.
* We need comparisons to be as fast as possible and called as seldom as possible.

Though I think this discussion should be on a separate issue or pull request.

**Comment by nickvandewiele** [comment]
see #350
