### ISSUE TITLE
Precision problem in rmgpy/kinetics/tunneling.pyx 

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#362]
On one of my computers, the tunnelingTest is failing on
```python
FAIL: Test the Eckart.calculateTunnelingFactor() method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/files/RMG-Py/rmgpy/kinetics/tunnelingTest.py", line 154, in test_calculateTunnelingFactor
    self.assertAlmostEqual(kexp, kact, delta=1e-3*kexp)
AssertionError: 1623051.0 != 4592927.993473404 within 1623.0509999999999 delta
```
Deeper checks against my other computer in which this test passes shows that all values are the same within the function except the precision in kappaE, which eventually gets summed to get the tunneling factor in line 189 in rmgpy/kinetics/tunneling.pyx
```python
kappaE = self.calculateTunnelingFunction(Elist)
```
The numpy versions are the same..  Not sure if this would affect anybody else.  All other tests in my RMG-Py on this linux computer pass.

**Comment by rwest** [comment]
The worrying thing is those values aren't even close! They're off by a factor of three!
Are we really that sensitive to machine precision? There must be a better algorithm or more sane maths?

**Comment by connie** [comment]
Fixed by https://github.com/ReactionMechanismGenerator/RMG-Py/pull/546
