### ISSUE TITLE
Bond Additive Corrections in CanTherm

### ISSUE THREAD

**Issue by bslakman** [ReactionMechanismGenerator/RMG-Py#363]
Many bond corrections are missing for some of the model chemistries.
Some are in this paper: http://scitation.aip.org/docserver/fulltext/aip/journal/jcp/109/24/1.477794.pdf?expires=1427745377&id=id&accname=2104641&checksum=F753A88F11894A039960F24936519B0F

How do we derive the rest if not in this paper? (N=C is not in this table or any for Silicon).

**Comment by bslakman** [comment]
Hopefully a working link now: http://scitation.aip.org/deliver/fulltext/aip/journal/jcp/109/24/1.477794.pdf;jsessionid=23427rb6tmjr4.x-aip-live-06?itemId=/content/aip/journal/jcp/109/24/10.1063/1.477794&mimeType=pdf&containerItemId=content/aip/journal/jcp

**Comment by connie** [comment]
Caleb has a chapter about the derivation of these in his thesis.  I can send it to you if you want it. He did a lot of calculations and did some fitting for the BACs against experimental/AcTc values.
