### ISSUE TITLE
Nondeterministic thermo group additivity: groups are added in alternate order lead to different values

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#366]
Ran two jobs (one was on a new branch but without any changes to the thermo alg.), Get the following differences in jobs:

```
! Thermo group additivity estimation: group(Cs-(Cds-Cds)CsHH) + other(R) + group(Cs-(Cds-Cds)CsHH) + other(R) + group(Cds-CdsCsOs) + other(R) + group
! (Cds-CdsCsH) + other(R) + group(Cds-Cds(Cds-Cds)H) + other(R) + group(Cds-Cds(Cds-Cds)H) + other(R) + group(Os-(Cds-Cd)H) + other(R) +
! ring(1,3-Cyclohexadiene) + radical(C=CJC=C) + radical(RC=COJ) + radical(Allyl_S)
C6H5O(19)               C 6  H 5  O 1       G100.000   5000.000  1013.51       1
 9.82961000E+00 2.47713506E-02-9.88273319E-06 1.86265971E-09-1.33245357E-13    2
 4.47242530E+04-2.65229924E+01 2.14946921E+00 3.02218927E-02 1.88443806E-05    3
-4.12359495E-08 1.64677896E-11 4.75578636E+04 1.69313861E+01                   4
```

vs.

```
! Thermo group additivity estimation: group(Cs-(Cds-Cds)CsHH) + other(R) + group(Cs-(Cds-Cds)CsHH) + other(R) + group(Cds-CdsCsOs) + other(R) + group
! (Cds-CdsCsH) + other(R) + group(Cds-Cds(Cds-Cds)H) + other(R) + group(Cds-Cds(Cds-Cds)H) + other(R) + group(Os-(Cds-Cd)H) + other(R) +
! ring(1,3-Cyclohexadiene) + radical(RC=COJ) + radical(Allyl_S) + radical(C=CJC=C)
C6H5O(19)               C 6  H 5  O 1       G100.000   5000.000  1013.50       1
 9.82955061E+00 2.47714509E-02-9.88279074E-06 1.86267325E-09-1.33246478E-13    2
 4.47242782E+04-2.65226576E+01 2.14948292E+00 3.02217298E-02 1.88449542E-05    3
-4.12366933E-08 1.64681049E-11 4.75578630E+04 1.69313371E+01                   4
```

Note that the last 3 groups are in a different order even though they are the same.  The coefficients end up having slightly different precision values in the last 4 digits.. see the 3rd coefficient.

Wondering if anyone else can duplicate this error?

**Comment by rwest** [comment]
I was about to say that these are exactly equivalent; but I agree that it would be nice for the logs and output files to be identical, so that one can use tools like "diff" to compare things, and "git" to track changes in your generated models, so it would indeed be nice for this to be non-random. Does it ever differ between runs on the same branch?

**Comment by connie** [comment]
The actual values are just slightly different if you check the last 4 digits of the 3rd value for instance....

Currently I am also debugging a kinetics issue =(

**Comment by rwest** [comment]
Are the polynomials from a constrained nonlinear optimization? I wouldn't expect the coefficients to be the same in all digits - I expect those evaluate to the same value within machine (or sensible) precision.
But still, I agree it would be nice if it were the same from run to run, for diffing purposes.
