### ISSUE TITLE
Re-using thermo of saturated species?

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#377]
This issue (rather: a potential performance gain) was raised by @connie and I believe she has a valid point.

In the current design we compute the thermochemistry of a molecule based on the fact whether it is present in the core or the edge of the CoreEdgeReactionModel. If a species is not present in union(core,edge), the thermochemistry will be computed.

However, there's a subspace of molecules for which the thermo will be calculated, regardless whether they belong to the core or edge: the saturated parent molecules.

For example:

When cyclohexane undergoes H-abstraction reactions 

![image](https://cloud.githubusercontent.com/assets/242147/7262503/291fc152-e848-11e4-9c2f-3c70df38d27c.png)

leading to 5 distinct radicals
![image](https://cloud.githubusercontent.com/assets/242147/7262536/7e01cab2-e848-11e4-960f-432f800c20e7.png)

When estimating the thermochemistry of the 5 radicals via the HBI method, the saturated molecule 'cyclohexane' will be generated for each of the 5 cases.

![image](https://cloud.githubusercontent.com/assets/242147/7262562/be936216-e848-11e4-9ab6-78931885587a.png)

Two remarks here: 
- The thermochemistry of cyclohexane will be computed via the methods we have (thermolibraries, GA, QMTP) even though there's a high chance that the thermo was already available because cyclohexane was already part of the core+edge. Ic: the radicals were generated from cyclohexane, so we are sure cyclohexane existed already.
- We will re-compute the thermo of cyclohexane 5 times.

The trade-off that should be considered here:
**Is looking up the thermo for saturated species slower or faster than recomputing it in the first place?**

In the current state of RMG-Py, we are forced to run species isomorphisms to compare species. But imagine a design with clever molecular fingerprints, and clever molecular caches that reduce the number of expensive isomorphism checks. 

Or imagine a hashed species dictionary where the retrieval of elements does not scale with the size of the dictionary (O(1)) as opposed to the current design that uses the very generic molecular formula as a key.

Thirdly, thermo originating from QMTP might be orders of magnitude more expensive to re-compute than thermo originating from group additivity.

**Comment by connie** [comment]
Recalculation of saturated molecule thermo is only done for GA. For QM this issue does not exist because RMG sees the cached thermo output files in the QMfiles folder.

**Comment by rwest** [comment]
True, but issue #375 makes me want to check we're saving the symmetry number in there too and loading it, otherwise even if the saturated molecule thermo itself is not recalculated, the symmetry number correction will be.  I haven't checked if this is the case. But it's a fairly minor point.

**Comment by connie** [comment]
Pretty sure it's not redone.  The symmetry calculation is performed in calculateThermoData() in qm/molecule.py  The generateThermoData() function that calls it returns the thermo if it exists prior to calling the calculateThermoData function.
