### ISSUE TITLE
Prune insignificant core reactions from final model

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#379]
Word on the street (at the international conference on numerical combustion) is that people don't like that RMG-built models have so many reactions in them, and a highly requested feature is the ability to prune insignificant reactions from the model core. This could be done just before saving the chemkin file if we want, although then our internal simulations will be of a different model to the one being output, making it harder to check, or we could actually delete the reactions from the core.  The user would have to specify another tolerance. Also it's not clear whether it should be based on sensitivity (of what target?) or flux (relative to what?)? 
This is basically model reduction, and perhaps we should borrow something intelligent from that literature. Other types of reduction (lumping etc.) have also been suggested, but I think first step is just throw out the reactions that needn't be there.
Thoughts?

**Comment by KEHANG** [comment]
If we use sensitivity, one thought for the target would be sum of square flux (maybe peak flux) error over all core species, meaning how much a small change of the investigated reaction kinetics affects the whole core kinetic simulation/ whole core flux-time diagram. But yeah, there's a lots of discussions in model reduction area, for example this paper, Klinke, D.J., Broadbelt, L.J., 1997. Mechanism reduction during computer generation of compact reaction models. AIChE J. 43, 1828–1837. doi:10.1002/aic.690430718

**Comment by connie** [comment]
Could someone present this for RMG study group next week?  ;)

**Comment by goldmanm** [comment]
Model reduction has been implemented (#448), but I don't think it runs automatically after an RMG run. Would we want to make this an option during a standard run, or leave it as an auxiliary step, as currently is done?

**Comment by goldmanm** [comment]
It seems based on #1018, that people who want reduction are running it after generation.
