### ISSUE TITLE
Anaconda Packaging of RMG-Py

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#387]
We are trying to package RMG-Py using the Anaconda platform.  This issue tracks the progress of the packaging. A checkbox indicates both binary and recipes are complete.

 - [ ] PyDAS
   - [X] Linux
   - [x] Mac OSX
   - [ ] Windows
 - [ ] PyDQED
   - [X] Linux
   - [x] Mac OSX
   - [ ] Windows
 - [ ] RMG-Py
   - [ ] Linux
   - [ ] Mac OSX
   - [ ] Windows

Dependencies we don't write, but need to ensure there are binaries for, and aren't in the official anaconda distro. For conda recipes, see https://github.com/ReactionMechanismGenerator/conda-recipes

 - [ ] quantities
   - [x] recipe
   - [x] Linux
   - [x] Mac OSX
   - [ ] Windows
 - [ ] guppy
   - [x] recipe
   - [x] Linux
   - [x] Mac OSX
   - [ ] Windows
 - [ ] gprof2dot
   - [x] recipe
   - [x] Linux
   - [x] Mac OSX
   - [ ] Windows
 - [ ] pydot (custom version that is compatible with pyparsing 2+)
  - [x] recipe
  - [x] Linux
  - [ ] Mac OSX
  - [ ] Windows
 - [ ] openbabel
   - [ ] recipe. Not fully working yet
   - [ ] Linux
   - [x] Mac OSX
   - [ ] Windows
 - [ ] rdkit. Maintained by rdkit
   - [ ] recipe
   - [x] Linux
   - [x] Mac OSX
   - [ ] Windows
 - [ ] boost. rdkit binary built against boost 1.56.0, which isn't in official anaconda
   - [ ] recipe
   - [x] Linux
   - [x] Mac OSX. 1.56.0 from rdkit
   - [ ] Windows
 - [ ] py2cairo - may not be needed (see cairocffi below)
   - [ ] recipe
   - [x] Linux
   - [x] Mac OSX. Binary copied from vgauthier; can't get recipe to build.
   - [ ] Windows
 - [ ] cairocffi - drop-in replacement for py2cairo
   - [ ] recipe
   - [ ] Linux
   - [ ] Mac OSX
   - [ ] Windows
 - [ ] cairo
   - [ ] recipe
   - [x] Linux
   - [x] Mac OSX
   - [ ] Windows
 - [ ] pixman (for cairo)
   - [ ] recipe
   - [ ] Linux
   - [x] Mac OSX
   - [ ] Windows
 - [ ] fontconfig (for cairo)
   - [ ] recipe
   - [ ] Linux
   - [x] Mac OSX. binary copied from vgauthier. can't get recip to build
   - [ ] Windows
 - [ ] MOPAC
   - [x] recipe
   - [x] Linux
   - [x] Mac OSX
   - [ ] Windows
 - [ ] symmetry
   - [x] recipe
   - [x] Linux
   - [ ] Mac OSX
   - [ ] Windows
 - [ ] graphviz (may be officially maintained?)
   - [ ] recipe
   - [ ] Linux
   - [ ] Mac OSX
   - [ ] Windows

Current `.condarc` references the following channels:
                                
    channels:
      - rmg
      - defaults

**To Do**

 - [x] Remove measure (deprecated)
 - [x] Place all scripts in setup.py so that they are added to conda bin properly
       - [x] Move scripts into scripts folder
       - [x] Documentation for standalone scripts (Mark working on them)
       - [x] Remove hardcoded paths for scripts (go into RMG-database scripts as well)
 - [x] Update version header for RMG log
 - [x] Make travis build branch for testing anaconda build independently
 - [x] RMG-database conda package.  rmgrc file instructions?
 - [x] QM stuff now uses symmetry installed in the conda bin folder.  This may break normal installation, so we may need some fallback measures
 - [x] Documentation for first-time users anaconda
 - [x] Documentation for developers using anaconda
 - [x] Update conda 'env' settings file
 - [x] Get 32-bit dependencies working for linux and mac

**Linux Testing**
- [x] Cantherm examples working
- [x] RMG examples that work: minimal, e85, diesel, liquid_phase, methylformate, minimal_sensitivity, TEOS, c3h4, ch3no2, 1,3-hexadiene
- [x] GenerateReactions example
- [x] Sensitivity example
- [x] ThermoEstimator example

**Comment by connie** [comment]
If we want to get databaseTest.py as a script:

Traceback (most recent call last):
  File "/home/connie/anaconda/envs/rmg2/bin/databaseTest.py", line 6, in <module>
    from external.wip import work_in_progress
ImportError: No module named external.wip

**Comment by rwest** [comment]
probably nothing in that `external` folder is being dealt with correctly yet. having cclib problems too.

**Comment by connie** [comment]
Openbabel additionally needs the python interface (I think all the current binstar packages don't have this so we may need our own recipe) http://open-babel.readthedocs.org/en/latest/UseTheLibrary/PythonInstall.html#linux-and-macosx

**Comment by rwest** [comment]
I found a promising looking but not finished recipe somewhere in github.
https://github.com/richlewis42/conda-openbabel

See also https://github.com/rmcgibbo/conda-cheminformatics

**Comment by connie** [comment]
Was able to create a working openbabel recipe (See https://github.com/GreenGroup/conda-recipes/commit/6e2b84b627d67127c47ca85bbe164430b847a23e) and the package for linux is now uploaded onto binstar.

**Comment by rwest** [comment]
your openbabel warnings suggest it's not entirely installed correctly.
I've done some work on the openbabel recipe, see https://github.com/GreenGroup/conda-recipes/pull/1
but I think it's still not quite there.

**Comment by connie** [comment]
Should get rid of hardcoding reference to jquery: 

    rmgpy/rmg/output.py:    <script type="text/javascript" src="../../../external/jquery.min.js"></script>

Maybe we can switch entirely to 

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"></script>

**Comment by connie** [comment]
Error related to the way QM finds RMG_bin_path when running either thermoEstimator or 1,3-hexadiene example. We will need to change the way this is handled in RMG-Py.

    Setting the quantum mechanics fileStore to /home/connie/Research/Code/RMG-Py/examples/rmg/1,3-hexadiene/QMfiles/pm3
    Setting the quantum mechanics scratchDirectory to /home/connie/Research/Code/RMG-Py/examples/rmg/1,3-hexadiene/QMscratch/pm3
    Traceback (most recent call last):
      File "/home/connie/anaconda//envs/rmg2/bin/rmg.py", line 147, in <module>
        rmg.execute(args)
      File "/home/connie/anaconda/envs/rmg2/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 442, in execute
        self.initialize(args)
      File "/home/connie/anaconda/envs/rmg2/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 351, in initialize
        self.quantumMechanics.initialize()
      File "/home/connie/anaconda/envs/rmg2/lib/python2.7/site-packages/rmgpy/qm/main.py", line 141, in initialize
        self.checkReady()
      File "/home/connie/anaconda/envs/rmg2/lib/python2.7/site-packages/rmgpy/qm/main.py", line 148, in checkReady
        self.checkPaths()
      File "/home/connie/anaconda/envs/rmg2/lib/python2.7/site-packages/rmgpy/qm/main.py", line 162, in checkPaths
        raise Exception("RMG-Py 'bin' directory {0} does not exist.".format(self.settings.RMG_bin_path))
    Exception: RMG-Py 'bin' directory /home/connie/anaconda/envs/rmg2/lib/python2.7/site-packages/bin does not exist.

**Comment by rwest** [comment]
Oh, and we should get it working on Travis CI too. I expect it will make our builds a lot faster! (No need to build RDKit from source every time!)

https://gist.github.com/dan-blanchard/7045057

**Comment by rwest** [comment]
We should add graphviz to the list.

**Comment by connie** [comment]
Finally got QM stuff working with the separate symmetry installation.

Has anyone seen this warning/error before? /home/connie/anaconda/envs/rmg/lib/python2.7/site-packages/rmgpy/qm/mopac.py:142: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  cclibMol.fromXYZ(cclibData.atomnos, cclibData.atomcoords[-1])

**Comment by pierrelb** [comment]
Yes I've come across it. I think it's a numpy warning about changes they plan on implementing.

**Comment by connie** [comment]
Ok fixed the numpy comparison problem via https://github.com/ReactionMechanismGenerator/RMG-Py/commit/6b72634b7eb9dcdfd5dce6d08a4d63475ddfe771

**Comment by connie** [comment]
Dependencies for anaconda now complete for linux, windows, and mac osx.  Binaries of RMG will be released for release 1.0.2
