### ISSUE TITLE
DASPK error leading to infinite loop.

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#392]
I got this error today while running a job:

    DASPK--  AT T (=R1) AND STEPSIZE H (=R2) THE                                    
        In above,  R1 =  0.5118705634138D+06   R2 =  0.3859840288851D-13
    DASPK--  ERROR TEST FAILED REPEATEDLY OR WITH ABS(H)=HMIN 

which was followed by

    DASPK--  THE LAST STEP TERMINATED WITH A NEGATIVE                               
    DASPK--  VALUE (=I1) OF IDID AND NO APPROPRIATE                                 
        In above message,  I1 =        -6
    DASPK--  ACTION WAS TAKEN. RUN TERMINATED

and this second error message was repeated until the job was aborted manually.

I think RMG should be able to catch such errors and end the job instead of repeatedly attempting to run the simulation. Has anyone else had this happen before?

The input file and associated seed mechanism can be found [here](https://www.dropbox.com/sh/fugu0qqixzj0p5p/AAD73U9tVQkbg29rJAPVl_Vza?dl=0) if anyone wants to replicate the issue.

**Comment by rwest** [comment]
Did you make any progress with this, Max? Did you find out what an `IDID` of `-6` means and how to deal with it?  (I have run into this issue too)

**Comment by mliu49** [comment]
I haven't looked into it that much. I've found that `IDID=-6` means that DASPK encountered repeated error test failures on the last attempted step, which doesn't seem very helpful. I'm not sure exactly what is causing the error test to fail, or how to deal with it yet.

**Comment by connie** [comment]
I think I've fixed the issue of infinite loop by catching the FORTRAN error from DASPK in PyDAS through https://github.com/ReactionMechanismGenerator/PyDAS/commit/c46aea866cbc5b4e20a7e622295badf7b1c6bd2e

Please update your PyDAS to official master.
