### ISSUE TITLE
Documentation 'make latexpdf' and 'make latex' not working 

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#395]
No pdf file is produced.

**Comment by rwest** [comment]
some progress on my `docs` branch

**Comment by connie** [comment]
Great it actually compiles a pdf now.  Mainly still failing on:
- Table of Contents
- Python Module Index
- Need documentation on stand-alone modules.  No information on model comparison/generateReactions, etc...

**Comment by rwest** [comment]
fixed up a few more latex bugs. compiles ok now, but a bit ugly in places

**Comment by rwest** [comment]
Title problem fixed. Remaining issues covered by #396
