### ISSUE TITLE
de-cythonize RMG-Py to run it in pure-python mode?

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#398]
I want to get rid of the requirements to compile the modules that contain cythonized python code, since it slows down my development, and debugging. 

The idea is to run RMG-Py, without the need to compile modules.

I saw that the `Makefile` in the main folder of RMG-Py contained a target `decython`, and the name suggests it serve that purpose I am interested in. However, the target instructions only seem to remove compiled code (`rm -rf *.so, *.pyc`). 

After
`make decython`

I run a test that uses RMG-Py modules by simply calling
`python myTest.py`

which leads to errors like:

```
  File "rmgpy/data/kinetics/common.py", line 36, in <module>
    from rmgpy.data.base import DatabaseError, LogicNode
  File "rmgpy/data/base.py", line 46, in <module>
    from rmgpy.molecule import Molecule, Group, InvalidAdjacencyListError
  File "rmgpy/molecule/__init__.py", line 31, in <module>
    from .adjlist import *
  File "rmgpy/molecule/adjlist.py", line 36, in <module>
    from .molecule import Atom, Bond
  File "rmgpy/molecule/molecule.py", line 48, in <module>
    from .graph import Vertex, Edge, Graph
ImportError: No module named graph
```

The error makes sense, because RMG-Py is still looking for those *.so files that don't exist anymore.

Any ideas to run RMG-Py without having to compile?

**Comment by rwest** [comment]
Some modules are not written in "pure Python" compatible mode and cannot be decythonized. I think graph may be among them, but cannot remember off the top of my head. The decythonize target is indeed what you were looking for and was made for the same reason, but has not been maintained. I am not sure how broken it is, but it is probably a good place to start.

**Comment by rwest** [comment]
It might have been the case that you had to `make decython` then `make minimal` to re-cythonize the minimal working set. But I don't think that target has been maintained either.
