### ISSUE TITLE
Unable to find reverse reaction due to forbidden groups

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#412]
I've gotten this error a few times with intra_H_migration and intra_substitutionS_isomerization. The issue is that the reactant is allowed but the product is forbidden, so RMG finds the forward reaction but is unable to find the reverse reaction. Currently, RMG gives the error and ends the job.

I was wondering if this is the best way to handle this situation? It seems that ideally, the forward reaction shouldn't be allowed either, if the product is forbidden.

**Comment by rwest** [comment]
You're right - I think it should do exactly what you describe (just skip the forward reaction if the product is forbidden). Is the product forbidden globally?  or just forbidden from reacting in that family? or just not matching the top node?
Perhaps you could give specific examples? (or even better, make a unit test that currently fails)
Thanks for opening the issue

**Comment by mliu49** [comment]
In the cases I've come across, the product is only forbidden from reacting in that family.

This is the most recent example:

    Error: Expecting one matching reverse reaction, not 0 in reaction family intra_substitutionS_isomerization for forward reaction <Molecule "[CH2]C(C)=C1[CH]C(=C)CSS1"> <=> <Molecule "C=C1[CH][C]=C(C)CSSC1">.
    
    Reactant
    multiplicity 3
    1  H u0 p0 c0 {19,S}
    2  H u0 p0 c0 {8,S}
    3  H u0 p0 c0 {8,S}
    4  H u0 p0 c0 {20,S}
    5  H u0 p0 c0 {12,S}
    6  H u0 p0 c0 {15,S}
    7  H u0 p0 c0 {15,S}
    8  C u0 p0 c0 {2,S} {3,S} {9,S} {13,S}
    9  H u0 p0 c0 {8,S}
    10 H u0 p0 c0 {19,S}
    11 H u0 p0 c0 {12,S}
    12 C u0 p0 c0 {5,S} {11,S} {18,D}
    13 C u0 p0 c0 {8,S} {14,D} {15,S}
    14 C u0 p0 c0 {13,D} {16,S} {20,S}
    15 C u1 p0 c0 {6,S} {7,S} {13,S}
    16 S u0 p2 c0 {14,S} {17,S}
    17 S u0 p2 c0 {16,S} {19,S}
    18 C u0 p0 c0 {12,D} {19,S} {20,S}
    19 C u0 p0 c0 {1,S} {10,S} {17,S} {18,S}
    20 C u1 p0 c0 {4,S} {14,S} {18,S}
    
    Product
    multiplicity 3
    1     C u0 p0 c0 {4,S} {9,S} {12,S} {13,S}
    2  *5 C u0 p0 c0 {5,S} {10,S} {11,S} {14,S}
    3     C u0 p0 c0 {4,S} {15,S} {16,S} {17,S}
    4     C u0 p0 c0 {1,S} {3,S} {8,D}
    5  *4 C u0 p0 c0 {2,S} {6,S} {7,D}
    6  *3 C u1 p0 c0 {5,S} {8,S} {18,S}
    7     C u0 p0 c0 {5,D} {19,S} {20,S}
    8     C u1 p0 c0 {4,D} {6,S}
    9  *1 S u0 p2 c0 {1,S} {10,S}
    10 *2 S u0 p2 c0 {2,S} {9,S}
    11    H u0 p0 c0 {2,S}
    12    H u0 p0 c0 {1,S}
    13    H u0 p0 c0 {1,S}
    14    H u0 p0 c0 {2,S}
    15    H u0 p0 c0 {3,S}
    16    H u0 p0 c0 {3,S}
    17    H u0 p0 c0 {3,S}
    18    H u0 p0 c0 {6,S}
    19    H u0 p0 c0 {7,S}
    20    H u0 p0 c0 {7,S}

**Comment by mliu49** [comment]
I looked into the issue some more, and it seems that it is due to differences in atom labeling when a species is a reactant vs. a product.

In the case I've been looking at, RMG finds the H_Abstraction reaction

    [CH2]C=CC=C[CH2] + RH <=> [CH2]C=CC=CC + R

but cannot find its reverse.

The relevant forbidden group in H_Abstraction is

    1 *1 R u0 {2,S} {3,S}
    2    R u0 {1,S} {4,D}
    3 *2 H u0 {1,S}
    4    R u0 {2,D} {5,S}
    5    R u0 {4,S} {6,D}
    6    R u0 {5,D} {7,S}
    7    R u1 {6,S}

which seems to match [CH2]C=CC=CC. However, when [CH2]C=CC=CC is the product, its atoms are labeled differently (with *2 and *3), which is not technically forbidden. Therefore, the forward reaction is found without any problems, but when RMG tries to look for the reverse reaction, [CH2]C=CC=CC is relabeled to match the forbidden group, so the reverse reaction cannot be found.

When a group is forbidden globally (in input/forbiddenStructures.py), the atoms are not labeled, so both the forward and reverse reactions are automatically forbidden.

Some thoughts I had regarding potential fixes:
* Not labeling forbidden groups - I don't know if this is allowed in RMG, but it also wouldn't be a good idea if a molecule can react multiple ways and only one way is meant to be forbidden
* Also forbid same group with different labels - Seems like the simplest option
* Add code to somehow detect when such a situation occurs - Might be unnecessarily complicated

On a semi-related note, it would be great if people wrote comments explaining the reasoning behind forbidden groups when they add them.

**Comment by connie** [comment]
Just wrote a hack fix in my enlargeReactionFilter branch here: https://github.com/ReactionMechanismGenerator/RMG-Py/commit/f0b57a5cb9f908a703406fe7c975ec7b6d82b3d5

The reason why I would be against 1) not labeling forbidden groups, is that we want to ban specific TS's or pathways, not entire molecules
2) forbidding same group with different labels, this should work if we can figure out how to find the reverse
3) The code fix = my hack so far, we should think of a better solution?  I think this way is ok since we're dealing with forbidden pathways that should probably be banned both ways, but 
4) we should come up with unit tests to help fix this error in the database when the reason is not forbiddenStructures
