### ISSUE TITLE
rdkit error in minimal example

### ISSUE THREAD

**Issue by bslakman** [ReactionMechanismGenerator/RMG-Py#416]
I am getting the following error on updated master branch of RMG-Py and RMG-database, on both my Mac and a Linux cluster: 

```
Adding rate rules from training set in kinetics families...
Traceback (most recent call last):
  File "rmg.py", line 139, in <module>
    cProfile.runctx(command, global_vars, local_vars, stats_file)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/Users/belinda/Code/RMG-Py/rmgpy/rmg/main.py", line 462, in execute
    self.initialize(args)
  File "/Users/belinda/Code/RMG-Py/rmgpy/rmg/main.py", line 354, in initialize
    self.loadDatabase()
  File "/Users/belinda/Code/RMG-Py/rmgpy/rmg/main.py", line 296, in loadDatabase
    family.addKineticsRulesFromTrainingSet(thermoDatabase=self.database.thermo)
  File "/Users/belinda/Code/RMG-Py/rmgpy/data/kinetics/family.py", line 893, in addKineticsRulesFromTrainingSet
    reactant.thermo = thermoDatabase.getThermoData(reactant, trainingSet=True)
  File "/Users/belinda/Code/RMG-Py/rmgpy/data/thermo.py", line 732, in getThermoData
    logging.info("Resonance isomer {0} {1} gives H298={2:.0f} J/mol".format(i+1, thermo[i][2].toSMILES(), thermo[i][1]))
  File "molecule.py", line 1424, in rmgpy.molecule.molecule.Molecule.toSMILES (build/pyrex/rmgpy/molecule/molecule.c:22385)
  File "molecule.py", line 1455, in rmgpy.molecule.molecule.Molecule.toSMILES (build/pyrex/rmgpy/molecule/molecule.c:22250)
  File "molecule.py", line 1530, in rmgpy.molecule.molecule.Molecule.toRDKitMol (build/pyrex/rmgpy/molecule/molecule.c:23447)
ArgumentError: Python argument types in
    rdkit.Chem.rdmolops.RemoveHs(Mol)
did not match C++ signature:
    RemoveHs(RDKit::ROMol mol, bool implicitOnly=False)
make: *** [eg1] Error 1
```

Can others replicate this error? I will go back in git time to try and see which commit (if any) is causing it because it was working recently. Or maybe it is an rdkit issue.

**Comment by connie** [comment]
Yeah, this is due to using the older version of RDKit.  Richard added this
line to help aromaticity detection, but it requires the newer version of
RDKit.

On Thu, Jul 23, 2015 at 1:29 PM, bslakman <notifications@github.com> wrote:

> I am getting the following error on updated master branch of RMG-Py and
> RMG-database, on both my Mac and a Linux cluster:
>
> Adding rate rules from training set in kinetics families...
> Traceback (most recent call last):
>   File "rmg.py", line 139, in <module>
>     cProfile.runctx(command, global_vars, local_vars, stats_file)
>   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cProfile.py", line 49, in runctx
>     prof = prof.runctx(statement, globals, locals)
>   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cProfile.py", line 140, in runctx
>     exec cmd in globals, locals
>   File "<string>", line 1, in <module>
>   File "/Users/belinda/Code/RMG-Py/rmgpy/rmg/main.py", line 462, in execute
>     self.initialize(args)
>   File "/Users/belinda/Code/RMG-Py/rmgpy/rmg/main.py", line 354, in initialize
>     self.loadDatabase()
>   File "/Users/belinda/Code/RMG-Py/rmgpy/rmg/main.py", line 296, in loadDatabase
>     family.addKineticsRulesFromTrainingSet(thermoDatabase=self.database.thermo)
>   File "/Users/belinda/Code/RMG-Py/rmgpy/data/kinetics/family.py", line 893, in addKineticsRulesFromTrainingSet
>     reactant.thermo = thermoDatabase.getThermoData(reactant, trainingSet=True)
>   File "/Users/belinda/Code/RMG-Py/rmgpy/data/thermo.py", line 732, in getThermoData
>     logging.info("Resonance isomer {0} {1} gives H298={2:.0f} J/mol".format(i+1, thermo[i][2].toSMILES(), thermo[i][1]))
>   File "molecule.py", line 1424, in rmgpy.molecule.molecule.Molecule.toSMILES (build/pyrex/rmgpy/molecule/molecule.c:22385)
>   File "molecule.py", line 1455, in rmgpy.molecule.molecule.Molecule.toSMILES (build/pyrex/rmgpy/molecule/molecule.c:22250)
>   File "molecule.py", line 1530, in rmgpy.molecule.molecule.Molecule.toRDKitMol (build/pyrex/rmgpy/molecule/molecule.c:23447)
> ArgumentError: Python argument types in
>     rdkit.Chem.rdmolops.RemoveHs(Mol)
> did not match C++ signature:
>     RemoveHs(RDKit::ROMol mol, bool implicitOnly=False)
> make: *** [eg1] Error 1
>
> Can others replicate this error? I will go back in git time to try and see
> which commit (if any) is causing it because it was working recently. Or
> maybe it is an rdkit issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactionMechanismGenerator/RMG-Py/issues/416>.
>



-- 
Connie Gao
connieg@mit.edu || homepage <http://www.conniegao.com> || 978-500-5197
Chemical Engineering PhD Candidate
Massachusetts Institute of Technology

**Comment by rwest** [comment]
We should add an RDKit version detection check to the Makefile. It checks that RDKit is present, but doesn't insist on a version number. (Though I'm not sure when this API was changed so which version to insist on)

**Comment by rwest** [comment]
I think it was something like this commit that added the needed option to the API
https://github.com/rdkit/rdkit/commit/c41ffea23ba597e8e17dfa9db052aedeffe807d2
so 2015.03 is probably the first official release with it in.

The version check is in pull request #423 so I'm closing this issue.

**Comment by rwest** [comment]
p.s. anyone upgrading RDKit after finding this issue: don't forget to install with InChI support!!
