### ISSUE TITLE
Two Classes of ReactionModel?

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#418]
class ReactionModel Found at: rmgpy.reaction
class ReactionModel Found at: rmgpy.rmg.model
class CoreEdgeReactionModel Found at: rmgpy.rmg.model

Is the one in rmgpy.reaction used for anything? seems to have a bunch of duplicated methods in the CoreEdgeReactionModel in rmgpy.rmg.model

**Comment by connie** [comment]
So it looks like `ReactionModel` in `rmgpy.rmg.model` is used as a subclass for `CoreEdgeReactionModel`, with just simple attributes `species` and `reactions` for use in both core and edge.  

The  `ReactionModel` in `rmgpy.rmg.reaction` is not used anywhere in the rmgpy module code, it is used instead in the scripts for merging and diffing models. I guess the two classes could be merged but it might not be ideal?  Perhaps we could rename one of them?
