### ISSUE TITLE
Latest version of graphviz cannot draw 'png' format graphs

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#421]
Using Graphviz 2.38 and pydot2.01 (from conda), the following code:

    import pydot
    graph = pydot.Dot(graph_type='graph', dpi="52")
    graph.add_edge(pydot.Edge(
                        src = 'b',
                       dst = 'c',
                       label = 'stuff',
                        fontname='Helvetica', fontsize = "16",
                   ))

    graph.create(prog='neato', format='png')

Gives the following error

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "build/bdist.linux-x86_64/egg/pydot.py", line 2023, in create
    pydot.InvocationException: Program terminated with status: 1. stderr follows: Format: "png" not recognized. Use one of: canon cmap cmapx cmapx_np dot eps fig gv imap imap_np ismap pic plain plain-ext pov ps ps2 svg svgz tk vml vmlz xdot xdot1.2 xdot1.4

This is an issue for RMG-website drawing of groups (@mliu49).  Does this work for people on Mac?

**Comment by connie** [comment]
Fixed by recompiling conda-recipe of Graphviz 2.38.0 and uploading to binstar.

Had to reinstall anaconda in the process, but hey it worked.

**Comment by waterofphysics** [comment]
@connie Could you please give more details about how you solve this problem? I have encountered the same problem. Thanks!
