### ISSUE TITLE
Investigating the Behavior of Training Reactions

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#434]
It has come to @nyee and my attention that the behavior of training reactions is not well understood, and that we need to make their estimation more transparent, as well as make them easier to add to the database.  Here are some tasks:

Tool to add training reactions to database
- Needs to show what rule template it falls into
- Needs to show the variance of the previously existing rate rule (to determine if a new group should be created.  We see several rate rules created in `H_Abstraction` where several training reactions collapse into 1).  
- Automatically stars the correct atoms.  We need to figure out when and where starred atoms are necessary, both when reaction is in forward vs. reverse direction with respect to the family's template.  What happens with cases where there is more than 1 transition state?

Bug fixes
- Do we set default ranks for training reactions?  What happens when `rank = None` for either a normal rate rule or training reaction? (RMG does not throw an error when running with no rank in the reactions.py)
  - Case example:  `CC(=O)C(C)CC + [OH] = [CH2]C(=O)C(C)CC + H2O`
    uses the template: `C/H3/CO;O_pri_rad` in the `H_Abstraction` family.
  - There are 4 rules total, 1 original rate rule, and 3 generated from training reactions 1003, 1004, 1007 
  - Kinetics picks the rule which has the highest rank out of the 4 rules, if the rank is equivalent, it picks the one that it hits first (this is chosen based on the numerically smallest entry index of the rate rule, noting that original rate rules always have smaller entry indices than training reaction created rate rules).  
  - A rank of `None` is considered in the same manner, just after anything with a rank.  See https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/data/kinetics/rules.py#L349

**Comment by nyee** [comment]
I have previously addressed some of these issues branch https://github.com/nyee/RMG-database/tree/csv. There is a script (in very nascent state) called generateDatabaseCsv, which makes a csv format for training depositories. It currently lists which template each reaction falls under, and will print when two reactions fall under the same template. 

I plan on expanding this in near future to more automatically compare training reactions and possibly give recommendation if new groups should be created.

**Comment by rwest** [comment]
I think we were planning for the interface for adding and editing training reactions would be via the website, and some of the features of the tool you describe above were (partly) implemented there? Is that still the easiest plan? (I think it probably is.)

**Comment by connie** [comment]
I think eventually we will want the website interface to work, but currently that seems to be quite broken ever since the training reactions have gotten divided into `reaction.py` and `dictionary.txt`. We should probably still have scripts that can do multiple reactions in one go.

**Comment by rwest** [comment]
Yes, I noticed that the reactions.py and dictionary.txt change was not totally smooth. It would be nicer if `Library` and `Depository` classes both just worked with the `save()` method, as they used to. Now you have to explicitly call `saveDictionary()` as well.   But that's another issue.
