### ISSUE TITLE
Redesigning Reaction classes

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#440]
I am working on a PR that would drastically change the way we deal with Reaction objects. Right now, I find it very difficult to add new functionality to RMG ( e.g. parallelizing reaction generation) without breaking existing code. 

RMG uses many Reaction classes throughout its databases and ReactionModel's, and uses many different types of reactant/product classes (Molecule, Species, Group).

Maybe one small step is to clearly define what each structure/reaction class should embody and how they should be used. 

Here's my trial. Comments are welcomed.
# Molecular structures:
- `rmgpy.molecule.molecule.Molecule` = a Graph with zero or more unspecified moieties (atoms, bonds, valencies), represents a single resonance isomer.
- `rmgpy.species.Species` = a structure that can be represented by 1 or more resonance isomers (Molecule).
- `rmgpy.molecule.group.Group` = a Graph with zero or more unspecified moieties (atoms, bonds, valencies), and one or more atoms labeled as reactive centers.
# Reaction collections
- `rmgpy.data.kinetics.library.Library` = a list of reactions put together as a collection based on the source (publication, mechanism, ...)

For example: Seed mechanisms can be used to create Library objects
- `rmgpy.data.kinetics.depository.Depository` = a Library with all reactions belonging to one specific reaction family 
  that can be used to create additional rate rules. 

For example: the NIST reactions for each reaction family is a depository
## Reaction classes
- `rmgpy.data.kinetics.library.LibraryReaction` = a reaction consisting of well-defined Species reactants and Species products, originating from a Library.
- `rmgpy.data.kinetics.depository.DepositoryReaction` = a reaction consisting of well-defined Group reactants and Group products with zero unspecified moieties. Group reactants and products in a DepositoryReaction can be considered as Species objects with one or more atoms labeled as reactive centers. DepositoryReaction objects are collected in a Depository.
- `rmgpy.data.kinetics.rules.RulesReaction` = a reaction consisting of one or more Group reactants, belonging to one specific reaction family. Products of a RulesReaction are not explicitly defined but computed based on the reaction family template and the reactive centers of the Group reactants. This class represents the (abstract) reaction associated with a rate rule.
- `rmgpy.data.kinetics.family.TemplateReaction` = a reaction consisting of well-defined Species reactants and Species products, created based on the application of a reaction family. 
## Reaction classes that should only be alive as part of a Database object:
- `rmgpy.data.kinetics.rules.RulesReaction`
- `rmgpy.data.kinetics.depository.DepositoryReaction`
## Reaction objects that should be part of a CoreEdgeReactionModel:
- `rmgpy.data.kinetics.family.TemplateReaction`
- `rmgpy.data.kinetics.library.LibraryReaction`

In this framework, the reactants or products of a reaction that is part of a growing reaction model should never be populated with Molecule objects, but always with Species objects. Likewise, reaction objects that live within a Database objects always use Group objects, never Molecule objects.

Moreover, previously the template of a ReactionFamily would be stored as a reaction object. In the new design, this would be a new class, e.g. `rmgpy.data.kinetics.family.FamilyTemplate`

The biggest hiatus that remains is where `rmgpy.rmg.pdep.PDepReaction` exactly fits in.

**Comment by nickvandewiele** [comment]
Which reaction classes should have a reaction path degeneracy attribute?

Reaction class | Degeneracy? | Why/ Why not?
------------ | ------------- | -------------
TemplateReaction | yes | derived from degeneracy-agnostic rate rules
LibraryReaction | no | degeneracy incorporated in rate coefficient (k)
DepositoryReaction | yes | degeneracy should be removed to create a rate rule
RulesReaction | no | impossible to determine degeneracy for Groups

**Comment by nickvandewiele** [comment]
Which reaction classes should have a `reversible` attribute?

Reaction class | Reversible | Why/ Why not?
------------ | ------------- | -------------
TemplateReaction | yes | to compute reverse rate coefficient
LibraryReaction | no | we use the rate coefficient (k) as is
DepositoryReaction | yes | to compute reverse rate rule if reaction is defined in reverse direction
RulesReaction | no | this reaction only lives in the database

**Comment by nickvandewiele** [comment]
Which reaction classes should have a `duplicate` attribute?

Reaction class | Duplicate | Why/ Why not?
------------ | ------------- | -------------
TemplateReaction | no | currently, we don't support multiple TS's within a reaction family
LibraryReaction | yes | in the same library 2 reactions may be declared as duplicates
DepositoryReaction | no | no support for multiple TS's within a reaction family
RulesReaction | no | no support for multiple TS's within a reaction family

**Comment by rwest** [comment]
Thanks for this clarification post/discussion. It'll help people if we transfer this into "developer documentation" once finalized. Your original post says LibraryReaction should only be in a CoreEdgeReactionModel and not part of a Database object - but what about reaction libraries? What do they contain, if not LibraryReactions? They don't quite match your description of DepositoryReaction.

**Comment by rwest** [comment]
You say LibraryReactions should not have a reversible attribute, but some reaction libraries (which are typically kinetic models imported from the literature) contain reactions that are irreversible. eg. in ERC-FoundationFuelv0.9:
```python
entry(
    index = 39,
    label = "CH + O2 => O + H + CO",
    degeneracy = 1,
    reversible = False,
    kinetics = Arrhenius(
        A = (2.8365e+08, 'cm^3/(mol*s)'),
        n = 1.43,
        Ea = (1200, 'cal/mol'),
        T0 = (1, 'K'),
    ),
)
```

Of our current libraries, this is how common it is:
Dooley/methylformate_all_ARHEbathgas/reactions.py:6
Dooley/methylformate_all_N2bathgas/reactions.py:6
ERC-FoundationFuelv0.9/reactions.py:10
GRI-Mech3.0/reactions.py:15
GRI-Mech3.0-N/reactions.py:15
Glarborg/C2/reactions.py:2
Glarborg/C3/reactions.py:3
Glarborg/highP/reactions.py:3
Nitrogen_Glarborg_Gimenez_et_al/reactions.py:13
Nitrogen_Glarborg_Lucassen_et_al/reactions.py:8
Nitrogen_Glarborg_Zhang_et_al/reactions.py:9
OxygenSingTrip/reactions.py:2

**Comment by nickvandewiele** [comment]
@rwest 
I agree, LibraryReaction instances should be created when importing reaction libraries (not associated with reaction families), and hence should be part of a Database object. And they should also live in the CERModel. That's probably the only reaction class that will live in a db as well as a CERModel.

**Comment by nickvandewiele** [comment]
About the reversible attribute, you are right again. I was confused and thinking of the `reverse` attribute of Reaction that is created at runtime. 

I think the `reversible` attribute should be kept for pretty much every reaction class. It can be discussed whether the `reverse` attribute might be valuable enough to store it in some reaction types.
