### ISSUE TITLE
Images can't distinguish between spin state of biradicals (2S or 2T)

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#46]
The images don't distinguish between 2T and 2S electron states.
This picture:
http://rmg.mit.edu/molecule/1%20C%202T;
<img src="http://rmg.mit.edu/molecule/1%20C%202T;">
looks the same as this picture:
http://rmg.mit.edu/molecule/1%20C%202S;
<img src="http://rmg.mit.edu/molecule/1%20C%202S;">

**Comment by connie** [comment]
We now have dots on triplet state and nothing on singlet state.
