### ISSUE TITLE
Reaction families hard-coded in RMG-Py (not just loaded from RMG-database)

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#466]
`/rmgpy/data/kinetics/common.py` has two big lists of all the reaction families hard coded. If you add one to the RMG-database, but not here, things probably break. And vice versa. Not good design. 

As Josh noted when he first wrote 15e965a9aef65fdcf84184fc0e097dcf53a1d53a:
> **I'd rather they weren't needed at all, of course,** but currently they are used when reading
and writing the old database to get the appropriate units.

I think there are a few other places where special things (like reactions that are their own reverse) are hard-coded, which it would also be good to retire.

**Comment by connie** [comment]
What we could do is hard code or provide this information in the database files with a new attribute. It would also make adding new families easier to do when the code is all in one repo.


_____________________________

**Comment by rwest** [comment]
Yes, hard-coding is somewhat inevitable, but I think moving it to the RMG-database project would be a great improvement.

**Comment by connie** [comment]
Those two lists and how they were used was taken care of by https://github.com/ReactionMechanismGenerator/RMG-Py/pull/504

Now they are only used for importing RMG-Java stuff, not used at all in RMG-Py
