### ISSUE TITLE
Windows installation instructions 

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#475]
We should update the instructions on the basis of this helpful advice from Nancy...

On Oct 22, 2015, at 2:47 AM, Olivier HERBINET wrote:

> Most of instructions are correct except the following one :
> * I used numpy 1.7.1
> * I used scipy 0.15.1
> * I directly downloaded daspk31.tgz and put it in the daspk31 folder (the web link does not work)
> * I used the RDKit_2015_03_1

**Comment by connie** [comment]
Closed via anaconda build: https://github.com/ReactionMechanismGenerator/RMG-Py/pull/534
