### ISSUE TITLE
Benzyne and cyclohexa-1,2,3,5-tetraene should be resonance isomers of each other

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#476]
Currently, 

benzyne 

```
1  C u0 p0 c0 {2,T} {6,S}
2  C u0 p0 c0 {1,T} {3,S}
3  C u0 p0 c0 {2,S} {4,D} {7,S}
4  C u0 p0 c0 {3,D} {5,S} {8,S}
5  C u0 p0 c0 {4,S} {6,D} {9,S}
6  C u0 p0 c0 {1,S} {5,D} {10,S}
7  H u0 p0 c0 {3,S}
8  H u0 p0 c0 {4,S}
9  H u0 p0 c0 {5,S}
10 H u0 p0 c0 {6,S}
```

and 

cyclohexa-1,2,3,5-tetraene

```
1 C u0 p0 c0 {2,D} {3,S} {7,S}
2 C u0 p0 c0 {1,D} {4,S} {8,S}
3 C u0 p0 c0 {1,S} {5,D} {9,S}
4 C u0 p0 c0 {2,S} {6,D} {10,S}
5 C u0 p0 c0 {3,D} {6,D}
6 C u0 p0 c0 {4,D} {5,D}
7 H u0 p0 c0 {1,S}
8 H u0 p0 c0 {2,S}
9 H u0 p0 c0 {3,S}
10 H u0 p0 c0 {4,S}
```

are not perceived as resonance isomers of each other. As a result, the 2 structures are not isomorphic to each other, and hence introduce separate species into models that are, in fact, representing the same structure. This may be problematic for models involving aromatics.

A 'benzyne' query in the issue and PR list, found #322 as a PR that discussed benzyne. This issue is somehow unrelated, though, since we are not trying to answer whether benzyne is aromatic or not.

**Comment by mliu49** [comment]
Fixed by #1452.
