### ISSUE TITLE
Sanitization error for Carbon Monoxide?

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#489]
My understanding is that we represent _carbon monoxide_ as the triple-bonded structure with charged atoms, each atom bearing 1 lone pair.

When I run this Molecule through RDKit's `Chem.Sanitize`, it complains the valency is not correct.

``` python

    from rmgpy.molecule import Molecule
    from rdkit import Chem
    import rmgpy.molecule.generator as generator
    adj = """
    1 O u0 p1 c+1 {2,T}
    2 C u0 p1 c-1 {1,T}
    """

    mol = Molecule().fromAdjacencyList(adj)
    rdkitmol = generator.toRDKitMol(mol, sanitize=False)
    Chem.SanitizeMol(rdkitmol)
```

RMG-Py, by default, runs RDKit's sanitize functionality for compounds that do not contain nitrogen atoms.

I wonder how the error of CO should be treated. The options I see:
- change the representation of CO to comply with RDKit's Sanitization procedure?
- avoid having CO in RMG-Py altogether?
- change the default settings for sanitization calls in RMG-Py

I could not find prior raised issues on this topic, apart from #367, in which the representation of carbon monoxide in the [`solvation.transformLonePairs`](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/data/solvation.py#L677) function of RMG-Py was changed into the biradical to avoid the same SanitizationError. https://github.com/bslakman/RMG-Py/commit/aa15c5c12fd0a902ec228efb5dce6a5b5335b24d

**Comment by rwest** [comment]
Not sure how we ought best to represent CO, but a molecule search for "carbon monoxide" returns formaldehyde, and one for `[C][O]` returns something even stranger.

**Comment by alongd** [comment]
In Wikipedia (for what it's worth) carbon monoxide's SMILES are ```[C-]#[O+]```, as @nickvandewiele 's AdjList suggests.
In the latest test I ran in RMG-Py (my ref xa1179) I added  ```[C-]#[O+]``` to the initial mixture, looking for its reactions with ethylamine (```NCC```). Surprisingly, the ```[C-]#[O+]``` species did not react with ethylamine (did react with H2, NH3, CH4...). Instead, RMG predicted the species ```[C]=O``` (triplet), which gave the reactions I was expecting.

See Issues: RMP-Py #184, ReactionMechanismGenerator/RMG-database#31

@connie reccomended to represent CO as ```[C-]#[O+]``` in issue ReactionMechanismGenerator/RMG-database#31. I agree we should continue to update this in the database. For example, In the 2+2_cycloaddition_CO kinetic family (in groups.py), CO is still defined as ```[C]=O``` (to the best of my understanding):
```
entry(
    index = 1,
    label = "CO",
    group = 
"""
1 *1 CO u0 {2,D}
2 *2 Od u0 {1,D}
""",
    kinetics = None,
)
```

Another problem (which brought up this issue for me in the first place) is that currently only radicals can react to abstract a proton in the H_Abstraction kinetic family (```reactants=["X_H_or_Xrad_H_Xbirad_H_Xtrirad_H", "Y_rad_birad_trirad_quadrad"]```), so I'm not getting the reactions I was expecting from CO (e.g.,```CH3CH2NH2 + CO <=> CH2CH2NH2 + HCO```) using the ```[C-]#[O+]``` species.

**Comment by soumsrani** [comment]
Hi, I am using 796adab1417a3289f15c29227cb95997778cf5df version of RMG-Py. I am also getting both [C-]#[O+] and [C]=O in the mechanism. The mechanism generated contains CH4, C2H6 and C3H8 chemistry.
[input.docx](https://github.com/ReactionMechanismGenerator/RMG-Py/files/155076/input.docx)

**Comment by connie** [comment]
I believe the `2+2_cycloaddition_CO` is not meant for carbon monoxide but instead of C=O double bonded forms, as the child groups of that entry are all things like methanal, etc.

I do believe that `H_Abstraction` only should occur with radical abstraction.  I forget what we were thinking but I thought there were routes for this reaction to occur not through `H_Abstraction` but I'm not sure..

**Comment by alongd** [comment]
Just ran 4 simulations of:
1% [C-]#[O+], 1% X in 98% Ar at 1500K for 10 s,
where X = H2 \ CH4 \ NH3 \ NCC

this structure of CO seems to react in RMG only via the ```1,2 Insertion CO``` family.
RMG generated reaction of this sort:
```
CO(1)+H2(2)=CH2O(4)
CO(1)+CH4(2)=C2H4O(7)
CO(1)+NH3(2)=CH3NO(5)
CO(1)+NCC(2)=C3H7NO(13)
CO(1)+C2H4(29)=C3H4O(37)
..........
```

I did _not_ get any of the following reactions (looked in chem_edge_annotated.inp as well):
```
CO+H2=HCO+H
CO+CH4=HCO+CH3
CO+NH3=HCO+NH2
CO+NCC=HCO+NCCrad
CO+C2H4=HCO+C2H3
..........
```

These are probably important to many RMG works, and should be added to the ```Disproportionation``` family template.

**Comment by rwest** [comment]
Sounds like this needs some serious attention.

**Comment by alongd** [comment]
In second thought, maybe ```Disproportionation``` is not the right template for these reactions.
```
Disproportionation:
*R1 + *R3-R2-H <=> R1-H + R3=R2
```
While we need to form a unique triple bond (`[R3+]#[R2-]`):
```
 *R1 + *R3-R2-H <=> R1-H + R3#R2
(*R  + *HCO     <=> R-H + [C-]#[O+])
```

I couldn't see any other fit from our reaction families.
Should we open a new reaction family, or did I miss something?

**Comment by alongd** [comment]
Perhaps we should open a `CO_disprop` family.

Strengthening the Wikipedia comment from above, the following paper says that `[C-]#[O+]` is indeed the right non-excited form of CO:
[Electronic structure of CO—An exercise in modern chemical bonding theory](http://onlinelibrary.wiley.com/doi/10.1002/jcc.20477/full)

**Comment by mliu49** [comment]
I think CO representation has been fixed, and the CO_disprop family has also been added already.
