### ISSUE TITLE
Bond Additivity Corrections for CBS-QB3 in CanTherm

### ISSUE THREAD

**Issue by faribas** [ReactionMechanismGenerator/RMG-Py#506]
Wondering if we should use BAC for CBS-QB3 from the work of Sabbe et al.(http://pubs.acs.org/doi/pdf/10.1021/jp050484r), table 2, or stick to what we already have in CanTherm? 
Currently in CanTherm, we are using CBS-Q corrections for CBS-QB3 (50d21c64221f88aaa04c945623e401678b60d2df).

**Comment by enochd** [comment]
There are only 4 values in Table 2 (note the typo of the last C-C entry
which should be C#C, triple bond). So, perhaps these 4 corrections can
replace the corresponding CBS-Q BACs, but you might want to conduct your
own comparisons of thermo based on the new BACs

**Comment by mliu49** [comment]
This has been addressed by #1272 which used an even newer publication.
