### ISSUE TITLE
Some tests need at least Openbabel 2.3.2

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#512]
The InChI parser / generator of Openbabel 2.3.2 seems to have changed from 2.3.1 to 2.3.2. Some of the unit tests that run successfully with 2.3.2 fail with 2.3.1. As a consequence, we should restrict the allowed versions of OB to 2.3.2+.

**Comment by mliu49** [comment]
The RMG anaconda channel provides OpenBabel 2.3.2.
