### ISSUE TITLE
Duplicate Reactions In Core Mechanism - RMG-Py

### ISSUE THREAD

**Issue by Alborzi** [ReactionMechanismGenerator/RMG-Py#513]
Dear all,

RMG-Py seems to have a major issue where it includes identical duplicate reactions in the final chemkin scheme (assuming it still builds up the model as it goes along.)

    The current git HEAD is:
    	670e781c961166271c9ea7e605de45cb8bf8d383
    	Sat Dec 5 09:57:58 2015 -0500

Inspection of the output.html file shows that the kinetics are identical and only the order in which the reactants are written has changed.

    43 
    T/[K] 	500	1000	1500	2000
    log10(k/[mole,m,s]) 	+7.3	+7.3	+7.3	+7.3
    Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Estimated using template (O_pri_rad;O_sec_rad) for rate rule (O_pri_rad;O_rad/NonDe)""")

    ! Template reaction: R_Recombination
    ! Estimated using template (O_pri_rad;O_sec_rad) for rate rule (O_pri_rad;O_rad/NonDe)
    HOJ(7)+C12OJ(2)=S(2)                                2.000e+13 0.000     0.000    

	Estimated using template (O_pri_rad;O_sec_rad) for rate rule (O_pri_rad;O_rad/NonDe)

    T/[K] 	500	1000	1500	2000
    log10(k/[mole,m,s]) 	+7.3	+7.3	+7.3	+7.3
    Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Estimated using template (O_sec_rad;O_pri_rad) for rate rule (O_rad/NonDe;O_pri_rad)""")
  	
    ! Template reaction: R_Recombination
    ! Estimated using template (O_sec_rad;O_pri_rad) for rate rule (O_rad/NonDe;O_pri_rad)
    C12OJ(2)+HOJ(7)=S(2)                                2.000e+13 0.000     0.000    

	Estimated using template (O_sec_rad;O_pri_rad) for rate rule (O_rad/NonDe;O_pri_rad)

The reaction is the decoposition of a C12 hydroperoxide.
CCCCCCCCCCCC(OOH) <-> CCCCCCCCCCCC[O] + [OH]

There is also a third entry for the same reaction from a custom library - however using different kinetics for an otherwise identical reaction.

The setup was a liquid phase reaction at 423K with no pressure dependence or similar.

**Comment by nickvandewiele** [comment]
you are correct. 

also mentioned in https://github.com/ReactionMechanismGenerator/RMG-database/issues/8, and in the process of being solved by 
https://github.com/ReactionMechanismGenerator/RMG-Py/tree/fixbug_RMG-database_81

sorry for the inconvenience!

**Comment by Alborzi** [comment]
Thanks Nick!

**Comment by nickvandewiele** [comment]
@Alborzi I'd like to check whether this is still an issue with the current state of RMG. Could you append your input file here?
