### ISSUE TITLE
forbidden group N_birad_singlet_2singleBonds looks shady

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#514]
e791c0a15ca49642cbf0f62577c88ef7461108ce shows a test in which the forbidden group (
https://github.com/ReactionMechanismGenerator/RMG-database/blob/master/input/forbiddenStructures.py#L55)

_N_birad_singlet_2singleBonds_

```
1 N u0 p1 {2,S} {3,S}
2 R ux {1,S}
3 R ux {1,S}
```
is successfully discovered in the "normal" looking molecule [CH2]-NH2

```
multiplicity 2
1 N u0 p1 c0 {2,S} {5,S} {6,S}
2 C u1 p0 c0 {1,S} {3,S} {4,S}
3 H u0 p0 c0 {2,S}
4 H u0 p0 c0 {2,S}
5 H u0 p0 c0 {1,S}
6 H u0 p0 c0 {1,S}
```

Although the name of the group suggests the forbidden group should hit singlet biradical nitrogen, I am unsure whether this molecule qualifies as such. 

My recommendation would be to remove that forbidden structure from the list, as it would prevent a lot of _normal_ nitrogen containing compounds from being formed.

**Comment by nickvandewiele** [comment]
@alongd would you agree?

**Comment by alongd** [comment]
I agree that *N_birad_singlet_2singleBonds* is problematic, I had to remove this structure (among others) from my *forbiddenStructures.py* file to be able to run N-chem in RMG.

Still, shouldn't this forbidden structure restrict N p1 with 2 single bonds? The N atom in **[CH2]-NH2** has three.

**Comment by rwest** [comment]
It is difficult (impossible?) to represent absence of a bond in RMG's adjacency list format for functional groups: a group that insists on there being [at least] 2 bonds will match a molecule that has 3 bonds.  We have previously resorted to work-arounds like specifying number of unpaired electrons, or whatever, to limit the overall valence; it might be time to think of a syntax for absence of bonds (would help in some cyclic transition state templates too, I think?)

If you're able to share what else you had to do to get N-chem working, please do so :)

**Comment by alongd** [comment]
I had to remove 5 structures from the *forbiddenStructures.py* file, only one directly involves nitrogen (the one Nick pointed to).

**N_birad_singlet_2singleBonds** restricts NH3 as well... I agree we need a no-bond syntax.
**Carbene_D_singlet** restricts the H2CC species from the *ERC-FoundationFuelv0.9* lib.
**Carbene_D_triplet** restricts the C2O species from the *Glarborg/C3* lib.
**Carbene_S_singlet** restricts the HCOH species from the *Nitrogen_Dean_and_Bozzelli* lib.
**C_quintet** restricts the C species from a new library I work with: *AramcoMech1.3*.

I wonder how come no one else had this problem when using, for example, *ERC-FoundationFuelv0.9* or *Glarborg/C3* in RMG.

**Comment by alongd** [comment]
Sorry, one more which IS N-related:

**N_monorad_3singleBonds** restricts the H2N) species from the *Nitrogen_Glarborg_Gimenez_et_al* lib.

It is indeed an N-radical with 3 single bonds, yet should be allowed:
*multiplicity 2*
*1 N u1 p0 c+1 {2,S} {3,S} {4,S}*
*2 H u0 p0 c0 {1,S}*
*3 H u0 p0 c0 {1,S}*
*4 O u0 p3 c-1 {1,S}*

**Comment by alongd** [comment]
See RMG-database PR 120 (https://github.com/ReactionMechanismGenerator/RMG-database/pull/120)
