### ISSUE TITLE
reaction library reactions are not added to core when all species are in core

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#515]
I ran `generateReactions` script of RMG-Py v1.0.1.

with the following input file:
```
# Data sources
database(
    thermoLibraries = ['primaryThermoLibrary'],
    reactionLibraries = [('Methylformate', False)],
    kineticsFamilies = ['R_Addition_MultipleBond'],
    kineticsEstimator = 'rate rules',
)

# List of species

species(
    label='HCjO',
    reactive=True,
    structure=adjacencyList(
        """
multiplicity 2
1 C u1 p0 c0 {2,D} {3,S}
2 O u0 p2 c0 {1,D}
3 H u0 p0 c0 {1,S}
        """),
)

species(
    label='CH2O',
    reactive=True,
    structure=adjacencyList(
        """
1 C u0 p0 c0 {2,D} {3,S} {4,S}
2 O u0 p2 c0 {1,D}
3 H u0 p0 c0 {1,S}
4 H u0 p0 c0 {1,S}
        """),
)

species(
    label='Fmoml',
    reactive=True,
    structure=adjacencyList(
        """
multiplicity 2
1 C u1 p0 c0 {3,S} {5,S} {6,S}
2 C u0 p0 c0 {3,S} {4,D} {7,S}
3 O u0 p2 c0 {1,S} {2,S}
4 O u0 p2 c0 {2,D}
5 H u0 p0 c0 {1,S}
6 H u0 p0 c0 {1,S}
7 H u0 p0 c0 {2,S}
        """),
)


simpleReactor(
    temperature=(1399,'K'),
    pressure=(1.93,'atm'),
    initialMoleFractions={
        "HCjO": 1,
    },
    terminationConversion={
        'HCjO': 0.999,
    },
    terminationTime=(1e-3,'s'),
)
```
The input file imports a reaction library (methylformate), and defines 3 input species that (HCjO, CH2O, Fmoml).

By default, the reactions from the reaction library will be added to the edge, while the 3 input species will be added to the core.

The reaction library contains 1 reaction involving those three species. Nevertheless, this library reaction does not make it to the core although all the species of the reaction belong to the core already. This is shown in the log below.

```
Summary of Model Enlargement
----------------------------
Added 1 new core species
    Fmoml(3)
Created 6 new edge species
    [CH2]OC([O])C=O(16)
    [CH2]O[CH]OC=O(17)
    [O]CCOC=O(18)
    [CH2]OCOC=O(19)
    [CH2]OC([O])COC=O(20)
    [CH2]O[CH]OCOC=O(21)
Added 0 new core reactions
Created 6 new edge reactions
    HCjO(1) + Fmoml(3) <=> [CH2]OC([O])C=O(16)
    HCjO(1) + Fmoml(3) <=> [CH2]O[CH]OC=O(17)
    CH2O(2) + Fmoml(3) <=> [O]CCOC=O(18)
    CH2O(2) + Fmoml(3) <=> [CH2]OCOC=O(19)
    Fmoml(3) + Fmoml(3) <=> [CH2]OC([O])COC=O(20)
    Fmoml(3) + Fmoml(3) <=> [CH2]O[CH]OCOC=O(21)

After model enlargement:
    The model core has 7 species and 0 reactions
    The model edge has 18 species and 19 reactions


Saving current model core to HTML file...
Saving current model core to Chemkin file...
Chemkin file contains 19 reactions.
Saving current model to verbose Chemkin file...
Chemkin file contains 19 reactions.
```
I believe, the problem is [this line] (https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/rmg/model.py#L838) in `rmgpy.rmg.model.processNewReactions`

```
   if not isNew: 
    	# The reaction is not new, so it should already be in the core or edge
    	continue
    if allSpeciesInCore:
        #for reaction in self.core.reactions:
        #    if isinstance(reaction, Reaction) and reaction.isEquivalent(rxn): break
        #else:
        self.addReactionToCore(rxn)
    else:
        #for reaction in self.edge.reactions:
        #    if isinstance(reaction, Reaction) and reaction.isEquivalent(rxn): break
        #else:
        self.addReactionToEdge(rxn)
```

Since the reaction is not new (it was already added at the start when reading in the reaction library), RMG-Py always ends up in the `continue`, rather than checking whether the species are all in the core.

This issue still exists in the current master of RMG-Py.

**Comment by connie** [comment]
It looks like when we do `addReactionLibraryToEdge()`, it does not place the input species onto the edge, even though the input species at that point exists neither on the edge nor the core.  It still sees that the species is not new.  Therefore in `processNewReactions()` we try to check if the edge reaction should enter the core, however:

we first check if the species exists in the edge species list before doing so to save time
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/rmg/model.py#L1049

And that's where it skips out because none of the input species exist in that list..
