### ISSUE TITLE
Ask for opinions: where to put unittest data files for modules directly under rmgpy/

### ISSUE THREAD

**Issue by KEHANG** [ReactionMechanismGenerator/RMG-Py#516]
In order to have an reasonable and understandable file structure of RMG-Py, I want to use this post to collect opinions (This is not an issue, but affects the structure of RMG-Py. ), for modules under `rmgpy/` like `chemkin.py`, `constants.py`, quantity.py, etc., if we need data files for their unittests, where should we put them? 

- One possible principle is always create data/ folder in the same directory as the module,  i.e., for this case directly under `rmgpy/`, but we already have a folder called `data/` serving very different purpose; 

- Second possible principle is under `rmgpy/` we don't allow to put any data files, all the modules should have their own sub-folder inside which people can put data folder. i.e., for this case is move`chemkin.py` into a new folder, inside the folder, we put `data/` folder. 

- BTW, our temporary solution now is put the data files under `tools/data/` since we think the chemkin.py is similar to the modules inside `tools`. One might ask why don't put `chemkin.py` into `tools`, we can do that as a next step but `chemkin.py` is imported by lots of other modules, we'd rather collect opinions before taking any further actions.

**Comment by nickvandewiele** [comment]
As I mentioned [here] (https://github.com/ReactionMechanismGenerator/RMG-Py/pull/511#issuecomment-169749954) I am in favor of creating a `test_data` folder within `rmgpy` for test data of modules directly residing in `rmgpy`. It's quick, it doesn't need a lot of reshuffling of modules and folders, and it makes sense (to me).

**Comment by rwest** [comment]
If the files are only for testing purposes then I think the folder name containing them should make this clear. Something like `test_data` as Nick suggests. We could still have several of these in module folders if helpful, eg. `rmgpy/test_data` and `rmgpy/solver/test_data` if they are used for testing different things, but I dislike calling the folders just `data`; that is for a module called `data`, as in `from rmgpy.data import ThermoLibrary`.

**Comment by KEHANG** [comment]
@nickvandewiele @rwest I'll make changes accordingly.
