### ISSUE TITLE
Intra_R_Add_Exocyclic and Intra_R_Add_Endocyclic families give excessive duplicates

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#522]
This is related to the fixes we had in RMG-Java such as https://github.com/ReactionMechanismGenerator/RMG-Java/commit/be2d356e242dc09cd5071c18cbf05fe896d0add5 and related changes https://github.com/ReactionMechanismGenerator/RMG-Java/commits/master/source/RMG/jing/rxn/ReactionTemplate.java

and in https://github.com/ReactionMechanismGenerator/RMG-Java/commits/master/source/RMG/jing/chemUtil/Graph.java

Basically we are still double counting fused cyclic transition states in RMG-Py whereas it got fixed in RMG-Java for JP-10 work.  Reactions such as the following still produce 2 duplicates:

![image](https://cloud.githubusercontent.com/assets/583115/12247941/6085387c-b884-11e5-98e1-1b1628599658.png)    ⇔     ![image](https://cloud.githubusercontent.com/assets/583115/12247947/6aae686e-b884-11e5-8a4a-b496ef691b70.png)

```
! Reaction index: Chemkin #37; RMG #10066
! Template reaction: Intra_R_Add_Exocyclic
! Estimated using template (R6_SSM_D;doublebond_intra;radadd_intra_cs) for rate rule (R6_SSM_D;doublebond_intra_HCd_pri;radadd_intra_csHNd)
! Multiplied by reaction path degeneracy 2
C12H17(6)=S(2760)                                   2.000e+10 0.000     46.850
DUPLICATE

! Reaction index: Chemkin #38; RMG #10074
! Template reaction: Intra_R_Add_Endocyclic
! Exact match found for rate rule (R5_SS_D;doublebond_intra_pri_HCd;radadd_intra_csHNd)
! Multiplied by reaction path degeneracy 2
C12H17(6)=S(2760)                                   2.600e+11 0.190     17.290
DUPLICATE
```

We do want these reactions to happen, but the kinetics being used is wrong due to the duplication, as well as probably the lack of specific rate rules for aromatic double bonds.  

But it is good that we do in fact also find formation of spirocyclics as suggested in the Burkle-Vitzthum paper for modeling PDD. 
![image](https://cloud.githubusercontent.com/assets/583115/12248027/c58a0b9e-b884-11e5-8605-aaa36c12d227.png)   ⇔ ![image](https://cloud.githubusercontent.com/assets/583115/12248029/cac68678-b884-11e5-898e-7882e487d2cc.png)

This means that RMG _can_ find the reactions, but we had been turning off these families due to these issues..

**Comment by nyee** [comment]
Addressed in [RMG-database pull request 148](https://github.com/ReactionMechanismGenerator/RMG-database/pull/148), by carefully making some forbidden groups for endocyclic, and creating more groups for exocyclic specifically for rings.

**Comment by nyee** [comment]
Not sure if we should close this. That PR has never been pulled in because @mliu49 and I think that the adding the ring attribute to adjlists is a better solution.

**Comment by goldmanm** [comment]
That makes a lot of sense.

**Comment by mliu49** [comment]
ReactionMechanismGenerator/RMG-database#271 has been merged, which should prevent this issue.
