### ISSUE TITLE
rmgpy.data.kinetics.family.generateReactions needs overhaul

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#552]
Issues #545 and #508 are both related.  We aren't properly calculating degeneracy in `__generateReactions` and are sometimes seeing symmetrical reactions because our checks aren't good enough in `__createReaction`.  The function itself also allows both reactants to be either

lists of molecules objects OR molecules objects 

However, our actual usage is only of the latter type, which makes a lot of the code superfluous.  See e9437726e414afc85e927e764f70eee6e9f62a33 for possible update.

Also, we often repeat our usage of generateResonanceIsomers() all over the place to make checks, but still retain molecule objects rather than reusing that information by placing things into Species() objects.  Tackling how to best store this information can potentially speed things up a great deal.  

This function has long been very difficult to understand and debug, so although I will not be tackling this issue in the next release I hope someone will be able to work on it.

**Comment by goldmanm** [comment]
overhauled in #1055
