### ISSUE TITLE
RMG-Py successful installation but failed unit test run

### ISSUE THREAD

**Issue by prathameSHenai** [ReactionMechanismGenerator/RMG-Py#567]
Hi, 

I have installed the latest version of RMG-Py (the one released end of Jan 2016) from source, with Anaconda, on our HPC cluster. During installation, there were no errors that I spotted. However, when I proceeded to run the test on RMG-Py, many tests failed. I am copying below an extract grepped for only the error/failed lines. The tests on database showed no errors.

Could anyone please advise how fatal/serious are these errors and how to get rid of them? I have meanwhile tried running the minimal example, and it seems to have worked fine. 

Thanks in advance!
Prathamesh

---

```
FAILED (SKIP=34, errors=29, failures=10)

Uses a Gaussian03 log file for ethylene (C2H4) to test that its ... SKIP: WIP test failed: -78.46694399999998 != -78.467452 within 4 places
Uses a Gaussian03 log file for ethylene (C2H4) to test that its ... SKIP: WIP test failed: -78.55632 != -78.562189 within 4 places
Test that the new ThermoDatabase generates appropriate thermo data. ... SKIP: WIP test failed: Expected list, got rmgpy.molecule.molecule.Molecule
Test we generate symmetry numbers correctly. ... SKIP: WIP test failed: Expected list, got rmgpy.molecule.molecule.Molecule
Test that the new ThermoDatabase generates appropriate thermo data. for Aromatics. ... SKIP: WIP test failed: Expected list, got rmgpy.molecule.molecule.Molecule
Test we generate symmetry numbers correctly. for Aromatics. ... SKIP: WIP test failed: Expected list, got rmgpy.molecule.molecule.Molecule
Test we can read an old style adjacency list with implicit hydrogens 5 ... SKIP: WIP test failed: Non-neutral molecule encountered. Currently, RMG does not support ion chemistry.
Test that N atom in the p-layer has correct symbol. ... SKIP: WIP test failed: Non-neutral molecule encountered. Currently, RMG does not support ion chemistry.
n-C5 chain with 2 unpaired electrons at the terminal carbon atoms, ... SKIP: WIP test failed: 'C5H6/c1-3-5-4-2/h1-3H2/u1,2/lp4,5' != 'C5H10/c1-3-5-4-2/h1-5H2/u1,2/lp4,5'
SKIP: WIP test failed: name 'openbabel' is not defined
SKIP: WIP test failed: Couldn't parse InChI=1/H3N/h1H3/p+1
- Mobile H spread over oxygen 2, 3, 4 ... SKIP: WIP test failed: list.remove(x): x not in list
Test isormophism check of a CS group vs. a sulfur containing molecule ... SKIP: WIP test failed: False is not true
Test the Molecule.countInternalRotors() method for dimethylacetylene. ... SKIP: WIP test failed: 2 != 1
Test we can make aromatic and Kekulized resonance isomers of 2-methylanthracen-1-ol ... SKIP: WIP test failed: Expected a resonance form Molecule(SMILES="CC1C=CC2=CC3=CC=CC=C3C=C2C=1O") that was not generated.
Test we can make both Kekulized resonance isomers of 2-Hydroxy-1-methylbenzene ... SKIP: WIP test failed: Didn't generate 3 resonance isomers
Test the Molecule.calculateAxisSymmetryNumber() on C=C=[C]C(C)(C)[C]=C=C ... SKIP: WIP test failed: 1 != 4
Test the Species.getSymmetryNumber() (total symmetry) on Cc1ccc(C)cc1 ... SKIP: WIP test failed: 18 != 36
Test the Molecule.calculateSymmetryNumber() on C(=CC(c1ccccc1)C([CH]CCCCCC)C=Cc1ccccc1)[CH]CCCCCC ... SKIP: WIP test failed: 9 != '36?'
Test the Reaction.generateReverseRateCoefficient() method works for the ArrheniusEP format. ... SKIP: WIP test failed: Unexpected kinetics type <type 'rmgpy.kinetics.arrhenius.ArrheniusEP'>; should be one of ('KineticsData', 'Arrhenius', 'MultiArrhenius', 'PDepArrhenius', 'MultiPDepArrhenius', 'Chebyshev', 'ThirdBody', 'Lindemann', 'Troe')
Test RMG work flow can match reaction template for kinetics estimation ... SKIP: WIP test failed: Lists differ: ['Ck_Ca', 'HJ'] != ['Ck_O', 'HJ']
Unit test for the jacobian function: ... SKIP: WIP test failed: 'rmgpy.solver.liquid.LiquidReactor' object has no attribute 'jacobian'
testC3H4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
testC4H6O (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
testC4H6O_2 (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
testC5H6O (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
testC5H6O_2 (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
ERROR
testC6H6 (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
testQuadri2DoubleBondMult5 (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
testQuadriRadicalDoubleBondZwitterMult5 (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
testTriRadical2DoubleBondMult4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
testTriRadicalDoubleBondMult4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
testTriRadicalZwitterMult4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
test_C2H2O3 (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
test_C3H2O3 (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
test_C3H3O3 (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
test_C3H4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
ERROR
test_C3H6_biradical_parsing (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
test_C6H10 (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
ERROR:root:Unable to correctly parse InChI=1/C6H6O4/c1-2-4-9-6(7)3-5-10-8/h2-3H,1,5H2 with backend try-all
ERROR
ERROR
test_C6H8 (rmgpy.molecule.inchiparsingTest.InChIParsingTest) ... ERROR
has same inchi as ammonia but gets a proton layer: /p+1 ... ERROR:root:Unable to correctly parse InChI=1/H3N/h1H3/p+1 with backend try-all
Test that augmented inchi with wrong layer is caught. ... [23:39:31] ERROR:
Test that we can generate a few SMILES strings as expected ... ERROR
test_C3H2 (rmgpy.molecule.pathfinderTest.FindAllylEndWithChargeTest) ... ERROR
test_C3H4 (rmgpy.molecule.pathfinderTest.FindAllylEndWithChargeTest) ... ERROR
test_C3H4O4 (rmgpy.molecule.pathfinderTest.FindAllylEndWithChargeTest) ... ERROR
test_C5H6O (rmgpy.molecule.pathfinderTest.FindAllylEndWithChargeTest) ... ERROR
ERROR:root:Unable to correctly parse InChI=1S/C6H6O4/c1-2-4-9-6(7)3-5-10-8/h2-3H,1,5H2 with backend try-all
ERROR
ERROR
ERROR: testC3H4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: testC4H6O (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: testC4H6O_2 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: testC5H6O (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: testC5H6O_2 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: testC5H6O_3 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: testC6H6 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: testQuadri2DoubleBondMult5 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: testQuadriRadicalDoubleBondZwitterMult5 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: testTriRadical2DoubleBondMult4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: testTriRadicalDoubleBondMult4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: testTriRadicalZwitterMult4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: test_C2H2O3 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: test_C3H2O3 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: test_C3H3O3 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: test_C3H4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: test_C3H4O4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: test_C3H6_biradical_parsing (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: test_C6H10 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: test_C6H6O4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: test_C6H6O6 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: test_C6H8 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
ERROR: Test that we can generate a few SMILES strings as expected
ERROR: test_C3H2 (rmgpy.molecule.pathfinderTest.FindAllylEndWithChargeTest)
ERROR: test_C3H4 (rmgpy.molecule.pathfinderTest.FindAllylEndWithChargeTest)
ERROR: test_C3H4O4 (rmgpy.molecule.pathfinderTest.FindAllylEndWithChargeTest)
ERROR: test_C5H6O (rmgpy.molecule.pathfinderTest.FindAllylEndWithChargeTest)
ERROR: test_C6H6O4 (rmgpy.molecule.pathfinderTest.FindButadieneEndWithChargeTest)
ERROR: test_C6H6O6 (rmgpy.molecule.pathfinderTest.FindButadieneEndWithChargeTest)

```

---

**Comment by nickvandewiele** [comment]
Thanks for reporting this. 

At first glance, the errors seem related to a missing openbabel dependency. We will check if the anaconda openbabel package is still intact.

Our unit tests try to cover as much of the code as possible, and an RMG simulation may not necessarily call all the functionalities that are being tested.

What is the platform you ran the code on? May I assume linux 64-bit?

**Comment by connie** [comment]
There is no need to worry about the SKIP'ed tests, because those are unit tests are currently labeled WIP (work in progress).  Like @nickvandewiele says, the openbabel dependency may be the issue.  Can you let me know if you are installing rmg to a fresh anaconda environment and sourcing that environment before running?  If so, can you please activate the environment and then type the following commands and print the output here?

`source activate rmg_env`
`conda info`
`conda list`

That would be helpful for us to understand what your system and conda package settings might be.

**Comment by prathameSHenai** [comment]
Hi Nick and Connie,

Thank you for your prompt replies. The platform I have installed RMG on is indeed 64-bit Redhat Linux. I have also installed it to a fresh anaconda environment followed by sourcing it. 

Below is the output you have requested.

******************************************************************************************************************************
**(rmg_env)bash-4.1$ conda info**
Current conda install:

             platform : linux-64
        conda version : 3.18.8
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.8.1
     root environment : /glb/data/ccb_nb1/inpskq/anaconda2  (writable)
  default environment : /glb/data/ccb_nb1/inpskq/anaconda2/envs/rmg_env
     envs directories : /glb/data/ccb_nb1/inpskq/anaconda2/envs
        package cache : /glb/data/ccb_nb1/inpskq/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
******************************************************************************************************************************

**(rmg_env)bash-4.1$ conda list**
# packages in environment at /glb/data/ccb_nb1/inpskq/anaconda2/envs/rmg_env:
#
boost                     1.56.0                   py27_3    rmg
bzip2                     1.0.6                         0    defaults
cairo                     1.12.18                       6    defaults
cairocffi                 0.5.3                    py27_0    rmg
cffi                      1.2.1                    py27_0    defaults
coverage                  4.0                      py27_0    defaults
cycler                    0.9.0                    py27_0    defaults
cython                    0.21                     py27_1    defaults
eigen                     3.2.1                         0    rmg
fontconfig                2.11.1                        5    defaults
freetype                  2.5.5                         0    defaults
gprof2dot                 2015.02.03               py27_0    rmg
graphviz                  2.38.0                        3    rmg
greenlet                  0.4.9                    py27_0    defaults
guppy                     0.1.10                   py27_0    rmg
jbig                      2.1                           0    defaults
jinja2                    2.8                      py27_0    defaults
jpeg                      8d                            0    defaults
libffi                    3.0.13                        0    defaults
libgcc                    4.8.5                         1    defaults
libgfortran               1.0                           0    defaults
libpng                    1.6.17                        0    defaults
libsodium                 1.0.3                         0    defaults
libtiff                   4.0.6                         1    defaults
libxml2                   2.9.2                         0    defaults
markupsafe                0.23                     py27_0    defaults
matplotlib                1.5.1               np110py27_0    defaults
mkl                       11.3.1                        0    defaults
mopac                     2012                          2    rmg
nose                      1.3.7                    py27_0    defaults
numpy                     1.10.4                   py27_0    defaults
openbabel                 2.3.2                    py27_4    rmg
openssl                   1.0.2f                        0    defaults
pip                       8.0.2                    py27_0    defaults
pixman                    0.32.6                        0    defaults
psutil                    3.4.2                    py27_0    defaults
pycairo                   1.10.0                   py27_0    defaults
pycparser                 2.14                     py27_0    defaults
pydas                     1.0.2                    py27_0    rmg
pydot                     2.0.1                    py27_0    rmg
pydot2                    1.0.32                    <pip>
pydqed                    1.0.1                    py27_0    rmg
pyparsing                 2.0.3                    py27_0    defaults
pyqt                      4.11.4                   py27_1    defaults
python                    2.7.11                        0    defaults
python-dateutil           2.4.2                    py27_0    defaults
pytz                      2015.7                   py27_0    defaults
pyzmq                     15.2.0                   py27_0    defaults
qt                        4.8.7                         1    defaults
quantities                0.10.1                   py27_0    rmg
rdkit                     2015.09.2           np110py27_0    rmg
readline                  6.2                           2    defaults
scipy                     0.17.0              np110py27_1    defaults
scoop                     0.7                      py27_0    rmg
setuptools                19.6.2                   py27_0    defaults
sip                       4.16.9                   py27_0    defaults
six                       1.10.0                   py27_0    defaults
sqlite                    3.9.2                         0    defaults
symmetry                  1.0.1                         0    rmg
tk                        8.5.18                        0    defaults
wheel                     0.26.0                   py27_1    defaults
xlwt                      1.0.0                    py27_0    defaults
xz                        5.0.5                         0    defaults
zeromq                    4.1.3                         0    defaults
zlib                      1.2.8                         0    defaults

******************************************************************************************************************************

**Comment by goldmanm** [comment]
If you are still experiencing this issue, feel free to reopen. Somehow we were unable to replicate this issue.
