### ISSUE TITLE
Integer initialMoleFractions gives "ZeroDivisionError: float division" error

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#580]
I was running with an initial composition not equal to 1:

```
# Reaction systems
simpleReactor(
    temperature=(1000,'K'),
    pressure=(1,'atm'),
    initialMoleFractions={
        "CH4": 47,
		"O2": 47,
		"NO": 6,
    },
    terminationTime=(20,'s'),
)
```

And after the 1st iteration I got the following error:
```
After model enlargement:
    The model core has 6 species and 0 reactions
    The model edge has 51 species and 312 reactions

Saving current model core to Chemkin file...
Chemkin file contains 0 reactions.
Saving current model to verbose Chemkin file...
Chemkin file contains 0 reactions.
Updating RMG execution statistics...
    Execution time (DD:HH:MM:SS): 00:00:00:21
    Memory used: 228.79 MB

Conducting simulation of reaction system 1...
Traceback (most recent call last):
  File "/home/alongd/ws/RMG-Py/rmg.py", line 165, in <module>
    rmg.execute(inputFile, output_dir, **kwargs)
  File "/home/alongd/ws/RMG-Py/rmgpy/rmg/main.py", line 534, in execute
    relativeTolerance = self.relativeTolerance,
  File "rmgpy/solver/base.pyx", line 325, in rmgpy.solver.base.ReactionSystem.simulate (build/pyrex/rmgpy/solver/base.c:10731)
  File "rmgpy/solver/base.pyx", line 370, in rmgpy.solver.base.ReactionSystem.simulate (build/pyrex/rmgpy/solver/base.c:7098)
  File "rmgpy/solver/simple.pyx", line 140, in rmgpy.solver.simple.SimpleReactor.initializeModel (build/pyrex/rmgpy/solver/simple.c:2705)
  File "rmgpy/solver/base.pyx", line 299, in rmgpy.solver.base.ReactionSystem.set_initial_derivative (build/pyrex/rmgpy/solver/base.c:6043)
  File "rmgpy/solver/simple.pyx", line 295, in rmgpy.solver.simple.SimpleReactor.residual (build/pyrex/rmgpy/solver/simple.c:5984)
ZeroDivisionError: float division
```

(strange error by the way, which isn't very helpful. From looking up "ZeroDivisionError" on GitHub I though it's because I'm missing a bath gas, as in issue #37)

When I switched to a 100%-sum initial mixture, the model ran smoothly:
```
# Reaction systems
simpleReactor(
    temperature=(1000,'K'),
    pressure=(1,'atm'),
    initialMoleFractions={
        "CH4": 0.47,
		"O2": 0.47,
		"NO": 0.06,
    },
    terminationTime=(20,'s'),
)
```

Doesn't RMG automatically normalize the inlet mixture composition?
The [documentation example](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/input.html) doesn't summ up to 100% as well:
```
simpleReactor(
        temperature=(1350,'K'),
        pressure=(1.0,'bar'),
        initialMoleFractions={
                "CH4": 0.104,
                "H2": 0.0156,
                "N2": 0.8797,
        },
```

**Comment by rwest** [comment]
My guess, without looking into it, is integer arithmetic of Python 2. 
I bet if you said `"NO": 6.` instead of `"NO": 6` (etc.) it would work.

In python2 `6/100 = 0` if 6 and 100 are both integers.

If I'm right then the fix for this is to wrap these inputs with `float()` when loading the input file, i.e in the `__init__` method of `simpleReactor` (and `liquidReactor` while we're at it)

**Comment by alongd** [comment]
The above was copied from my input file as is. Sorry, but I didn't add a decimal point.

**Comment by rwest** [comment]
I'm suggesting you try again *with* a decimal point, and see if that works.

**Comment by alongd** [comment]
@rwest, you are right.
(sorry, didn't read your msg right)

**Comment by rwest** [comment]
Even if we got your simulation working, I don't think this issue is closed until [other] people can put integers in their input files.

**Comment by connie** [comment]
Yeah.. we should probably read everything in as a float regardless of what they put in.

**Comment by nickvandewiele** [comment]
[this](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/rmg/input.py#L128) is a good starting point.

Make sure both SimpleReactor as well as LiquidReactor are fixed.

**Comment by connie** [comment]
Closed via https://github.com/ReactionMechanismGenerator/RMG-Py/pull/612
