### ISSUE TITLE
Problem with Forbidden Structure: "N_birad_singlet_2singleBonds" 

### ISSUE THREAD

**Issue by ejtierne** [ReactionMechanismGenerator/RMG-Py#589]
This forbidden structure: 

entry(
 label = "N_birad_singlet_2singleBonds", 
group =
 """ 
1 N u0 p1 {2,S} {3,S} 
2 R ux {1,S} 
3 R ux {1,S} """, 
shortDesc = u"""""", 
longDesc =
 u"""

""", 
)
chokes on amines. From the title, I wonder if the issue occurs because it should read u2 instead of u0 in the connectivity diagram (i.e. biradical?)

**Comment by alongd** [comment]
solved by https://github.com/ReactionMechanismGenerator/RMG-database/pull/223
