### ISSUE TITLE
SpeciesConstraints applied to training reactions

### ISSUE THREAD

**Issue by nyee** [ReactionMechanismGenerator/RMG-Py#602]
When setting species constraints in input file, it seems to affect the training reactions. When setting `maxCarbonAtoms=6`, we get the error:
rmgpy.data.kinetics.common.KineticsError: Unable to calculate degeneracy for reaction Molecule "C=C1C=CC[CH]C1" <=> Molecule "[CH2]C12C=CCC1C2" in reaction family Intra_R_Add_Exocyclic. Expected 1 reaction but generated 0.

If we set `maxCarbonAtoms=8`, we get:
rmgpy.data.kinetics.common.KineticsError: Unable to calculate degeneracy for reaction Molecule "[CH2]C=CCC=C1C=CC=C1" <=> Molecule "C1C=C[C](C=1)C1CC=CC1" in reaction family Intra_R_Add_Exocyclic. Expected 1 reaction but generated 0

The molecule RMG complains about is always one C higher than the max allowed. I haven't looked too thoroughly into this yet, but if I were to guess, I bet RMG is applying the speciesConstraints to these species in the training reaction, but still give back some Species object in the Reaction object. The Species object is probably flawed, maybe missing all its atoms. So when RMG tries to calculate the degeneracy it can't find any labelled atoms and gives back a degeneracy of 0.

**Comment by connie** [comment]
Closed via aedfdeb46021dd29f4a9e68304a6b36784ebae70
