### ISSUE TITLE
Different gas constants between RMG, Cantera, and CHEMKIN

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#603]
The universal gas constant R differs between the three programs, which leads to some discrepancies in the simulations.  Or in values for thermo calculations, ie. the same NASA polynomial produces these slightly different values in cantera vs RMG:

**Cantera**
H(298) (J/mol) -3.1179232875
S(298) (J/mol \* K) 154.83526991
Cp(298) (J/mol \* K) 20.78615525

**RMG**
H(298) (J/mol) -3.117927
S(298) (J/mol \*  K) 154.835454272
Cp(298) (J/mol \* K) 20.78618

Where the cantera object is:

```
species(name=u'Ar',
        atoms='Ar:1',
        thermo=(NASA([200.00, 1000.00],
                     [ 2.50000000E+00,  0.00000000E+00,  0.00000000E+00,
                       0.00000000E+00,  0.00000000E+00, -7.45375000E+02,
                       4.37967000E+00]),
                NASA([1000.00, 6000.00],
                     [ 2.50000000E+00,  0.00000000E+00,  0.00000000E+00,
                       0.00000000E+00,  0.00000000E+00, -7.45375000E+02,
                       4.37967000E+00])))
```

Turns out it is just a difference in the gas constant values between the two program and that changing them to match makes the results have no discrepancies:

**Gas constant values**
RMG: R = 8.314472 J/mol \* K
Cantera: 8314.4621 J/kmol \* K
CHEMKIN: 8.31451 ergs/mol \* K  (value might have changed in latest version but CHEMKIN III had this value according to p119 in https://www3.nd.edu/~powers/ame.60636/CHEMKIN_III.pdf)

Not sure if there's any reason to update our gas constant to one of these other values, but it should be noted that our simulations vs. cantera or chemkin will have slight differences.

**Comment by cfgoldsmith** [comment]
Interesting that none of the three values is equal to the value recommended by NIST:
8.3144598 J/mol*K
(http://physics.nist.gov/cgi-bin/cuu/Value?r)
(I seem to recall Sandeep and I finding the same issue a long time ago)

**Comment by rwest** [comment]
[This](http://physics.nist.gov/cuu/Constants/Preprints/lsa2010.pdf) is where Ray @speth got the Cantera one:
https://github.com/Cantera/cantera/commit/aab72379fea2261e9f5dfd519e438a687279cda3
I guess NIST changed it again in the 2014 CODATA update

**Comment by mliu49** [comment]
We should update our value following the CODATA 2018 recommendations, now that both the Boltzmann and Avogadro constants are defined to be exact values.

The new value for R is 8.314462618 (exact!)

https://physics.nist.gov/cuu/pdf/wall_2018.pdf
