### ISSUE TITLE
Git clone different that zipfile

### ISSUE THREAD

**Issue by chatelak** [ReactionMechanismGenerator/RMG-Py#616]
Does anyone already experienced this?

From a the same project we performed a git clone and dowloaded the associated zipfile. At the end, one runs perfectly, the other one crashed at the beginning (reading the step).

According to the file "version.py" it seems to be the same version.

**Comment by rwest** [comment]
Sounds strange. Have you tried something like `diff -r directory1 directory2` to see what the differences are?

**Comment by goldmanm** [comment]
If other people experience this issue or have something to add, feel free to reopen.
