### ISSUE TITLE
Flux diagram generation error

### ISSUE THREAD

**Issue by prathameSHenai** [ReactionMechanismGenerator/RMG-Py#636]
Hi, 

I have been trying to generate the flux diagram for a completed RMG run, both via online interface and the local script. However, it always ends up in an error typically as the one shown below (from online interface):

********************************************************************************************************************
IOError at /simulate/flux
[Errno 2] No such file or directory: '/var/www/RMG-website/rmgweb/media/rmg/tools/flux/1/flux_diagram_0049.png'

Request Method:
POST 

Request URL:
http://rmg.mit.edu/simulate/flux 

Django Version:
1.8.5 

Exception Type:
IOError 

Exception Value:
[Errno 2] No such file or directory: '/var/www/RMG-website/rmgweb/media/rmg/tools/flux/1/flux_diagram_0049.png'

Exception Location:
build/bdist.linux-x86_64/egg/pydot.py in write, line 1895 

Python Executable:
/usr/bin/python 

Python Version:
2.7.6 

Python Path:
['/var/www/RMG-website/rmgweb',
 '/var/www/RMG-Py',
 '/opt/anaconda/envs/rmg/lib/python2.7/site-packages/gprof2dot-2015.2.3-py2.7.egg',
 '/opt/anaconda/envs/rmg/lib/python2.7/site-packages/pydot2-1.0.32-py2.7.egg',
 '/opt/anaconda/envs/rmg/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg',
 '/opt/anaconda/envs/rmg/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/dist-packages/PyDAS-1.0.0-py2.7-linux-x86_64.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client',
 '/var/www/RMG-website',
 '/var/www/RMG-website/rmgweb',
 '/var/www/RMG-database',
 '/var/www/RMG-Py']
 

Server time:
Tue, 19 Apr 2016 00:01:20 -0400 

********************************************************************************************************************

**Comment by connie** [comment]
Hopefully works now.  Closed by https://github.com/ReactionMechanismGenerator/RMG-Py/issues/711
