### ISSUE TITLE
Mutable constructors in classes

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#640]
Nathan brought this to my attention: http://stackoverflow.com/questions/4841782/python-constructor-and-default-value

Initializing a class with a mutable object such as an empty default list `[]` can sometimes like to problems when recreating another instance of that class.  I wasn't super aware of this, and so far it seems that RMG doesn't immediately have this problem but we could maybe scour the classes with a script just to be sure.

**Comment by rwest** [comment]
Yes, I think the standard procedure is to initialize it with `None` and have the `__init__` method create the empty list. One of the python "gotchas" like [integer division](https://github.com/ReactionMechanismGenerator/RMG-Py/commit/63298c2a45c40b0ecef28bfca1a9429bbaafd4c5).  If someone is into static analysis scripting, you could check for instances of that too!

**Comment by nickvandewiele** [comment]
https://github.com/ReactionMechanismGenerator/RMG-Py/issues/292

**Comment by rwest** [comment]
Hah - thanks @nickvandewiele, I'd forgotten that one!

**Comment by connie** [comment]
Mutable constructors found in the following code through regex search:

https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/group.py#L537

https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/tools/canteraModel.py#L166

Use of `[]` and `{}` in:
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/tools/observablesRegression.py#L67

Mutiple uses of `{}` in:
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/tools/plot.py
