### ISSUE TITLE
Molecule.removeAtom leads to missing edges in shallow copies of the Molecule

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#641]
`Molecule.removeAtom(Atom at)` not only removes the atom of interest, but also its attached bonds (edges). The way this is implemented in [Graph.removeVertex](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/graph.pyx#L276) is through the `del` command.
```cython

    cpdef removeVertex(self, Vertex vertex):
        """
        Remove `vertex` and all edges associated with it from the graph. Does
        not remove vertices that no longer have any edges as a result of this
        removal.
        """
        cdef Vertex vertex2
        for vertex2 in vertex.edges:
            del vertex2.edges[vertex]
        vertex.edges = dict()
        self.vertices.remove(vertex)
```

Given a molecule 'a':
```python
a = Molecule(SMILES="CC")

a.toAdjacencyList()
1 C u0 p0 c0 {2,S} {3,S} {4,S} {5,S}
2 C u0 p0 c0 {1,S} {6,S} {7,S} {8,S}
3 H u0 p0 c0 {1,S}
4 H u0 p0 c0 {1,S}
5 H u0 p0 c0 {1,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {2,S}
```
When making a shallow copy of a Molecule object:

`b = a.copy()`

and removing an atom from the original container a:
```python
a.removeAtom(a.atoms[0])

a.toAdjacencyList()

1 C u0 p0 c0 {5,S} {6,S} {7,S}
2 H u0 p0 c0
3 H u0 p0 c0
4 H u0 p0 c0
5 H u0 p0 c0 {1,S}
6 H u0 p0 c0 {1,S}
7 H u0 p0 c0 {1,S}
```

The shallow copy is also affected by the removal operation, i.e. atom no. 0 does not have any bonds anymore:
```python
b.toAdjacencyList()

1 C u0 p0 c0
2 C u0 p0 c0 {6,S} {7,S} {8,S}
3 H u0 p0 c0
4 H u0 p0 c0
5 H u0 p0 c0
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {2,S}
```

This was unexpected to me, and I think the behavior should be changed. A shallow copy of a molecule should not be affected by changes to another container.

Could it be that the `del` command removes the object from memory even when there are still existing references to it, rather than removing the reference to it in the dictionary?

**Comment by rwest** [comment]
I think that's the point of a deep copy. Any operations to edit a shallow copy of an object risks changing the original. 
To reduce the risk of error we could rename things so default "copy" is deep, but the cost is increased risk of slower code.

**Comment by nickvandewiele** [comment]
I do believe there's a great benefit of having a shallow copy method for Molecule, and would therefore very much like to keep the current option of choosing a deep or shallow copy. 

My idea was to change the way the `removeVertex()` is implemented while keeping the end result the same (i.e. removing the references of the attached edges as well).

**Comment by nickvandewiele** [comment]
Closing this:

Because the edges are stored as attributes of an object one is trying to remove, there's no way the edges can be retained.
