### ISSUE TITLE
Reactions created that violate mass balance

### ISSUE THREAD

**Issue by nyee** [ReactionMechanismGenerator/RMG-Py#661]
On an RMG job for phenol pyrolysis, I am getting reactions like this:

![image](https://cloud.githubusercontent.com/assets/1444635/15409828/95dbd59c-1de4-11e6-9066-9f13fd95b5f2.png)

<img width="840" alt="screen shot 2016-05-19 at 5 28 34 pm" src="https://cloud.githubusercontent.com/assets/1444635/15410341/281c5862-1de7-11e6-9402-01f5525b3377.png">

Both Connie and I have seen this occur on the master branch. Here is what we know so far:
1. So far it only happens with reactions with acetylene
2. It occurs for multiple reaction families, not from any library reactions
3. RMG does not throw any exceptions or crash. I have gotten to a fully converged RMG mechanism while making many imbalanced reactions. 
4. I get the error when phenol and Ar start in the input file. I do not get the error if I start with acetylene, phenol, and Ar to try to get the reaction to appear earlier.
5. I have only been able to get the error when I use a specific reaction library. This reaction library was converted from an RMG-generated mechanism for n-butane oxidation. I don't know if the library is causing the error or just influencing RMG to generate specific reactions where the error occurs. 

From above, you can see it we have had difficulties trouble-shooting the error. At best, it takes us about ten minutes to verify if the occurs or not. Anybody have any idea what is going on?

**Comment by nickvandewiele** [comment]
call [reaction.isBalanced()](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/reaction.py#L879) after a reaction is created and raise an Exception when the method returns False.

**Comment by rwest** [comment]
I notice that the nodes it hit when finding kinetics for the reactions are unambiguously an H atom radical, `1 * H u1`, which means that at the time of searching for kinetics the Molecules were correct and the reaction balanced. At some point that Molecule must be being swapped for the pointer to the C2H2 Species. Possibly some "check for existing" is going wrong. Or maybe it's to do with the scoop worker/master infrastructure eg `inflate` is getting the wrong species index?  I'd love to understand that new code better than I currently do.

Nick's is a good suggestion to help debug. Use a debugger that pauses when you hit that exception.

**Comment by nickvandewiele** [comment]
Can someone add an input file so that we can all test and enjoy this?

**Comment by nyee** [comment]
Here is a reaction library and input file that I see the error on. I don't seem to get the error if I don't use the reaction library. 

[dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/274768/dictionary.txt)
[reactions.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/274771/reactions.txt)

[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/274766/input.txt)

**Comment by nyee** [comment]
I just tested the [PR, #662](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/662) and it did not fix this specific instance of improperly mass balanced reactions. Still unsure what is causing it.
