### ISSUE TITLE
AssertionError upon clicking on reaction # in output.html

### ISSUE THREAD

**Issue by PWstmrlnd** [ReactionMechanismGenerator/RMG-Py#668]
Should get the rules used etc, but get the attached "AssertionError" instead.
[RMG Output.pdf](https://github.com/ReactionMechanismGenerator/RMG-Py/files/300276/RMG.Output.pdf)
[AssertionError.pdf](https://github.com/ReactionMechanismGenerator/RMG-Py/files/300278/AssertionError.pdf)

**Comment by rwest** [comment]
I think it's most likely a problem with rmg.mit.edu [RMG-website](https://github.com/ReactionMechanismGenerator/RMG-website/issues).
Maybe moleculeFromURL is not splitting into lines at the semicolons.
It looks embarrassingly like @whgreen's issue from March 2015... https://github.com/ReactionMechanismGenerator/RMG-website/issues/80

Any volunteers to take a look?

**Comment by rwest** [comment]
@PWstmrlnd could you confirm what version of RMG this output.html was generated by? (should be near the top of the accompanying RMG.log file)?  
My guess is that updating your RMG will fix this.  If it's not obvious how, make a new issue suggesting we add some "upgrading" documentation alongside the "installing" documentation!

## Details:

This commit changed the URL syntax expected by the RMG-website
https://github.com/ReactionMechanismGenerator/RMG-website/commit/c4130530d37aecda668c6ef5ca2ea61583d5276e
it no longer interprets `;` as a newline in an adjacency list (but instead uses URLlib to encode the whole thing with linebreaks). 
This was reflected in RMG-Py commit https://github.com/ReactionMechanismGenerator/RMG-Py/commit/e007b5d243830432960b0f8b9a8a282cffae26eb
which made it into Master branch November 2 2015.

It's unfortunate we can't keep the website backwards-compatible with older versions, but I don't think it's worth the pain - we're better off encouraging you to upgrade. 

If upgrading doesn't fix this, please reopen this issue.
