### ISSUE TITLE
Liquid phase reaction: Diffusion limit for solvent species

### ISSUE THREAD

**Issue by yunsiechung** [ReactionMechanismGenerator/RMG-Py#670]
For liquidreactor, the kinetic rate is corrected by the diffusion factor between 0 and 1. 
This diffusion factor is calculated under pseudo-binary reactions, which work for dilute solute species. 

However, if any of the reacting molecules is the solvent species, shouldn't the diffusion factor be 1 and the effective rate should equal to the intrinsic kinetic rate because the reaction involving solvent species is not diffusion-limited? Or does the high concentration of the solvent species automatically take that into account?

**Comment by rwest** [comment]
That's a good point. 
One thing to consider: the solvent will only be a reactant in one direction, not the reverse. But maybe that will already be taken care of: I think the algorithm uses the diffusion factor (0,1] from whichever direction is closest to zero, and making one of them (the direction in which the solvent is a reactant) equal to 1 wouldn't change this?

**Comment by yunsiechung** [comment]
@rwest I think the algorithm you described is correct. Here is the code that corresponds to this algorithm:

`        if reactants == 1:
            if products == 1:
                k_eff = k_forward
            else: # two products; reverse rate is limited
                k_diff = self.getDiffusionLimit(T, reaction, forward=False)
                k_eff_reverse = k_reverse*k_diff/(k_reverse+k_diff)
                k_eff = k_eff_reverse * Keq
        else: # 2 reactants
            if products == 1 or products == 3:
                k_diff = self.getDiffusionLimit(T, reaction, forward=True)
                k_eff = k_forward*k_diff/(k_forward+k_diff)
            else: # 2 products
                if Keq > 1.0: # forward rate is faster and thus limited
                    k_diff = self.getDiffusionLimit(T, reaction, forward=True)
                    k_eff = k_forward*k_diff/(k_forward+k_diff)
                else: # reverse rate is faster and thus limited
                    k_diff = self.getDiffusionLimit(T, reaction, forward=False)
                    k_eff_reverse = k_reverse*k_diff/(k_reverse+k_diff)
                    k_eff = k_eff_reverse * Keq
        return k_eff  `


My concern is that according to this code, RMG chooses which direction to be diffusion limited based on the number of reactants and products or the value of the equilibrium constant. But this does not check whether the solvent species is a reactant in the "diffusion limited reaction" that the algorithm chose. I think it would be safe to add one more criteria that checks whether the solvent is involved in the diffusion limited reaction or not.

For example, if there are 2 reactants and 2 products and Keq > 1.0, the k_eff is calculated using the forward reaction diffusion factor. However, if the solvent is one of the reactants in the forward reaction, then the forward reaction is not diffusion limited and therefore the reverse rate should be selected as a diffusion limited direction. 

Do you think my reasoning is correct? I am wondering whether I missed any other factors,
