### ISSUE TITLE
Non-identical thermo for [C-]#[N+] between v1.0.4 and current master

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#677]
RMG-tests has recently been generating mechanisms for methylamine that have diverged from the previous benchmark (v.1.0.4 of RMG). 

I believe that a different thermo calculation 
See this [build](https://travis-ci.org/ReactionMechanismGenerator/RMG-tests/builds/136575046)

```
Non-identical thermo!
tested: [C-]#[N+]
original:   [C-]#[N+]
Hf(300K)  |S(300K)   |Cp(300K)  |Cp(400K)  |Cp(500K)  |Cp(600K)  |Cp(800K)  |Cp(1000K) |Cp(1500K) 
     95.89|     51.61|      8.62|      8.68|      8.61|      8.50|      8.34|      8.33|      8.35
     76.55|      8.98|      2.40|      2.02|      1.88|      1.79|      1.43|      1.12|      1.74
thermo: Thermo library: thermo_DFT_CCSDTF12_BAC + radical(Cs_P)
thermo: Thermo group additivity estimation: group(N) + other(R) + group(Ct-CtCs) + other(R) + radical(Cs_P)

```

is at the basis of the much larger discrepancies in terms of kinetics:

```
Non-identical kinetics!
tested:
rxn: [C-]#[N+](926) + CH3CHO(33) <=> CH2CHO(32) + HNC(76)       family: H_Abstraction
benchm:
rxn: CH2CHO(32) + HNC(76) <=> CH3CHO(33) + [C-]#[N+](926)       family: H_Abstraction
k(1bar)|300K   |400K   |500K   |600K   |800K   |1000K  |1500K  |2000K  
k(T):  |  -2.06|   0.03|   1.34|   2.25|   3.46|   4.24|   5.40|   6.07
k(T):  |   1.01|   2.13|   2.84|   3.34|   4.02|   4.46|   5.14|   5.55
Kinetics: Arrhenius(A=(48170,'cm^3/(mol*s)'), n=2.56, Ea=(9.731,'kcal/mol'), T0=(1,'K'), comment="""Estimated using template (X_H;Y_rad) for rate rule (C/H3/CO;Y_rad)
Kinetics: Arrhenius(A=(810000,'cm^3/(mol*s)'), n=1.87, Ea=(4.84,'kcal/mol'), T0=(1,'K'), comment="""Estimated using template (N5_H;Cs_rad) for rate rule (N5_H;C_rad/H2/CO)""")
kinetics: Estimated using template (X_H;Y_rad) for rate rule (C/H3/CO;Y_rad)
kinetics: Estimated using template (N5_H;Cs_rad) for rate rule (N5_H;C_rad/H2/CO)

Non-identical kinetics!
tested:
rxn: [C](=N)O(2391) + [N+](=[N-])O(1049) <=> [C](=[N])O(2125) + [NH+](=[N-])O(1314)     family: H_Abstraction
benchm:
rxn: [C](=[N])O(2125) + [NH+](=[N-])O(1314) <=> [C](=N)O(2391) + [N+](=[N-])O(1049)     family: H_Abstraction
k(1bar)|300K   |400K   |500K   |600K   |800K   |1000K  |1500K  |2000K  
k(T):  |   2.60|   3.44|   3.98|   4.36|   4.89|   5.25|   5.81|   6.16
k(T):  |   4.14|   4.54|   4.82|   5.04|   5.36|   5.59|   6.00|   6.27
Kinetics: Arrhenius(A=(3.936e+06,'cm^3/(mol*s)'), n=1.797, Ea=(3.359,'kcal/mol'), T0=(1,'K'), comment="""Estimated using template (N3_H;N3_rad) for rate rule (N3_H;N3d_rad)""")
Kinetics: Arrhenius(A=(920000,'cm^3/(mol*s)'), n=1.94, Ea=(0.87,'kcal/mol'), T0=(1,'K'), comment="""Estimated using template (N5_H;N3_rad) for rate rule (N5d_H;N3_rad)""")
kinetics: Estimated using template (N3_H;N3_rad) for rate rule (N3_H;N3d_rad)
kinetics: Estimated using template (N5_H;N3_rad) for rate rule (N5d_H;N3_rad)

...
```

Some notes:
- The methylamine models do not always diverge.   So there is a random factor also present.
- Manually checking some Travis Build logs have shown that the divergence is very recent. I have seen it appear in `restore-forbidden-structures`, and in the latest build of `liquid`, but not in the previously build, suggesting that a rebase of that branch after a merge of master (with `restore-forbidden-structures`) may have caused it. 

Since the `restore-forbidden-structures` branch has nothing to do with this type of error, I believe the  error is introduced by merging a branch from an external user account, e.g.: `update_lone_pairs`. PR's from external user account cannot be run through the RMG-tests framework, hence we don't have a build log for them.

**Comment by rwest** [comment]
Is the change that one found a library value and the other didn't? If so, Did the library change? Or the isomorphism check?

**Comment by nickvandewiele** [comment]
Yes, the origin of the thermo changed from GAVs (the benchmark RMG-Py v1.0.4, RMG-database v1.1.0) to the library value.

The hit library was added a long time ago.

**Comment by alongd** [comment]
Closing due to fixes in the new nitrogen branch. Hope to merge into master one day (soon!)
