### ISSUE TITLE
Adding constantSpecies flag not working on liquid_phase example input.

### ISSUE THREAD

**Issue by Spencer-S** [ReactionMechanismGenerator/RMG-Py#685]
Hello,

I am can run successfully the RMG-Py example: "RMG-Py/examples/rmg/liquid_phase/input.py".  However, if I add the constantSpecies option to the example (see code excerpt below), the example will not run (it says that the option constantSpecies is not recognized).

Can anyone else reproduce this error?

Any help is appreciated.  Thanks in advance, Spence

``` python
##### from the example "RMG-Py/examples/rmg/liquid_phase/input.py", line 29 ####
# Reaction systems
liquidReactor(
    temperature=(500,'K'),
    initialConcentrations={
        "octane": (6.154e-3,'mol/cm^3'),
        "oxygen": (4.953e-6,'mol/cm^3')
    },
    terminationTime=(5,'s'),
    constantSpecies=['oxygen']  # will not run with this option, does run if commented out.
)

```

**Comment by bslakman** [comment]
Hi @Spencer-S , I can't reproduce your error, it's working for me. Can you please paste your entire input file and also your error?

**Comment by Spencer-S** [comment]
Hello @bslakman.  Thanks for the fast response.  Glad to hear that the example works for you; the problem is most likely on my end then.  Before you invest any more time, let me pull the most recent source, recompile, and try one more time.  I will provide an update once I try that.  Thanks, Spence

**Comment by Spencer-S** [comment]
Problem solved... the version tagged 1.0.4 does not contain the code for constantSpecies.  Testing again with the MASTER branch solved the problem.

**Comment by rwest** [comment]
Glad you figured it out. @connie or @nickvandewiele -- is it time for a new release soon?

**Comment by connie** [comment]
There will probably be a release once parallelization is fixed. ;)
