### ISSUE TITLE
migrate symmetry perception algo's away from Molecule?

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#70]
Not an error but rather an 'idea' for rmg-py's architecture

I was currently revising the symmetry perception algorithms in rmg-py. They consist of several sub sections (atom, bond, axis, etc) as envisioned by Joanna Yu if I am not mistaken. In RMG-Java many of the molecule symmetry perception algorithms are slightly modified to internal rotors (as I am currently experiencing in trying to port those algorithm's to rmg-py).

Would you not consider removing all the perception algorithms from Molecule into a separate dedicated calculator type? Molecule is already getting quite heavy-weight (if you ask me) and symmetry perception is not really a core part. Moreover, then we could have a look how to unify both the rotor symmetry perception algo's and the regular molecule symmetry algo's into more generally applicable procedures.

Just my two cents... :)

**Comment by goldmanm** [comment]
Symmetry has been migrated to rmgpy/molecule/summetry
