### ISSUE TITLE
I/O disk writing and buffering?

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#715]
I am running into a MOPAC problem related to buffering, and writing to the disk. With your experience in calling external executables, perhaps you understand the problem better, and know how to solve it.

What I observe is that the QMTP code of RMG-Py wants to parse the contents of the written MOPAC output file of a calculation, but can't, throwing an error like:

`AttributeError: 'ccData' object has no attribute 'vibfreqs'`

The theory of previous lab member @keceli Murat Keceli is that the OS has not yet finished writing to the file, while python already continues to the next line of code, despite the blocking `Popen.communicate()` call. The idea is that the OS wants to reduce the number of writes by buffering some data and only physically writing that data to the storage.

My current code looks like this:
A call to `os.fsync` should help to empty the OS's buffer. Unfortunately, without the wanted result.
```python
    def run(self):
        self.testReady()
        # submits the input file to mopac
        process = Popen([self.executablePath, self.inputFilePath], stderr=PIPE)
        stdout, stderr = process.communicate()  # necessary to wait for executable termination!

        with open(self.outputFilePath) as f:
            os.fsync(f.fileno())

        if "ended normally" not in stderr.strip():
            logging.warning("Mopac error message:" + stderr)
        return self.verifyOutputFile()
```

Any solutions that fix this? The trivial `sleep` is unacceptable, for now.
Perhaps @pierrelb @rwest ?

**Comment by rwest** [comment]
Are you running on a cluster with a networked file system?   I have tried many things, over the years.
We have found the only way to make this reliable is to add a short delay, with `sleep`.
See issue #134 and https://github.com/ReactionMechanismGenerator/RMG-Py/commit/56ca670b5b37b8e116b4244ea569781efb8858d5 

I used to agree it's unacceptable, then downgraded to unsatisfactory, and finally unsatisfying, but it works. I guess you could use a try/except blocks that only sleeps if it's failed? That may be the best solution.  Let me know if you find a better one! (but don't waste too long trying!)

**Comment by nickvandewiele** [comment]
Thanks for the input. Apparently, many people have already noticed this.

You're right, I don't see it happen when running on a local filesystem. Only on a networked ones.

**Comment by nickvandewiele** [comment]
The following construction seems to be a more robust method that does not need 'sleep'.

It runs the external executable in a _temporary_ directory, and copies the output back to the destination directory before being processed in subsequent steps.

I believe the temporary directory is always a subfolder of `/tmp/`, which will be part of the local hard drive of the pc, rather than a location on the NFS.

```python
dirpath = tempfile.mkdtemp()

# copy input file to temp dir:
tempInpFile = os.path.join(dirpath, os.path.basename(self.inputFilePath))
shutil.copy(self.inputFilePath, dirpath)      

process = Popen([self.executablePath, tempInpFile], stderr=PIPE)
stdout, stderr = process.communicate()  # necessary to wait for executable termination!

# copy output file from temp dir to output dir:
tempOutFile = os.path.join(dirpath, os.path.basename(self.outputFilePath))
shutil.copy(tempOutFile, self.outputFilePath)

# delete temp folder:
shutil.rmtree(dirpath)

# process output file
...
```

I think that the fact that this seems to solve my problem only exemplifies that I did not really understand what is really at the root of the problem.

**Comment by rwest** [comment]
One could do the processing from the temp directory; may be faster. There were plans (maybe never very well formed) to have different SCRATCH and TEMP etc. folders, to do some QM calculations on local (presumed faster) drives. Not sure it ever got implemented properly, and so perhaps the settings and options were removed.
