### ISSUE TITLE
Chlorine in RMG

### ISSUE THREAD

**Issue by Ilyasem** [ReactionMechanismGenerator/RMG-Py#717]
I am very new to Python and chemical modeling in general.
I am trying to model a flash photolysis of chlorine in the presence of methanol.

Here is the error I am stuck on:

Generating thermodynamics for new species...
Traceback (most recent call last):
  File "rmg.py", line 165, in <module>
    rmg.execute(inputFile, output_dir, *_kwargs)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\rmg\main.py", line 541, in execute
    bimolecularReact=self.bimolecularReact)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\rmg\model.py", line 764, in enlarge
    spec.generateThermoData(database, quantumMechanics=self.quantumMechanics)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\rmg\model.py", line 100, in generateThermoData
    thermo0 = database.thermo.getThermoData(self, trainingSet=None, quantumMechanics=quantumMechanics)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\data\thermo.py", line 724, in getThermoData
    tdata = self.estimateThermoViaGroupAdditivity(molecule)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\data\thermo.py", line 999, in estimateThermoViaGroupAdditivity
    thermoData = self.estimateRadicalThermoViaHBI(molecule, self.computeGroupAdditivityThermo)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\data\thermo.py", line 936, in estimateRadicalThermoViaHBI
    thermoData_sat = stableThermoEstimator(saturatedStruct)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\data\thermo.py", line 1042, in computeGroupAdditivityThermo
    self.__addGroupThermoData(thermoData, self.groups['group'], molecule, {'_':atom})
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\data\thermo.py", line 1126, in __addGroupThermoData
    while node.data is None and node is not None:
AttributeError: 'NoneType' object has no attribute 'data'

I added thermo data for [C] after running into issues with that into primarythermolibrary.

[primaryThermoLibrarycopy.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/369807/primaryThermoLibrarycopy.txt)

[inputcopy.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/369801/inputcopy.txt)

I ran databaseTest and found no issues.
You might note that I removed many of the reaction libraries in diagnostic effort.
What troubleshooting actions should I take? Thank you!!

**Comment by nickvandewiele** [comment]
Hi @Ilyasem 
Thank you for your interest in RMG-Py.

As far as I know, heteroelements such as Cl are currently not supported, mostly because we do not have the right estimation methods to compute thermo and kinetics for Cl containing components and reactions.

Perhaps have a look at [this thread](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/457)  for some ideas to hack RMG to add unsupported elements.

**Comment by rwest** [comment]
FYI I am working towards adding chlorine chemistry, but it is a long way from ready; we might be able to collaborate, depending on your interests.

**Comment by Ilyasem** [comment]
Thanks for you for your prompt reply.
 I have a list of reactions involving chlorine that we can expect and can find reaction rates for those. I was thinking about adding that into a seed mechanism. The thread with unsupported elements may hold the solution to have RMG handle the non chlorine containing compounds and adding in any reactions involving chlorine manually. 

Alternatively, I was considering attempting to find all possible reactions without the chlorine and generating a mechanism, and adding in chlorine reactions manually at the end. Would it be best to work with chlorine before RMG or after?

**Comment by mliu49** [comment]
RMG now supports chlorine as an element. Creating a reaction library to use as a seed mechanism should work without any issues. Generation of new reactions may be limited by the capabilities of the existing families though.
