### ISSUE TITLE
`database.thermo.getThermoData` clears molecule's labeled atoms

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#725]
This behavior works when running an RMG job because getThermoData is used mostly in `rmgpy.rmg.model` as shown by the history of the function: https://github.com/ReactionMechanismGenerator/RMG-Py/commit/29cf8dc85222d0fd37459a7329f218904394ad1d

But can lead to erratic behavior if using outside of a normal RMG run because it erases all labeled atoms.

It is also called in `database.thermo.getThermoDataFromGroups` and whenever radical count > 1.  BUT the atom labels are not erased when the thermo is directly retrieved from libraries or QM and radical count = 0, so it can definitely lead to unexpected issues in the future with these inconsistencies.

**Comment by nyee** [comment]
When does an inputted molecule start with labels/What was the application for this?
