### ISSUE TITLE
RMG should also output Cantera input files

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#737]
A suggestion to generate a Cantera input file (.cti) based on the annotated and non-annotated RMG-generated Chemkin files. The ck2cti script already exists, it doesn't treat our annotations so great, but overall does a good job.
Should this be a choice in the RMG input file (and if yes, then be also set to default?), or simply always enforced?

**Comment by rwest** [comment]
👍  I think we should always generate a .cti file.

**Comment by alongd** [comment]
How about creating a "model" directory, instead of "chemkin" with files:
chem.inp
chem.cti
chem_annotated.inp
chem_annotated.cti
chem_edge.inp (optional)
chem_edge.cti (optional)
species_dictionary.txt
species_edge_dictionary.txt (optional)
tran.dat
[cti files will include transport data I guess, if not than a separate Cantera transport file]

and all the chemxxxx.inp and chem_edgexxxx.inp will be relocated to a subfolder named "model_generation" inside "model", or something of that sort?

This should all be done after RMG has finished generating the model, I guess.
