### ISSUE TITLE
CanTherm model chemistries

### ISSUE THREAD

**Issue by bslakman** [ReactionMechanismGenerator/RMG-Py#742]
I'm a bit confused about what is meant by some of the model chemistries in CanTherm. I want to do calculations using G3//B3LYP (i.e. Gaussian-3 theory on B3LYP geometries). Is the appropriate model chemistry to use `DFT_G03_b3lyp`, `G3`, or neither? I used to think the former referred to calculations done with the _program_ Gaussian 03, but this seems incorrect now as none of the others refer to the program used.
However if it is the former, I'm not sure that we should be adding in the spin orbit corrections, as we don't for `G3` itself.
Edit: see https://github.com/ReactionMechanismGenerator/RMG-Py/issues/263

**Comment by nyee** [comment]
Maybe the documentation under model chemistry helps? Does G3 imply a specific basis set like CBS-QB3 does? If so, I would guess you want to use the G3 corrections.

https://github.com/ReactionMechanismGenerator/RMG-Py/blob/15880913bbfab08e2e29b5199b4ae58ea0301857/documentation/source/users/cantherm/input.rst

**Comment by alongd** [comment]
closed via #1324
