### ISSUE TITLE
pdf documentation fails to import many modules

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#745]
In the RMG-Py/documentation folder, the RMG-Py_API_Reference.pdf has issues importing modules like quantities, rdkit, DipoleMoment, Quantity, TerminationTime, and Energy.

Here is an example error:

```
autodoc: failed to import class u’MopacMolPM7’ from module u’rmgpy.qm.mopac’; the following ex-
ception was raised: Traceback (most recent call last): File “/home/connie/anaconda/lib/python2.7/site-
packages/Sphinx-1.3.1-py2.7.egg/sphinx/ext/autodoc.py”, line 385, in import_object __import__(self.modname) File
“/home/connie/Research/Code/RMG-Py/rmgpy/qm/mopac.py”, line 9, in <module> from qmdata import CCLibData
File “/home/connie/Research/Code/RMG-Py/rmgpy/qm/qmdata.py”, line 4, in <module> from rmgpy.quantity import
Energy, Mass, Length, Frequency ImportError: cannot import name Energy
```

**Comment by KEHANG** [comment]
did you activate your environment `rmg_env` before `make latexpdf `?

**Comment by goldmanm** [comment]
I just retried it with the `rmg_env` activated. The resulting pdf still has many `autodoc` errors like the one mentioned above. 

It also wasn't working on Max's computer when I first posted the issue.

Is it working on your end?

**Comment by KEHANG** [comment]
@goldmanm it's working on my end. Seems you are using connie's repo: `/home/connie/Research/Code/RMG-Py/rmgpy/qm/qmdata.py`, you sure it's up to date?

**Comment by goldmanm** [comment]
Just to update: 
The error originated from python not using the anaconda 
The fix involved installing sphinx, restarting the terminal (not sure why), and running in python `import sphinx; sphinx.__file__` to ensure the proper anaconda directory is used. I adjusted my path to get the right sphinx package and it worked.
