### ISSUE TITLE
We should switch to the new CCLib

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#756]
CCLib have [just released](https://github.com/cclib/cclib/releases) version 1.5 which includes an updated MOPAC parser (based somewhat on our code, it seems: https://github.com/cclib/cclib/pull/257 )

If we can switch to using the official CCLib instead of our own fork, that would be great. Would avoid issues like https://github.com/ReactionMechanismGenerator/RMG-Py/issues/177. 
And if it's not good enough for us, then there is now a clear upstream place to send our improvements :)

**Comment by mliu49** [comment]
We are a bit closer. During the Python 3 transition, @amarkpayne reconciled most of our changes with the official cclib v1.6. Those changes are located in his fork [amarkpayne/cclib](https://github.com/amarkpayne/cclib). However, I think he did not merge the MOPAC parsers, and both our version and the official version exist side-by-side (they were named differently). This is the version which was used to create the 1.6.1.rmg conda build of cclib currently in the RMG channel.

Ideally, we should identify the remaining differences and pull request to the official version.

**Comment by rwest** [comment]
Would anyone  like to pick up the torch and help us switch for good?  (Or else update the "RMG" version and push a suite of new conda binaries).  I think the need to use this old conda build of cclib is holding up https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2088
