### ISSUE TITLE
DipolMoment in tran.dat gets an unrealistic value

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#763]
In tran.dat I get strannge numbers for DiplMom such as `552817292552000018941088890880.000`. I know...

here's an example:
```
! Species         Shape    LJ-depth  LJ-diam   DiplMom   Polzblty  RotRelaxNum Data     
! Name            Index    epsilon/k_B sigma     mu        alpha     Zrot      Source   
Ar                  0     136.501     3.330     0.000     0.000     0.000    ! GRI-Mech
CH4(1)              2     141.400     3.746     0.000     2.600    13.000    ! GRI-Mech
O2(2)               1     107.400     3.458     0.000     1.600     3.800    ! GRI-Mech
H2O(8)              2     572.402     2.605 552817292552000018941088890880.000     0.000     4.000    ! GRI-Mech
CH2O(17)            2     498.002     3.590     0.000     0.000     2.000    ! GRI-Mech
CH3O(23)            2     417.002     3.690 509647178599999949077582184448.000     0.000     2.000    ! GRI-Mech
CO(11)              1      98.100     3.650     0.000     1.950     1.800    ! GRI-Mech
C2H3(25)            2     209.001     4.100     0.000     0.000     1.000    ! GRI-Mech
CH2(S)(22)          2     144.001     3.800     0.000     0.000     0.000    ! GRI-Mech
CH2(16)             2     144.001     3.800     0.000     0.000     0.000    ! GRI-Mech
C2H2(20)            1     209.001     4.100     0.000     0.000     2.500    ! GRI-Mech
```

It happens often (and for the same species: H2O, CH3O, and CH2OH)
Here are an input file that generates it (but I guess this error should be very easy to generate), and my output tran.dat file:
[xo1208.py.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/448368/xo1208.py.txt)
[tran.dat.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/448369/tran.dat.txt)

**Comment by KEHANG** [comment]
Based on [wikipedia](https://en.wikipedia.org/wiki/Bond_dipole_moment), `1 C m = 2.9979e29 D`. From your trans.dat, `H2O(8)` is from `GRI-Mech`, which records water has `1.844 C*m`, which equals to `5.5281e29 D`. I guess RMG is doing the right conversion although the number is big.

**Comment by alongd** [comment]
I now see where the value came from, but I'm not sure that GRI's original value was in `C*m` units. From the GRI3.0 [Chemkin transport file](http://combustion.berkeley.edu/gri-mech/version30/files30/transport.dat), the dipole moment (5th column) of H2O for example is `1.844`. Chemkin raises an error, however, for the value generated by RMG after unit conversion, `552817292552000018941088890880.000`.
Since GRI is already in a Chemkin format, it seems like it's already in `debye` and no conversion is needed.
(For my Chemkin\Cantera sims I manually change these value to avoid the error, and get reasonable results)

**Comment by rwest** [comment]
Also based on [wikipedia](https://en.m.wikipedia.org/wiki/Dipole#Molecular_dipoles), water vapor has a dipole of 1.85 D not 1.85 Cm

**Comment by alongd** [comment]
Right, I missed that. So we should not automatically convert the dipole moment units (and should avoid conversion for GRI)

**Comment by KEHANG** [comment]
OK, in summary, in RMG we have two units for dipole moment, one is `De`, the other is `C*m`. RMG is able to convert from one to the other. The problem here is when people made the transport library `GRI-Mech`, they didn't pay enough attention on the unit, all the dipole moment is using `C*m`, which is a big unit. By double checking all the entries in that library, we have four written in wrong units. They are `CH2OH`, `CH3O`, `H2O` and `NH3`.

I've made a [PR](https://github.com/ReactionMechanismGenerator/RMG-database/pull/126) to fix that. @alongd I used your input file with this patch and was able to get rid of the big numbers. Please try by yourself and see if it works.

**Comment by alongd** [comment]
Yep, works great!
