### ISSUE TITLE
Seed/reaction library and P-dep have unclear interaction

### ISSUE THREAD

**Issue by nyee** [ReactionMechanismGenerator/RMG-Py#764]
From what i can tell, this issue from RMG-Java is still relevant and unchanged for RMG-Py: ReactionMechanismGenerator/RMG-Java#74

Relevant lines in code [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/e89318eb411cd4c92888eb8bdcb5673cb79df092/rmgpy/rmg/model.py#L736-L747)

**Comment by rwest** [comment]
Quick gut response: I think reaction libraries [should] behave like seed mechanisms, and be assumed to include pressure dependence.
If you have high-pressure-limit rates they should go in a family as training reactions, which RMG-Java did not have. They will then be used for the specific reaction if it shows up.


However, we could probably expand the reaction library syntax to include an attribute on each reaction saying whether it is high-pressure-limit or includes PDep effects if this is needed?

There are certainly still unclear details around this issue, eg. about how to merge a PDep well-skipping reaction library rate with a generated unimolecular network that includes and expands beyond the original net paths.

**Comment by nyee** [comment]
I was wrong in the first post, it looks like the issue is slightly changed.

Any high-pressure-limits rates can be inputted into Cantherm(?) to create expandable p-dep networks, regardless of the source for the high-pressure-limit rate.

Seed mechanisms getting added 'as-is' into the core, without creating a :class:PdepNetwork. This means if a new core species is had unimolecular reactions that would overlap with the seed mechanism's pdep rates, we would just create an entirely separate :class:PdepNetwork. In the chemkin output, we would get phenomenological rates from two different networks: the seeded one and an RMG generated one. I'm sure this is not what we want, but i'm also unsure what output we _do_ want. 

Do we want we want:
1. keep the seed mechanism's pdep network 'as-is', and don't create a separate one at all
2. start with the seed mechanism and expand it with RMG-generated rates.

As Richard stated, I'm uncertain that we can even implement option 2. 

Reaction libraries have one additional problem along with issue stated for seed mechanisms. We keep pdep-reactions only if all their species are added to the core. Thus, the chemkin mechanism can end up with phenomenological rates from an incomplete network.
