### ISSUE TITLE
valency of elements and benzene bonds

### ISSUE THREAD

**Issue by nyee** [ReactionMechanismGenerator/RMG-Py#767]
@KEHANG, @mliu49, and I were discussing refactoring and fixes for valency. First, we seem to have places where we have duplicated hard-coding for calculating valency, such as [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/adjlist.py#L43) and [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/molecule.py#L359). We suggest moving all of these to the rmgpy.molecule.element.py so that at least it is all hard-coded in the same place.

Second, benzene bond valency is unclear because of Cbf atomtype, which can have three 'B' bonds. After looking at a few example PAH's, we think the best fix is to use a valency of 4/3 if there are exactly three benzene bonds and 3/2 in all other cases. We considered creating a new bond order 'FB' for fused benzene bonds, but rejected it because it still has unclear valency when PAHs get big enough. For example, in pyrene the apparent bond order for 'FB' could be 1 or 2 depending on which bond you are looking at.

**Comment by nyee** [comment]
#403 is related

**Comment by mliu49** [comment]
Addressed by #769.
