### ISSUE TITLE
Binary installation not working (error occurs during the cmd.exe process)

### ISSUE THREAD

**Issue by kimgoblue** [ReactionMechanismGenerator/RMG-Py#779]
Hello. 

I want to use the RMG as just a basic user, so, downloaded Anaconda2 (in windows, 32 bit, 2.7 python) and installed it. 
I followed all the instructions in, http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaUserWindows.html, but, while the command prompt shoots out an error message. 

I typed "conda create -c rmg --name rmg_env rmg rmgdatabase" command into the cmd.exe prompt, and it shoots out the attached error message. 
Could you figure out what is wrong and how I can solve this problem? 
![1](https://cloud.githubusercontent.com/assets/22629860/19100175/65c4d38c-8a8a-11e6-8ed9-35d3c0c92cb6.JPG)
![2](https://cloud.githubusercontent.com/assets/22629860/19100174/65c44926-8a8a-11e6-9457-471f6c4e9939.JPG)

Best, Taemin Kim

**Comment by rwest** [comment]
`WindowsError: [Error 5]` ... Error 5 is access is denied, so this is either a permissions error, or an issue with the Windows file lock.  [These posts](https://github.com/conda/conda/issues/708) suggest you try rebooting the computer (in case it's a file lock), and running the anaconda prompt, from which you run `conda create -c rmg --name rmg_env rmg rmgdatabase`,  as an administrator (in case it's a permissions error).

**Comment by rwest** [comment]
Other suggestions include [temporarily disabling virus scanners.](https://github.com/conda/conda/issues/2893#issuecomment-229782970)
