### ISSUE TITLE
Installing on Linux without Anaconda: settings.pxi : not found

### ISSUE THREAD

**Issue by sreihani** [ReactionMechanismGenerator/RMG-Py#784]
Installing RMG from command line generates error message "settings.pxi : not found".  Looking at the Makefile, I noticed pydas cannot locate daspk or dassl, while both are installed on my machine.  I am not sure pydas is a product from your group or from python. Any suggestion for fixing this issue?

Seyed

**Comment by rwest** [comment]
`/rmgpy/solver/settings.pxi` should be a small text file that tells cython whether your PyDAS  has been installed with DASPK (in which case it contains "DEF DASPK = 1") or if have to use DASSL (in which case it contains "DEF DASPK = 0").  If you execute the Makefile by typing `make`, having installed PyDAS correctly into your python path, it will create the textfile using these lines
```bash
DASPK=$(shell python -c 'import pydas.daspk; print pydas.daspk.__file__')
DASSL=$(shell python -c 'import pydas.dassl; print pydas.dassl.__file__')

solver:
ifneq ($(DASPK),)
	@ echo "DASPK solver found. Compiling with DASPK and sensitivity analysis capability..."
	@ (echo DEF DASPK = 1) > rmgpy/solver/settings.pxi 
else ifneq ($(DASSL),)
	@ echo "DASSL solver found. Compiling with DASSL.  Sensitivity analysis capabilities are off..."
	@ (echo DEF DASPK = 0) > rmgpy/solver/settings.pxi
else
	@ echo 'No PyDAS solvers found.  Please check if you have the latest version of PyDAS.'
	@ python -c 'import pydas.dassl' 
endif
	python setup.py build_ext solver --build-lib . --build-temp build --pyrex-c-in-temp

```

If you wish to compile things without using Anaconda, you may want to refer to an older version of our instructions, such as 
https://github.com/ReactionMechanismGenerator/RMG-Py/tree/f9a7ac3d9ad4ae11ce383383fb0a67edd0aa28d7/documentation/source/users/rmg/installation

Specifically, you must make and install PyDAS and PyDQED. Something like:
```bash
git clone https://github.com/ReactionMechanismGenerator/PyDAS.git
cd PyDAS; make F77=gfortran; sudo make install; cd ..
git clone https://github.com/ReactionMechanismGenerator/PyDQED.git
cd PyDQED; make F77=gfortran; sudo make install; cd ..
```

PyDAS and PyDQED are maintained by this organization:
https://github.com/ReactionMechanismGenerator/PyDAS 
https://github.com/ReactionMechanismGenerator/PyDQED

Does that help?

**Comment by sreihani** [comment]
Hello Richard,

I am getting the following error, after the "make" command in RMG-Py directory (I have not installed rdkit yet):

 Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib64/python2.6/site-packages/PyDAS-1.0.2-py2.6-linux-x86_64.egg/pydas/daspk.so: undefined symbol: _gfortran_transfer_integer_write
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib64/python2.6/site-packages/PyDAS-1.0.2-py2.6-linux-x86_64.egg/pydas/dassl.so: undefined symbol: _gfortran_transfer_integer_write
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named rdkit
Checking you have PyDQED...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib64/python2.6/site-packages/pydqed.so: undefined symbol: _gfortran_transfer_array_write
make: *** [main] Error 1

Any thought?

Seyed

**Comment by rwest** [comment]
Looks like dassl.so and pydqed.so can't find the gfortran libraries they were built against. Check your LD_LIBRARY_PATH?

**Comment by sreihani** [comment]
The issue is still there. I am wondering where daspk.so and dassl.so are created. I found the folder where their static libraries are made, but not sure about these two files.

Thanks.

Seyed

**Comment by rwest** [comment]
I'm not sure what you're asking. If you do `make` but not `make install` then you might find them. I think `make install` moves them into your /usr/lib64/python2.6/site-packages/
