### ISSUE TITLE
Cantherm thermo and Chebyshev output not formatted correctly for Chemkin

### ISSUE THREAD

**Issue by zjburas** [ReactionMechanismGenerator/RMG-Py#789]
This is more of an annoyance than a serious issue, but the chem.inp file generated by Cantherm does not output either the thermo or Chebyshev blocks in the correct Chemkin format.

First, the thermo block does not include the the number of each atom type present in the molecule (e.g., C 4  H 10 for butane). Instead, the correct atom types are identified, but the number of each is simply listed as 0 (e.g., C 0  H 0 for butane). It is probably easiest to see this by running the n-butanol example under RMG-Py/examples/cantherm/networks/n-butanol. The lack of numbers causes pre-processing errors in Chemkin and currently has to be fixed manually.

Second, the Chebyshev block lacks the necessary (+M) on both the reactant and product side. An example of this is at RMG-Py/examples/cantherm/networks/acetyl+O2. Again, this causes pre-processing errors in Chemkin and has to be fixed manually.

Obviously the chem.inp output of an RMG job does not have these formatting errors, so it must just be an issue when using Cantherm as a standalone unit.

**Comment by mliu49** [comment]
I found that Cantherm has a completely independent set of methods for writing Chemkin entries, instead of using the (clearly) more robust methods that RMG uses.

For the thermo problem, Cantherm has a [placeholder](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/cantherm/thermo.py#L173) for counting the number of each element, but no actual code. For the kinetics problem, Cantherm directly [writes](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/cantherm/pdep.py#L451) the reaction string using RMG's representation.

It would seem that the best solution would be to try and import RMG's Chemkin methods to use in Cantherm. It might take some time to compare the two to make sure we aren't losing any functionality, but I can look into it.

**Comment by mliu49** [comment]
I looked at it a bit more, and it seems that the writing kinetics entries can be easily switched over to use `rmgpy.chemkin.writeKineticsEntry`, but it's the issue with thermo entries is not as straightforward. Cantherm does not create Molecule objects at all, so the `retrieveElementCount` function does not work. Thermo jobs also do not store any kind of molecular structure or formula information, which is probably why element counting was not implemented in the first place.

**Comment by rwest** [comment]
If this is for generating thermo blocks from the basis of reading in Gaussian (or some other QChem package) file, then we could grab the number of each atom type from there.

**Comment by nyee** [comment]
We were just talking about this, but not every cantherm job has to read the geometry from a log file.

**Comment by nyee** [comment]
Proposed solution from study group: 
1. Read in atom number from user input
2. Modify rmpy.chemkin.writeEntry to accept a new argument specifying number of tsom

**Comment by zjburas** [comment]
The chem.inp file output by Cantherm could be improved even more (i.e., make it easier to directly run in Chemkin without manual intervention) by making the following changes:

1. Automatically including a Chemkin ELEMENTS block

2. Automatically including a Chemkin SPECIES block

3. Adding THERMO ... "default T range" ... END to thermo block

4. Adding REACTIONS ... END to reactions block, with units specified in first line if they differ from CHEMKIN default (cm, s, mol, cal/mol, K)

I think with all of these changes it should be possible to directly take a chem.inp file from Cantherm and immediately plug it in to Chemkin without the user needing to do all of the manual work above. RMG already does all of this, so I imagine Cantherm could as well.

However, users should be cautioned that when running P-dep Cantherm jobs, reactions involving only reactants/isomers (no products) are written irreversibly in both directions in the chem.inp file. Apparently it was the intention of the Cantherm developers that the user manually remove the duplicate reactions, as stated in the documentation:

[http://reactionmechanismgenerator.github.io/RMG-Py/users/cantherm/output.html](url)

Maybe this should also be changed, otherwise users are very likely to try running a mechanism with almost twice as many reactions as necessary (I've done it).

**Comment by goldmanm** [comment]
I think this was fixed with #1071
