### ISSUE TITLE
Add installation issues FAQ to documentation

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#790]
See issues such as 

- https://github.com/ReactionMechanismGenerator/RMG-website/issues/125
- https://github.com/ReactionMechanismGenerator/RMG-Py/issues/784
- https://github.com/ReactionMechanismGenerator/RMG-Py/issues/779

It would be good to collect up some general advice for common (and rare!) problems that can occur installing RMG and add to a page in the documentation.

And perhaps reintroduce the "build from source" instructions (although we recommend the Anaconda approach, there's no need to delete the old instructions - some people may need them.)

**Comment by KEHANG** [comment]
I agree, I've started creating a branch to add back the instruction of`build from source without anaconda`, will add FAQ section if possible
