### ISSUE TITLE
Discontinuities in heat capacity curves?

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#792]
Search thermo for this C3H2 species  `InChI=1S/C3H2/c1-2-3-1/h1H2`

```
1 C u0 p0 c0 {2,S} {3,S} {4,S} {5,S}
2 C u0 p1 c0 {1,S} {3,S}
3 C u0 p1 c0 {1,S} {2,S}
4 H  u0 p0 c0 {1,S}
5 H  u0 p0 c0 {1,S}
```

eg. by clicking [here](http://rmg.mit.edu/database/thermo/molecule/1%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D%20%7B5,S%7D%0A2%20C%20u0%20p1%20c0%20%7B1,S%7D%20%7B3,S%7D%0A3%20C%20u0%20p1%20c0%20%7B1,S%7D%20%7B2,S%7D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0A5%20H%20u0%20p0%20c0%20%7B1,S%7D%0A) 
and you will notice a few things.
1.  the picture looks like cyclopropane, C3H6, because it does not draw the lone pairs,
2. the heat capacity, entropy, and gibbs free energy, curves all have big discontinuities at 1500K.

<img width="532" alt="screen shot 2016-10-21 at 2 11 06 pm" src="https://cloud.githubusercontent.com/assets/93807/19607496/3f903272-9798-11e6-93aa-0fb6f0ac6c06.png">

**Comment by bslakman** [comment]
Lone pair issue is related to #364 but I guess we only did it for solvation.. do we want to do this for all thermo, when we are estimating via Group additivity?
