### ISSUE TITLE
generateReverseRateCoefficient cannot handle PDepArrhenius with MultiArrhenius rates

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#797]
This was discovered while using the Plot Kinetics tool on the website.

The input included pressure dependent rates in PLOG format, but with two sets of Arrhenius parameters at each pressure. RMG parsed this as a PDepArrhenius object with a MultiArrhenius rate at each pressure. However, the `generateReverseRateCoefficient` function assumes that PDepArrhenius objects only have Arrhenius rates for each pressure, and errors while trying to calculate the reverse rate.

Questions:
- Is this the correct way for RMG to be interpreting the rate?
- If so, is it ok to modify `generateReverseRateCoefficient` to recognize such a form?

**Comment by rwest** [comment]
See PR https://github.com/ReactionMechanismGenerator/RMG-Py/pull/329 which fixed issue https://github.com/ReactionMechanismGenerator/RMG-Py/issues/147 which has a detailed write-up.  I *think* after Connie's fix the answer to you first bullet point is yes, and thus it'd be helpful if we could reverse such rates, somehow.

**Comment by mliu49** [comment]
Fixed by #1659
