### ISSUE TITLE
RMG cannot read the last species in a kinetic library dictionary without two empty lines at the end of the dictionary

### ISSUE THREAD

**Issue by yunsiechung** [ReactionMechanismGenerator/RMG-Py#798]
When I created my own kinetic library and used it as a seedMechanism, RMG cannot find some species from a kinetic library dictionary even though they are there. When I moved those species and put it as the first few entries in the dictionary, RMG found them and ran fine. 

But the order of the species in the dictionary should not affect whether RMG can find all the species or not.

**Comment by rwest** [comment]
Can you post the library (and dictionary) to allow others to help debug?

**Comment by yunsiechung** [comment]
My reactions are:
```
entry(
    index = 1,
    label = "R1 + O2 <=> R1OO",
    degeneracy = 1,
    kinetics = Arrhenius(A=(1.21875e+9, 'cm^3/(mol*s)'), n=-0.99, Ea=(1.33, 'kcal/mol'), T0=(1, 'K')),
)

entry(
    index = 2,
    label = "R1 <=> R1a",
    degeneracy = 1,
    kinetics = Arrhenius(A=(2.5e+12, 's^-1'), n=0.080, Ea=(24.3, 'kcal/mol'), T0=(1, 'K')),
)

entry(
    index = 3,
    label = "R1 <=> R1b",
    degeneracy = 1,
    kinetics = Arrhenius(A=(3.6e+11, 's^-1'), n=0.446, Ea=(26.0, 'kcal/mol'), T0=(1, 'K')),
```
`
and my dictionary file is:
[dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/554480/dictionary.txt)

In the dictionary, I listed the species in the following order: R1, O2, R1OO, R1a, R1b
And I get the error message of:
> 
Loading kinetics library CineoleR1 from C:\Code\RMG-database\input\kinetics\libraries\CineoleR1\reactions.py...
Traceback (most recent call last):
  File "C:/Code/RMG-Py/rmg.py", line 164, in <module>
    rmg.execute(**kwargs)
  File "C:\Code\RMG-Py\rmgpy\rmg\main.py", line 506, in execute
    self.initialize(**kwargs)
  File "C:\Code\RMG-Py\rmgpy\rmg\main.py", line 372, in initialize
    self.loadDatabase()
  File "C:\Code\RMG-Py\rmgpy\rmg\main.py", line 303, in loadDatabase
    depository = False, # Don't bother loading the depository information, as we don't use it
  File "C:\Code\RMG-Py\rmgpy\data\rmg.py", line 101, in load
    kineticsDepositories
  File "C:\Code\RMG-Py\rmgpy\data\rmg.py", line 164, in loadKinetics
    depositories=kineticsDepositories
  File "C:\Code\RMG-Py\rmgpy\data\kinetics\database.py", line 104, in load
    self.loadLibraries(os.path.join(path, 'libraries'), libraries)
  File "C:\Code\RMG-Py\rmgpy\data\kinetics\database.py", line 209, in loadLibraries
    library.load(library_file, self.local_context, self.global_context)
  File "C:\Code\RMG-Py\rmgpy\data\kinetics\library.py", line 256, in load
    raise DatabaseError('Species {0} in kinetics library {1} is missing from its dictionary.'.format(product, self.label))
rmgpy.data.base.DatabaseError: Species R1b in kinetics library CineoleR1 is missing from its dictionary.

But if I change the order to: R1b, R1, O2, R1OO, R1a
it runs fine without the error. 

Are my kinetic libraries wrong??

**Comment by nyee** [comment]
You need two empty lines at the end of your dictionary, or it doesn't read the last species in the dictionary. No idea why, but we all have hit this before.

**Comment by yunsiechung** [comment]
Oh I see. I thought it was the order of species issue. 
Thank you. I will change the issue name. 

Has anyone attempted to fix that?

**Comment by rwest** [comment]
I was going to guess it was something like that. Thanks for confirming, @nyee. It's the kind of stupid behaviour you see in chemkin. We should definitely fix it!

Look at [getSpecies()](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/data/base.py#L273):
It doesn't process the species and do `species = Species().fromAdjacencyList(adjlist)` until it hits a blank line (`line.strip() == ''`).   Should be fixed.

**Comment by yunsiechung** [comment]
Thanks for all the comments. I will leave this issue open until it is fixed. 
I will try to fix it when I get a chance!

**Comment by nyee** [comment]
#799 contains a that commit should fix the issue, although I'm not sure I found every occurrence of this bug.
