### ISSUE TITLE
QM scratch file taking too much space in the RMG output files

### ISSUE THREAD

**Issue by yunsiechung** [ReactionMechanismGenerator/RMG-Py#802]
When using the on-the-fly QM MOPAC method for RMG run, most of the space in the output files is taken by QM scratch files. 
For example, my entire output files are 2.30 GB and the QM scratch folder itself is 2.01 GB. This is causing a problem in Pharos because it is taking too much memory. 
But it seems like only the QMfiles folder is needed and the QMscratch folder is not used once the thermo is calculated from the on-the-fly QM and saved in the QMfiles folder. 

Should we add a line in RMG to delete the QM scratch file once it is done?

**Comment by rwest** [comment]
Or add a line in your bash script that calls RMG, that you submit to the queuing system on Pharos.

**Comment by mliu49** [comment]
I thought that if you don't specify a scratch directory, then RMG won't save the the scratch files. I may be wrong though. The default setting for QMscratch is None.

In terms of usage, I do know that RMG will check both QMfiles and QMscratch. QMfiles has priority, but QMscratch is checked if there is no data for the species in QMfiles. RMG will only run a new calculation if the species can't be found in either location.
