### ISSUE TITLE
Errno 13: Please Help Me Resolve This

### ISSUE THREAD

**Issue by Prosbin** [ReactionMechanismGenerator/RMG-Py#817]
Hi,
This is my first time with RMG-Py. I encountered the error shown below when I tried using the  Minimal Example Input File. The same error repeats when I tried using it with my own input file. Please suggest how I can resolve this. Thanks.

```
(rmg_env) C:\>python %RMGPy%\rmg.py input.py
Traceback (most recent call last):
  File "C:\Anaconda2\envs\rmg_env\Scripts\rmg.py", line 128, in <module>
    initializeLog(level, os.path.join(args.output_directory, 'RMG.log'))
  File "C:\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\rmg\main.py", line 113
1, in initializeLog
    fh = logging.FileHandler(filename=log_file_name) #, backupCount=3)
  File "C:\Anaconda2\envs\rmg_env\lib\logging\__init__.py", line 913, in __init_
_
    StreamHandler.__init__(self, self._open())
  File "C:\Anaconda2\envs\rmg_env\lib\logging\__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: 'C:\\RMG.log'
```

**Comment by Prosbin** [comment]
@rwest I have restarted my computer, and disabled my antivirus as suggested in #779 but the error persists. Do you think it can be resolved if I try installation by source?

**Comment by mliu49** [comment]
This might be a naive suggestion, but maybe try relocating your input file to your Documents folder and run RMG-Py from there. I think writing directly to the root C:\ directory may require administrative permissions.

**Comment by rwest** [comment]
I think that's a good suggestion. You could try running the command prompt as an Administrator, but probably better just to run it from somewhere that you have write permissions.

**Comment by Prosbin** [comment]
@rwest and @mliu49 Thank you so much; it worked after I ran anaconda prompt as admin, as advised. Thanks for your help.
