### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Prosbin** [ReactionMechanismGenerator/RMG-Py#819]
Hi,
My installation worked well with the Minimal Example Input File; but on trying my own file (for pyrolysis of PET), I got the error above after about a minute. Please help me look into it. The input file (pet.py) is attached. See the RMG.log below:

`Global RMG Settings:
   database.directory   = C:\Anaconda2\envs\rmg_env\share\rmgdatabase (from C:\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\rmgrc)
RMG execution initiated at Tue Nov 15 12:33:21 2016

#########################################################
# RMG-Py - Reaction Mechanism Generator in Python       #
# Version: 2.0.0                                        #
# Authors: RMG Developers (rmg_dev@mit.edu)             #
# P.I.s:   William H. Green (whgreen@mit.edu)           #
#          Richard H. West (r.west@neu.edu)             #
# Website: http://reactionmechanismgenerator.github.io/ #
#########################################################

The current anaconda package for RMG-Py is:
rmg                       2.0.0                   py27_92    rmg

The current anaconda package for RMG-database is:
rmgdatabase               2.0.0                    py27_1    rmg

Reading input file "C:\Windows\system32\pet.py"...
database(
    thermoLibraries = ['primaryThermoLibrary'],
    reactionLibraries = [],
    seedMechanisms = [],
    kineticsDepositories = 'default',
    kineticsFamilies = 'default',
    kineticsEstimator = 'rate rules',
)

species(
    label = "PET",
    reactive = True,
    structure = adjacencyList(
"""
1  C u0 p0 c0 {2,S} {11,S} {15,S} {16,S}
2  C u0 p0 c0 {1,S} {12,S} {17,S} {18,S}
3  C u0 p0 c0 {5,D} {8,S} {9,S}
4  C u0 p0 c0 {6,D} {7,S} {10,S}
5  C u0 p0 c0 {3,D} {6,S} {19,S}
6  C u0 p0 c0 {4,D} {5,S} {20,S}
7  C u0 p0 c0 {4,S} {8,D} {21,S}
8  C u0 p0 c0 {3,S} {7,D} {22,S}
9  C u0 p0 c0 {3,S} {13,S} {23,D}
10 C u0 p0 c0 {4,S} {14,S} {24,D}
11 O u0 p2 c0 {1,S} {25,S}
12 O u0 p2 c0 {2,S} {26,S}
13 O u0 p2 c0 {9,S} {27,S}
14 O u0 p2 c0 {10,S} {28,S}
15 H u0 p0 c0 {1,S}
16 H u0 p0 c0 {1,S}
17 H u0 p0 c0 {2,S}
18 H u0 p0 c0 {2,S}
19 H u0 p0 c0 {5,S}
20 H u0 p0 c0 {6,S}
21 H u0 p0 c0 {7,S}
22 H u0 p0 c0 {8,S}
23 O u0 p2 c0 {9,D}
24 O u0 p2 c0 {10,D}
25 H u0 p0 c0 {11,S}
26 H u0 p0 c0 {12,S}
27 H u0 p0 c0 {13,S}
28 H u0 p0 c0 {14,S}
"""),
)

simpleReactor(
    temperature = (723,"K"),
    pressure = (1,"atm"),
    initialMoleFractions={
        "PET": 0.9,
    },
    terminationTime = (360,"s"),
    terminationConversion = {
        "PET": 0.95,
    },
)

simulator(
    atol = 1e-16,
    rtol = 1e-08,
    sens_atol = 1e-06,
    sens_rtol = 0.0001,
)

model(
    toleranceMoveToCore = 0.1,
    toleranceKeepInEdge = 0,
    toleranceInterruptSimulation = 1,
    maximumEdgeSpecies = 100000,
    minCoreSizeForPrune = 50,
    minSpeciesExistIterationsForPrune = 2,
    filterReactions = 0,
)

options(
    units = "si",
    saveRestartPeriod = (60.0,"second"),
    generateOutputHTML = True,
    generatePlots = True,
    saveSimulationProfiles = True,
    saveEdgeSpecies = True,
    keepIrreversible = None,
    verboseComments = True,
    wallTime = 00:00:00:00,
)

Error: The input file "C:\Windows\system32\pet.py" was invalid:
Error: invalid syntax (pet.py, line 84)
Traceback (most recent call last):
  File "C:\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\rmg\input.py", line 395, in readInputFile
    exec f in global_context, local_context
  File "C:\Windows\system32\pet.py", line 84
    wallTime = 00:00:00:00,
                 ^
SyntaxError: invalid syntax

[pet.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/591825/pet.txt)
`

**Comment by rwest** [comment]
Check the documentation carefully for how to specify walk time. I think you are missing some quotes ""

**Comment by alongd** [comment]
Also, it looks like you're running your input file from 'C:\Windows\system32\'
It's reccomended to open a folder for each run, i.e. 'C:\Code\runs\run1\'

**Comment by Prosbin** [comment]
@rwest Thanks for your help; after inserting quotes around the wallTime, the problem was solved. Although I encountered a another error message somewhere down the line. Please see #821. Thanks.
 
@alongd Thanks also. However, I tried running the code from the new folder but an error message showed up: No such file or directory: 'C:\\Windows\\system32\\pet.py' It looks to me like the program looks into system32 folder only. It didn't change even after I added the new folder to PATH. But then, @rwest 's suggestion worked; I'll just have to deal with the clutter that'll be created in my system32 folder.
