### ISSUE TITLE
IOError: error while writing to output stream

### ISSUE THREAD

**Issue by Prosbin** [ReactionMechanismGenerator/RMG-Py#826]
Hi,
Please suggest what I can do. My simulation keeps showing the error above after some minutes. Thanks!
![screenshot](https://cloud.githubusercontent.com/assets/23437345/20433032/2f58d9b6-ada2-11e6-86d8-ffc94b58b9f9.png)

**Comment by nyee** [comment]
Try turning off the html drawing option. In your input file, find the block that looks something like this:
```
options(
    units='si',
    saveRestartPeriod=None,
    generateOutputHTML=True,
    generatePlots=False,
    saveEdgeSpecies=True,
    saveSimulationProfiles=True,
)
```

and change the line `generateOutputHTML=True,` to     `generateOutputHTML=False,`
