### ISSUE TITLE
symmetry number of reactants should affect reaction rate

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#833]
Currently, RMG uses rates from the database regardless of the symmetry number of reactants. 

A reactants' symmetry number changing by 2x should decrease the a factor for a reaction by 2x (if retrieved from the same rate rule. This mostly plays out in the isotope chemistry, but also can occur in non-isotopic cases as well.

example from R-Addition
[`CC(C)=C(C)C + H <=> CC(C)-[CH](C)C`](http://rmg.mit.edu/database/kinetics/families/R_Addition_MultipleBond/rate_rules/reactant1=1%20%20C%20u0%20p0%20c0%20%7B5,S%7D%20%7B7,S%7D%20%7B8,S%7D%20%7B9,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B5,S%7D%20%7B10,S%7D%20%7B11,S%7D%20%7B12,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B6,S%7D%20%7B13,S%7D%20%7B14,S%7D%20%7B15,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B6,S%7D%20%7B16,S%7D%20%7B17,S%7D%20%7B18,S%7D%0A5%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B2,S%7D%20%7B6,D%7D%0A6%20%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B4,S%7D%20%7B5,D%7D%0A7%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A8%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A10%20H%20u0%20p0%20c0%20%7B2,S%7D%0A11%20H%20u0%20p0%20c0%20%7B2,S%7D%0A12%20H%20u0%20p0%20c0%20%7B2,S%7D%0A13%20H%20u0%20p0%20c0%20%7B3,S%7D%0A14%20H%20u0%20p0%20c0%20%7B3,S%7D%0A15%20H%20u0%20p0%20c0%20%7B3,S%7D%0A16%20H%20u0%20p0%20c0%20%7B4,S%7D%0A17%20H%20u0%20p0%20c0%20%7B4,S%7D%0A18%20H%20u0%20p0%20c0%20%7B4,S%7D%0A__reactant2=multiplicity%202%0A1%20H%20u1%20p0%20c0%0A__product1=multiplicity%202%0A1%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B6,S%7D%20%7B7,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B8,S%7D%20%7B9,S%7D%20%7B10,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B11,S%7D%20%7B12,S%7D%20%7B13,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B6,S%7D%20%7B14,S%7D%20%7B15,S%7D%20%7B16,S%7D%0A5%20%20C%20u0%20p0%20c0%20%7B6,S%7D%20%7B17,S%7D%20%7B18,S%7D%20%7B19,S%7D%0A6%20%20C%20u1%20p0%20c0%20%7B1,S%7D%20%7B4,S%7D%20%7B5,S%7D%0A7%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A8%20%20H%20u0%20p0%20c0%20%7B2,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B2,S%7D%0A10%20H%20u0%20p0%20c0%20%7B2,S%7D%0A11%20H%20u0%20p0%20c0%20%7B3,S%7D%0A12%20H%20u0%20p0%20c0%20%7B3,S%7D%0A13%20H%20u0%20p0%20c0%20%7B3,S%7D%0A14%20H%20u0%20p0%20c0%20%7B4,S%7D%0A15%20H%20u0%20p0%20c0%20%7B4,S%7D%0A16%20H%20u0%20p0%20c0%20%7B4,S%7D%0A17%20H%20u0%20p0%20c0%20%7B5,S%7D%0A18%20H%20u0%20p0%20c0%20%7B5,S%7D%0A19%20H%20u0%20p0%20c0%20%7B5,S%7D%0A) and [`CCC(C)=C(C)C + H <=> CCC(C)-[CH](C)C`](http://rmg.mit.edu/database/kinetics/families/R_Addition_MultipleBond/rate_rules/reactant1=1%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B6,S%7D%20%7B8,S%7D%20%7B9,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B10,S%7D%20%7B11,S%7D%20%7B12,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B6,S%7D%20%7B13,S%7D%20%7B14,S%7D%20%7B15,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B7,S%7D%20%7B16,S%7D%20%7B17,S%7D%20%7B18,S%7D%0A5%20%20C%20u0%20p0%20c0%20%7B7,S%7D%20%7B19,S%7D%20%7B20,S%7D%20%7B21,S%7D%0A6%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B3,S%7D%20%7B7,D%7D%0A7%20%20C%20u0%20p0%20c0%20%7B4,S%7D%20%7B5,S%7D%20%7B6,D%7D%0A8%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A10%20H%20u0%20p0%20c0%20%7B2,S%7D%0A11%20H%20u0%20p0%20c0%20%7B2,S%7D%0A12%20H%20u0%20p0%20c0%20%7B2,S%7D%0A13%20H%20u0%20p0%20c0%20%7B3,S%7D%0A14%20H%20u0%20p0%20c0%20%7B3,S%7D%0A15%20H%20u0%20p0%20c0%20%7B3,S%7D%0A16%20H%20u0%20p0%20c0%20%7B4,S%7D%0A17%20H%20u0%20p0%20c0%20%7B4,S%7D%0A18%20H%20u0%20p0%20c0%20%7B4,S%7D%0A19%20H%20u0%20p0%20c0%20%7B5,S%7D%0A20%20H%20u0%20p0%20c0%20%7B5,S%7D%0A21%20H%20u0%20p0%20c0%20%7B5,S%7D%0A__reactant2=multiplicity%202%0A1%20H%20u1%20p0%20c0%0A__product1=multiplicity%202%0A1%20%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B4,S%7D%20%7B7,S%7D%20%7B8,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B5,S%7D%20%7B7,S%7D%20%7B9,S%7D%20%7B10,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B14,S%7D%20%7B15,S%7D%20%7B16,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B17,S%7D%20%7B18,S%7D%20%7B19,S%7D%0A5%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B11,S%7D%20%7B12,S%7D%20%7B13,S%7D%0A6%20%20C%20u0%20p0%20c0%20%7B7,S%7D%20%7B20,S%7D%20%7B21,S%7D%20%7B22,S%7D%0A7%20%20C%20u1%20p0%20c0%20%7B1,S%7D%20%7B2,S%7D%20%7B6,S%7D%0A8%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B2,S%7D%0A10%20H%20u0%20p0%20c0%20%7B2,S%7D%0A11%20H%20u0%20p0%20c0%20%7B5,S%7D%0A12%20H%20u0%20p0%20c0%20%7B5,S%7D%0A13%20H%20u0%20p0%20c0%20%7B5,S%7D%0A14%20H%20u0%20p0%20c0%20%7B3,S%7D%0A15%20H%20u0%20p0%20c0%20%7B3,S%7D%0A16%20H%20u0%20p0%20c0%20%7B3,S%7D%0A17%20H%20u0%20p0%20c0%20%7B4,S%7D%0A18%20H%20u0%20p0%20c0%20%7B4,S%7D%0A19%20H%20u0%20p0%20c0%20%7B4,S%7D%0A20%20H%20u0%20p0%20c0%20%7B6,S%7D%0A21%20H%20u0%20p0%20c0%20%7B6,S%7D%0A22%20H%20u0%20p0%20c0%20%7B6,S%7D%0A)

Both reactions obtain the same group in the RMG-database. The second reaction has a loss of symmetry of the reactant (by a factor of 4). If we normalize for degeneracy, the second reaction should be one quarter as fast due to its lower symmetry number. RMG, however, would say that they are identical. Then RMG would adjust for the back reaction using the different thermo, which likely messes up that reaction. 

RMG gets the symmetry numbers of [`CC(C)=C(C)C`](http://rmg.mit.edu/database/thermo/molecule/1%20%20C%20u0%20p0%20c0%20%7B5,S%7D%20%7B7,S%7D%20%7B8,S%7D%20%7B9,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B5,S%7D%20%7B10,S%7D%20%7B11,S%7D%20%7B12,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B6,S%7D%20%7B13,S%7D%20%7B14,S%7D%20%7B15,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B6,S%7D%20%7B16,S%7D%20%7B17,S%7D%20%7B18,S%7D%0A5%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B2,S%7D%20%7B6,D%7D%0A6%20%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B4,S%7D%20%7B5,D%7D%0A7%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A8%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A10%20H%20u0%20p0%20c0%20%7B2,S%7D%0A11%20H%20u0%20p0%20c0%20%7B2,S%7D%0A12%20H%20u0%20p0%20c0%20%7B2,S%7D%0A13%20H%20u0%20p0%20c0%20%7B3,S%7D%0A14%20H%20u0%20p0%20c0%20%7B3,S%7D%0A15%20H%20u0%20p0%20c0%20%7B3,S%7D%0A16%20H%20u0%20p0%20c0%20%7B4,S%7D%0A17%20H%20u0%20p0%20c0%20%7B4,S%7D%0A18%20H%20u0%20p0%20c0%20%7B4,S%7D%0A) and [`CCC(C)=C(C)C`](http://rmg.mit.edu/database/thermo/molecule/1%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B6,S%7D%20%7B8,S%7D%20%7B9,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B10,S%7D%20%7B11,S%7D%20%7B12,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B6,S%7D%20%7B13,S%7D%20%7B14,S%7D%20%7B15,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B7,S%7D%20%7B16,S%7D%20%7B17,S%7D%20%7B18,S%7D%0A5%20%20C%20u0%20p0%20c0%20%7B7,S%7D%20%7B19,S%7D%20%7B20,S%7D%20%7B21,S%7D%0A6%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B3,S%7D%20%7B7,D%7D%0A7%20%20C%20u0%20p0%20c0%20%7B4,S%7D%20%7B5,S%7D%20%7B6,D%7D%0A8%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A10%20H%20u0%20p0%20c0%20%7B2,S%7D%0A11%20H%20u0%20p0%20c0%20%7B2,S%7D%0A12%20H%20u0%20p0%20c0%20%7B2,S%7D%0A13%20H%20u0%20p0%20c0%20%7B3,S%7D%0A14%20H%20u0%20p0%20c0%20%7B3,S%7D%0A15%20H%20u0%20p0%20c0%20%7B3,S%7D%0A16%20H%20u0%20p0%20c0%20%7B4,S%7D%0A17%20H%20u0%20p0%20c0%20%7B4,S%7D%0A18%20H%20u0%20p0%20c0%20%7B4,S%7D%0A19%20H%20u0%20p0%20c0%20%7B5,S%7D%0A20%20H%20u0%20p0%20c0%20%7B5,S%7D%0A21%20H%20u0%20p0%20c0%20%7B5,S%7D%0A) correctly (to my knowledge).

**Comment by nyee** [comment]
To my knowledge, RMG does not directly use symmetry numbers to calculate reaction degeneracy. The only place that we calculate degeneracy is [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/7b4de65bb814440b9c9d848f0c983ca41a3ee066/rmgpy/molecule/molecule.py#L347). Which very generally handle the case where two different mappings have the same reactants and products.  Thus, this can handle the basic case of adding +2 degeneracy on H-abstraction from a methyl group, but will miss more subtle symmetry related cases.

I'm pretty sure this is a known problem (possibly never documented). It has probably never been addressed because we're usually many orders of magnitude off in rate, so a x2 error from symmetry doesn't seem like a big deal.

**Comment by rwest** [comment]
Might it be taken care of when the rate rule is entered? I.e. the symmetry factor when getting from TST to k(T) should have been taken care of by whoever was putting the number into the database?

**Comment by goldmanm** [comment]
The input into the database does implicitly take into account the symmetry of the molecules used in the database. When it uses that rate to estimate similar kinetics but where the reactant molecules have a different symmetry numbers than the one studied (for example with an isotopically labeled propane or in the example in this issue), RMG will estimate it as if it had the same symmetry number as the original database input.

I do think @nyee is right that this has been a known problem, and also that we are worried about larger errors in general with RMG. It is a bigger problem for isotopic ratio calculations. With that in mind, I think there are at least 2 options:

1. I change just the isotope prediction to account for the affect in changing reactant symmetry number. This will only affect the isotope models and will not require any database changes.
2. I let the core of RMG account for the symmetry differences when obtaining rates from rate rules and training reactions. This will likely require all rmg rate rules to have the symmetry and/or species' graphs explicitly mentioned (or skip the module if not listed).

Any thoughts on the preferable path?
