### ISSUE TITLE
Tool to visualize reaction templates

### ISSUE THREAD

**Issue by zjburas** [ReactionMechanismGenerator/RMG-Py#853]
Can a tool be created, either on the website or as a standalone script, that allows the user to visualize a reaction template? For example, right now if I have the following template for the intra_H_migration family:

[R4H_SSS;C_rad_out_H/NonDeC;Cs_H_out_2H]

I would have to search for each group in that family individually, probably using the page for that reaction family on the rmg website ([http://rmg.mit.edu/database/kinetics/families/intra_H_migration/groups/](url))  in order to figure out that my template consists of the following three groups:

![image](https://cloud.githubusercontent.com/assets/12465817/21395094/2d4f718a-c769-11e6-9f7a-5492239dc934.png)
+

![image](https://cloud.githubusercontent.com/assets/12465817/21395119/4c2d2d72-c769-11e6-94fe-0fbfb06b87cd.png)
+

![image](https://cloud.githubusercontent.com/assets/12465817/21395139/5cbe3e2e-c769-11e6-9482-a661a936a66f.png)

Then, I have to manually piece together how the 3 groups  fit together to represent the overall template, using the * atoms as a guide. In this example it's not too hard, but if you have many templates to check this process can become quite time-consuming.

If a tool could be made that can do all of this automatically, it would be helpful in at least 2 situations:

1. If you have an estimated reaction in an RMG mechanism and want to know what the template it is using actually looks like.

2. If you want to add in a new training reaction, but first want to visualize if the template that reaction will match (determined by running convertKineticsLibraryToTrainingReactions.ipynb) is specific enough.

Even if the tool can only visualize the different groups, but not stitch them together, that would be an improvement over the current manual approach.

**Comment by mutlay** [comment]
@zjburas I'm not sure whether it might be something you're looking for but I've done several things to visualize reaction networks of RMG. Check it out there: [Article Link](http://pubs.rsc.org/en/Content/ArticleLanding/2015/CP/C4CP04736B#!divAbstract)

**Comment by zjburas** [comment]
Closing my obsolete issues
