### ISSUE TITLE
Isomorphism check gives erroneous result after conversion to single bonds

### ISSUE THREAD

**Issue by cgrambow** [ReactionMechanismGenerator/RMG-Py#867]
I have encountered a problem where RMG does not correctly determine if molecules are isomorphic after converting all bonds to single bonds. I have made a small working example below to illustrate this. Note that I have specified all hydrogens explicitly and that each SMILES string contains two fragments, the first of which is identical for both structures. The second fragment of the first structure is a peroxy-carbene and the second fragment of the second structure is formic acid. The second fragments clearly have different connectivity even after converting all bonds so single bonds, so they should not be isomorphic.

The structures are specified as follows:
```python
from rmgpy.molecule import Molecule
mol1 = Molecule().fromSMILES('[CH3][CH]=O.[CH]O[OH]')
mol2 = Molecule().fromSMILES('[CH3][CH]=O.O=[CH][OH]')
```

Executing the following yields `False`, as expected:
`mol1.isIsomorphic(mol2)`

However, executing this yields `True`:
`mol1.toSingleBonds().isIsomorphic(mol2.toSingleBonds())`

**Comment by KEHANG** [comment]
I'm not sure we are supposed to use isomorphism check for molecules that actually contain two graphs. What I'm pretty sure is we don't have any tests for this kind of situations in RMG-Py. So I won't be surprised it gives you weird results.

What I will do in your situation is firstly split the molecule and then do the isomorphism check separately. Quick example code as follows:

```
from rmgpy.molecule.molecule import Molecule

mol1 = Molecule().fromSMILES('[CH3][CH]=O.[CH]O[OH]')
mol2 = Molecule().fromSMILES('[CH3][CH]=O.O=[CH][OH]')
mol1_s = mol1.toSingleBonds()
mol2_s = mol2.toSingleBonds()
[a, b] = mol1_s.split()
[c, d] = mol2_s.split()

if a.isIsomorphic(c) and b.isIsomorphic(d): print True
elif a.isIsomorphic(d) and b.isIsomorphic(c): print True
else:
    print False
```

**Comment by cgrambow** [comment]
I see. I guess I'll make sure to split the molecules before checking for isomorphism. Thanks for your help!
