### ISSUE TITLE
Restart options are poorly documented

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#877]
Someone just emailed me asking how to restart a job from a restart file. As I looked for the appropriate page in the documentation to refer them to, I couldn't find it mentioned anywhere.

I believe from looking at https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmg.py#L79 that you just add `-r` (or `--restart`) to the command line when running the job, i.e.
```
$ python rmg.py -r input.py
```
but it would be great if someone could check that this works and add it to the documentation, along with the other various command line options!
Perhaps in the section on "Running a Job" https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/documentation/source/users/rmg/running.rst

**Comment by samimiomid** [comment]
Yes, it works by adding -r to the command. 
thanks
Omid

**Comment by KEHANG** [comment]
documentation added via #878
