### ISSUE TITLE
Idea for Improving Polycyclic Corrections

### ISSUE THREAD

**Issue by zjburas** [ReactionMechanismGenerator/RMG-Py#883]
I recently encountered the following issue while trying to generate an RMG mechanism for 1,3-cyclopentadiene (CPD) pyrolysis:

## Issue
A lot of species containing the highly ring-strained 1,2-CPD subunit (shown below) were produced:

![image](https://cloud.githubusercontent.com/assets/12465817/22660488/bda3b360-ec6f-11e6-80eb-f7c8508c41f3.png)

Unsurprisingly, this was because there was no specific ring() correction for the above species, so its ring-strain was being estimated by cyclopentane, which is of course way more stable. The obvious solution was to calculate the thermo of 1,2-CPD, and create its own ring() correction, which I did. This small thermo database change had the intended effect of almost  completely eliminating  1,2-CPD containing monocyclics in the mechanisms.

However, bicyclic species containing the same 1,2-CPD unit, such as the below, were still produced in abundance because there was no corresponding **polycycic()** correction for these species, so the thermo was being estimated by averaging much more stable compounds.

polycyclic(![image](https://cloud.githubusercontent.com/assets/12465817/22661685/4db754a8-ec74-11e6-9edf-d6a0cfcf12d7.png)) **_estimated by_** _average_[polycyclic(![image](https://cloud.githubusercontent.com/assets/12465817/22663746/d34a58a2-ec7b-11e6-9ed3-0bd0c0971737.png)), polycyclic(![image](https://cloud.githubusercontent.com/assets/12465817/22663834/34db31ae-ec7c-11e6-865f-b9c3ade042b1.png)),...]

Even worse, tricyclic and higer polycyclic species were being estimated by the following formula:

polycyclic(![image](https://cloud.githubusercontent.com/assets/12465817/22662744/04793fc8-ec78-11e6-8c18-5fb52df88037.png)) =  
_average_[polycyclic(![image](https://cloud.githubusercontent.com/assets/12465817/22663746/d34a58a2-ec7b-11e6-9ed3-0bd0c0971737.png)), polycyclic(![image](https://cloud.githubusercontent.com/assets/12465817/22663853/482935bc-ec7c-11e6-9f97-c90494c5a21c.png)),...] +
 _average_[polycyclic(![image](https://cloud.githubusercontent.com/assets/12465817/22663746/d34a58a2-ec7b-11e6-9ed3-0bd0c0971737.png)), polycyclic(![image](https://cloud.githubusercontent.com/assets/12465817/22663859/525bdd64-ec7c-11e6-957e-a8af9c716187.png)),...] -
 ring(![image](https://cloud.githubusercontent.com/assets/12465817/22660488/bda3b360-ec6f-11e6-80eb-f7c8508c41f3.png))

In other words, the polycyclic corrections already underestimate deltaH because they don't include the highly-strained 1,2-CPD subunit, and then the new ring() correction for 1,2-CPD (which has a huge positive deltaH) is subtracted from them, making the overall deltaH much too low.

Again, the obvious solution is to include new polycyclic() corrections for species containing the 1,2-CPD subunit. However, this would require a lot of new polycyclic groups that at least include the following 6:

![image](https://cloud.githubusercontent.com/assets/12465817/22663241/e42896e0-ec79-11e6-8bdb-15a3fac26587.png)

![image](https://cloud.githubusercontent.com/assets/12465817/22663246/e79e4edc-ec79-11e6-9877-2b8ccd4c155a.png)

![image](https://cloud.githubusercontent.com/assets/12465817/22663251/eb8e1b8a-ec79-11e6-91cc-3f87a03d870f.png)

![image](https://cloud.githubusercontent.com/assets/12465817/22663254/efc9b24a-ec79-11e6-8854-cab5b75c7d27.png)

![image](https://cloud.githubusercontent.com/assets/12465817/22663259/f2af45a6-ec79-11e6-8534-80060009e703.png)

![image](https://cloud.githubusercontent.com/assets/12465817/22663263/f5e29fa2-ec79-11e6-979c-d5fdf289dd8a.png)

Once you consider all of the unsaturated variations of the above, the number of new polycyclic() groups to make (and quantum jobs to run) quickly explodes. And this is just for one highly-strained ring species (1,2-CPD). The same issue would come up with a polycyclic that contains a highly-strained 1,2,3-cyclohexatriene ring, for example:

![image](https://cloud.githubusercontent.com/assets/12465817/22663447/9f7817a4-ec7a-11e6-8064-0f40f4ae8ebe.png)

## Idea
Rather than calculate each of the polycyclic corrections above explicitly, perhaps they could be estimated by the following formula (shown for an example bicyclic):

polycyclic(![image](https://cloud.githubusercontent.com/assets/12465817/22661685/4db754a8-ec74-11e6-9edf-d6a0cfcf12d7.png))= 
polycyclic(![image](https://cloud.githubusercontent.com/assets/12465817/22663746/d34a58a2-ec7b-11e6-9ed3-0bd0c0971737.png)) - 
ring(![image](https://cloud.githubusercontent.com/assets/12465817/22663608/3f02b59a-ec7b-11e6-967e-ba228fa6b421.png)) +
ring(![image](https://cloud.githubusercontent.com/assets/12465817/22663611/44d3595c-ec7b-11e6-8cc6-be7ca9c87c3f.png))

In other words, talk the saturated version of the polycyclic correction and replace the cyclopentane unit with the much more strained 1,2-CPD unit. All of the values on the right-hand side of the equation are already in the database. 

I have implemented the formula above manually for the 6 polycyclic corrections above in order to prevent formation of 1,2-CPD containing polycyclics in my mechanisms. It definitely seems like this is something that could be automated, and perhaps incorporated into the thermo estimation algorithm. The result could be much more accurate polycyclic() corrections for species containing highly-strained rings, without having to add more data to the database, other then the new ring() correction.

I haven't checked how accurate this approach is yet, so I suppose the next step should be quantum calcs of the 6 polycyclics above to compare with the new estimate. I've discussed with @KEHANG , and we wanted to see what other people thought of this idea first.

**Comment by rwest** [comment]
I like the idea. The proof will be in the pudding.

**Comment by zjburas** [comment]
Closing my obsolete issues. This idea is adopted in RMG-Py Master
