### ISSUE TITLE
Adding resonance structures involving multiple bonds and electronegative atoms

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#885]
I'm trying to add resonance structures in RMG of the type in the title, my motivation is to include SO3's structures (the sulfur branch is able to represent oxygenated sulfur species):
![image](https://cloud.githubusercontent.com/assets/16158262/22700214/dab7764a-ed27-11e6-83ff-0368cb10737b.png)

I think that the template we should use is the following (considering only `O` / `N` as electronegative atoms):
- Identifying `O` / `N` atoms with multiple bonds
- Identifying `O` / `N` atoms with single or double bonds and a negative charge (3 lone pairs for `O`, 2 lone pairs for `N`)
- Apply a respective transition recipe for each of the above, and filter out only unique species to return.

We might stumble upon new atomTypes here (I already got `N` with two double bonds and one single bond), in which case only a warning should be outputted (shouldn't crush).

## Some examples: 
- The following transitions should be filtered-out and only one representative structure should be returned:
![image](https://cloud.githubusercontent.com/assets/16158262/22698124/afb9cdd6-ed21-11e6-99ed-6ec338d981b4.png)
- The above transitions, although not generating unique structures for SO3 (or nitro-methane, see below), should be explored when the electronegative atoms aren't the same element:
![image](https://cloud.githubusercontent.com/assets/16158262/22699497/a9ed6a58-ed25-11e6-83c5-799f07d3146f.png)
- For SO3, the following four unique structures should be returned:
![image](https://cloud.githubusercontent.com/assets/16158262/22700256/02ee4d82-ed28-11e6-886b-d3d8f27f6431.png)

I'd love to get your opinions if this is a correct approach, and if there are any suggestions or issues that we can see in advance.

**Comment by alongd** [comment]
I added a first draft code that explores these resonance transitions: 1c6a3dd8b311c247e362d483bded50bcdca77950
Seems to work (discussion below), but definitely not the best piece of code ever written... would love to get comments on how to make it more efficient (checkout the entire sulfur branch if you want to test something like SO3).

My approach was the following (adding it here for documentation):
The most comprehensive case is SO3 (other resonance structures of the same class will have less\similar number of transitions). All structures in SO3 must be explored (what if one of the O is substituted with an N? and another one with an S? then we really get 8 non isomorphic resonance structures)
![image](https://cloud.githubusercontent.com/assets/16158262/22765996/29ac17aa-ee41-11e6-9bf2-28aa5aeffb35.png)

Since we don't know what structure was given as input to start exploring from, all alternatives were considered. I also thought of taking whatever structure is given, and converting all bonds to just one type, and exploring from there, but it didn't simplify the code by much. So I made a table of the actions that should be taken to explore the other resonance structures depending on the starting structure:
![untitled-1](https://cloud.githubusercontent.com/assets/16158262/22766125/b5b7889c-ee41-11e6-8a73-39c6df78be98.jpg)

numM is the number of multiple bonds in the starting structure between a central atom and an electronegative atom, and numC is the number of charged (-1) electronegative atoms connected to the central atom. For now, electronegative atoms were taken as O / N only, hopefully will be elaborated to sulfur as well.
Ci and Mj represent the actions that should be taken from that specific starting point: Ci means that charged atom i should loose its charge and the bond between atom i and the central atom incremented; Mj means that atom j gains a (negative) charge and the bond between atom j and the central atom decremented. The `+` sign means that transitions should be applied simultaneously.

**Here are the results from implementing this approach:**
## SO2:
species has 3 resonance structures:
![image](https://cloud.githubusercontent.com/assets/16158262/22766696/ffcd7cae-ee44-11e6-82a1-17bbe3a37e58.png), ![image](https://cloud.githubusercontent.com/assets/16158262/22766700/03822f48-ee45-11e6-818f-3c5f01c62a2d.png), ![image](https://cloud.githubusercontent.com/assets/16158262/22766703/06a578ce-ee45-11e6-83d3-90d827f23a00.png)

## SO3:
species has 4 resonance structures:
![image](https://cloud.githubusercontent.com/assets/16158262/22766712/1918649e-ee45-11e6-9d66-1adfb756270e.png), ![image](https://cloud.githubusercontent.com/assets/16158262/22766716/1cbf792a-ee45-11e6-971d-19871e9c0cdf.png), ![image](https://cloud.githubusercontent.com/assets/16158262/22766718/1fa26c2e-ee45-11e6-8735-29dd4912386b.png) ,![image](https://cloud.githubusercontent.com/assets/16158262/22766721/22e23eb4-ee45-11e6-9fbc-c4ffcc32c3ba.png)

## Formaldehyde
species has 2 resonance structures:
![image](https://cloud.githubusercontent.com/assets/16158262/22766754/50be0958-ee45-11e6-98e2-d5f85a26c857.png), ![image](https://cloud.githubusercontent.com/assets/16158262/22766757/5583d8be-ee45-11e6-8c27-1668aff5baae.png)

## It has LIMITED success with SO2N (SO3, one O is substituted with N):
species has 9 resonance structures:
![image](https://cloud.githubusercontent.com/assets/16158262/22766893/0ccccbac-ee46-11e6-8a59-65aebd441357.png), ![image](https://cloud.githubusercontent.com/assets/16158262/22766898/114f67f2-ee46-11e6-9990-c91a93e7553e.png), ![image](https://cloud.githubusercontent.com/assets/16158262/22766908/1a41d728-ee46-11e6-89e7-26013a4c27db.png), ![image](https://cloud.githubusercontent.com/assets/16158262/22766910/1f419d12-ee46-11e6-874d-ac512cdc1ee6.png), ![image](https://cloud.githubusercontent.com/assets/16158262/22766915/23347a34-ee46-11e6-913c-92a98461483b.png), ![image](https://cloud.githubusercontent.com/assets/16158262/22766917/26604ec2-ee46-11e6-8468-47c06335910a.png), ![image](https://cloud.githubusercontent.com/assets/16158262/22766921/29d37598-ee46-11e6-8392-70f9597c71ea.png), ![image](https://cloud.githubusercontent.com/assets/16158262/22766925/2c394704-ee46-11e6-9e46-eda5eda11b02.png), ![image](https://cloud.githubusercontent.com/assets/16158262/22766928/3127c7c2-ee46-11e6-8d35-331f68072d6d.png)

(there are three redundancies. should enforce isIsomorphic)

## It FAILS with CO2:
species has 3 resonance structures:
![image](https://cloud.githubusercontent.com/assets/16158262/22766781/818e8756-ee45-11e6-9742-aeeba11e2b0c.png), ![image](https://cloud.githubusercontent.com/assets/16158262/22766784/85f23d1a-ee45-11e6-94ed-cfbcd315bf68.png), ![image](https://cloud.githubusercontent.com/assets/16158262/22766787/8bbf31c6-ee45-11e6-9424-e73533d610cd.png)
CO2 should have these resonance structures instead:
![image](https://cloud.githubusercontent.com/assets/16158262/22766821/aa37a688-ee45-11e6-9a1b-9c29a0fa0300.png)

Perhaps CO2 should be forbidden in this method? Currently CO2 has no resonance structures in RMG (probably not important to have anyway?)

**Comment by mliu49** [comment]
It seems to me that you should be able to adapt the framework that is currently being used for adjacent, lone pair/radical, and N5dd/N5ts resonance structures.

I don't think it's necessary to pre-identify all of the possible resonance options in the molecule. As long as you convert each option one at a time, you'll end up with all of the possible combinations.

I'll test it out and see.

**Comment by mliu49** [comment]
I created a new branch `sulfur_resonance` implementing the method I mentioned. The relevant commit is 428172eae97b05a469405762d1f7ee2d9d0719cb. (Also, you're probably aware, but the sulfur branch has broken 100+ unit tests.)

However, I also wanted to ask about the importance of these resonance forms. I have no idea how much the charged structures contribute to the actual structure of the molecule, but it also seems that they won't offer much in terms of reactivity since RMG can't react charged species. From another view, we never consider the charged resonance structure of other carbonyl species, but they shouldn't be that different. The carbon and sulfur apparently have very similar electronegativity, at least according to wikipedia.

**Comment by alongd** [comment]
Thanks for the clean implementation, @mliu49!

In my understanding, most of the broken unit tests are because of the new sulfur atomTypes (for example when `Sd` is expected, but we now call it `S2d`. Will be addressed soon).

I agree that these resonance structures will probably have no role in our rate rules (we'll use the all-double-bonds form). But I think it is important to capture all resonance forms to avoid duplicate species in RMG's output, since the user can input a different structure or create a library with a different SO3 structure. I thought it'll be more flexible and feasible to treat these structures correctly than to somehow allow only one of them.

I see that you only treated sulfur as a central atom in the code, I guess we're not interested in representing the resonance structures of carbon species such as formaldehyde for the reason you mentioned (charged resonance structures).

Thanks again!!
