### ISSUE TITLE
addAtomLabelsForReaction not robust

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#889]
the method `addAtomLabelsForReaction` in `family.py` throws an error on some compounds. [this notebook](https://github.com/goldmanm/rmg_walkthroughs/blob/master/issues/addAtomLabelsForReaction%20bug%20example.ipynb) shows an example of the error. 

We might consider adding a unittest for  `addAtomLabelsForReaction` while we are at it.

**Comment by goldmanm** [comment]
I think the issue I was coming across was related to forbidden groups. adding `family.forbidden = ForbiddenGroups()` erased all of these and the method worked as expected.

**Comment by mliu49** [comment]
Has this been addressed by #1247?
