### ISSUE TITLE
SMILES Draws a Fused Cyclic Species Differently than InChI and AdjList (although they all represent the same molecule)

### ISSUE THREAD

**Issue by zjburas** [ReactionMechanismGenerator/RMG-Py#890]
If  you look up the following molecule in "Molecule Search" on the RMG website using its SMILES, [CH]1C2=CC3CC2C13 

![image](https://cloud.githubusercontent.com/assets/12465817/22850454/9439e1e6-efd7-11e6-8f11-fd8e4fbb2b5d.png)

then take the InChI or AdjList that you generate and plug it back into  "Molecule Search" you will get a different molecule back (but that still has the same SMILES):

![image](https://cloud.githubusercontent.com/assets/12465817/22850490/ffb15f4e-efd7-11e6-9014-54951ec6c688.png)

This discrepancy caused me some confusion while visualizing an RMG-generated mechanism, because the incorrect structure was drawn, which made it appear as if invalid reactions were occurring.

I've seem this behavior for at least one other similar molecule (I don't have it anymore, but I can dig it up if anyone is interested in another test case).

**Comment by mliu49** [comment]
I think those are actually the same molecule, just drawn differently. This may or may not help with visualizing it, but here is another way to draw it:

![mol](https://cloud.githubusercontent.com/assets/10817103/22851173/d94f7c22-efe7-11e6-9994-2e3000b26e3f.png)

**Comment by zjburas** [comment]
You're totally right. Thanks.

**Comment by rwest** [comment]
You might want to open a new issue saying that the drawing of fused cyclic species is not repeatable which makes mechanism visualization confusing.

**Comment by zjburas** [comment]
As discussed above, for the example fused polycyclic it is drawn differently if you use its SMILES compared to using its InChI or AdjList, although both structures are valid and represent the same molecule.
