### ISSUE TITLE
Sidebar links to update documentation broken

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#896]
I was browsing 
http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html
and clicked the sidebar link to "Edit this page" which points to 
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/documentation/source/users/rmg/installation/anacondaDeveloper.rst.rst
which has too many ".rst" suffixes at the end.

**Comment by KEHANG** [comment]
Fixed by PR #900, the site is  working now
