### ISSUE TITLE
Installation instructions inconsistent in environment name

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#897]
Looking at http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html
it seems the environment_XXX.yml files create environments called `rmg_env`, which is reflected in the instructions to type `source activate rmg_env` but a few lines later it suggests adding `export PATH=~/anaconda/envs/rmg/bin:$PATH` to your `.bashrc` which presumes the environment is called `rmg`. 

Personally I much prefer the `rmg` name (which would require changing the environment_XXX.yml files, but we should at least be consistent across all the documentation.

**Comment by mliu49** [comment]
I don't remember why it was changed from `rmg` to `rmg_env`. I remember it happening because I had to remake the environments for the websites. I also liked `rmg` better.

**Comment by KEHANG** [comment]
I'll make it consistent. Changing it back to `rmg`, probably will be a future task.

**Comment by KEHANG** [comment]
fixed via #902
