### ISSUE TITLE
Benzene bonds of sulfur (and nitrogen?) cause Travis to crash, probably a string/float issue

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#899]
An atomTypeTest for an aromatic compound containing sulfur crashed. Heteroatoms in aromatics are not fully developed in RMG, but I wrote this test on the sulfur branch to check that the benzene-bonded sulfur atomType (`S4b`) functions as expected.
The molecule tested:
```python
self.mol25 = Molecule().fromAdjacencyList('''
1 S u0 p1 c0 {2,B} {5,B}
2 C u0 p0 c0 {1,B} {3,B} {6,S}
3 C u0 p0 c0 {2,B} {4,B} {7,S}
4 C u0 p0 c0 {3,B} {5,B} {8,S}
5 C u0 p0 c0 {1,B} {4,B} {9,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {3,S}
8 H u0 p0 c0 {4,S}
9 H u0 p0 c0 {5,S}''')
```
![image](https://cloud.githubusercontent.com/assets/16158262/22945595/c5245528-f2c2-11e6-99a6-c8a68dde0be7.png)
and the test is:
```python
self.assertEqual(self.atomType(self.mol25, 0), 'S4b')
```
It crashed with the following trace:
```

======================================================================
ERROR: Test that getAtomType() returns appropriate sulfur atom types.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ReactionMechanismGenerator/RMG-Py/rmgpy/molecule/atomtypeTest.py", line 222, in setUp
    9 H u0 p0 c0 {5,S}''')
  File "rmgpy/molecule/molecule.py", line 1280, in rmgpy.molecule.molecule.Molecule.fromAdjacencyList (build/pyrex/rmgpy/molecule/molecule.c:24509)
    def fromAdjacencyList(self, adjlist, saturateH=False):
  File "rmgpy/molecule/molecule.py", line 1288, in rmgpy.molecule.molecule.Molecule.fromAdjacencyList (build/pyrex/rmgpy/molecule/molecule.c:24084)
    self.vertices, self.multiplicity = fromAdjacencyList(adjlist, group=False, saturateH=saturateH)
  File "/home/travis/build/ReactionMechanismGenerator/RMG-Py/rmgpy/molecule/adjlist.py", line 703, in fromAdjacencyList
    for atom in atoms: ConsistencyChecker.check_partial_charge(atom)
  File "/home/travis/build/ReactionMechanismGenerator/RMG-Py/rmgpy/molecule/adjlist.py", line 99, in check_partial_charge
    bonds=','.join([bond.order for bond in atom.bonds.values()])
TypeError: sequence item 0: expected string, float found
```

This is understood given the unique aromatic bond that includes a lone pair for sulfur (and some of the nitrogen compounds: `N5b` but not `N3b` atomTypes). In this case one of the lone pairs of the heteroatom contributes to the resonance structure. So the bond order of the `S` atom is actually 4. But RMG probably counts a benzene bond from the adjList as 1.5, deriving a total bond order of 3.

Miraculously, the `N5b` atomTypeTest on the nitrogen branch did not crash... which makes me a bit uncertain of my above interpretation of why the `S4b` test did.

**Comment by mliu49** [comment]
The error trace is the same issue as #898. We're retrieving bond.order and expecting a string ([code here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/adjlist.py#L91)).

However, this error was encountered in the process of raising an InvalidAdjacencyListError, so it seems that aromatic furan does work yet. It's because electrons are being double counted between the benzene bonds and one of the lone pairs. I'm surprised that your N5b test worked, since it should encounter the same issue.

**Comment by mliu49** [comment]
Closing since we don't support aromatic bonds for non-benzenoid molecules yet.
