### ISSUE TITLE
Module 'networkx' not in rmg_env by default (Very Low Priority)

### ISSUE THREAD

**Issue by ghost** [ReactionMechanismGenerator/RMG-Py#904]
The ipython script mechanism_analyzer depends on the 'networkx' module, although it is not installed in the default rmg_env environment created by the configuration file 'environment_linux.yml'. It is an easy fix for the user (simply type 'pip install networkx' when the environment is activated) but should this be included by default?

**Comment by mliu49** [comment]
Thanks for noticing! It seems that networkx is available from anaconda, so it would be as simple as adding it to the environment_[os].py files. Would you like to make the addition and submit a pull request?

**Comment by amarkpayne** [comment]
Can do!
