### ISSUE TITLE
Windows Users can't "make" RMG-Py

### ISSUE THREAD

**Issue by zjburas** [ReactionMechanismGenerator/RMG-Py#921]
On the current master branch I can't compile RMG-Py on my local Windows machine using the following command line entry: mingw32-make.  I get the following error after less than a  minute of compiling:

C:/Anaconda/envs/rmg_env/share/mingwpy/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file .\rmgpy\molecule\atomtype.pyd: Permissi
on denied
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\Anaconda\\envs\\rmg_env\\Scripts\\gcc.exe' failed with exit status 1
makefile:21: recipe for target 'main' failed
mingw32-make: *** [main] Error 1

I have tried running as an administrator, but it doesn't help. @soumsrani has also encountered the same problem on her Windows machine (although permission is denied for a different file in her case).

**Comment by KEHANG** [comment]
If some hidden programs are holding the files, maybe restarting your windows machine can help.

**Comment by zjburas** [comment]
Restarting windows fixed the problem. @soumsrani is also able to compile again (also probably after restarting).

Thanks.
