### ISSUE TITLE
Website GAV thermo calulation gives different results than RMG-Py

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#926]
The GAV of C=CC[CH]C=C results in [a NASA polynomial that seems to be valid in the range 100 - 5000 K](http://rmg.mit.edu/database/thermo/molecule/multiplicity%202%0A1%20%20C%20u0%20p0%20c0%20%7B2,D%7D%20%7B8,S%7D%20%7B9,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,D%7D%20%7B3,S%7D%20%7B10,S%7D%0A3%20%20C%20u1%20p0%20c0%20%7B2,S%7D%20%7B4,S%7D%20%7B5,S%7D%0A4%20%20H%20u0%20p0%20c0%20%7B3,S%7D%0A5%20%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B6,S%7D%20%7B11,S%7D%20%7B12,S%7D%0A6%20%20C%20u0%20p0%20c0%20%7B5,S%7D%20%7B7,D%7D%20%7B13,S%7D%0A7%20%20C%20u0%20p0%20c0%20%7B6,D%7D%20%7B14,S%7D%20%7B15,S%7D%0A8%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A10%20H%20u0%20p0%20c0%20%7B2,S%7D%0A11%20H%20u0%20p0%20c0%20%7B5,S%7D%0A12%20H%20u0%20p0%20c0%20%7B5,S%7D%0A13%20H%20u0%20p0%20c0%20%7B6,S%7D%0A14%20H%20u0%20p0%20c0%20%7B7,S%7D%0A15%20H%20u0%20p0%20c0%20%7B7,S%7D%0A).
However, [evaluating the polynomial at 4000 K](http://www.wolframalpha.com/input/?i=-4.48834066e1%2B9.41549316e-2*4000-2.89329538e-5*4000%5E2%2B4.28088307e-10*4000%5E3%2B1.66926125e-13*4000%5E4) results in a negative Cp.

I'm not sure about other cases, but this might be an abundant error since we usually only visualize up to ~2000 K.

I know that 4000 K sounds extremely high, but we have users searching for such thermo data (I got an email from BTU Cottbus, Germany, with this error, so I'm opening this issue).

A relatively easy fix might be to evaluate the max T range for each species and set it at the point where things become un-physical, so at least users will know its validity range. Of course, the desired solution is to correct the GAV method so it can be applied at the temperature range we claim it is.

**Comment by alongd** [comment]
The Cp values were reported by one of our users to decrease with increasing T above 1800 K for the above species.

**Comment by rwest** [comment]
I thought as part of the process we calculate the heat capacity at infinite temperature. Is this being messed up or is it just a fitting problem of representing it with NASA polynomials poorly?

**Comment by gmagoon** [comment]
I'm not familiar with how the current system works, but the Wilhoit form
shouldn't allow this (related to the Cpinf that Richard mentioned).

**Comment by alongd** [comment]
Calculating the same polynomial [at 40,000 K](http://www.wolframalpha.com/input/?i=-4.48834066e1%2B9.41549316e-2*40000-2.89329538e-5*40000%5E2%2B4.28088307e-10*40000%5E3%2B1.66926125e-13*40000%5E4) (instead of 4,000 K) **does** result in a positive value. So apparently Cp(inf) did not catch this problem.

**Comment by gmagoon** [comment]
The 40000 K result of NASA polynomial won't mean much if it is only fit up
to 5000 K. The way it used to work (and perhaps still does?) was GAV >
Wilhoit > NASA. Although the Wilhoit form will be valid at arbitrarily high
temperature, the NASA polynomial won't be valid extrapolating this far
outside the temperature range.

Sounds to me like maybe a fitting issue of some sort in Wilhoit-to-NASA
like Richard mentioned. One other thing you might check is whether Cp(1500
K) is higher than Cp(Inf). I don't think this would lead to the issue
you're seeing (basically, Wilhoit will have trouble fitting the GAVs since
it only gives monotonic behavior as I recall, but that shouldn't lead to
negative Cp) but it has been awhile since I've worked on this.

**Comment by mliu49** [comment]
After looking into it, I found that the website does not go through the standard process for retrieving thermo data. It calls a method that is essentially only used by the website to get all sources of thermo data for a species. The website then directly fits NASA polynomials from T=100 to T=5000. Group additivity estimates are returned as ThermoData objects, which only have Cp values up to 1500, so this can be very inaccurate (as we see here).

During normal RMG operation, thermo estimation is no handled by ThermoEngine, which does perform an intermediate conversion to Wilhoit, specifically for this reason. The best solution would probably be fixing the website algorithm to do the Wilhoit to NASA method.

**Comment by alongd** [comment]
Right. Using the ThermoEstimator script, I got a different NASA polynomial for that species, with a positive Cp value at 4000 K.

**Comment by iamruta** [comment]
I would like to be informed when the website will be fixed. Thank You for helping. Great job with RMG...keep it up!  Warm regards from Cottbus, Germany.

**Comment by alongd** [comment]
@iamruta , you are now subscribed to this particular GitHub issue page, you'll be automatically informed regarding any progress with it, and when it is fixed.
Happy modeling!

**Comment by mliu49** [comment]
This issue has been fixed. The website now uses the same conversion process via Wilhoit as RMG normally uses.
