### ISSUE TITLE
Sulfur Charge Bug

### ISSUE THREAD

**Issue by rgillis8** [ReactionMechanismGenerator/RMG-Py#929]
In the RMG simulations of a current system I am working on I have started to generating a limited number of sulfur species with a +4 charge and 0 lone pairs. Looking at updateCharge it seems that somewhere along the way the lone pairs were lost and RMG seeing just two single bonds and no other electrons assigned the +4 charge. Here is the exact species and reaction that generates this species.

![image](https://cloud.githubusercontent.com/assets/17207564/23477406/db7d723a-fe8b-11e6-8799-492f9c18ecdc.png)

The products of this and similar reactions (differing in the number of Sulfur atoms from 2 to 6) are the only species in the mechanism that have a +4 charge in the species dictionary. The mechanism contains many aromatic and sulfur species that do not have this charge issue. This is the only reaction that the charged species participates in. 

Strangely enough while this bug appears in a full run of RMG but if I isolate the creation of these species with generateReactions script the charge and lone pairs are correct.

RMG Generate Mechanism Species Dictionary
[species_dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/811837/species_dictionary.txt)

Generate Reactions Script Species Dictionary
[species_dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/811842/species_dictionary.txt)

**Comment by mliu49** [comment]
I think this is due to the fact that lone pairs are not properly handled when converting to an RDKit mol, which was previously done for generating Kekule structures.

The kekulization algorithm has been completely rewritten in current master, so this should no longer occur. If you get a chance, please check again to see if you still encounter this issue.

**Comment by alongd** [comment]
@rgillis8, could you confirm this is now solved on master (with the new charged atomTypes definitions no +4 charge is allowed)?
