### ISSUE TITLE
lpsolve55 not in requirements.txt

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#932]
Commit 0ba818d08f6051d078db87c41dd86b66cd5e4db2 added it to the conda environments and travis testing info, but it is not in the requirements.txt for people installing RMG without anaconda.

Furthermore, I'm not sure where to get it from (`pip install lpsolve55` doesn't work).

cc: @pat-hanbury @chiyw13

**Comment by mliu49** [comment]
For users who are not using anaconda, it would need to be downloaded and installed from https://sourceforge.net/projects/lpsolve/. There are two components: the core lpsolve code (written in C) and the Python wrapper.

However, I have not actually tried installing that way, so I don't know the specific steps involved. I thought we were no longer officially supporting installation without anaconda, so I did not really look into it.
