### ISSUE TITLE
Documentation missing for rmgrc settings to choose database path.

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#934]
The path to the database to use can be specified in the `rmgrc` file which can exist in (in this order of priority) the current working directory (from which you ran python), a hidden directory in your home folder `~/.rmg/`, or the same directory as the rmgpy package (eg. `...RMG-Py/rmgpy/`.   This way a user can override the system default with their general preference, and can over-ride it again on a per-job basis. 
See docstrings at
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/05f40bd1ef6c694980030fc668cc1833ae651296/rmgpy/__init__.py#L87

This does not seem to be documented anywhere (even the docstring mentioned above is not converted via sphinx autodoc into the API manual).

**Comment by rwest** [comment]
Also, the example currently at https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/rmgrc
has `database.directory : ../../RMG-database/input` which is a bad suggestion, because the relative path is relative to where python is called from, not relative to where that file is.

eg. if you run `python ../../../../rmg.py input.py` from inside a deep nested folder, or `python $RMGpy/rmg.py input.py` from somewhere else entirely, it will not find the correct database.
Much better to use an absolute path as the example, or relative to `$RMGpy` or something.

**Comment by dyu2017** [comment]
Using the rmgrc, the program can find the database in a user's home.
But how can I make sure the executable also point to the modified one in a user's home, not the one on a computer cluster's root?

**Comment by rwest** [comment]
1. Ensure the RMG-Py folder that you want comes nearest the front of your $PYTHONPATH environment variable so that if you open a Python terminal then type "import rmgpy" then "rmgpy" (or "import rmgpy.molecule" then "rmgpy.molecule" it reports the path you expect. 
2. When actually running an RMG job with the command "python path/to/your/rmg.py path/to/your/input.py" ensure you point to the rmg.py that you want. 


Also, if you're using anaconda you could create your own environment(s) in your user space and activate them as you choose.

**Comment by rwest** [comment]
To clarify, you must do both 1 and 2 above. (if you changed the rmg.py; else perhaps just 1, but safest to do both)

**Comment by dyu2017** [comment]
Thanks for your help. That fixed my problem.
