### ISSUE TITLE
Heapy Initialization Errors

### ISSUE THREAD

**Issue by stroiano** [ReactionMechanismGenerator/RMG-Py#94]
Guppy's heapy module has several well-documented issues that prevent it from loading. For example, the one-liner:

```python -c 'import guppy; hp = guppy.hpy()'```

returns an ImportError. This is normally passed as an exception to the RMG output, but has been found to cause a run-crashing segmentation fault on at least one Linux (Red Hat) setup.

So, since we don't actually utilize the heapy profiling that much anyway, I've disabled it entirely in 4d638dd577c8bbb7683da5a6ca3da9864d4e59c3. This issue should serve as a more permanent reminder to reenable profiling once a fixed version of guppy has been released.

P.S. It seems that there is a [patch](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=614498#19) for the root error, at least in 64-bit machines, but we shouldn't have to worry about applying fixes to every machine that we want to run profiling on. Better to just wait for a stable guppy release.

**Comment by rwest** [comment]
Guppy removed in #791
