### ISSUE TITLE
Mopac presence not identified by RMG

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#951]
After doing a standard install of mopac on my mac computer rmg couldn't identify that I had mopac.  I managed to fix this by going into Mopac and having it try "/opt/mopac/MOPAC2016.exe" as the mopac executable path before anything else.  

This seems to be an issue with the fact that it sets executablePath to /anaconda/envs/rmg_env/bin/mopac rather than /opt/mopac/MOPAC2016.exe, however what it finds in /anaconda/envs/rmg_env/bin/mopac links to the actual mopac executable so I don't understand why it doesn't believe that it has mopac later on when given that executablePath.  

The code is: 

 executablesToTry = ('MOPAC2016.exe', 'MOPAC2012.exe', 'MOPAC2009.exe', 'mopac')

    for exe in executablesToTry:
        try:
            executablePath = distutils.spawn.find_executable(exe)
        except:
            executablePath = None
        if executablePath is not None:
            break
    else:  # didn't break
        logging.debug("Did not find MOPAC on path, checking if it exists in a declared MOPAC_DIR...")
        mopacEnv = os.getenv('MOPAC_DIR', default="/opt/mopac")
        for exe in executablesToTry:
            executablePath = os.path.join(mopacEnv, exe)
            if os.path.exists(executablePath):
                break
        else:  # didn't break
            executablePath = os.path.join(mopacEnv , '(MOPAC 2009 or 2012 or 2016)')

Removing the first for loop and just using the else sets executable path to the appropriate executable under /opt/mopac and fixes the problem for me, but while I don't think you can install mopac without defining MOPAC_DIR or having mopac in /opt/ on mac, I'm unsure what the side effects of leaving the first for loop out might be for other operating systems.

**Comment by KEHANG** [comment]
not exactly sure what the issue here in your case. But `mopac` is automatically installed when you created `rmg_env` (the executable is usually located `~/anaconda/envs/rmg_env/bin/mopac`, it should not be a link), so you don't have to manually install that.

If your previous `rmg_env` doesn't work, maybe consider re-create the `rmg_env` again.

**Comment by mjohnson541** [comment]
Oh, ok, this all makes sense now.  I didn't need to install it and the rmg mopac doesn't have the key the version I installed does right now.  Thanks!
