### ISSUE TITLE
Numpy warning in compile RMG

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#955]
I have the warnings rated to numpy in building RMG.
Do I need to fix it?
 

Checking you have PyDQED...
/share/apps/anaconda-python/install/envs/rmg_env2/lib/python2.7/site-packages/pydqed.so
python setup.py build_ext main --build-lib . --build-temp build --pyrex-c-in-temp
running build_ext
cythoning rmgpy/kinetics/arrhenius.pyx to build/pyrex/rmgpy/kinetics/arrhenius.c
creating build
creating build/pyrex
creating build/pyrex/rmgpy
creating build/pyrex/rmgpy/kinetics
building 'rmgpy.kinetics.arrhenius' extension
creating build/build
creating build/build/pyrex
creating build/build/pyrex/rmgpy
creating build/build/pyrex/rmgpy/kinetics
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I. -I/share/apps/anaconda-python/i                                                         nstall/envs/rmg_env2/lib/python2.7/site-packages/numpy/core/include -I/share/apps/anaconda-python/install/envs/rmg_env2/include/pyth                                                         on2.7 -c build/pyrex/rmgpy/kinetics/arrhenius.c -o build/build/pyrex/rmgpy/kinetics/arrhenius.o
In file included from /share/apps/anaconda-python/install/envs/rmg_env2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarray                                                         types.h:1788:0,
                 from /share/apps/anaconda-python/install/envs/rmg_env2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarray                                                         object.h:18,
                 from /share/apps/anaconda-python/install/envs/rmg_env2/lib/python2.7/site-packages/numpy/core/include/numpy/arrayob                                                         ject.h:4,
                 from build/pyrex/rmgpy/kinetics/arrhenius.c:232:
/share/apps/anaconda-python/install/envs/rmg_env2/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2                                                         ****: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \****
  ^
In file included from /share/apps/anaconda-python/install/envs/rmg_env2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarray                                                         object.h:27:0,
                 from /share/apps/anaconda-python/install/envs/rmg_env2/lib/python2.7/site-packages/numpy/core/include/numpy/arrayob                                                         ject.h:4,
                 from build/pyrex/rmgpy/kinetics/arrhenius.c:232:
/share/apps/anaconda-python/install/envs/rmg_env2/lib/python2.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1448:1: wa                                                         rning: ‘_import_array’ defined but not used [-Wunused-function]
 _import_array(void)
 ^
build/pyrex/rmgpy/kinetics/arrhenius.c: In function ‘__pyx_f_5rmgpy_8kinetics_9arrhenius_18MultiPDepArrhenius_getRateCoefficient’:
build/pyrex/rmgpy/kinetics/arrhenius.c:16841:86: warning: ‘__pyx_v_Phigh’ may be used uninitialized in this function [-Wmaybe-uninit                                                         ialized]

**Comment by mjohnson541** [comment]
That's entirely normal when compiling.  It sounds like it's related to cython #102.
