### ISSUE TITLE
Pycairo not installed 

### ISSUE THREAD

**Issue by cehangir** [ReactionMechanismGenerator/RMG-Py#960]
hi, 

I have installed the RMG and ran it successfully using Binary installation on Windows. However, I am unable to see the 2D structures of the molecules in the output.html file and no PNG are stored in the species folder. 
![image](https://cloud.githubusercontent.com/assets/26471170/24173265/c9dd2440-0e61-11e7-851b-7a4bdb1635e6.png)

It seems likes CAIRO wasnt installed when i installed the RMG. I have check the list of packages that are installed using (conda create -c rmg --name rmg_env rmg rmgdatabase) and cairoPy isnt in the list. 

The following NEW packages will be INSTALLED:

    boost:           1.56.0-py27_3                rmg
    bzip2:           1.0.6-vc9_3                      [vc9]
    cantera:         2.3.0a3-np111py27_1_gdd7a374 rmg
    coolprop:        6.0.1dev-py27_0              rmg
    coverage:        4.3.4-py27_0
    cycler:          0.10.0-py27_0
    cython:          0.21-py27_1
    ffmpeg:          2.7.0-0                      rmg
    functools32:     3.2.3.2-py27_0
    gprof2dot:       2015.02.03-py27_0            rmg
    graphviz:        2.38.0-0                     rmg
    greenlet:        0.4.12-py27_0
    guppy:           0.1.10-py27_0                rmg
    icu:             57.1-vc9_0                       [vc9]
    jinja2:          2.9.5-py27_0
    jpeg:            9b-vc9_0                         [vc9]
    libpng:          1.6.27-vc9_0                     [vc9]
    libxml2:         2.9.3-vc9_0                  rmg [vc9]
    lpsolve:         5.5.2.5-0                    rmg
    lpsolve55:       5.5-py27_1                   rmg
    markupsafe:      0.23-py27_2
    matplotlib:      2.0.0-np111py27_0
    mkl:             2017.0.1-0
    mopac:           2016-1                       rmg
    nose:            1.3.7-py27_1
    numpy:           1.11.3-py27_0
    openbabel:       2.4.1-py27_1                 rmg
    openssl:         1.0.2k-vc9_0                     [vc9]
    pandas:          0.19.2-np111py27_1
    pip:             9.0.1-py27_1
    psutil:          5.2.0-py27_0
    pydas:           1.0.2-py27_0                 rmg
    pydot:           1.2.2-py27_0                 rmg
    pydqed:          1.0.1-py27_0                 rmg
    pyparsing:       2.1.4-py27_0
    pyqt:            5.6.0-py27_2
    python:          2.7.13-0
    python-dateutil: 2.6.0-py27_0
    pytz:            2016.10-py27_0
    pyzmq:           16.0.2-py27_0
    qt:              5.6.2-vc9_3                      [vc9]
    quantities:      0.10.1-py27_0                rmg
    rdkit:           2016.03.1-np111py27_1        rmg
    rmg:             2.1.0-py27_257               rmg
    rmgdatabase:     2.1.0-py27_1                 rmg
    scipy:           0.19.0-np111py27_0
    scoop:           0.7-py27_0                   rmg
    setuptools:      27.2.0-py27_1
    sip:             4.18-py27_0
    six:             1.10.0-py27_0
    subprocess32:    3.2.7-py27_0
    symmetry:        1.0.1-0                      rmg
    tk:              8.5.18-vc9_0                     [vc9]
    vs2008_runtime:  9.00.30729.5054-0
    vs2015_runtime:  14.0.25123-0
    wheel:           0.29.0-py27_0
    xlwt:            1.2.0-py27_0
    zlib:            1.2.8-vc9_3                      [vc9]

Can you suggest how i can install cairo separately while retaining it as part of the rmg_env.

**Comment by mliu49** [comment]
Are you running on Windows? Cairo should be installed automatically when creating rmg_env on Linux or Mac.

Assuming you are running on Windows, you can obtain cairo and cairocffi from other conda channels. Make sure that rmg_env is activated, then install using the following commands:
```
conda install cairo -c conda-forge
conda install cairocffi -c index49
```

**Comment by cehangir** [comment]
I am running on Windows. 

The issue is resolved after installing cairo and cairocffi. The 2D images are visible now

Thanks

**Comment by rwest** [comment]
If there are now working windows conda binaries for these, we could copy them to the RMG channel and uncomment them from the environment_windows.yml file.

**Comment by KEHANG** [comment]
added these two binaries and updated the environment_windows.yml by PR #986
