### ISSUE TITLE
How to speed up serial simulation

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#963]
Is there anyway to speed up the serial simulation?
If I add all the possible products as the species in the initial input file, will this save time and speed up simulation?

How to get the products  from one simulation automatically into an input file? 
Are there scripts doing that?

**Comment by mjohnson541** [comment]
That approach will work.  Other ways to speed up simulation without increasing tolerance are adding species constraints, not using pdep or not using quantum calculations (see RMG-Py/examples/rmg/commented.py).  

Ideally you would want to compile your output into a library, put it in your database and then add it as seed mechanism in your input file.  I believe the script you need is RMG-database/scripts/importChemkinLibrary.py.

**Comment by dyu2017** [comment]
Thanks!
