### ISSUE TITLE
visualize the reaction network

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#966]
Is there any scripts to visualize the generated reaction network?

**Comment by mliu49** [comment]
There are a couple of different tools available:
- Visualize Chemkin File (on the [website](http://rmg.mit.edu/tools/chemkin)): produces an prettified html version of the mechanism, draws molecules and reactions, shows thermo and rate data
- Generate Flux Diagram (RMG-Py/scripts/generateFluxDiagram.py and on the [website](http://rmg.mit.edu/tools/flux)): produces a very basic video flux diagram of your mechanism simulated at the reactor conditions specified in your RMG input file.
- Mechanism Pathway Analyzer (RMG-Py/ipython/mechanism_analyzer.ipynb): A more in depth and interactive mechanism analyzer that can also draw pathways.

**Comment by dyu2017** [comment]
Thanks!
For the mechanism pathway analyzer, which file should I use as input?

**Comment by amarkpayne** [comment]
To run the mechanism pathway analyzer:

1) Place the mechanism_analyzer.ipynb file in the directory that you want to work in

2) Inside this directory, create a subdirectory titled 'data'. Inside this directory create another subdirectory 'pathway_analysis'.

3) Inside the subdirectory 'pathway_analysis' create another subdirectory with the same name as the variable 'mech' (which is set to 'minimal' by default).

4) Inside this subdirectory, place your chemkin input file (chem.inp), your species dictionary file (species_dictionary.txt), and your chemkin simulation file that you obtained from running chemkin (CKSoln.ckcsv)

**Comment by dyu2017** [comment]
This may be a stupid question. How do I run chemkin in RMG and obtain the simulation file CKSoln.ckcsv?

**Comment by alongd** [comment]
@dyu2017, after running RMG you get an output Chemkin file.
Alternatively, you may obtain a Chemkin-format mechanism from literature (e.g., [FFCM-1](http://web.stanford.edu/group/haiwanglab/FFCM1/pages/download.html))

Then you run the Chemkin software for the conditions you're interested in, and get the ROP analysis file (CKSoln.ckcsv), which you then use as a feed for our mechanism analyzer script.

**Comment by amarkpayne** [comment]
One thing to note is that this script requires the ROPs (rate of production) in order to work, so it is important to specify the Chemkin output from the Chemikin job to include ROPs (I am not certain that it does this by default).

**Comment by dyu2017** [comment]
Is there any free software I can use besides chemkin?

**Comment by alongd** [comment]
[Cantera ](http://cantera.org/docs/sphinx/html/index.html) is open source.
But  the stand alone script mechanism_analyzer.ipynb was built for Chemkin (it requires the CKSoln.ckcsv file).
Principally, it could be adjusted to be used for other software as well (but it'll take some work).

**Comment by mutlay** [comment]
@dyu2017 I've done several things in my paper to visualize RMG output, check it out: http://pubs.rsc.org/en/Content/ArticleLanding/2015/CP/c4cp04736b#!divAbstract Although the code is based on R and python and quite flexible, unfortunately it's not open source since in commercial use. However if you study the paper, I believe you can figure it out something.
