### ISSUE TITLE
Reactions involved quarterphenyl

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#971]
I found that there is always an error when I have quarterphenyl.
Is there an limitation in RMG on how many aromatic rings a molecule can have?

Error: <Molecule "C1=CC=C(C=C1)C1=CC23C=CC1C1C(=CC=C2C13)C1C=CC=CC=1">

**Comment by amarkpayne** [comment]
This is not a fix, but it appears that this molecule has a lot of issues with bi-cyclic rings. I was running a simulation and a lot of seemingly impossible species like this were showing up in my mechanism. This is because RMG is not as accurate in estimating the thermo for species like this, which is something that is being worked on. To fix this I cherry-picked a few commits to RMG-database from others working on this issue. Like I said this is not a fix but it might prevent this issue for now, so feel free to try it out. To cherry-pick a commit:

1) Go to your RMG-database folder
2) Create a new branch for these commits using `git branch my_new_branch_name`. Type `git branch` to see what branch you are currently on. If you did not switch to this new branch then type `git checkout my_new_branch_name`.
3) For each of the commits listed below type `git cherry-pick commit_id`

The commit_ids you need are:
0edac6f
09145bc
d367764
de2250b

**Comment by amarkpayne** [comment]
Sorry, these commit ids should be correct now. Also see https://github.com/ReactionMechanismGenerator/RMG-database/commits/Surrogate_Oil_AMP if you are having trouble. The commits are the top 4 that you see

**Comment by mliu49** [comment]
Was there a more detailed error traceback printed?

**Comment by dyu2017** [comment]
There was no detailed error traceback.
@amarkpayne Have you ever successfully run parallel simulations for molecules with two or more aromatic rings?
If I switched to these branch, do I need to rebuild my executable (make clean, make)?
How can I get back to my original branch, is it "git branch master"?

**Comment by mjohnson541** [comment]
I don't know much about that branch, but in general you can try just doing make and do a test run to see if you need to rebuild the executable or you can just rebuild the executable (make clean, make) in RMG-Py.  

You can switch back with "git checkout master", git branch is primarily used for creating and deleting branches.

**Comment by dyu2017** [comment]
Thanks. @mjohnson541

**Comment by dyu2017** [comment]
@mliu49 
I found the error is actually from calculateDegeneracy module in family.py
Because I commented out "raise KineticsError", it does not give a traceback.
It can still output the error for the molecule.
What can I do with this kind of errors?

    def calculateDegeneracy(self, reaction):
        """
        For a `reaction` given in the direction in which the kinetics are
        defined, compute the reaction-path degeneracy.
        """
        reactions = self.__generateReactions(reaction.reactants, products=reaction.products, forward=True)
        if len(reactions) != 1:
            for reactant in reaction.reactants:
                logging.error('errortest1')
                logging.error(reactant)
            for product in reaction.products:
                logging.error('errortest2')
                logging.error(product)
#            raise KineticsError(('Unable to calculate degeneracy for reaction {0} '
#                                 'in reaction family {1}. Expected 1 reaction '
#                                 'but generated {2}').format(reaction, self.label, len(reactions)))
        return reactions[0].degeneracy

**Comment by amarkpayne** [comment]
Mainly I just stick with running RMG jobs in serial--even for fairly large jobs it shouldn't take longer than a day or two. How big is the molecule you are trying to run (number of carbon atoms)?

**Comment by mliu49** [comment]
Degeneracy issues typically arise from RMG not being able to identify two molecules as being resonance structures of each other. There is work currently being done to try and improve the degeneracy calculation algorithm, but it's not ready yet. Unfortunately, there is no easy way around this at the moment.

Could you also provide the other species that were logged? This error should report all the reactants and products for the problematic reaction. It would help with finding the specific reason.

**Comment by dyu2017** [comment]
@amarkpayne I am testing on polyaromatic molecules with # of carbon atom from 12-18.
For serial job, it takes at least more than 10 days and I haven't had a clean finished job yet.
The more species I have in the core, the longer it takes (one day or two) to add one species in it.

**Comment by mjohnson541** [comment]
So I believe n-dodecane (C12) ~ 12 days at reasonable tolerance.  About how many species are in your models at 10 days?  What tolerance are you running at?  Ordinarily you can often cutoff mechanism generation early and get reasonable results, but for large polyaromatics I would be cautious about that.

**Comment by mliu49** [comment]
@dyu2017 You're actually working in unexplored territory right now. We've only somewhat recently started improving the aromatic capabilities of RMG. Most of our past RMG modeling projects have been with aliphatic systems. There are people currently working on hexylbenzene (C12) and phenyldodecane (C18), and RMG has trouble with formation of additional aromatic rings in those systems.

I've been working extensively on representation and handling of aromaticity in RMG, and there has been a lot of work done by others to add more data for aromatic species. However, we have yet to successfully go beyond species with two aromatic rings. This is definitely an area that is still under constant development.

**Comment by dyu2017** [comment]
Does  len(reactions) mean degeneracy of reactions?
If resonance causes degeneracy problems, can we turn off resonance and degeneracy?

**Comment by mliu49** [comment]
Not exactly, `len(reactions)` just checks the number of reactions that were returned. The `calculateDegeneracy` method expects to receive a single reaction from the `__generateReactions` call. If it doesn't, it means something went wrong with degeneracy calculation.

It's definitely not advisable to turn of resonance and degeneracy, as they're very important to the reaction generation algorithm. If you just turned off resonance, you would get even more degeneracy errors. If you turned off degeneracy, you would end up with countless duplicate reactions in your model.

**Comment by dyu2017** [comment]
@mliu49 how is possible that _generateReactions return more than one reaction for the same reactants?

**Comment by mliu49** [comment]
`__generateReactions` looks at all the possible ways for the reactants to react within the reaction family. Depending on the family, there can be many different reactions that can occur. For example, in the `H_abstraction` family, it will create a reaction for every H atom that could be abstracted by the radical species. `calculateDegeneracy` also provides the expected products of the reaction, so `__generateReactions` will filter all of the possible reactions and return only the ones which give the desired product.

**Comment by dyu2017** [comment]
If both the reactants and products are fixed, there should be one reaction, right?
How can then it return more than one reaction?

**Comment by mliu49** [comment]
It is possible for the reactants to give different products that are actually identical due to resonance. However, RMG will occasionally fail to recognize that two molecules are actually resonance structures of each other. There are a couple of know issues with the robustness of `__generateReactions` and the resonance algorithms.

**Comment by rwest** [comment]
Some further elaboration, though I may be missing context and just adding confusion:
For example, OH abstracting a hydrogen from CH4 will generate four reactions (you can abstract each of the H atoms) which all have the same products - CH3 and H2O. This would then be merged to one reaction with a degeneracy of 4.

What's a little weirder is this, where there's a radical site (j) on the 1st atom of a 6-atom chain.
C1j-C2-C3-C4-C5-C6
It could reach around and abstract from C3, producing C1-C2-C3j-C4-C5-C6 via a 4-membered TS (C1,C2,C3 and the H) or it could abstract from C4 producing C1-C2-C3-C4j-C5-C6 via a 5-membered TS (C1,C2,C3,C4 and the H) which would have a different reaction rate (different amount of ring strain etc in the TS). But both are the same products (once you remove the atom labels, they're both hex-3-yl), hence the same reaction but with DIFFERENT transition states and not a degeneracy.   That may be unrelated to what you're asking, but I thought worth mentioning as it's been a point of discussion and deliberation, not to say confusion, many times.
