### ISSUE TITLE
Removing Dead, Deprecated, and Unreachable Code

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#975]
I am curious if we want to deprecate any functionality in RMG. I am thinking that not-often-used and poorly understood functionalities could be removed to allow easier bug checking, code support, and development. We may also be able to just cut some redundant methods. One example I came across would be to remove the method `rmgpy/molecule/molecule/Bond/isSpecificCaseOf` and integrate its code into `rmgpy/molecule/molecule/Bond/equivalent`. 

If people think it may be worthwhile to have a list of methods to cut, we may want to have a warning placed in docStrings, similar to how Cantera placed some in their code to warn users.

**Comment by goldmanm** [comment]
#1021 mentions some to get rid of

**Comment by goldmanm** [comment]
I couldn't find a place where the attribute `Reaction.label` is clearly assigned and utilized. Possibly we could deprecate it.

**Comment by goldmanm** [comment]
I just thought we might want to deprecate the `restart` file functionality. It didn't seem like it was working over 2 years ago, and as of now, it doesn't seem to be usable either (due to long saving times).

**Comment by alongd** [comment]
Does anyone use RMG-Java?
Perhaps we could depreciate the duplicate code for dealing with this older format?
I think that leaving just the import scrips is enough.

**Comment by mliu49** [comment]
I agree with deprecating RMG-Java methods. See #1021 for additional discussion related to this.

**Comment by mliu49** [comment]
As far as I'm aware, we don't have a existing deprecation process. It might be good to start one though. I think for typical software projects, deprecation means that a feature is no longer supported or recommended for use. Complete removal of the feature is done later on a fixed timeline.

This might be difficult for us though, since we don't have a fixed release schedule. A possible plan for us might be to add the deprecation warning in one release, then remove the method in the next release. Unless we start making small releases more often, in which case we could have a couple releases between deprecation and removal.

**Comment by alongd** [comment]
I was too fast to vote for removing on #1021. I agree that we should develop a deprecation process.

**Comment by goldmanm** [comment]
We may also want to deprecate the non-web versions of scripts like `diffModels`, and only support one type of output for them.

**Comment by alongd** [comment]
We could also depreciate the `saveRestartPeriod` now that automatic seed generation works

**Comment by goldmanm** [comment]
I'd add group additivity methods in 'family.py' to the list of deprecatable methods.

**Comment by alongd** [comment]
We could deprecate the FAME (used in RMG-Java) to CanTherm/Arkane file type converter.
(Has anyone ever seen a FAME input file lately?)

**Comment by goldmanm** [comment]
I wanted to add a few more things to this thread:

* It seems like there are two methods to calculate collision rate. One is in `reaction.py`. The other one is in `pdep/configuration.pyx`. Each uses completely separate code to calculate the rate. We should consolidate these.
* Some methods in network.py, like solveFullME and solveReducedME,  are not used in the rest of the program.

**Comment by alongd** [comment]
Searching for `DeprecationWarning` in the repository brings brings up many
```python
warnings.warn("X is no longer supported and may be"
              " removed in version 2.3.", DeprecationWarning)
```
results.

Shall we go ahead and remove these functions, given that v 3.0 was just released?

**Comment by JacksonBurns** [comment]
Here is a list of methods which should (allegedly) be deleted: [link](https://github.com/search?q=repo%3AReactionMechanismGenerator%2FRMG-Py%20deprecation%20warning&type=code)

**Comment by JacksonBurns** [comment]
The `ci-report-status` step of the CI can also be removed since the target for required CI was set to both the ubuntu and mac runners.

**Comment by JacksonBurns** [comment]
> The `ci-report-status` step of the CI can also be removed since the target for required CI was set to both the ubuntu and mac runners.

Done in #2448
