### ISSUE TITLE
Error from generateFluxDiagram.py

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#979]
I got the following errors with generateFluxDiagram.
Can anyone help with this?

Traceback (most recent call last):
  File "/home/dyu/RMG-WORK2/RMG-Py/scripts/generateFluxDiagram.py", line 44, in <module>
    main()
  File "/home/dyu/RMG-WORK2/RMG-Py/scripts/generateFluxDiagram.py", line 41, in main
    fluxdiagram.run(inputFile, speciesPath, useJava)
  File "/home/dyu/RMG-WORK2/RMG-Py/rmgpy/tools/fluxdiagram.py", line 492, in run
    rmg = loadRMGJob(inputFile, useJava=useJava)
  File "/home/dyu/RMG-WORK2/RMG-Py/rmgpy/tools/loader.py", line 49, in loadRMGJob
    rmg = loadRMGPyJob(inputFile, chemkinFile, speciesDict, generateImages, useChemkinNames=useChemkinNames)
  File "/home/dyu/RMG-WORK2/RMG-Py/rmgpy/tools/loader.py", line 85, in loadRMGPyJob
    reactionSystem.initialMoleFractions = dict([(speciesDict[spec], frac) for spec, frac in reactionSystem.initialMoleFractions.iteritems()])
AttributeError: 'rmgpy.solver.liquid.LiquidReactor' object has no attribute 'initialMoleFractions'

**Comment by alongd** [comment]
Did you use a liquidReactor, or simpleReactor (gas phase) in the input file?
`AttributeError: 'rmgpy.solver.liquid.LiquidReactor' object has no attribute 'initialMoleFractions'`
Make sure you specify the initial mole fracs for liquidReactor, if relevant

**Comment by dyu2017** [comment]
I used a liquidReactor
If I add initial mol fractions for the liquid reactor in the input file, I would get another error. 
TypeError: liquidReactor() got an unexpected keyword argument 'initialMoleFractions'

**Comment by alongd** [comment]
Right.
Try `initialConcentrations` as in the example: http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/liquids.html

**Comment by dyu2017** [comment]
I used initialConcentrations but it won't allow me to generate flux diagram as seen in my first post.

**Comment by mliu49** [comment]
It seems that the generate flux diagram script does not support the liquidReactor yet.

**Comment by cgrambow** [comment]
Should be fixed with #1225.
