### ISSUE TITLE
Duplicate reactions confusion c.f. RMG-Java

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#99]
Trying to import the RMG-Java database is causing problems in the OxygenSingTrip reaction library, because the three reactions:

 1. third body irreversible
 2. third body reversible
 3. pressure-independent irreversible

are considered unique by RMG-Java, but duplicates by RMG-Py (which therefore expects to see a DUPLICATE tag).

Suggestions?

**Comment by connie** [comment]
Closing this older issue.  Please refer to https://github.com/ReactionMechanismGenerator/RMG-Py/pull/337 for more details on duplicates.
