### ISSUE TITLE
kinetics simulation after model generation

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#992]
I have two questions regarding kinetics simulation after model generation.
(1) Can I use the model generated at 500C to simulate the system at 400 C, and for arbitrary length of time?
(2) It seems that simulate.py can perform the simulation for gas phase, is there any script to simulate liquid reactor?

**Comment by mliu49** [comment]
1. Yes, you can always simulate at a different temperature from what the model was generated at, but the larger the difference the less accurate your results will be. RMG builds the model by finding the "important" reactions at the temperature you specify, so if you run at a different temperature, then you might be missing important pathways. With respect to time, it would not be advisable to run significantly longer than the termination time you specified in the RMG job. Again, there could be chemistry occurring at later times which the model does not capture.
2. I would suggest using a different software such as Chemkin or Cantera for simulating your model. At the moment, the liquid reactor is not fully supported across all of RMG's features/scripts.

**Comment by dyu2017** [comment]
I remember seeing  the script for running Cantera somewhere on RMG website.
Can you tell me how to run Cantera?

**Comment by rwest** [comment]
I would refer you to the cantera documentation, which is quite thorough (although a little bit dispersed in different places.) You could start here:

http://www.cantera.org/docs/sphinx/html/cython/tutorial.html
https://github.com/Cantera/cantera-jupyter#cantera-jupyter

**Comment by dyu2017** [comment]
I thought that there is a simple script embedded in RMG-Py distribution to run Cantera.

**Comment by mliu49** [comment]
There is an ipython notebook ([here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/ipython/canteraSimulation.ipynb)), but you'll need to modify it for a liquid reactor.
