### ISSUE TITLE
Sensitivity analysis doesn't work for liquid reactor

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#993]
After a reaction model is generated, are there any methods to analyze the model to see which reaction step causes the discrepancy between the model and experiments?
For example, there may be a four times difference in kinetics between the simulation using the generated model and experiments. If we can figure out which step is the rate-limiting step, that step can be used to modify the model if the rates or thermodynamics is not accurate enough.

**Comment by alongd** [comment]
After model generation you should run a sensitivity analysis (using either RMG, or a post processing software). Then you should check in the commented Chemkin file how were the rates for the reactions your observable is most sensitive to derived (rate rule estimation? library? if so, what level of theory?)
The sensitivity analysis isn't identical to the RDS, but it's very relevant to what you're trying to achieve.

**Comment by dyu2017** [comment]
It seems that sensitivity analysis only works for gas phase reactor, not liquid reactor.

**Comment by dyu2017** [comment]
How do you use RMG to run sensitivity analysis after model generation?
The script sensitivity.py does not take liquid reactor. @alongd

**Comment by alongd** [comment]
I'm not experienced with liquid phase simulations in RMG (I assumed gas phase for your original question).
As this should obviously be fixed in RMG, for now I'd recommend using a different software for the SA calculation (Chemkin/Cantera).

**Comment by mliu49** [comment]
This has been fixed by #1181.
