### ISSUE TITLE
findParameterSourcesAndAssignUncertainties.ipynb broken: chemkin file too old

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#995]
Due to the https://github.com/ReactionMechanismGenerator/RMG-Py/commit/342956322d7567312fda57b3a1ae9b8b4de7572a  the old chemkin file found in `ipython/parseSource/chem_annotated.inp` doesn't work with the ipython notebook anymore because it uses the old parentheses formatting for rate rules.  Should replace it with a newer model.

**Comment by KEHANG** [comment]
Good catch! Direct text replacement seems a little tricky, maybe regenerating the model from RMG is better. Do you still remember which example/input is used for this model generation?

**Comment by connie** [comment]
Not super sure what the original input was, but my guess is that it's minimal example with GRI-Mech3.0 as a seed, C3 as a reaction library, with Pdep turned on to get the most variety of kinetics.

**Comment by KEHANG** [comment]
Cool, thanks! I'll update that.

**Comment by KEHANG** [comment]
fixed via #998
